local AddPrefabPostInit = AddPrefabPostInit
GLOBAL.setfenv(1, GLOBAL)

local BlowInHUrricaneLight = {
    "asparagus_cooked",
    "asparagus_seeds",
    "asparagus",
    "balloon",
    "berries_cooked",
    "berries_juicy_cooked",
    "berries_juicy",
    "berries",
    "blue_cap_cooked",
    "blue_cap",
    "butterflywings",
    "cactus_meat_cooked",
    "cactus_meat",
    "carrot_cooked",
    "carrot_seeds",
    "carrot",
    "cave_banana_cooked",
    "cave_banana",
    "charcoal",
    "cookedsmallmeat",
    "corn_cooked",
    "corn_seeds",
    "corn",
    "cutgrass",
    "cutreeds",
    "dragonfruit_cooked",
    "dragonfruit_seeds",
    "dragonfruit",
    "durian_cooked",
    "durian_seeds",
    "durian",
    "eggplant_cooked",
    "eggplant_seeds",
    "eggplant",
    "fabric",
    "feather_crow",
    "feather_robin_winter",
    "feather_robin",
    "feather_thunder",
    "featherfan",
    "fig_cooked",
    "fig",
    "garlic_cooked",
    "garlic_seeds",
    "garlic",
    "goose_feather",
    "grass_umbrella",
    "green_cap_cooked",
    "green_cap",
    "kelp_cooked",
    "kelp_dried",
    "kelp",
    "nightmarefuel",
    "onion_cooked",
    "onion_seeds",
    "onion",
    "palmcone_seed",
    "papyrus",
    "pepper_cooked",
    "pepper_seeds",
    "pepper",
    "petals_evil",
    "petals",
    "pinecone",
    "pomegranate_cooked",
    "pomegranate_seeds",
    "pomegranate",
    "potato_cooked",
    "potato_seeds",
    "potato",
    "pumpkin_cooked",
    "pumpkin_seeds",
    "pumpkin",
    "red_cap_cooked",
    "red_cap",
    "seeds_cooked",
    "seeds",
    "silk",
    "smallmeat_dried",
    "smallmeat", 
    "stinger",
    "tomato_cooked",
    "tomato_seeds",
    "tomato",
    "twiggy_nut",
    "twigs",
    "umbrella",
    "watermelon_cooked",
    "watermelon_seeds",
    "watermelon",
}

local BlowInHUrricaneMedium = {
    "acorn", -- add cooked?
    "barnacle_cooked",
    "barnacle",
    "batnose_cooked",
    "batnose",
    "batwing_cooked",
    "batwing",
    "bird_egg_cooked",
    "bird_egg",
    "cookedmeat",
    "cookedmonstermeat",
    "drumstick_cooked",
    "drumstick",
    "fishmeat_cooked", -- add living ocean fish?
    "fishmeat_small_cooked",
    "fishmeat_small",
    "fishmeat",
    "froglegs_cooked",
    "froglegs",
    "goldnugget",
    "humanmeat_cooked",
    "humanmeat_dried",
    "humanmeat",
    "ice",
    "meat_dried",
    "meat",
    "monstermeat_dried",
    "monstermeat",
    "nitre",
    "plantmeat_cooked",
    "plantmeat",
    "poop",
    "rope",
    "rottenegg",
    "spidergland",
    "spoiledfood",
    "torch",
    "transistor",
}

local BlowInHUrricaneHeavy = {
    "flint",
    "gears",
    "heatrock",
    "livinglog",
    "log",
    "lureplant_bulb",
    "rocks",
}

for _, prefab in pairs(BlowInHUrricaneLight) do
    AddPrefabPostInit(prefab, function(inst)
        MakeBlowInHurricane(inst, TUNING.WINDBLOWN_SCALE_MIN.LIGHT, TUNING.WINDBLOWN_SCALE_MAX.LIGHT)
    end)
end

for _, prefab in pairs(BlowInHUrricaneMedium) do
    AddPrefabPostInit(prefab, function(inst)
        MakeBlowInHurricane(inst, TUNING.WINDBLOWN_SCALE_MIN.MEDIUM, TUNING.WINDBLOWN_SCALE_MAX.MEDIUM)
    end)
end

for _, prefab in pairs(BlowInHUrricaneHeavy) do
    AddPrefabPostInit(prefab, function(inst)
        MakeBlowInHurricane(inst, TUNING.WINDBLOWN_SCALE_MIN.HEAVY, TUNING.WINDBLOWN_SCALE_MAX.HEAVY)
    end)
end
