GLOBAL.setfenv(1, GLOBAL)

local seg_time = TUNING.SEG_TIME
local day_time = TUNING.DAY_SEGS_DEFAULT * seg_time
local dusk_time = TUNING.DUSK_SEGS_DEFAULT * seg_time
local night_time = TUNING.NIGHT_SEGS_DEFAULT * seg_time
local total_day_time = TUNING.TOTAL_DAY_TIME

local wilson_attack = TUNING.SPEAR_DAMAGE
local wilson_health = TUNING.WILSON_HEALTH

local tuning = {
	CAFFEINE_FOOD_BONUS_SPEED = 5, -- player base speed plus this
	FOOD_SPEED_LONG = total_day_time/2, -- drinking coffee
    SEASON_LENGTH_VERYHARSH_VERYSHORT = 5,
    SEASON_LENGTH_VERYHARSH_SHORT = 7,
    SEASON_VERYHARSH_DEFAULT = 10,
    SEASON_LENGTH_VERYHARSH_LONG = 15,
    SEASON_LENGTH_VERYHARSH_VERYLONG = 20,

    TEMPERATE_LENGTH = 10,
    HUMID_LENGTH = 10,
    LUSH_LENGTH = 10,
    APORKALYPSE_LENGTH = 20,

    APORKALYPSE_NEAR_TIME = 7 * total_day_time,
    APORKALYPSE_PERIOD_LENGTH = 60 * total_day_time,

    MACHETE_DAMAGE = wilson_attack * .88,
    MACHETE_USES = 100,

	ARMOR_SNAKESKIN_PERISHTIME = total_day_time*8, --was 10
	SNAKESKINHAT_PERISHTIME = total_day_time*8, --was 10

	VINE_REGROW_TIME = total_day_time * 4,

	JUNGLETREESEED_GROWTIME = {base=4.5*day_time, random=0.75*day_time},
	JUNGLETREE_GROW_TIME =
	{
		{base=4.5*day_time, random=0.5*day_time},   --tall to short
		{base=8*day_time, random=5*day_time},   --short to normal
		{base=8*day_time, random=5*day_time},   --normal to tall
	},
	

	----------
    GLOWFLY_COCOON_HEALTH = 300,

    GLOWFLY_WALK_SPEED = 6,
    GLOWFLY_RUN_SPEED = 8,

    GLOWFLY_DELAY_DEFAULT = 5,
    GLOWFLY_DELAY_MIN = 2,
    GLOWFLY_DELAY_MAX = 50,

    GLOWFLY_BASEDELAY_DEFAULT = 5,
    GLOWFLY_BASEDELAY_MIN = 0,
    GLOWFLY_BASEDELAY_MAX = 50,

    GLOWFLY_DEFAULT = 7,
    GLOWFLY_MAX = 14,
    GLOWFLY_MIN = 0,

    ASPARAGUS_REGROWTH_TIME = day_time * 20,
    ASPARAGUS_REGROWTH_TIME_MULT = 1,
	
	ALOE_REGROWTH_TIME = day_time * 20,
    ALOE_REGROWTH_TIME_MULT = 1,
	
	RADISH_REGROWTH_TIME = day_time * 20,
    RADISH_REGROWTH_TIME_MULT = 1,
	
	TUBERTREE_REGROWTH_TIME = total_day_time * 5,
    TUBERTREE_REGROWTH_TIME_MULT = 1,

    TREE_CREAK_RANGE = 16,

    JUNGLETREE_CHOPS_SMALL = 5,
    JUNGLETREE_CHOPS_NORMAL = 10,
    JUNGLETREE_CHOPS_TALL = 15,
    JUNGLETREE_WINDBLOWN_SPEED = 0.2,
    JUNGLETREE_WINDBLOWN_FALL_CHANCE = 0.01,

	-- standard poison vars
	VENOM_GLAND_DAMAGE = 75,
	VENOM_GLAND_MIN_HEALTH = 5,

    POISON_PERISH_PENALTY = 0.5,
    POISON_HUNGER_DRAIN_MOD = 0.80,
    POISON_DAMAGE_MOD = -0.25,
    POISON_ATTACK_PERIOD_MOD = 0.25,
    POISON_SPEED_MOD = 0.75,
    POISON_SANITY_SCALE = 0.05, -- sanity hit = poison hit * POISON_SANITY_SCALE  set to 0 to turn off

    POISON_IMMUNE_DURATION = total_day_time, -- the time you are immune to poison after taking antivenom
    POISON_DURATION = 120, -- the time in seconds that poison normally endures
    POISON_DAMAGE_PER_INTERVAL = 2, -- the amount of health damage poison causes per interval
    POISON_INTERVAL = 10, -- how frequently damage is applied

    POISON_DAMAGE_RAMP = {-- Elapsed time must be greater than the time value for the associated damage_scale/fxlevel value to be used
        -- (total damage after 3 days: 289.54)
        {time = 0.00 * total_day_time, damage_scale = 0.50, interval_scale = 1.0, fxlevel = 1}, -- 48.00 DMG
        {time = 1.00 * total_day_time, damage_scale = 0.75, interval_scale = 1.0, fxlevel = 1}, -- 54.00 DMG
        {time = 1.75 * total_day_time, damage_scale = 1.00, interval_scale = 1.0, fxlevel = 2}, -- 48.00 DMG
        {time = 2.25 * total_day_time, damage_scale = 1.25, interval_scale = 0.9, fxlevel = 2}, -- 60.00 DMG
        {time = 2.70 * total_day_time, damage_scale = 1.50, interval_scale = 0.7, fxlevel = 3}, -- 41.14 DMG
        {time = 2.90 * total_day_time, damage_scale = 2.00, interval_scale = 0.5, fxlevel = 4}, -- 38.40 DMG
    },

    FOG_MOISTURE_RATE_SCALE = 0.6,
	
	-----------------
	-- AUTO TUNING --
	-----------------
	LITTLE_HAMMER_USES = 10,
	CORK_BAT_USES = 20,
	WALKING_STICK_DAMAGE = wilson_attack*.6,
	WEREWILBA_DAMAGE = wilson_attack*1.75,
	PIG_RUINS_DART_DAMAGE = wilson_attack,
	MAGNIFYING_GLASS_DAMAGE = wilson_attack *.125,
	CORK_BAT_DAMAGE = wilson_attack * 1.5,
	BRUSH_DAMAGE = wilson_attack*.8,
	
	TRUSTY_SHOOTER_DAMAGE_HIGH = 60,
	TRUSTY_SHOOTER_DAMAGE_MEDIUM = 45,
	TRUSTY_SHOOTER_DAMAGE_LOW = wilson_attack,
	TRUSTY_SHOOTER_ATTACK_RANGE_HIGH = 11,
	TRUSTY_SHOOTER_ATTACK_RANGE_MEDIUM = 9,
	TRUSTY_SHOOTER_ATTACK_RANGE_LOW = 7,
	TRUSTY_SHOOTER_HIT_RANGE_HIGH = 13,
	TRUSTY_SHOOTER_HIT_RANGE_MEDIUM = 11,
	TRUSTY_SHOOTER_HIT_RANGE_LOW = 9,
	TRUSTY_SHOOTER_TIERS = {
		AMMO_HIGH = {
			"gears",
			"purplegem",
			"bluegem",
			"redgem",
			"orangegem",
			"yellowgem",
			"greengem",
			"oinc10",
			"oinc100",
			"nightmarefuel",
			"gunpowder",
			"relic_1",
			"relic_2",
			"relic_3",
			"relic_4",
			"relic_5",
		}, 
		AMMO_LOW = {
			"feather_crow",
			"feather_robin",
			"feather_robin_winter",
			"feather_thunder",
			"ash",
			"beardhair",
			"beefalowool",
			"butterflywings",
			"clippings",
			"cutgrass",
			"cutreeds",
			"foliage",
			"palmleaf",
			"papyrus",
			"petals",
			"petals_evil",
			"pigskin",
			"silk",
			"seaweed",
		}, 
	}, 

	LITTLE_HAMMER_DAMAGE = wilson_attack*0.3,
	SHEARS_DAMAGE = wilson_attack * .5,
	SHEARS_USES = 20,
	MAGNIFYING_GLASS_USES = 10,
	HALBERD_DAMAGE = wilson_attack*1.3,
	HALBERD_USES = 100,
	WALKING_STICK_SPEED_MULT = 1.3,
	PIG_GUARD_DEFEND_DIST = 20,
	CITY_PIG_GUARD_TARGET_DIST = 20,  
	
	PIG_BANDIT_DAMAGE = 33,
	PIG_BANDIT_HEALTH = 250,
	PIG_BANDIT_ATTACK_PERIOD = 3,
	PIG_BANDIT_TARGET_DIST = 16,
	PIG_BANDIT_LOYALTY_MAXTIME = 2.5*total_day_time,
	PIG_BANDIT_LOYALTY_PER_HUNGER = total_day_time/25,
	PIG_BANDIT_MIN_POOP_PERIOD = seg_time * .5,
	PIG_BANDIT_RUN_SPEED = 7,
	PIG_BANDIT_WALK_SPEED = 3,
	
	
	
	THUNDERBIRD_RUN_SPEED = 5.5,
	THUNDERBIRD_WALK_SPEED = 2,
	
	LIGHTING_HITTARGET_CHANCE = 0.3,

	HONEY_LANTERN_MINE = 6,
	HONEY_LANTERN_MINE_MED = 4,
	HONEY_LANTERN_MINE_LOW = 2,
	HONEY_CHEST_MINE = 6,
	HONEY_CHEST_MINE_MED = 4,
	HONEY_CHEST_MINE_LOW = 2,
	ROCKS_MINE_GIANT = 10,

	SCARER_SPEED = 2.5, 
	GASMASK_PERISHTIME = total_day_time*3,		
	PEAGAWKHAT_PERISHTIME = total_day_time*0.9,
	PITHHAT_PERISHTIME = total_day_time*8,
	
	--PORKLAND HATS
	BANDITHAT_PERISHTIME = total_day_time*1,
	THUNDERHAT_PERISHTIME = total_day_time*4,
	THUNDERHAT_USAGE_PER_LIGHTINING_STRIKE = 0.05, -- Percent
	SNEAK_SIGHTDISTANCE = 8,
	BATHAT_PERISHTIME = total_day_time*2,
	HAYFEVERHAT_PERISHTIME = total_day_time*5,
	WALKING_STICK_PERISHTIME = total_day_time*3,
	
	FLIPPABLE_ROCK_REPOPULATE_TIME = total_day_time*8,
	FLIPPABLE_ROCK_REPOPULATE_VARIANCE = total_day_time*2,
	
	ARMORVORTEX = wilson_health*3,
	ARMORVORTEX_ABSORPTION = 1,
	ARMORVORTEX_DMG_AS_SANITY = 0.20,
	ARMORVORTEX_REFUEL_PERCENT = 0.10,

	RESEARCH_COST_CHEAP = 30,
	PERISH_APORKALYPSE_MULT = 1.5,
	SANITY_PLAYERHOUSE_GAIN = 100/(day_time*32),
	PLATEAU_SEASON_LENGTH_DEFAULT = 10,
	PLATEAU_SEASON_LENGTH_VERYSHORT = 2.5,
	PLATEAU_SEASON_LENGTH_SHORT = 6,
	PLATEAU_SEASON_LENGTH_LONG = 15,
	PLATEAU_SEASON_LENGTH_VERYLONG = 25,
	CREEPY_EYES = {
		{maxsanity=.8, maxeyes=0}, 
		{maxsanity=.6, maxeyes=2}, 
		{maxsanity=.4, maxeyes=4}, 
		{maxsanity=.2, maxeyes=6}, 
	}, 

	DIVINING_DISTANCES = {
		{maxdist=50, describe="hot", pingtime=1}, 
		{maxdist=100, describe="warmer", pingtime=2}, 
		{maxdist=200, describe="warm", pingtime=4}, 
		{maxdist=400, describe="cold", pingtime=8}, 
	}, 
	DIVINING_MAXDIST = 300,
	APORKALYPSE_GROWTH_MODIFIER = 1.5,
	
	WARBUCKS_HEALTH = 150,
	WARBUCKS_HUNGER = 120,
	WARBUCKS_SANITY = 200,
	WILBA_HEALTH = 150,
	WILBA_HUNGER = 200,
	WILBA_SANITY = 100,
	WEREWILBA_HEALTH = 350,
	WHEELER_HEALTH = 100,
	WHEELER_HUNGER = 150,
	WHEELER_SANITY = 200,
	WHEELER_DODGE_COOLDOWN = 1.5,
	DODGE_TIMEOUT = 0.25,
	
	DECID_MONSTER_DAY_THRESHOLDS = { 20, 35, 70 }, 
	DECID_MONSTER_SPAWN_CHANCE_BASE = .033,
	MOISTURE_SPRINKLER_PERCENT_INCREASE_PER_SPRAY = 0.5,
	BABYOX_GROW_TIME = {base=3*day_time, random=2*day_time}, 

	GAS_DAMAGE_PER_INTERVAL = 5, -- the amount of health damage gas causes per interval
	GAS_INTERVAL = 1, -- how frequently damage is applied
	POISON_PERISH_PENALTY = 0.5,

	CORKBOAT_HEALTH = 80,
	CORKBOAT_PERISHTIME = total_day_time*3,
	CORKBOAT_SANITY_DRAIN = 0,-- -0.08,
	CORKBOAT_SPEED = -2,
	CORKBOAT_LEAKING_HEALTH = 30,	    
	
	PLATEAU_LUSH_START_TEMP = 40, --50
	PLATEAU_LUSH_DEVIATE_TEMP = 0, --30
	PLATEAU_LUSH_DAY_TEMP_INCREASE = 20,
	PLATEAU_LUSH_NIGHT_TEMP_INCREASE = -10,
	PLATEAU_LUSH_DUSK_TEMP_INCREASE = -5,
	PLATEAU_LUSH_POLLEN_PARTICLES = 1,		
	PLATEAU_HUMID_START_TEMP = 30,
	PLATEAU_HUMID_DEVIATE_TEMP = 0,  -- -30,
	PLATEAU_HUMID_MIN_TEMP = 0,
	PLATEAU_HUMID_NIGHT_TEMP_INCREASE = -20,
	PLATEAU_HUMID_DUSK_TEMP_INCREASE = -10,
	PLATEAU_TEMPERATE_START_TEMP = 40,
	PLATEAU_DAY_TEMP = 10, --Peak temp change during the day
	PLATEAU_NIGHT_TEMP = -5, --Peak temp change during the night
	PLATEAU_HURRICANE_TEMP = -10, --Peak temp change during a hurricane
	PLATEAU_HURRICANE_WIND_TEMP = -10, --Peak temp change during hurricane wind gusts 'wind chill'		
	
	WIND_GUSTDELAY_MIN_LUSH = 15,
	WIND_GUSTDELAY_MAX_LUSH = 720,

	HYDRO_BONUS_COOL_RATE = 4,
	FLOTSAM_BATCH_SIZE = { min = 2, max = 5 }, 
	FLOTSAM_SPAWN_RADIUS = 35,
	
	BLUNDERBUSS_ATTACK_RANGE = 9,
	BLUNDERBUSS_HIT_RANGE = 11,
	
	DUNG_BEETLE_RUN_SPEED = 6, --7  
	DUNG_BEETLE_WALK_SPEED = 3.5,    --3		
	DUNG_BEETLE_HEALTH = 60,  
	
	SPIDER_MONKEY_SPEED_AGITATED = 5.5,  --4
	SPIDER_MONKEY_SPEED = 5.5, --2		
	SPIDER_MONKEY_HEALTH = 550,
	SPIDER_MONKEY_DAMAGE = 60,
	SPIDER_MONKEY_ATTACK_PERIOD = 2,
	SPIDER_MONKEY_ATTACK_RANGE = 4,
	SPIDER_MONKEY_HIT_RANGE = 3,
	SPIDER_MONKEY_MELEE_RANGE = 4,
	SPIDER_MONKEY_TARGET_DIST = 8,
	SPIDER_MONKEY_WAKE_RADIUS = 6,
	SPIDER_MONKEY_DEFEND_DIST = 12,
	SPIDER_MONKEY_MATING_SEASON_BABYDELAY = total_day_time*1.5,
	SPIDER_MONKEY_MATING_SEASON_BABYDELAY_VARIANCE = 0.5*total_day_time,
	
	RUINS_ENTRANCE_VINES_HACKS = 4,
	RUINS_DOOR_VINES_HACKS = 2,
	
	GRABBING_VINE_HEALTH = 100,
	GRABBING_VINE_DAMAGE = 10,
	GRABBING_VINE_ATTACK_PERIOD = 1,
	GRABBING_VINE_TARGET_DIST = 3,
	GRABBING_VINE_SPAWN_MIN = 6,
	GRABBING_VINE_SPAWN_MAX = 9,
	HANGING_VINE_SPAWN_MIN = 8,
	HANGING_VINE_SPAWN_MAX = 16,
	
	ZEB_DAMAGE = 20,
	ZEB_ATTACK_RANGE = 3,
	ZEB_ATTACK_PERIOD = 2,
	ZEB_WALK_SPEED = 6,
	ZEB_RUN_SPEED = 10,
	ZEB_TARGET_DIST = 5,
	ZEB_CHASE_DIST = 30,
	ZEB_FOLLOW_TIME = 30,
	ZEB_MATING_SEASON_BABYDELAY = total_day_time*1.5,
	ZEB_MATING_SEASON_BABYDELAY_VARIANCE = 0.5*total_day_time,	
	
	SCORPION_HEALTH = 200,
	SCORPION_DAMAGE = 20,
	SCORPION_ATTACK_PERIOD = 3,
	SCORPION_TARGET_DIST = 4,
	SCORPION_INVESTIGATETARGET_DIST = 6,
	SCORPION_WAKE_RADIUS = 4,
	SCORPION_FLAMMABILITY = .33,
	SCORPION_SUMMON_WARRIORS_RADIUS = 12,
	SCORPION_EAT_DELAY = 1.5,
	SCORPION_ATTACK_RANGE = 3,		
	SCORPION_STING_RANGE = 2,		
	SCORPION_WALK_SPEED = 3,
	SCORPION_RUN_SPEED = 5,
	
	SNAKE_SPEED = 3,
 	SNAKE_TARGET_DIST = 8,
 	SNAKE_KEEP_TARGET_DIST= 15,
 	SNAKE_HEALTH = 100,
 	SNAKE_DAMAGE = 10,
 	SNAKE_ATTACK_PERIOD = 3,
 	SNAKE_POISON_CHANCE = 0.25,
 	SNAKE_POISON_START_DAY = 3, -- the day that poison TUNING.SNAKEs have a chance to show up
 	SNAKEDEN_REGEN_TIME = 3,--*TUNING.SEG_TIME
 	SNAKEDEN_RELEASE_TIME = 5,
 	SNAKE_JUNGLETREE_CHANCE = 0.5, -- chance of a normal TUNING.SNAKE
 	SNAKE_JUNGLETREE_POISON_CHANCE = 0.25, -- chance of a poison TUNING.SNAKE
 	SNAKE_JUNGLETREE_AMOUNT_TALL = 2, -- num of times to try and spawn a TUNING.SNAKE from a tall tree
 	SNAKE_JUNGLETREE_AMOUNT_MED = 1, -- num of times to try and spawn a TUNING.SNAKE from a normal tree
 	SNAKE_JUNGLETREE_AMOUNT_SMALL = 1, -- num of times to try and spawn a TUNING.SNAKE from a small tree
 	SNAKEDEN_MAX_SNAKES = 3,
 	SNAKEDEN_CHECK_DIST = 20,
 	SNAKEDEN_TRAP_DIST = 2,
	
	BILL_TUMBLE_SPEED = 8,
	BILL_RUN_SPEED = 5,
	BILL_DAMAGE = wilson_attack * 0.5,
	BILL_HEALTH = 250,
	BILL_ATTACK_PERIOD = 3,
	BILL_TARGET_DIST = 50,
	BILL_AGGRO_DIST = 15,
	BILL_EAT_DELAY = 3.5,
	BILL_SPAWN_CHANCE = 0.2,
	
	GIANT_GRUB_WALK_SPEED = 2,
	GIANT_GRUB_DAMAGE = 44,
	GIANT_GRUB_HEALTH = 600,
	GIANT_GRUB_ATTACK_PERIOD = 3,
	GIANT_GRUB_ATTACK_RANGE = 3,
	GIANT_GRUB_TARGET_DIST = 25,
	
	ANTMAN_DAMAGE = wilson_attack * 2/3,
	ANTMAN_HEALTH = 250,
	ANTMAN_ATTACK_PERIOD = 3,
	ANTMAN_TARGET_DIST = 16,
	ANTMAN_LOYALTY_MAXTIME = 2.5*total_day_time,
	ANTMAN_LOYALTY_PER_HUNGER = total_day_time/25,
	ANTMAN_MIN_POOP_PERIOD = seg_time * .5,
	ANTMAN_RUN_SPEED = 5,
	ANTMAN_WALK_SPEED = 3,
	ANTMAN_MIN = 3,
	ANTMAN_MAX = 4,
	ANTMAN_REGEN_TIME = seg_time * 4,
	ANTMAN_RELEASE_TIME = seg_time,
	ANTMAN_ATTACK_ON_SIGHT_DIST = 4,
	ANTMAN_LOYALTY_PER_HUNGER = total_day_time/25,
-------------------------------------------------------------------
	ANTMAN_WARRIOR_DAMAGE = wilson_attack * 1.25,
	ANTMAN_WARRIOR_HEALTH = 300,
	ANTMAN_WARRIOR_ATTACK_PERIOD = 3,
	ANTMAN_WARRIOR_TARGET_DIST = 16,
	ANTMAN_WARRIOR_RUN_SPEED = 7,
	ANTMAN_WARRIOR_WALK_SPEED = 3.5,
	ANTMAN_WARRIOR_REGEN_TIME = seg_time,
	ANTMAN_WARRIOR_RELEASE_TIME = seg_time,
	ANTMAN_WARRIOR_ATTACK_ON_SIGHT_DIST = 8,
--------------------------------------------------------------------
	ANTQUEEN_HEALTH = 3500,
	ANCIENT_HERALD_HEALTH = 2000,
	ANCIENT_HERALD_DAMAGE = 50,
	CHICKEN_HEALTH = 100,
	CHICKEN_RESPAWN_TIME = day_time*4,
	CHICKEN_RUN_SPEED = 4,
	
	PIKO_HEALTH = 100,
	PIKO_RESPAWN_TIME = day_time*4,
	PIKO_RUN_SPEED = 4,
	PIKO_DAMAGE = 2,
	PIKO_ATTACK_PERIOD = 2,
	PIKO_TARGET_DIST = 20,
	PIKO_RABID_SANITY_THRESHOLD = 0.8,
	
	RABID_BEETLE_HEALTH = 60,
	RABID_BEETLE_DAMAGE =  10,
	RABID_BEETLE_ATTACK_PERIOD = 2,
	RABID_BEETLE_TARGET_DIST = 20,
	RABID_BEETLE_SPEED = 12,
	RABID_BEETLE_FOLLOWER_TARGET_DIST = 10,
	RABID_BEETLE_FOLLOWER_TARGET_KEEP = 20,
	
	DECO_RUINS_BEAM_WORK = 6,
	
	PEAGAWK_DAMAGE = 20,
	PEAGAWK_HEALTH = 50,
	PEAGAWK_ATTACK_PERIOD = 3,
	PEAGAWK_RUN_SPEED = 8,
	PEAGAWK_WALK_SPEED = 3,
	PEAGAWK_REGROW_TIME =  total_day_time,
	PEAGAWK_PICKTIMER = 180,
	PEAGAWK_PRISM_STOP_TIMER = 45,
	PEAGAWK_TAIL_FEATHERS_MAX = 7,
	PEAGAWK_REGEN_TIME = total_day_time * 10,
    PEAGAWK_RELEASE_TIME = 5,
    PEAGAWK_MAX = 1,
    PEAGAWK_ENABLED = true,
	
	VAMPIREBAT_HEALTH = 130,
	VAMPIREBAT_DAMAGE = 25,
	VAMPIREBAT_ATTACK_PERIOD = 1.8,
	VAMPIREBAT_WALK_SPEED = 10, -- 8?
	
	FLYTRAP_CHILD_HEALTH = 250,
	FLYTRAP_CHILD_DAMAGE = 15,
	FLYTRAP_CHILD_SPEED = 4,   
	FLYTRAP_TEEN_HEALTH = 300,
	FLYTRAP_TEEN_DAMAGE = 20,
	FLYTRAP_TEEN_SPEED = 3.5,
	FLYTRAP_HEALTH = 350,
	FLYTRAP_DAMAGE = 25,
	FLYTRAP_SPEED = 3,
	FLYTRAP_TARGET_DIST = 8,
	FLYTRAP_KEEP_TARGET_DIST= 15,
	FLYTRAP_ATTACK_PERIOD = 3,
	
	ADULT_FLYTRAP_HEALTH = 400,
	ADULT_FLYTRAP_DAMAGE = 30,
	ADULT_FLYTRAP_ATTACK_PERIOD = 5,
	ADULT_FLYTRAP_ATTACK_DIST = 4,
	ADULT_FLYTRAP_STOPATTACK_DIST = 6,
	
	LOTUS_REGROW_TIME = total_day_time*5,
	
	MANDRAKEMAN_DAMAGE = 40,
	MANDRAKEMAN_HEALTH = 200,
	MANDRAKEMAN_ATTACK_PERIOD = 2,	   
	MANDRAKEMAN_RUN_SPEED = 6,
	MANDRAKEMAN_WALK_SPEED = 3,
	MANDRAKEMAN_PANIC_THRESH = .333,
	MANDRAKEMAN_HEALTH_REGEN_PERIOD = 5,
	MANDRAKEMAN_HEALTH_REGEN_AMOUNT = (200/120)*5,
	MANDRAKEMAN_SEE_MANDRAKE_DIST = 8,
	MANDRAKEMAN_TARGET_DIST = 10,
	MANDRAKEMAN_DEFEND_DIST = 30,
	
	HOME_RESEARCH_MACHINE_DIST = 30,
	BRAMBLE_THORN_DAMAGE = 3,

	FOG_GROGGY_SPEED_MOD = .7,
	
	HIPPO_DAMAGE = 50,
	HIPPO_HEALTH = 500,
	HIPPO_ATTACK_PERIOD = 2,
	HIPPO_WALK_SPEED = 5,
	HIPPO_RUN_SPEED = 6,
	HIPPO_TARGET_DIST = 12,
	
	PUGALISK_HEALTH = 3000,
	PUGALISK_ATTACK_PERIOD = 3,
	PUGALISK_MELEE_RANGE = 6,
	PUGALISK_DAMAGE = 200,
	PUGALISK_TARGET_DIST = 40,
	PUGALISK_TAIL_TARGET_DIST = 6,
	PUGALISK_RUINS_PILLAR_WORK = 3,
	
	DISARMINGKIT_USES = 10,
	SPEAR_TRAP_HEALTH = 100,
	SPEAR_TRAP_DAMNAGE = wilson_attack,
	CLAWPALMTREE_GROW_TIME = {
		{base = 8 * day_time, random = 0.5 * day_time},  --tall to short
		{base = 12 * day_time, random = 5 * day_time},  --short to normal
		{base = 12 * day_time, random = 5 * day_time},  --normal to tall
	}, 
	
    WEEVOLE_WALK_SPEED = 5,
    WEEVOLE_HEALTH = 150,
    WEEVOLE_DAMAGE = 6,
    WEEVOLE_PERIOD_MIN = 4,
    WEEVOLE_PERIOD_MAX = 5,
    WEEVOLE_ATTACK_RANGE = 5,
    WEEVOLE_HIT_RANGE = 1.5,
    WEEVOLE_MELEE_RANGE = 1.5,
    WEEVOLE_RUN_AWAY_DIST = 3,
    WEEVOLE_STOP_RUN_AWAY_DIST = 5,
    WEEVOLE_TARGET_DIST = 6,
    WEEVOLE_SHARE_TARGET_RANGE = 30,
    WEEVOLE_SHARE_MAX_NUM = 10,
	WEEVOLE_ENABLED = true,
	
    WEEVOLEDEN_REGEN_TIME = TUNING.SEG_TIME * 3,
    WEEVOLEDEN_RELEASE_TIME = 5,
    WEEVOLEDEN_MAX_WEEVOLES = 3, 
	
	ARMOR_WEEVOLE_DURABILITY = wilson_health*6,
	ARMOR_WEEVOLE_ABSORPTION = .65,
	
	CANDLEHAT_LIGHTTIME = night_time*2,
	ANTMASKHAT_PERISHTIME = total_day_time*10,
	ANTSUIT_PERISHTIME = total_day_time*10,
	ROBOT_TARGET_DIST = 15,  
	ROBOT_RIBS_DAMAGE = wilson_attack,
	ROBOT_RIBS_HEALTH = 1000,
	ROBOT_LEG_DAMAGE = wilson_attack*2,
	LASER_DAMAGE = 20,
	PAN_USES = 30,
	
	POG_ATTACK_RANGE = 3,
	POG_MELEE_RANGE = 2.5,
	POG_TARGET_DIST = 25,
	POG_WALK_SPEED = 2,
	POG_RUN_SPEED = 4.5,
	POG_DAMAGE = 25,
	POG_HEALTH = 150,
	POG_ATTACK_PERIOD = 2,
	POG_EAT_DELAY = 0.5,
	POG_SEE_FOOD = 30,
	
	MIN_POGNAP_INTERVAL = 30,
	MAX_POGNAP_INTERVAL = 120,
	MIN_POGNAP_LENGTH = 20,
	MAX_POGNAP_LENGTH = 40,		
	POG_LOYALTY_MAXTIME = total_day_time,
	POG_LOYALTY_PER_ITEM = total_day_time*.1,

	PANGOLDEN_HEALTH = 500,
	PANGOLDEN_DAMAGE = 34,	 
	PANGOLDEN_TARGET_DIST = 5,
	PANGOLDEN_CHASE_DIST = 30,	  
	PANGOLDEN_BALL_DEFENCE = 0.75,  
	-- PANGOLDEN_CHASE_DIST = 30,
	-- PANGOLDEN_FOLLOW_TIME = 30,
	-- INTERIOR ROOM SIZES
	
	ROOM_TINY_WIDTH   = 15,
	ROOM_TINY_DEPTH   = 10,
	ROOM_SMALL_WIDTH  = 18,
	ROOM_SMALL_DEPTH  = 12,
	ROOM_MEDIUM_WIDTH = 24,
	ROOM_MEDIUM_DEPTH = 16,
	ROOM_LARGE_WIDTH  = 26,
	ROOM_LARGE_DEPTH  = 18,
	ROC_SPEED = 20,
	ROC_SHADOWRANGE = 8,
	ROC_LEGDSIT = 6,
	
	GNATMOUND_REGEN_TIME = seg_time * 4,
	GNATMOUND_RELEASE_TIME = seg_time,
	GNATMOUND_MAX_WORK	= 6,
	GNATMOUND_MAX_CHILDREN	= 1,
	
	GNAT_WALK_SPEED = 2,
	GNAT_RUN_SPEED = 7,
	
	ROBIN_HATCH_TIME = total_day_time * 3,
	ARMORMETAL = wilson_health*8,
	ARMORMETAL_ABSORPTION = .85,
	ARMORMETAL_SLOW = -0.10,
	ARMOR_KNIGHT = wilson_health*8,
	ARMOR_KNIGHT_ABSORPTION = .85,
	SPRINKLER_MAX_FUEL_TIME = total_day_time,
	BUGREPELLENT_USES = 20,
	MOSQUITO_MAX_SPAWN = 1,
	MOSQUITO_REGEN_TIME = day_time/2,
	FROG_POISON_MAX_SPAWN = 1,
	FROG_POISON_REGEN_TIME = day_time/2,
	PIGHOUSE_CITY_RESPAWNTIME = total_day_time*3,
	GUARDTOWER_CITY_RESPAWNTIME = total_day_time*3,
	NETTLE_REGROW_TIME = total_day_time*3,
	NETTLE_MOISTURE_WET_THRESHOLD = 20,
	NETTLE_MOISTURE_DRY_THRESHOLD = 10,
	BIRDWHISLE_USES = 5,
	SADDLEHORN_USES = 10,
	PINNABLE_RECOVERY_LEEWAY = 1.5,
	FIRECRACKERS_STARTLE_RANGE = 10,
	FIRECRACKERS_FUSE = 2,
	ARMORBRAMBLE_DMG = wilson_attack/1.5,
	ARMORBRAMBLE_ABSORPTION = .8,
	ARMORBRAMBLE = wilson_health * 3,
	TRAP_BRAMBLE_USES = 10,
	TRAP_BRAMBLE_DAMAGE = 40,
	TRAP_BRAMBLE_RADIUS = 2.5,
	GOGGLES_HEAT_PERISHTIME = 2*total_day_time,
	GOGGLES_ARMOR_ARMOR = wilson_health*4,
	GOGGLES_SHOOT_USES = 10,
	GOGGLES_HEAT= {
		HOT= {
			MULT_COLOUR = {0.0, 1.0, 0.5, 1.0}, 
			ADD_COLOUR  = {1.0, 0.1, 0.3, 1.0}, 
		}, 
		COLD= {
			DESATURATION = 0.7,
			MULT_COLOUR = {0.0, 0.0, 0.3, 1.0}, 
			ADD_COLOUR  = {0.1, 0.1, 0.5, 1.0}, 
		}, 
		GROUND= {
			MULT_COLOUR = {0.0, 0.1, 0.3, 1.0}, 
			ADD_COLOUR  = {0.1, 0.1, 0.5, 1.0}
		}, 
		WAVES= {
			MULT_COLOUR = {0.0, 0.0, 0.3, 1.0}, 
			ADD_COLOUR  = {0.1, 0.1, 0.6, 1.0}, 
		}, 
		BLUR= {
			STRENGTH = 0.16,
		}, 
	}, 

	NEARSIGHTED_ACTION_RANGE = 4,
	ANCIENT_HULK_DAMAGE = 200,
	ANCIENT_HULK_MINE_DAMAGE = 100,
	ANCIENT_HULK_MELEE_RANGE = 5.5,
	ANCIENT_HULK_ATTACK_RANGE = 5.5,
	IRON_LORD_DAMAGE = wilson_attack*2,
	IRON_LORD_TIME = 3*60,
	INFUSED_IRON_PERISHTIME = total_day_time*2,
	
	-- Note: in DS the following two values are 1.5 and 2.0 by default but they get overriden manually in the porkland prefab -Half
    RAINFOREST_CANOPY_ROTATION_SPEED = 5,	        -- 5 seconds per rotation
    RAINFOREST_CANOPY_TRANSLATION_SPEED = 5,	    -- 5 seconds per translation
    RAINFOREST_CANOPY_MAX_ROTATION = 20,			-- max 20 degrees from base rotation
    RAINFOREST_CANOPY_MAX_TRANSLATION = 1,		    -- max 1 world unit from base position
    RAINFOREST_CANOPY_SCALE = 6,				    -- scale for the texture
    RAINFOREST_CANOPY_MIN_STRENGTH = 0.2,		    -- blend min strength - modulated with avg ambient
    RAINFOREST_CANOPY_MAX_STRENGTH = 0.7,		    -- blend max strength - modulated with avg ambient
	
	
}

for key, value in pairs(tuning) do
    if TUNING[key] then
        print("OVERRIDE: " .. key .. " in TUNING")
    end

    TUNING[key] = value
end
