local DecoCreator = require("prefabs/deco_util")

return  DecoCreator:Create("deco_plantholder_basic",                    "interior_plant",       "interior_plant",       "plant_basic",                    {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_wip",                      "interior_plant",       "interior_plant",       "plant_wip",                      {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_fancy",                    "interior_plant",       "interior_plant",       "plant_fancy",                    {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_bonsai",                   "interior_plant",       "interior_plant",       "plant_bonsai",                   {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_dishgarden",               "interior_plant",       "interior_plant",       "plant_dishgarden",               {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_philodendron",             "interior_plant",       "interior_plant",       "plant_philodendron",             {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_orchid",                   "interior_plant",       "interior_plant",       "plant_orchid",                   {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_draceana",                 "interior_plant",       "interior_plant",       "plant_draceana",                 {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_xerographica",             "interior_plant",       "interior_plant",       "plant_xerographica",             {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_birdcage",                 "interior_plant",       "interior_plant",       "plant_birdcage",                 {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_palm",                     "interior_plant",       "interior_plant",       "plant_palm",                     {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_zz",                       "interior_plant",       "interior_plant",       "plant_zz",                       {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_fernstand",                "interior_plant",       "interior_plant",       "plant_fernstand",                {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_fern",                     "interior_plant",       "interior_plant",       "plant_fern",                     {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_terrarium",                "interior_plant",       "interior_plant",       "plant_terrarium",                {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_plantpet",                 "interior_plant",       "interior_plant",       "plant_plantpet",                 {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_traps",                    "interior_plant",       "interior_plant",       "plant_traps",                    {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_pitchers",                 "interior_plant",       "interior_plant",       "plant_pitchers",                 {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_marble",                   "interior_floor_decor", "interior_floor_decor", "plant",                          {tags={"furniture", "rotatableobject"}, onbuilt=true }),
        DecoCreator:Create("deco_plantholder_winterfeasttreeofsadness", "interior_plant",       "interior_plant",       "plant_winterfeasttreeofsadness", {tags={"furniture", "rotatableobject"}, onbuilt=true })
