local DecoCreator = require("prefabs/deco_util")

return  DecoCreator:Create("swinging_light_basic_bulb",          "ceiling_lights", "ceiling_lights", "light_basic_bulb",         {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_floral_bloomer",      "ceiling_lights", "ceiling_lights", "light_floral_bloomer",     {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_basic_metal",         "ceiling_lights", "ceiling_lights", "light_basic_metal",        {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_chandalier_candles",  "ceiling_lights", "ceiling_lights", "light_chandelier_candles", {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_rope_1",              "ceiling_lights", "ceiling_lights", "light_rope1",              {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_rope_2",              "ceiling_lights", "ceiling_lights", "light_rope2",              {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_floral_bulb",         "ceiling_lights", "ceiling_lights", "light_floral_bulb",        {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_pendant_cherries",    "ceiling_lights", "ceiling_lights", "light_pendant_cherries",   {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_floral_scallop",      "ceiling_lights", "ceiling_lights", "light_floral_scallop",     {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_floral_bloomer",      "ceiling_lights", "ceiling_lights", "light_floral_bloomer",     {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_tophat",              "ceiling_lights", "ceiling_lights", "light_tophat",             {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_derby",               "ceiling_lights", "ceiling_lights", "light_derby",              {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true }),
        DecoCreator:Create("swinging_light_bank",                "ceiling_lights", "ceiling_lights", "light_bank",               {--[[decal=true,]] loopanim=true, light=true, followlight ="electric_1", tags={"NOBLOCK", "NOCLICK", "centerlight"}, onbuilt=true })