name: Bug Report
description: A bug that shouldn't have happend
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: This will be automatically formatted into code, so no need for backticks.
      render: text
