GLOBAL.STRINGS.ANTNAMES={}
for i=1, 100 do
    table.insert(GLOBAL.STRINGS.ANTNAMES,"Drone #"..math.random(1,1000000))
end

GLOBAL.STRINGS.ANTWARRIORNAMES = {}
for i=1, 100 do
    table.insert(GLOBAL.STRINGS.ANTWARRIORNAMES,"Warrior #"..math.random(1,1000000))
end

return {
    ACTIONS = {
        HACK = "Hack",
        PAN = "Pan",
        PICK = {
            FLIP = "Flip",
            DIGIN = "Dig in",
        },
        PICKUP = {
            SHELF = "Take",
        },
        GIVE = {
            SHELF = "Put",
        },
        ACTIVATE = {
            FOUNTAIN = "Steal from {name}",
        },
        OPEN_CRAFTING = {
            CITY = "Start Planning",
        },
        BUILD_ROOM = "Build Room",
        DEMOLISH_ROOM = "Demolish Room",
        INVESTIGATE = "Investigate",
        SHOP = "Purchase",
        SHEAR = "Shear",
        SMELT = "Smelt",
        SHOP_LONG = "Buy {wantitem}\nfor {qty} {payitem}",
        SHOP_TAKE = "Steal {wantitem}",
        RENOVATE = "Renovate",
        DISARM = "Disarm",
        REARM = "Rearm",
        WEIGHDOWN = "Weigh Down",
        DISLODGE = "Chisel",
        GAS = "Gas",
        SPY = "Investigate",
        USEDOOR = "Enter",
    },
    NAMES = {
        CAVE_EXIT_ROC = "Stone Plug",

        ADULT_FLYTRAP = "Snaptooth Flytrap",
        ALLOY = "Alloy",
        ALOE = "Aloe",
        ALOE_COOKED = "Cooked Aloe",
        ALOE_PLANTED = "Aloe",
        ALOE_SEEDS = "Aloe Seeds",
        ANCIENT_HERALD = "Ancient Herald",
        ANCIENT_HULK = "Large Iron Hulk",
        ANCIENT_REMNANT = "Dark Tatters",
        ANCIENT_ROBOTS_ASSEMBLY = "Large Iron Hulk",
        ANCIENT_ROBOT_CLAW = "Iron Hulk",
        ANCIENT_ROBOT_HEAD = "Iron Hulk",
        ANCIENT_ROBOT_LEG = "Iron Hulk",
        ANCIENT_ROBOT_RIBS = "Iron Hulk",
        ANTCHEST = "Honey Chest",
        ANTCOMBHOME = "Antcomb Home",
        ANTHILL = "Mant Hill",
        ANTLER = "Bird Whistle",
        ANTLER_CORRUPTED = "Nightmarish Bird Whistle",
        ANTMAN_WARRIOR = "Mant Warrior",
        ANTMAN_WARRIOR_EGG = "Mant Warrior Egg",
        ANTMASKHAT = "Mant Mask",
        ANTQUEEN = "Queen Womant",
        ANTQUEEN_CHAMBERS = "Queen Womant Chambers",
        ANTQUEEN_THRONE = "Stalacmite Throne",
        ANTSUIT = "Mant Suit",
        ANT_CAVE_LANTERN = "Lamp",
        APORKALYPSE_CLOCK = "Aporkalypse Calendar",
        ARMORVORTEXCLOAK = "Vortex Cloak",
        ARMOR_BRAMBLE = "Bramble Husk",
        ARMOR_METALPLATE = "Tin Suit",
        ARMOR_WEEVOLE = "Weevole Mantle",
        ASPARAGUS = "Asparagus",
        ASPARAGUSSOUP = "Asparagus Soup",
        ASPARAGUS_COOKED = "Cooked Asparagus",
        ASPARAGUS_PLANTED = "Asparagus",
        ASPARAGUS_SEEDS = "Asparagus Seeds",
        BALLPEIN_HAMMER = "Ball Pein Hammer",
        BANDITHAT = "Swashy Hat",
        BANDITMAP = "Bandit Stash Map",
        BANDITTREASURE = "Secret Bandit Camp",
        BASEFAN = "Oscillating Fan",
        BATHAT = "Cowl",
        BAT_HIDE = "Pig Skin?",
        BILL = "Platapine",
        BILL_QUILL = "Platapine Quill",
        BLUNDERBUSS = "Blunderbuss",
        BOAT_TORCH ="Boat Torch",
        BOATREPAIRKIT = "Boat Repair Kit",
        BONESTAFF = "Pugalisk Wand",
        BRAMBLESPIKE = "Brambles",
        BRAMBLE_BULB = "Bramble Bulb",
        BRAMBLE_CORE = "Bramble Bloom",
        BUGREPELLENT = "Bug B'Gone",
        BURR = "Jungle Burr",
        BURR_SAPLING = "Rainforest Tree Sapling",
        CANDLEHAT = "Cork Candle Hat",
        CHICKEN = "Chicken",
        CHITIN = "Chitin",
        COFFEE = "Coffee",
        COFFEEBEANS = "Coffee Beans",
        COFFEEBEANS_COOKED = "Roasted Coffee Beans",
        CITY_HAMMER = "Executive Hammer",
        CITY_LAMP = "Lamp Post",
        CLAWPALMTREE = "Claw Palm Tree",
        CLAWPALMTREE_SAPLING = "Claw Palm Sapling",
        CLIPPINGS = "Clippings",
        COMPOSTWRAP = "Compost Wrap",
        CONSTRUCTION_PERMIT = "Building Permit",
        CONSTRUCTION_PERMIT = "House Expansion Permit",
        CORK = "Cork",
        CORKBOAT = "Cork Bowl Canoe",
        CORKCHEST = "Cork Barrel",
        CORK_BAT = "Cork Bat",
        CUTNETTLE = "Nettle",
        DECO_CAVE_BAT_BURROW = "Spooky Hole",
        DECO_CAVE_BEAM_ROOM = "Unimportant Rock Pillar",
        DECO_RUINS_BEAM_ROOM = "Unimportant Pillar",
        DECO_RUINS_BEAM_ROOM_BLUE = "Unimportant Pillar",
        DECO_RUINS_ENDSWELL = "End's Well",
        DECO_RUINS_FOUNTAIN = "Wishing Well",
        DEED = "Deed of Home Ownership",
        DEFLATED_BALLOON = "Deflated Balloon",
        DEFLATED_BALLOON_BASKET = "Wicker Basket",
        DEMOLITION_PERMIT = "Demolition Permit",
        DISARMING_KIT = "Disarming Tools",
        DISGUISEHAT = "Shamlet Mask",
        DUG_NETTLE = "Nettle Plant",
        DUG_NETTLE = "Nettle Plant",
        DUNGBALL = "Dung Ball",
        DUNGBEETLE = "Dung Beetle",
        DUNGPILE = "Dung Pile",
        FEATHER_THUNDER = "Thunder Feather",
        FEIJOADA = "Feijoada",
        FIRECRACKERS = "Firecrackers",
        FISH_KOI = "Koi",
        FLOWER_RAINFOREST = "Exotic Flower",
        FROGLEGS_POISON = "Poison Dartfrog Legs",
        FROGLEGS_POISON_COOKED = "Cooked Dartfrog Legs",
        GASCLOUD = "Noxious Cloud",
        GASMASKHAT = "Gas Mask",
        GIANTGRUB = "Giant Grub",
        GLOWFLY = "Glowfly",
        GLOWFLY_COCOON = "Glowfly Cocoon",
        GOLDENMACHETE = "Luxury Machete",
        GNAT = "Gnat Swarm",
        GNATMOUND = "Gnat Mound",
        GOGGLESARMORHAT = "Visor",
        GOGGLESHEATHAT = "Infroggles",
        GOGGLESNORMALHAT = "Spectoggles",
        GOGGLESSHOOTHAT = "Fryfocals",
        GOLDPAN = "Gold Pan",
        GOLD_DUST = "Gold Dust",
        GRABBING_VINE = "Hanging Vine",
        GRASS_TALL = "Tall Grass",
        GUMMY_CAKE = "Gummy Cake",
        HALBERD = "Halberd",
        HANGING_VINE = "Hanging Vine",
        HARDSHELL_TACOS = "Hard Shell Tacos",
        HAT_PIGCROWN = "Regal Scepter",
        HEDGE = "Hedge",
        HIPPOPOTAMOOSE = "Hippopotamoose",
        HIPPO_ANTLER = "Hippopotamoose Antler",
        HOGUSPORKUSATOR = "Hogus Porkusator",
        ICEDTEA = "Iced Tea",
        INFUSED_IRON = "Infused Iron",
        IRON = "Iron Ore",
        MACHETE = "Machete",
        JELLYBUG = "Bean Bugs",
        JELLYBUG_COOKED = "Cooked Bean Bugs",
        KEY_TO_CITY = "Key to the City",
        KINGFISHER = "Kingfisher",
        LAWNORNAMENT = "Lawn Decoration",
        LIFEPLANT = "Magic Flower",
        LILYPAD = "Giant Lily Pad",
        LILYPAD = "Lily Pad",
        LIVING_ARTIFACT = "Living Artifact",
        LOTUS = "Lotus Plant",
        LOTUS_FLOWER ="Lotus Flower",
        LOTUS_FLOWER_COOKED ="Cooked Lotus Root",
        MAGNIFYING_GLASS = "Magnifying Glass",
        MANDRAKEHOUSE = "Mandrake Hill",
        MANDRAKEMAN = "Elder Mandrake",
        MEAN_FLYTRAP = "Snaptooth Seedling",
        MEATED_NETTLE = "Meated Nettles",
        METALPLATEHAT = "Fancy Helmet",
        NECTAR_POD = "Nectar",
        NETTLE = "Nettle Vine",
        NETTLELOSANGE = "Nettle Rolls",
        OINC = "Oinc",
        OINC10 = "Tenpiece Oinc",
        OINC100 = "Centapiece Oinc",
        OINC_PL = "Oincs",
        PANGOLDEN = "Pangolden",
        PARROT_BLUE = "Parrot",
        PEAGAWK = "Peagawk",
        PEAGAWKFEATHER = "Peagawk Plume",
        PEAGAWKFEATHERHAT = "Peagawk Hat",
        PEAGAWKFEATHER_PRISM = "Vibrant Peagawk Plume",
        PEAGAWK_BUSH = "Blinkbush",
        PEDESTAL_KEY = "Royal Gallery Key",
        PEEKHEN = "Peep Hen",
        PHEROMONESTONE = "Pherostone",
        PHLEGM = "Phlegm",
        PIGBANDIT = "Masked Pig",
        PIGCROWNHAT = "Royal Crown",
        PIGEON = "Pigeon",
        PIGGHOST ="Ancient Spirit",
        PIGHOUSE_CITY = "Town House",
        PIGHOUSE_FARM = "Farm House",
        PIGHOUSE_MINE = "Quarry Lodgings",
        PIGMAN_BANKER = "Banker",
        PIGMAN_BEAUTICIAN = "Beautician",
        PIGMAN_COLLECTOR = "Collector",
        PIGMAN_FARMER = "Farmer",
        PIGMAN_FLORIST = "Florist",
        PIGMAN_MAYOR = "Mayor Truffleston",
        PIGMAN_MECHANIC = "Worker",
        PIGMAN_MINER = "Miner",
        PIGMAN_QUEEN = "Pig Queen",
        PIGMAN_ROYALGUARD = "Royal Guard",
        PIGMAN_STOREOWNER = "Shopkeep",
        PIG_COIN = "Sty Piece",
        PIG_GUARD_TOWER ="Watch Tower",
        PIG_GUARD_TOWER_PALACE ="Watch Tower",
        PIG_LATIN_1 = "Some strange pig scrawl",
        PIG_RUINS_ARTICHOKE = "Crumbling Carved Stone",
        PIG_RUINS_CREEPING_VINES = "Vines",
        PIG_RUINS_DART_STATUE = "Striking Statue",
        PIG_RUINS_DART_TRAP = "Striking Carving",
        PIG_RUINS_ENTRANCE = "Ruinous Entrance",
        PIG_RUINS_ENTRANCE2 = "Ruinous Entrance",
        PIG_RUINS_ENTRANCE3 = "Ruinous Entrance",
        PIG_RUINS_ENTRANCE4 = "Ruinous Entrance",
        PIG_RUINS_ENTRANCE5 = "Ruinous Entrance",
        PIG_RUINS_ENTRANCE_SMALL = "Ruinous Entrance",
        PIG_RUINS_EXIT = "Ruinous Entrance",
        PIG_RUINS_EXIT2 = "Ruinous Entrance",
        PIG_RUINS_EXIT4 = "Ruinous Entrance",
        PIG_RUINS_EXTRACTED = "Chiseled Stone",
        PIG_RUINS_HEAD = "Crumbling Visage",
        PIG_RUINS_IDOL = "Tempting Idol",
        PIG_RUINS_MUSHROOM = "The Jeweled Truffle",
        PIG_RUINS_PIG = "Crumbling Icon",
        PIG_RUINS_PLAQUE = "Eroding Totem",
        PIG_RUINS_PRESSURE_PLATE = "Suspicious Stone",
        PIG_RUINS_SOW = "The Blue Sow",
        PIG_RUINS_SPEAR_TRAP = "Decorative Holes?",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "Busted Spear Trap",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Nasty Spear Trap",
        PIG_RUINS_TORCH = "Crumbling Brazier",
        PIG_RUINS_TORCH_WALL = "Wall Brazier",
        PIG_SCEPTER = "Regal Scepter",
        PIG_SCEPTER = "Royal Scepter",
        PIG_SHOP_ACADEMY = "Swinesbury Academy",
        PIG_SHOP_ANTIQUITIES = "'The Sty' Oddities Emporium",
        PIG_SHOP_ARCANE = "The Flying Pig \nArcane Shop",
        PIG_SHOP_BANK = "Swinesbury Mineral Exchange",
        PIG_SHOP_CITYHALL = "Swinesbury City Hall",
        PIG_SHOP_CITYHALL_PLAYER = "My City Hall",
        PIG_SHOP_DELI = "The Sterling Trough Deli",
        PIG_SHOP_FLORIST = "Miss Sow's\nFloral Arrangements",
        PIG_SHOP_GENERAL = "Pigg and Pigglet's\nGeneral Store",
        PIG_SHOP_HATSHOP = "The Sow's Ear \nHat Shop",
        PIG_SHOP_HOOFSPA = "Curly Tails\nMud Spa",
        PIG_SHOP_PRODUCE = "Swinesbury Fine Grocer's",
        PIG_SHOP_TINKER = "The Tinkerer's Tower",
        PIG_SHOP_WEAPONS = "The Boar's Tusk \nWeapon Shop",
        PIG_PALACE = "Palace",
        PIKO = "Piko",
        PIKO_ORANGE = "Orange Piko",
        PITHHAT = "Pith Hat",
        POG = "Pog",
        POISON = "Poison",
        POISONBALM = "Poison Balm",
        PORKLAND_ENTRANCE = "Skyworthy",
        PORKLAND_EXIT = "Skyworthy",
        PORKLAND_INTRO = "Maxameleon",
        PORKLAND_INTRO_BALLOON = "Deflated Balloon",
        PORKLAND_INTRO_BASKET = "Wicker Basket",
        PORKLAND_INTRO_FLAGS = "Useless Flags",
        PORKLAND_INTRO_SANDBAG = "Bag of Sand",
        PORKLAND_INTRO_SUITCASE = "Monogrammed Luggage",
        PORKLAND_INTRO_TRUNK = "Monogrammed Luggage",
        PROP_DOOR = "Door",
        PUGALISK = "Pugalisk",
        PUGALISK_CORPSE = "Petrifying Bones",
        PUGALISK_FOUNTAIN = "Fountain of Youth",
        PUGALISK_RUINS_PILLAR = "Teetering Pillar",
        PUGALISK_SKULL = "Pugalisk Skull",
        PUGALISK_TRAP_DOOR = "Ominous Carving",
        RABID_BEETLE = "Rabid Beetle",
        RADISH = "Radish",
        RADISH_COOKED = "Cooked Radish",
        RADISH_PLANTED = "Radish",
        RADISH_SEEDS = "Radish Seeds",
        RAINFORESTTREE = "Rainforest Tree",
        RAINFORESTTREE_ROT = "Sick Rainforest Tree",
        REEDS_WATER = "Reeds",
        RELIC_1 = "Lost Idol",
        RELIC_2 = "Lost Totem",
        RELIC_3 = "Relic Fragment",
        RELIC_4 = "The Blue Sow",
        RELIC_5 = "The Jeweled Truffle",
        ROCK_ANTCAVE = "Stalagmite",
        ROCK_BASALT = "Basalt Eruption",
        ROCK_FLIPPABLE = "Stone Slab",
        ROC_HEAD = "BFB",
        ROC_LEG = "BFB",
        ROC_NEST_BRANCH1 = "Weathered Branch",
        ROC_NEST_BRANCH2 = "Weathered Branch",
        ROC_NEST_BUSH = "Weathered Shrub",
        ROC_NEST_DEBRIS1 = "Weathered Stick",
        ROC_NEST_DEBRIS2 = "Weathered Stick",
        ROC_NEST_DEBRIS3 = "Weathered Stick",
        ROC_NEST_DEBRIS4 = "Weathered Stick",
        ROC_NEST_EGG1 = "Petrified Egg",
        ROC_NEST_EGG2 = "Petrified Egg",
        ROC_NEST_EGG3 = "Petrified Egg",
        ROC_NEST_EGG4 = "Petrified Egg",
        ROC_NEST_HOUSE = "Weathered House",
        ROC_NEST_RUSTY_LAMP = "Rusty Lamp",
        ROC_NEST_TREE1 = "Weathered Tree",
        ROC_NEST_TREE2 = "Weathered Tree",
        ROC_NEST_TRUNK = "Weathered Trunk",
        ROC_ROBIN_EGG = "Stone Egg",
        ROC_TAIL = "BFB",
        ROOTTRUNK_CHILD = "Root Trunk",
        ROYAL_GALLERY = "Royal Gallery Exhibit",
        RO_BIN = "Ro Bin",
        RO_BIN_GIZZARD_STONE = "Ro Bin Gizzard Stone",
        RUINS_ARTICHOKE = "Old Statue",
        RUIN_GIANT_HEAD = "Massive Statue",
        SCORPION = "Scorpion",
        SECURITYCONTRACT = "Security Contract",
        SEDIMENTPUDDLE = "Sparkling Pool",
        SHEARS = "Shears",
        SHOP_BUYER = "",
        SHOP_SELLER = "Sell",
        SHOP_TRINKET = "Valuable Beads",
        SILVERNECKLACE = "Silver Necklace",
        SLUGBUG = "Gummy Slug",
        SLUGBUG_COOKED = "Cooked Gummy Slug",
        SMASHINGPOT = "A Smashing Pot",
        SMELTER = "Smelter",
        SNAKE_BONE = "Snake Bone",
        SNAKEBONESOUP = "Snake Bone Soup",
        SNAKE_AMPHIBIOUS = "Viper",
        SNAKE_FIRE = "Fire Snake",

        ARMOR_SNAKESKIN = "Snakeskin Jacket",
        SNAKESKINHAT = "Snakeskin Hat",
        SNAKESKIN = "Snakeskin",
        SNAKESKINSAIL = "Snakeskin Sail",

        SNAPDRAGON = "Snap Dragon",
        SPICYVEGSTINGER = "Spicy Vegetable Stinger",
        SPIDER_MONKEY = "Spider Monkey",
        SPIDER_MONKEY_TREE = "Cocooned Tree",
        SPRINKLER = "Sprinkler",
        STEAMEDHAMSANDWICH = "Steamed Ham Sandwich",
        SUNKEN_RELIC = "Sunken Object",
        TEA = "Tea",
        TEATREE = "Tea Tree",
        TEATREE_NUT = "Seed Pod",
        TEATREE_NUT_COOKED = "Cooked Seed Pod",
        TEATREE_NUT_SAPLING = "Tea Tree Sapling",
        TELEBRELLA = "Telebrella",
        TELIPAD = "Telipad",
        THUMPER = "Thumper",
        THUNDERBIRD = "Thunderbird",
        THUNDERBIRDNEST = "Thundernest",
        THUNDERHAT = "Thunderhat",
        TOPIARY = "Intricate Topiary",
        TRAP_BRAMBLE = "Bramble Trap",
        TREE_PILLAR = "Great Leafy Stalk",
        TRINKET_GIFTSHOP_1 = "Queen Malfalfa",
        TRINKET_GIFTSHOP_3 = "Post Card of the Royal Palace",
        TRINKET_GIFTSHOP_4 = "Can of Silly String",
        TRUSTY_SHOOTER = "Pew-matic Horn",
        TUBERTREE = "Tuber Tree",
        TUBER_BLOOM_CROP = "Blooming Tuber",
        TUBER_BLOOM_CROP_COOKED = "Fried Blooming Tuber",
        TUBER_CROP = "Tuber",
        TUBER_CROP_COOKED = "Fried Tuber",
        TURF_BEARD_HAIR = "Beard Hair Rug",
        TURF_COBBLEROAD = "Stone Road Turf",
        TURF_DEEPRAINFOREST = "Dense Rainforest Turf",
        TURF_DEEPRAINFOREST_NOCANOPY = "Dense Turf",
        TURF_FIELDS = "Cultivated Turf",
        TURF_FOUNDATION = "Flat Stone Turf",
        TURF_GASJUNGLE = "Toxic Turf",
        TURF_LAWN = "Lawn Turf",
        TURF_MOSS = "Mossy Turf",
        TURF_PIGRUINS = "Ancient Stone Turf",
        TURF_RAINFOREST = "Rainforest Turf",
        VAMPIREBAT = "Vampire Bat",
        VAMPIREBATCAVE = "Cave Cleft",
        VAMPIRE_BAT_WING = "Batilisk Wing?",
        VENUS_STALK = "Flytrap Stalk",
        VENOMGLAND = "Venom Gland",
        WALKINGSTICK = "Stalking Stick",
        WALLCRACK_RUINS = "Suspicious Crack",
        WALL_PIG_RUINS = "Ancient Wall",
        WATERDROP = "Magic Water",
        WEEVOLE = "Weevole",
        WEEVOLE_CARAPACE = "Weevole Carapace",
        WEREWILBAFUR_BODY = "Body Hair",
        WEREWILBAFUR_HANDS = "Body Hair",
        WEREWILBAFUR_HEAD = "Body Hair",
        WHEELER_TRACKER = "Navigadget",
        ZEB = "Zeb",

        -- HOME DECO ITEMS NAMES --
        INTERIOR_FLOOR_MARBLE = "Marble Flooring",
        INTERIOR_FLOOR_CHECK = "Checkered Flooring",
        INTERIOR_FLOOR_PLAID_TILE = "Slate Flooring",
        INTERIOR_FLOOR_SHEET_METAL = "Sheet Metal Flooring",
        INTERIOR_FLOOR_WOOD = "Wood Flooring",
        INTERIOR_FLOOR_GARDENSTONE = "Garden Stone Flooring",
        INTERIOR_FLOOR_GEOMETRICTILES = "Geometric Tiles Flooring",
        INTERIOR_FLOOR_SHAG_CARPET = "Shag Carpet",
        INTERIOR_FLOOR_TRANSITIONAL = "Transitional Flooring",
        INTERIOR_FLOOR_WOODPANELS = "Wood Panel Flooring",
        INTERIOR_FLOOR_HERRINGBONE = "Herringbone Flooring",
        INTERIOR_FLOOR_HEXAGON = "Hexagon Flooring",
        INTERIOR_FLOOR_HOOF_CURVY = "Curvy Hoof Flooring",
        INTERIOR_FLOOR_OCTAGON = "Octagon Flooring",

        INTERIOR_WALL_WOOD = "Wood Paneling",
        INTERIOR_WALL_CHECKERED = "Checkered Wall Paper",
        INTERIOR_WALL_FLORAL = "Floral Wall Paper",
        INTERIOR_WALL_SUNFLOWER = "Sunflower Wall Paper",
        INTERIOR_WALL_HARLEQUIN = "Harlequin Wall Paper",
        INTERIOR_WALL_PEAGAWK = "Peagawk Wall Paper",
        INTERIOR_WALL_PLAIN_DS = "Orange Wall Paper",
        INTERIOR_WALL_PLAIN_ROG = "Purple Wall Paper",
        INTERIOR_WALL_ROPE = "Rope Wall Paneling",
        INTERIOR_WALL_CIRCLES = "Circle Wall Tiling",
        INTERIOR_WALL_MARBLE = "Marble Wall Tiling",
        INTERIOR_WALL_MAYORSOFFICE = "Fine Wall Tiling",
        INTERIOR_WALL_FULLWALL_MOULDING = "Full Wall Moulding",
        INTERIOR_WALL_UPHOLSTERED = "Upholstered Wall",

        DECO_CHAISE = "Fancy Chaise",
        DECO_CHAIR_CLASSIC = "Classic Chair",
        DECO_CHAIR_CORNER = "Corner Chair",
        DECO_CHAIR_BENCH = "Bench",
        DECO_CHAIR_HORNED = "Horned Chair",
        DECO_CHAIR_FOOTREST = "Footrest",
        DECO_CHAIR_LOUNGE = "Lounge Chair",
        DECO_CHAIR_MASSAGER = "Massager Chair",
        DECO_CHAIR_STUFFED = "Stuffed Chair",
        DECO_CHAIR_ROCKING = "Rocking Chair",
        DECO_CHAIR_OTTOMAN = "Ottoman Chair",

        DECO_LAMP_FRINGE = "Fringe Lamp",
        DECO_LAMP_STAINGLASS = "Stainglass Lamp",
        DECO_LAMP_DOWNBRIDGE = "Downbridge Lamp",
        DECO_LAMP_2EMBROIDERED = "Dual Embroidered Lamp",
        DECO_LAMP_CERAMIC = "Ceramic Lamp",
        DECO_LAMP_GLASS = "Glass Lamp",
        DECO_LAMP_2FRINGES = "Dual Fringes Lamp",
        DECO_LAMP_CANDELABRA = "Candelabra Lamp",
        DECO_LAMP_ELIZABETHAN = "Elizabethan Lamp",
        DECO_LAMP_GOTHIC = "Gothic Lamp",
        DECO_LAMP_ORB = "Orb Lamp",
        DECO_LAMP_BELLSHADE = "Bellshade Lamp",
        DECO_LAMP_CRYSTALS = "Crystals Lamp",
        DECO_LAMP_UPTURN = "Upturn Lamp",
        DECO_LAMP_2UPTURNS = "Dual Upturn Lamp",
        DECO_LAMP_SPOOL = "Spool Lamp",
        DECO_LAMP_EDISON = "Edison Lamp",
        DECO_LAMP_ADJUSTABLE = "Adjustable Lamp",
        DECO_LAMP_RIGHTANGLES = "Right Angle Lamp",
        DECO_LAMP_HOOFSPA = "Fancy Lamp",

        DECO_PLANTHOLDER_BASIC = "Basic Plantholder",
        DECO_PLANTHOLDER_WIP = "WIP Plantholder",
        DECO_PLANTHOLDER_FANCY = "Fancy Plantholder",
        DECO_PLANTHOLDER_BONSAI = "Bonsai Plantholder",
        DECO_PLANTHOLDER_DISHGARDEN = "Dishgarden Plantholder",
        DECO_PLANTHOLDER_PHILODENDRON = "Philodendron Plantholder",
        DECO_PLANTHOLDER_ORCHID = "Orchid Plantholder",
        DECO_PLANTHOLDER_DRACEANA = "Draceana Plantholder",
        DECO_PLANTHOLDER_XEROGRAPHICA = "Xerographica Plantholder",
        DECO_PLANTHOLDER_BIRDCAGE = "Birdcage Plantholder",
        DECO_PLANTHOLDER_PALM = "Palm Plantholder",
        DECO_PLANTHOLDER_ZZ = "ZZ Plantholder",
        DECO_PLANTHOLDER_FERNSTAND = "Fernstand Plantholder",
        DECO_PLANTHOLDER_FERN = "Fern Plantholder",
        DECO_PLANTHOLDER_TERRARIUM = "Terrarium Plantholder",
        DECO_PLANTHOLDER_PLANTPET = "Plantpet Plantholder",
        DECO_PLANTHOLDER_TRAPS = "Traps Plantholder",
        DECO_PLANTHOLDER_PITCHERS = "Pitcher Plantholder",
        DECO_PLANTHOLDER_MARBLE = "Marble Plantholder",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "\"Character\" Tree",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "Festive Tree.",

        DECO_TABLE_ROUND = "Round Table",
        DECO_TABLE_BANKER = "Hard Wood Desk",
        DECO_TABLE_DIY = "DIY Table",
        DECO_TABLE_RAW = "College Table",
        DECO_TABLE_CRATE = "Crate Table",
        DECO_TABLE_CHESS = "Chess Table",

        HOUSE_DOOR = "Simple Doorway",
        WOOD_DOOR = "Hardwood Door",
        STONE_DOOR = "Stone Archway",
        ORGANIC_DOOR = "Forest Door",
        IRON_DOOR = "Wrought Iron Door",
        PILLAR_DOOR = "Gothic Door",
        CURTAIN_DOOR = "Curtained Door",
        ROUND_DOOR = "Round Doorway",
        PLATE_DOOR = "Industrial Door",

        WINDOW_ROUND_CURTAINS_NAILS = "Round Window",
        WINDOW_ROUND_BURLAP = "Round Burlap Window",
        WINDOW_SMALL_PEAKED = "Peaked Window",
        WINDOW_LARGE_SQUARE = "Square Window",
        WINDOW_SMALL_PEAKED_CURTAIN = "Peaked Curtain Window",
        WINDOW_TALL = "Tall Window",
        WINDOW_LARGE_SQUARE_CURTAIN = "Large Square Curtain Window",
        WINDOW_TALL_CURTAIN = "Tall Curtain Window",
        WINDOW_GREENHOUSE = "Greenhouse Wall",
        WINDOW_ROUND = "Round Window",

        DECO_WOOD_BASE  = "Wooden Beam",
        DECO_WOOD       = "Planed Wood Column",
        DECO_MILLINERY  = "Millinery Column",
        DECO_ROUND      = "Round Column",
        DECO_MARBLE     = "Lit Marble Column",

        SWINGING_LIGHT_FLORAL_BLOOMER = "Floral Shade Hanging Light",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "Chandelier",
        SWINGING_LIGHT_ROPE_1 = "Rope Light",
        SWINGING_LIGHT_FLORAL_BULB = "Blown Glass Bulb",
        SWINGING_LIGHT_PENDANT_CHERRIES = "Cherry Lamp Shade",
        SWINGING_LIGHT_BASIC_METAL = "Metal Shade Lamp",
        SWINGING_LIGHT_BASIC_BULB = "Wired Bulb",
        SWINGING_LIGHT_ROPE_2 = "Dual Rope Light",
        SWINGING_LIGHT_FLORAL_SCALLOP = "Hanging Blooming Lamp",
        SWINGING_LIGHT_FLORAL_BLOOMER = "Hanging Floral Lamp",
        SWINGING_LIGHT_TOPHAT = "Top Hat Light",
        SWINGING_LIGHT_DERBY = "Derby Light",

        DECO_WALLORNAMENT_PHOTO = "Photo",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Full Length Mirror",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Embroidery Hoop",
        DECO_WALLORNAMENT_MOSAIC = "Mosaic",
        DECO_WALLORNAMENT_WREATH = "Wreath",
        DECO_WALLORNAMENT_AXE = "Axe",
        DECO_WALLORNAMENT_HUNT = "Hunt",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "Periodic Table",
        DECO_WALLORNAMENT_GEARS_ART = "Gears Art",
        DECO_WALLORNAMENT_CAPE = "Cape",
        DECO_WALLORNAMENT_NO_SMOKING = "No Smoking",
        DECO_WALLORNAMENT_BLACK_CAT = "Black Cat",
        DECO_ANTIQUITIES_WALLFISH = "Tasteful Fish Mounting",
        DECO_ANTIQUITIES_BEEFALO = "Beefalo Mounting",

        RUG_ROUND = "Eye Rug",
        RUG_SQUARE = "Square Throw Rug",
        RUG_OVAL = "Oval Rug",
        RUG_RECTANGLE = "Large Rug",
        RUG_FUR = "Fur Throw Rug",
        RUG_HEDGEHOG = "Hedgehog Rug",
        RUG_PORCUPUSS = "Porcupus Hide",
        RUG_HOOFPRINT = "Hoofprint Rug",
        RUG_OCTAGON = "Octagon Rug",
        RUG_SWIRL = "Swirl Rug",
        RUG_CATCOON = "Catcoon Rug",
        RUG_RUBBERMAT = "Rubbermat Rug",
        RUG_WEB = "Web Rug",
        RUG_METAL = "Metal Rug",
        RUG_WORMHOLE = "Wormhole Rug",
        RUG_BRAID = "Braid Rug",
        RUG_BEARD = "Beard Rug",
        RUG_NAILBED = "Nailbed Rug",
        RUG_CRIME = "Crime Rug",
        RUG_TILES = "Soccer Rug",

        SHELVES_WOOD = "Carved Bookshelf",
        SHELVES_BASIC = "Basic Bookshelf",
        SHELVES_CINDERBLOCKS = "Cinderblock Bookshelf",
        SHELVES_MARBLE = "Marble Shelf",
        SHELVES_MIDCENTURY = "Windowed Cabinet",
        SHELVES_GLASS = "Glass Shelf",
        SHELVES_LADDER = "Ladder Shelf",
        SHELVES_HUTCH = "Hutch Shelf",
        SHELVES_INDUSTRIAL = "Industrial Shelf",
        SHELVES_ADJUSTABLE = "Adjustable Shelf",
        SHELVES_WALLMOUNT = "Wall Mounted Shelf",
        SHELVES_AFRAME = "A-Frame Shelf",
        SHELVES_CRATES = "Crates Shelf",
        SHELVES_FRIDGE = "Fridge",
        SHELVES_HOOKS = "Hook Shelf",
        SHELVES_FLOATING = "Floating Shelf",
        SHELVES_PIPE = "Pipe Shelf",
        SHELVES_HATTREE = "Hat Tree",
        SHELVES_PALLET = "Pallet Shelf",
        SHELVES_METAL = "Metal Shelf",
        SHELVES_DISPLAYCASE = "Display Case",

        PLAYERHOUSE_CITY = "Slanty Shanty",
        PLAYERHOUSE_VILLA = "Glorious Villa",
        PLAYERHOUSE_COTTAGE = "Cozy Cottage",
        PLAYERHOUSE_MANOR = "Impressive Manor",
        PLAYERHOUSE_TUDOR = "Tudor Home",
        PLAYERHOUSE_GOTHIC = "Gothic Home",
        PLAYERHOUSE_BRICK = "Brick Home",
        PLAYERHOUSE_TURRET = "Turreted Home",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Cottage Kit",
        PLAYER_HOUSE_VILLA_CRAFT = "Villa Kit",
        PLAYER_HOUSE_TUDOR_CRAFT = "Tudor Home Kit",
        PLAYER_HOUSE_MANOR_CRAFT = "Manor Kit",
        PLAYER_HOUSE_GOTHIC_CRAFT = "Gothic Home Kit",
        PLAYER_HOUSE_BRICK_CRAFT = "Brick Home Kit",
        PLAYER_HOUSE_TURRET_CRAFT = "Turreted Home Kit",

        HEDGE_BLOCK_ITEM = "Block Hedge",
        HEDGE_BLOCK = "Hedge",
        HEDGE_CONE_ITEM = "Cone Hedge",
        HEDGE_CONE = "Hedge",
        HEDGE_LAYERED_ITEM = "Layered Hedge",
        HEDGE_LAYERED = "Hedge",

        LAWNORNAMENT_1 = "Layer Tree",
        LAWNORNAMENT_2 = "Irregular Tree",
        LAWNORNAMENT_3 = "Umbrella Tree",
        LAWNORNAMENT_4 = "Floopy Tree",
        LAWNORNAMENT_5 = "Funbrella Tree",
        LAWNORNAMENT_6 = "Flowering Tree",
        LAWNORNAMENT_7 = "Spiral Tree",

    },
    RECIPE_DESC = {
        ANTMASKHAT = "A face only a Mant could love.",
        ARMORVORTEXCLOAK = "Pockets, dimensions deep.",
        GOGGLESNORMALHAT = "Basic super goggles. Reveal hidden dangers.",
        PLAYER_HOUSE_COTTAGE_CRAFT = "A comfortable cozy facade.",
        ANTLER = "For calling birds. Did you make it too big?",
        ANTLER_CORRUPTED = "Strikes fear into even the biggest birds.",
        ANTSUIT = "Walk a mile in a Mant's carapace.",
        ARMORVORTEXCLOAK = "Pockets, dimensions deep.",
        ARMOR_METALPLATE = "Strong and sturdy.",
        ARMOR_WEEVOLE = "Kinda gross, but surprisingly strong.",
        BOAT_TORCH = "See, at sea.",
        BOATREPAIRKIT = "Stay afloat in that boat!",
        BASEFAN = "Relieves hay fever, keeps you dry.",
        GOLDENMACHETE = "Hack stuff in STYLE!",
        BALLPEIN_HAMMER = "For when you wanna wreck things gently.",
        BATHAT = "Harness the power of sonar.",
        BLUNDERBUSS = "Loud and messy, but gets the job done.",
        BONESTAFF = "Wield the gaze of the Pugalisk!",
        BRUSH = "Relieve beefalo of their hair buildup.",
        BUGREPELLENT = "In case you don't enjoy the company of bugs.",
        CANDLEHAT = "Hands free spelunking on shoe string.",
        CITY_LAMP = "I can't believe I can make this.",
        CLAWPALMTREE_SAPLING = "It's a wonder these things grow at all.",
        COMPOSTWRAP = "\"Herbal\" therapy.",
        CONSTRUCTION_PERMIT = "Add that den you've always wanted.",
        CORKBOAT = "Good for portage and tough as porridge.",
        CORKCHEST = "Fill and put a cork in it.",
        CORK_BAT = "Like a wiffle bat filled with pain.",
        DEMOLITION_PERMIT = "Destroy that den you've always wanted.",
        DISARMING_KIT = "It's disarming.",
        DISGUISEHAT = "A fresh face.",
        GASMASKHAT = "Makes everything smell like bird.",
        GOGGLESARMORHAT = "Armored lenses.",
        GOGGLESHEATHAT = "Is everything hot or not.",
        GOGGLESNORMALHAT = "Basic super goggles. Reveal hidden dangers.",
        GOGGLESSHOOTHAT = "Static boom focusing apparatus.",
        GOGGLESSHOOTHAT = "Static boom focusing apparatus.",
        GOLDPAN = "Pans gold actually.",
        HALBERD = "Pointy and hurty.",
        MACHETE = "Hack stuff!",
        HEDGE_BLOCK_ITEM = "For Squares.",
        HEDGE_CONE_ITEM = "For difference.",
        HEDGE_LAYERED_ITEM = "For variety.",
        HOGUSPORKUSATOR = "Pigs can do tricks too.",
        LIVING_ARTIFACT = "Lets just mix em and see what happens.",
        MAGNIFYING_GLASS = "See things from a different perspective.",
        METALPLATEHAT = "Strong, sturdy and classy.",
        MINISIGN_ITEM = "Draw on these with a Feather Pencil.",
        PEAGAWKFEATHERHAT = "Always watching.",
        PHEROMONESTONE = "Ancient scratch and sniff technology.",
        PIGHOUSE_CITY = "Shelters one tax paying pig.",
        PIG_GUARD_TOWER = "Protect the citizens.",
        PIG_SHOP_ANTIQUITIES = "Where else can you get a shriveled head.",
        PIG_SHOP_ARCANE = "For the magic half of Science and Magic.",
        PIG_SHOP_BANK = "Gold is a solid investment.",
        PIG_SHOP_CITYHALL_PLAYER = "You are the Mayor now.",
        PIG_SHOP_DELI = "We need more good places to eat.",
        PIG_SHOP_FLORIST = "There's a little green thumb in everyone.",
        PIG_SHOP_GENERAL = "For all your handy needs.",
        PIG_SHOP_HATSHOP = "All the best new fashions.",
        PIG_SHOP_HOOFSPA = "The mud really cleans the pores.",
        PIG_SHOP_PRODUCE = "Shop smart.",
        PIG_SHOP_TINKER = "You can't think of everything on your own.",
        PIG_SHOP_WEAPONS = "All adventurers need to defend themselves.",
        PITHHAT = "Keeps your hair easy and breezy.",
        PLAYERHOUSE_CITY = "Home Sweet Home.",
        POISONBALM = "The excruciating pain means it's working.",
        PORKLAND_ENTRANCE = "Hop on. What could possibly go wrong?",
        ROOTTRUNK_CHILD = "Pass things along the grape vine.",
        SECURITYCONTRACT = "The Ink is pretty expensive.",
        SPRINKLER = "Waters plants.",
        SHEARS = "Cut your way into adventure.",
        SMELTER = "Turn Iron into Alloy.",
        SNAKESKINSAIL = "Heavy duty wind catcher.",
        SNAKESKINHAT = "Keep rain out and look cool doing it.",
        ARMOR_SNAKESKIN = "Stay dry. And leathery.",
        TELEBRELLA = "A revolutionary walker.",
        TELEBRELLA = "A revolutionary walker.",
        TELIPAD = "A revolutionary platform.",
        THUMPER = "A revolutionary harvester.",
        THUNDERHAT = "Don't be shocked.",
        TURF_COBBLEROAD = "The life of a thriving village.",
        TURF_DEEPRAINFOREST_NOCANOPY = "As tame as wild jungle can be.",
        TURF_FIELDS = "A civilized patch of dirt.",
        TURF_FOUNDATION = "The foundation of a solid village.",
        TURF_LAWN = "Fully tamed grass.",
        VENOMGLAND = "Freshly squeezed poison.",


        LOGRAFT = "Boat at your own risk.",
        CARGOBOAT = "Hoarding at sea!",
        ROWBOAT = "Row, row, row your boat!",


        -- HOME DECO ITEMS DESC --
        INTERIOR_FLOOR_CHECK = "Hear the echo of quality.",
        INTERIOR_FLOOR_GARDENSTONE = "A soft mossy feel.",
        INTERIOR_FLOOR_GEOMETRICTILES = "Like a swimming pool.",
        INTERIOR_FLOOR_HERRINGBONE = "Stone flooring. A little fishy.",
        INTERIOR_FLOOR_HEXAGON = "Not just for bathrooms.",
        INTERIOR_FLOOR_HOOF_CURVY = "Very avant-garde, for pigs.",
        INTERIOR_FLOOR_MARBLE = "Buffed to a mirror polish.",
        INTERIOR_FLOOR_OCTAGON = "Just elegance.",
        INTERIOR_FLOOR_PLAID_TILE = "If it's good enough for city hall...",
        INTERIOR_FLOOR_SHAG_CARPET = "Fuzzy.",
        INTERIOR_FLOOR_SHEET_METAL = "What to do with your industrial metal.",
        INTERIOR_FLOOR_TRANSITIONAL = "When you can't decide.",
        INTERIOR_FLOOR_WOOD = "Hard wood flooring is always in style.",
        INTERIOR_FLOOR_WOODPANELS = "Goes up less easy.",
        INTERIOR_WALL_CHECKERED = "For that Diner chic.",
        INTERIOR_WALL_CIRCLES = "It's circles on wall paper.",
        INTERIOR_WALL_FLORAL = "Feel the velvet embossing.",
        INTERIOR_WALL_FULLWALL_MOULDING = "A lot of work, but worth the effort.",
        INTERIOR_WALL_HARLEQUIN = "Edgy and elegant.",
        INTERIOR_WALL_MARBLE = "A solid way to finish.",
        INTERIOR_WALL_MAYORSOFFICE = "Often chosen by pigs in office.",
        INTERIOR_WALL_PEAGAWK = "Smooth some ruffled feathers.",
        INTERIOR_WALL_PLAIN_DS = "A deep orange.",
        INTERIOR_WALL_PLAIN_ROG = "A deep purple.",
        INTERIOR_WALL_ROPE = "Tie the the room together.",
        INTERIOR_WALL_SUNFLOWER = "The fall harvest look.",
        INTERIOR_WALL_UPHOLSTERED = "Like a sofa on your wall.",
        INTERIOR_WALL_WOOD = "Goes up easy.",

        DECO_CHAIR_BENCH = "The ominous look.",
        DECO_CHAIR_CLASSIC = "A rosy little chair.",
        DECO_CHAIR_CORNER = "For side sitting.",
        DECO_CHAIR_FOOTREST = "Take a load off.",
        DECO_CHAIR_HORNED = "Grim and comfortable.",
        DECO_CHAIR_LOUNGE = "Molded wood.",
        DECO_CHAIR_MASSAGER = "You'll never need another chair.",
        DECO_CHAIR_OTTOMAN = "You oughta love it!",
        DECO_CHAIR_ROCKING = "It rocks.",
        DECO_CHAIR_STUFFED = "Bagged.",
        DECO_CHAISE = "Hoity toity place for your bottom.",

        DECO_LAMP_2EMBROIDERED = "Roses, roses all the way.",
        DECO_LAMP_2FRINGES = "More fringe benefits.",
        DECO_LAMP_2UPTURNS = "Double the cones.",
        DECO_LAMP_ADJUSTABLE = "Accommodating illumination.",
        DECO_LAMP_BELLSHADE = "A gloomier light.",
        DECO_LAMP_CANDELABRA = "Light the flames.",
        DECO_LAMP_CERAMIC = "Everything's coming up roses.",
        DECO_LAMP_CRYSTALS = "Dire yet luminous.",
        DECO_LAMP_DOWNBRIDGE = "Add some color to your light.",
        DECO_LAMP_EDISON = "Bare bones and bare bulbed.",
        DECO_LAMP_ELIZABETHAN = "Can belong to someone not named Elizabeth.",
        DECO_LAMP_FRINGE = "A fringe benefit.",
        DECO_LAMP_GLASS = "Glass-ic.",
        DECO_LAMP_GOTHIC = "Street chic.",
        DECO_LAMP_HOOFSPA = "A dash of gold.",
        DECO_LAMP_ORB = "Sphere-ious.",
        DECO_LAMP_RIGHTANGLES = "Boxy bulbed.",
        DECO_LAMP_SPOOL = "A timber table lamp.",
        DECO_LAMP_STAINGLASS = "No stain on your reputation.",
        DECO_LAMP_UPTURN = "Uplifting.",

        DECO_PLANTHOLDER_BASIC = "Basic home decor.",
        DECO_PLANTHOLDER_BIRDCAGE = "Hang in there.",
        DECO_PLANTHOLDER_BONSAI = "Add some zen.",
        DECO_PLANTHOLDER_DISHGARDEN = "Succulent.",
        DECO_PLANTHOLDER_DRACEANA = "Draconian.",
        DECO_PLANTHOLDER_FANCY = "For the fancy horticulturist.",
        DECO_PLANTHOLDER_FERN = "A hanging fern.",
        DECO_PLANTHOLDER_FERNSTAND = "Fine fernishing.",
        DECO_PLANTHOLDER_MARBLE = "Chiseled elegance.",
        DECO_PLANTHOLDER_ORCHID = "Fragrant.",
        DECO_PLANTHOLDER_PALM = "Add a little green to your room.",
        DECO_PLANTHOLDER_PHILODENDRON = "Green and leafy.",
        DECO_PLANTHOLDER_PITCHERS = "Eclectic ceilingware.",
        DECO_PLANTHOLDER_PLANTPET = "Hardly needs watering.",
        DECO_PLANTHOLDER_TERRARIUM = "Caged plants.",
        DECO_PLANTHOLDER_TRAPS = "Watch your fingers.",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "Pure majesty.",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "It's the thought that counts.",
        DECO_PLANTHOLDER_WIP = "Ready for unwrapping.",
        DECO_PLANTHOLDER_XEROGRAPHICA = "How's it staying in there?",
        DECO_PLANTHOLDER_ZZ = "A touch of green.",

        DECO_TABLE_BANKER = "Heavy, so hire movers.",
        DECO_TABLE_CHESS = "Knights not included.",
        DECO_TABLE_CRATE = "Recycled repurposed trees.",
        DECO_TABLE_DIY = "Put together for you.",
        DECO_TABLE_RAW = "Made from raw materials.",
        DECO_TABLE_ROUND = "Well rounded.",

        CURTAIN_DOOR = "Offers little in sound proofing.",
        HOUSE_DOOR =   "Room to move.",
        IRON_DOOR =    "An ornamental ingress.",
        ORGANIC_DOOR = "It just grew that way.",
        PILLAR_DOOR =  "Bats were harmed in the making of this.",
        PLATE_DOOR =   "For the metal lover.",
        ROUND_DOOR =   "Includes a curtain of teeth.",
        STONE_DOOR =   "The keystone to good living space.",
        WOOD_DOOR =    "Crowning achievement in crown molding.",

        SWINGING_LIGHT1 = "It's a light.",
        SWINGING_LIGHT_BASIC_BULB = "At least it's wired.",
        SWINGING_LIGHT_BASIC_METAL = "A sturdy metal design.",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "Soft and bold.",
        SWINGING_LIGHT_DERBY = "Render the hat unusable.",
        SWINGING_LIGHT_FLORAL_BLOOMER = "Brighting your ceiling.",
        SWINGING_LIGHT_FLORAL_BULB = "Delicate yet substantial.",
        SWINGING_LIGHT_FLORAL_SCALLOP = "Floral themed illumination.",
        SWINGING_LIGHT_FLORAL_SCALLOP = "Wonderful craftsmanship.",
        SWINGING_LIGHT_PENDANT_CHERRIES = "A sweet cheerful design.",
        SWINGING_LIGHT_ROPE_1 = "Light with a rustic feel.",
        SWINGING_LIGHT_ROPE_2 = "Twice the bleakness.",
        SWINGING_LIGHT_TOPHAT = "Add some sophistication.",

        DECO_ANTIQUITIES_BEEFALO = "The eyes are glass.",
        DECO_ANTIQUITIES_WALLFISH = "Show your piscatorial pride.",
        DECO_WALLORNAMENT_AXE = "Always handy.",
        DECO_WALLORNAMENT_BLACK_CAT = "Often seen in the Bohemian district.",
        DECO_WALLORNAMENT_CAPE = "You can never have too many capes.",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Hand-stitched by a Great Aunt.",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Get the full picture.",
        DECO_WALLORNAMENT_GEARS_ART = "Not cog-nizant of its aesthetic effect.",
        DECO_WALLORNAMENT_HUNT = "Hunter chic.",
        DECO_WALLORNAMENT_MOSAIC = "A motley of stones.",
        DECO_WALLORNAMENT_NO_SMOKING = "For health and safety.",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "Senti-elemental.",
        DECO_WALLORNAMENT_PHOTO = "Did this picture come with the frame?",
        DECO_WALLORNAMENT_WREATH = "Not just for Christmas anymore.",

        DECO_MARBLE     = "Lighten up the place.",
        DECO_MARBLE_CORNERBEAM = "Elegant and understated.",
        DECO_MILLINERY  = "Moderately refined.",
        DECO_ROUND      = "Round the bend.",
        DECO_WOOD       = "Holds up nicely.",
        DECO_WOOD_CORNERBEAM = "Raise the roof on a budget.",

        RUG_BEARD = "Recycled from chin shavings.",
        RUG_BRAID = "Homemade.",
        RUG_CATCOON = "Rustic.",
        RUG_CRIME = "Don't ask.",
        RUG_FUR = "100% Beefalo hide.",
        RUG_HEDGEHOG = "A trendy floor covering.",
        RUG_HOOFPRINT = "Elegance with a dash of cute.",
        RUG_METAL = "Metallurgic sophistication.",
        RUG_NAILBED = "Prove your will power.",
        RUG_OCTAGON = "Eight sides of comfort.",
        RUG_OVAL = "Rose patterned.",
        RUG_PORCUPUSS = "A great status piece.",
        RUG_RECTANGLE = "Large rug, rectangular.",
        RUG_ROUND = "Stylish paranoia.",
        RUG_RUBBERMAT = "Industrial.",
        RUG_SQUARE = "Compact and fringed.",
        RUG_SWIRL = "Hypnotic.",
        RUG_TILES = "Geometric luxury.",
        RUG_WEB = "Sticky.",
        RUG_WORMHOLE = "Non-active.",

        SHELVES_ADJUSTABLE = "Flexible furnishings.",
        SHELVES_AFRAME = "A+ shelving.",
        SHELVES_BASIC = "A basic bookshelf for basic books.",
        SHELVES_CINDERBLOCKS = "Dormitory approved.",
        SHELVES_CRATES = "Wholesale chic.",
        SHELVES_FLOATING = "Try a different angle.",
        SHELVES_FRIDGE = "Cool.",
        SHELVES_GLASS = "Breakable yet practical.",
        SHELVES_HATTREE = "Not actually a tree.",
        SHELVES_HOOKS = "Get hooked.",
        SHELVES_HUTCH = "A place for things.",
        SHELVES_INDUSTRIAL = "Practical storage.",
        SHELVES_LADDER = "Use it to reach the high shelf.",
        SHELVES_MARBLE = "Classic, yet avant-garde.",
        SHELVES_METAL = "Don't mettle with it.",
        SHELVES_MIDCENTURY = "Elegantly curved.",
        SHELVES_PALLET = "Barely palatable.",
        SHELVES_PIPE = "Plumb the depths of this shelving.",
        SHELVES_WALLMOUNT = "Nailed it.",
        SHELVES_WOOD = "A staple for bookworms.",

        PLAYER_HOUSE_BRICK_CRAFT = "Proven better than wood and hay.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "Bats sold seperately.",
        PLAYER_HOUSE_MANOR_CRAFT = "Ominously comfortable.",
        PLAYER_HOUSE_TUDOR_CRAFT = "The beauty of the middle ages.",
        PLAYER_HOUSE_TURRET_CRAFT = "Practical? Maybe. Cool? Probably.",
        PLAYER_HOUSE_VILLA_CRAFT = "A towering elegant surface.",

        LAWNORNAMENT_1 = "A happy little tree.",
        LAWNORNAMENT_2 = "A complex little tree.",
        LAWNORNAMENT_3 = "Does not protect you from rain.",
        LAWNORNAMENT_4 = "A bent little tree.",
        LAWNORNAMENT_5 = "Does not protect you from fun.",
        LAWNORNAMENT_6 = "The pot is plastic.",
        LAWNORNAMENT_7 = "The tree is plastic.",

        WINDOW_GREENHOUSE = "Sunlight and creepers.",
        WINDOW_LARGE_SQUARE = "Doubles as a tic-tac-toe board.",
        WINDOW_LARGE_SQUARE_CURTAIN = "Comes with drapery.",
        WINDOW_ROUND = "Have a look around.",
        WINDOW_ROUND_BURLAP = "Simple natural light.",
        WINDOW_SMALL_PEAKED = "Hard wood, soft light.",
        WINDOW_SMALL_PEAKED_CURTAIN = "Frugal and functional.",
        WINDOW_TALL = "Well rounded.",
        WINDOW_TALL_CURTAIN = "Fancy.",
    },

    CITY_PIG_TALK_FOLLOWWILSON = {
                                    DEFAULT = {"WHEREFORE ART THINE BAD GUYS?", "ONCE MORE UNTO THE BREACH, UNPIG", "TAKE ARMS!", "KILL, KILL, KILL!", "CRY HAVOC!", "THE GAME IS AFOOTS!",},
                                    pigman_beautician = {"VISIT MINE SHOP FOR MEDICINES", "SELLEST ME THINE FEATHERS", "I HATH NEED OF FEATHERS"},
                                    pigman_mechanic = {"SELLEST ME THINE REFINED'D THINGS", "IN NEED OF FIXINGS?", "SELLEST ME THINE ROPE", "SELLEST ME THINE BOARDS"},
                                    pigman_mayor = {"YOU VOTETH?", "GIVE ME THINE GOLD FOR GOOD CAUSE", "ENDORSETH ME?",},
                                    pigman_collector = {"WANT'ST STRANGE THINGS?", "SELLEST ME THINE WEIRDITIES",},
                                    pigman_banker = {"ALL THAT GLITTERS WORTH OINCS", "HAST THOU JEWELS?", "I BUY THOU JEWELS"},
                                    pigman_florist = {"VISIT MINE SHOP FOR SEEDS", "HAST THOU PLOP TO SELL?", "HAST THOU PETALS?"},
                                    pigman_farmer = {"I HAST FARM", "SELLETH ME THINE GRASS", "STEALEST NAUGHT MINE STUFFS"},
                                    pigman_miner = {"I WILLST BUY THINE ROCKS", "HAST THOU ROCKS TO SELL?", "STEAL NOT FROM MINE MINE"},
                                    pigman_shopkeep = {"HAST THOU CLIPPINGS?", "GIVETH ME YON CLIPPINGS FROM YON HEDGE", "TRIMETH YON SHRUBS"},
                                    pigman_storeowner = {"HAS'T THOU CUTTINGS O' HEDGE?", "YON HEDGES NEED'TH TRIMMING",},
                                    pigman_erudite = {"NEED'ST THOU MAGICS? COME'ST TO MINE SHOP", "NEED'ST FUEL O' NIGHTMARES", "HAST THOU FUEL O' NIGHTMARES?"},
                                    pigman_hatmaker = {"NEED'ST HATS? VISIT YON HAT SHOP", "HAST THOU SILK?", "THY HEAD IS'T IN NEED O' COVERINGS"},
                                    pigman_professor = {"VISIT YON ACADEMY", "HA'ST THOU RELICS?", "HATH THOU STUFFS O' OLDEN'D TIMES?"},
                                    pigman_hunter = {"NEED'ST THOU WEAPONS? VISIT MINE SHOP", "HAS'T THOU TOOTH O' THE HOUND?", "GET THEE TO YON WEAPONS SHOP"},
                                    },
    CITY_PIG_TALK_FIND_LIGHT = {
                                    DEFAULT = {"ONCE MORE UNTO THE LIGHT!", "WHEREFORE ART LIGHT?", "WHEREFORE IS'T SUN?", "FREINDS, PIGGIES, UNPIGGIES, LEND ME YOUR LIGHT"},
                                    pigman_beautician = {"I AM TOO MUCH I' THE DARK", "'TIS DARK!", "WHEREFORE ART THE LIGHT?"},
                                    pigman_mechanic = {"IS'T DARK! IS'T SCARY!", "THAT WAY MADNESS LIES!",},
                                    pigman_mayor = {"FRIENDS, PIGGIES, UNPIGGIES, LEND ME YOUR LIGHT!", "WHEREFORE ART MINE LIGHT?"},
                                    pigman_royalguard = {"TAKE NAUGHT THE LIGHT!", "TAKE ARMS!", "ONCE MORE UNTO THE LIGHT!"},
                                    pigman_royalguard = {"TAKE NAUGHT THE LIGHT!", "TAKE ARMS!", "ONCE MORE UNTO THE LIGHT!"},
                                    pigman_collector = {"WHEREFORE ART THE LIGHT?!", "I NEED'ST LIGHT!",},
                                    pigman_banker = {"BRINGETH BACK THE LIGHT!", "THIS WAY DARKNESS LIES!"},
                                    pigman_florist = {"I AM TOO MUCH I' THE DARK!", "THIS WAY DARKNESS LIES!",},
                                    pigman_storeowner = {"ONCE MORE UNTO THE LIGHT!", "WHEREFORE ART THOU, LIGHT?"},
                                    pigman_farmer = {"WHEREFORE IS'T SUN?", "NEED'ST LIGHT!",},
                                    pigman_miner = {"FINDETH LIGHT!", "IS'T TOO MUCH SCARY"},
                                    pigman_shopkeep = {"PROTECTETH ME!", "TAKETH NAUGHT THE LIGHT!",},
                                    pigman_erudite = {"'TIS TOO MUCH DARKNESS!", "DARKNESS IS AFOOTS!"},
                                    pigman_hatmaker = {"THIS WAY DARKNESS LIES!", "I AM TOO MUCH I' THE DARK!"},
                                    pigman_professor = {"THIS WAY DARKNESS LIES!", "DARKNESS 'TIS NAUGHT GOOD!"},
                                    pigman_hunter = {"BRING'ST BACK THE LIGHT!", "IS'T DARK! IS'T SCARY!"},
                                    },
    CITY_PIG_TALK_LOOKATWILSON_TRADER = {
                                    DEFAULT = {"HOW NOW?","HAVE THEE %s?","WELL MET","GOOD FORTUNE, THOSE WHO HAVE %s","MY KINGDOM FOR SOME %s"},
                                    pigman_beautician = {"HAS'T THOU FEATHERS?", "VISIT YON SHOP IF THOU HAS'T BOO-BOOS", "SELLEST ME FEATHERS"},
                                    pigman_mechanic = {"WHATFORE IS YOU?", "HAS'T THOU BOARDS?", "HAS'T THOU ROPE?", "I BUY'ST THINGS REFINED'D"},
                                    pigman_mayor = {"WANTS THOU HOME IN HAMLET?", "WANTS THOU PIG O' SECURITY?", "VOTE FOR ME ONLY"},
                                    pigman_collector = {"HAS'T THOU ODD STUFFS?", "I CAN'ST BUY YOUR ODD STUFFS?", "I SELL'ST ODD STUFFS!"},
                                    pigman_banker = {"HAS'T THOU JEWELS?", "I BUY'ST JEWELS FROM THOU", "WILL-TH THOU SELLEST ME THINE JEWELS?"},
                                    pigman_florist = {"NEED'ST I STUFFS O' PLANTS", "HAS'T THOU PETALS?"},
                                    pigman_farmer = {"HAS'T THOU GRASS?", "DON'T TAKETH MINE FARM STUFFS", "CAN'ST THOU SELL ME THINE GRASS?"},
                                    pigman_miner = {"HAS'T THOU ROCKS?", "TAKETH NAUGHT MINE ROCKS", "I WILL GIVETH THEE OINCS FOR ROCKS"},
                                    pigman_shopkeep = {"HAS'T THOU CLIPPINGS?", "GET THEE TO A SHRUBBERY", "SELLEST ME THINE CLIPPINGS"},
                                    pigman_storeowner = {"HAS'T THOU CLIPPINGS?", "GET THEE TO A SHRUBBERY", "SELLEST ME THINE CLIPPINGS"},
                                    pigman_erudite = {"HAS'T THOU RELICS O' PIGGIES?", "SELLEST ME THINE PIGGY RELICS", "RELIC HATH MUCH WORTH"},
                                    pigman_hatmaker = {"HAS'T THOU HATS?", "ME HAVE HATS FOR HEADETHS", "ME BUYEST FEATHERS FROM YOU"},
                                    pigman_professor = {"YOU HAVE RELICS?", "COME TO SHOP, ME HAVE RELICS", "I NEED OLD STUFFS"},
                                    pigman_hunter = {"YOU NEED SMASH STUFF?", "ME TAKE OINCS FOR WEAPON", "WEAPON MAKE YOU NOT SCARED"},
                                    },
    CITY_PIG_TALK_LOOKATROYALTY_TRADER = {
                                    DEFAULT = {"GREETINGS YOUR HIGHNESS","NEED'ST THOU %s?","GOOD DAY","NEED'ST %s. HAV'TH THOU THAT?","I WANT'ST %s. WILL BUY", "YOUR MAJESTY"},
                                    pigman_beautician = {"THOU HAST MOST BEAUTIFUL SNOUT", "YON MAJESTY", "TAKETH THEE A GIFT?"},
                                    pigman_mechanic = {"HOW NOW, YOUR MAJESTY", "AT-ETH YON SERVICE", "THOU MIGHTY SCEPTER'D BEING"},
                                    pigman_mayor = {"YON MAJESTY!", "ME HONORED'D!", "AT YON SERVICE"},
                                    pigman_royalguard = {"MINE SERVICE UNTO YOU", "YON MAJESTY", "LONG LIVE YON MAJESTY!"},
                                    pigman_royalguard_2 = {"THOU HONOR US LOWLY PIGS", "YON MAJESTY", "THOU MIGHTY SCEPTER'D BEING"},
                                    pigman_collector = {"AT THINE SERVICE", "THOU DO-EST US AN HONOR", "TAKEST THOU A GIFT?"},
                                    pigman_banker = {"YON MAJESTY!", "THOU DO-EST ME AN HONOR", "I AM AT-ETH THY SERVICE",},
                                    pigman_florist = {"TAKEST THINE MINE FLOWERS?", "AT YON SERVICE", "ME HONORED'D AT THINE PRESENCE!"},
                                    pigman_farmer = {"THINE HUMBL'EST SERVENT", "YOUR MAJESTY", "AT THINE SERVICE"},
                                    pigman_miner = {"YOU HONOR ME", "TAKE'ST THOU A GIFT", "ACCEPT'ETH MINE GIFT!"},
                                    pigman_shopkeep = {"HOW NOW, YON MAJESTY?", "LIKETH THY MINE GIFT?", "TAKE'ST THEE A GIFT?",},
                                    pigman_storeowner = {"AT THINE SERVICE", "LIKEST THY MINE GIFT?", "THOU MIGHTY SCEPTER'D BEING"},
                                    pigman_erudite = {"ACCEPT MINE HUMBLEST GIFT", "LONG LIVE YON MAJESTY", "WILL'ST THOU ACCEPT A GIFT?"},
                                    pigman_hatmaker = {"YON MAJESTY", "AT THINE SERVICE", "THOU MIGHTY SCEPTER'D BEING"},
                                    pigman_professor = {"ACCEPT'ST THOU A GIFT?", "THY HONOR ME?", "I AM THOU MOST HUMBLEST PIGGY SERVANT"},
                                    pigman_hunter = {"THY HONOR US LOWLY PIGS", "YON MAJESTY", "AT YON SERVICE, YON MAJESTY"},
                                    },
    CITY_PIG_TALK_LOOKATWILSON = {
                                        DEFAULT = {"WHAT HO, UNPIG", "HOW NOW, GOOD UNPIG", "WHAT NEWS?", "WELL MET"},
                                        ROYALTY = {"LONG LIVE THE QUEEN!","HAIL, GOOD NOBLE PIG!", "MINE LIEGE", "HAIL TO YOU, GOOD GENTLEPIGGY",},
                                        },
    CITY_PIG_TALK_APORKALYPSE_SOON = {    DEFAULT = { "THE APORKALYPSE APPROACH-ETH", "WOE, DESTRUCTION, RUIN, AND DECAY!", "DOOMSDAY IS NEAR!", "SOMETHING WICKED THIS WAY COMES", "PORKTENTOUS FIGURES!", "FEAR AND PORKTENT!"}},
    CITY_TALK_ANNOUNCE_APORKALYPSE = {    DEFAULT = { "THE APORKALYPSE COMETH!", "THE CRACK OF DOOM!", "DEATH HAVE ITS DAY!", "THEY HATH RETURNED!", "THEY KILL US FOR THEIR SPORT", "A PLAGUE ON ALL OUR HOUSES!", "BE ALL AND END ALL!"}},
    CITY_PIG_TALK_RUNAWAY_WILSON = {
                                    DEFAULT = {"THOUST ART NOT KIND!", "STAYEST THOU AWAY!", "GET-ETH THEE AWAY!", "ADIEU YOU!"},
                                    pigman_beautician = {"GOODNESS!", "EEP! SNORT!", "LEAVETH THOU!!", "THOU HAST THE SMELL OF UNPIG"},
                                    pigman_mechanic = {"I TRUST THEE NOT!", "STAY'ST THOU BACK", "GET THEE GONE, UNPIG"},
                                    pigman_mayor = {"GET THEE GONE!", "GO-EST THOU AWAY!", "GUARDS! PROTECT-ETH ME!",},
                                    pigman_shopkeep = {"TOO CLOSE! THOU TOO CLOSE!", "BACK-ETH THEE OFF!", "GET THEE GONE!"},
                                    pigman_royalguard = {"STAYEST THOU AWAY!", "GET THEE GONE!", "THOU HAST THE STENCH OF UNPIG!"},
                                    pigman_royalguard_2 = {"GO'ST THOU AWAY", "BACK-ETH THEE OFF!", "TALK'ST THOU TO ME?"},
                                    pigman_storeowner = {"THINE CLOSENESS DOST OFFENDETH ME", "TOO CLOSE!", "BACK'ST THOU UP!"},
                                    pigman_farmer = {"WHATFORE THOU WANT'ETH WITH ME?", "GET'ST BACK!", "BACK-ETH OFF!"},
                                    pigman_miner = {"LEAVE'ST ME BE!", "SHOO!", "STAYEST THOU AWAY!"},
                                    pigman_collector = {"TAKETH NAUGHT MINE STUFFS!", "GET THEE GONE", "GO'EST THOU AWAY!"},
                                    pigman_banker = {"THOU HAST THE SMELL OF UNPIG", "TAKE-ETH OFF!", "GET THEE GONE!"},
                                    pigman_florist = {"ADIEU!", "THOU ART TOO CLOSE!", "STAND-EST NAUGHT SO CLOSE TO ME!"},
                                    pigman_erudite = {"LEAVETH ME BE!", "WHYFORE YOU BUG-ETH ME?", "BACK-EST THOU OFF!"},
                                    pigman_hatmaker = {"GO'ST THOU AWAY!", "WANT THOU TO STEAL'EST MINE STUFFS?", "GET THEE GONE!", "I TRUSTETH THEE NAUGHT!"},
                                    pigman_professor = {"LEAVETH ME BE!", "GO-EST THOU AWAY", "WHYFORE YOU SO CLOSE?"},
                                    pigman_hunter = {"BACK-ETH AWAY!", "CROWD-EST ME NAUGHT!", "GET-ETH THEE AWAY!"},
                                    },
    CITY_PIG_TALK_FIGHT = {
                                    DEFAULT = {"AVAST!", "TO THINE DEATH!", "RAAAWR!", "I BITE MY HOOF AT THEE!"},
                                    pigman_beautician = {"DIE-EST NOW!", "ME KILL THEE", "TO THY DEATH!"},
                                    pigman_mechanic = {"I HAMMER THEE!", "HIT, HAMMER! HIT!", "I DESTROY THEE!"},
                                    pigman_mayor = {"KILL!", "DIE THOU!", "ME MOST VEXED!", "DESTROY!"},
                                    pigman_shopkeep = {"I GET THEE!", "THOU NOT NICE!", "I GET THEE!"},
                                    pigman_storeowner = {"GETEST THEE OUT!", "THY NOT BE WELCOME!", "GET OFF MINE PROPERTY!"},
                                    pigman_farmer = {"GET THEE BACK!!", "I BURY THINE!", "I GET THEE!"},
                                    pigman_miner = {"I CRUSHETH YOU!", "THY DYING!", "THOU DONE IT NOW!"},
                                    pigman_collector = {"THOU ART DONE FOR!", "GET THINE HENCE!", "THY BAD UNPIG!"},
                                    pigman_banker = {"THY NOT MINE FRIEND!", "I CHOP-ETH THEE!", "DIE! DIE!"},
                                    pigman_florist = {"THOU ART THE WORST!", "GO AWAY-EST!", "THOU ART A VILLAIN!"},
                                    pigman_erudite = {"VILLAIN UNPIG! BAD!", "THINE ART THE BADEST!", "AWAY FROM ME!"},
                                    pigman_hatmaker = {"YOU BE UNDONE!", "I SAY THEE OUT!!", "YOU MOST VEXING!"},
                                    pigman_professor = {"BE DONE-EST WITH THEE!", "WILL NOT YOU GO?!!", "OUT, DAMNED UNPIG!"},
                                    pigman_hunter = {"I ATTACK-ETH THEE!", "GET THOU AWAY FROM HERE!", "YOU MOST NOT WELCOME!"},
                                    },
    CITY_PIG_TALK_DAILYGIFT = {        DEFAULT = {"WARE FOR ART THOU", "THY HUMBL'ST PIGGY SERVANT", "REMEMBER'ST ME", "GIFT FOR'ST YOU", "WITH MINE HUMBLEST GRATITUDE","TAKEST THEE MINE GIFT, YOUR MAJESTY"}},
    CITY_PIG_TALK_POOPTIP = {
                                    DEFAULT = {"OUT, DAMNED PLOP", "HUMBLE THANKS, KIND UNPIG", "MY THANKS"},
                                    pigman_beautician = {"TAKEST THEE THY COIN", "HERE BE YOUR OUTRAGEOUS FORTUNE", "THANK YE, UNPIG"},
                                    pigman_mechanic = {"OUT, DAMNED PLOP!", "FAIR PRICE, FAIR UNPIG?", "LET-EST ME PAY FOR THYST HELP"},
                                    pigman_mayor = {"IS THAT PLOP I SEE BEFORE THEE?", "HONEST UNPIG", "KINDEST UNPIG"},
                                    pigman_shopkeep = {"UNPIG IS AN HONORABLE UNPIG", "I GIVE EVERY PLOP MINE OINC", "FAIR TERMS"},
                                    pigman_storeowner = {"FOR THY PLOP PICKING", "MOST EXCELLENT PICKING", "HONORABLE UNPIG"},
                                    pigman_farmer = {"FOR THY HONEST MANURING", "TAKEST THOU WHAT THOU'ST OWED", "HONEST OINC FOR UNPIG"},
                                    pigman_miner = {"'TIS FOUL", "IS A JUST PAYMENT?", "'TIS WORTHY DEED"},
                                    pigman_collector = {"HERE BE OINC FOR THOUST MANURE", "ALAS POOR UNPIG", "FORTUNE SMILES ONST THEE"},
                                    pigman_banker = {"AN OINC FOR THY TROUBLE", "A TAX FOR THY PLOP PICKING", "MANY THANKS"},
                                    pigman_florist = {"WE WILLST PAY FOR THY PLOPPING", "IS POO, UNPIG?", "ME PAYEST FOR PLOP PICKING"},
                                    pigman_erudite = {"FAIR PRICE FOR FOUL DEED", "THY PLOP-PICKING IS MOST PROFESSIONALS", "FOR PLOP OF PIGGY MAN"},
                                    pigman_hatmaker = {"I GIVE THE UNPIG ITS DUE", "WHAT PIECE OF WORK IS UNPIG", "YOU'ST PAID FOR PLOP OF PIG"},
                                    pigman_professor = {"THOUST MILK OF UNPIG KINDNESS", "SUCH STUFF AS PLOP IS MADE ON", "FOR THY TROUBLES"},
                                    pigman_hunter = {"PLOP AND CIRCUMSTANCE", "FOR POUND OF PLOP", "HAVE OINCS THRUST UPON THEE"},
                                    },

    CITY_PIG_TALK_ROYAL_POOPTIP = {
                                    DEFAULT = {"OUT, DAMNED PLOP", "HUMBLE THANKS, YOUR HIGHNESS",},
                                    pigman_beautician = {"ACCEPTEST THEE MINE COIN?", "HERE BE YOUR OUTRAGEOUS FORTUNE", "HUMBLE THANKS, YOUR MAJESTY"},
                                    pigman_mechanic = {"OUT, DAMNED PLOP!", "THOU ART THE FINEST OF PLOP PICKERS!", "THOU DO US HONOR"},
                                    pigman_mayor = {"WE ARE NOT WORTHY OF THINE PLOP", "'TIS A KIND THING YOU DO", "ACCEPTEST THEE MINE COIN?"},
                                    pigman_shopkeep = {"WE ARE NOT WORTHY OF THINE SERVICE", "I GIVE EVERY PLOP MY OINC", "HUMBLE THANKS, YOUR MAJESTY"},
                                    pigman_storeowner = {"FOR THY FINE PLOP PICKING", "MOST EXCELLENT PICKING", "HONORABLE PLOP PICKER!"},
                                    pigman_farmer = {"FOR THY HONEST MANURING", "FOR THY ROYAL PLOP PICKING", "THOU DO US'T HONOR"},
                                    pigman_miner = {"OUT, DAMNED PLOP!", "FOR THY ROYAL PLOP PICKING", "HUMBLEST OF THANKS, YOUR MAJESTY"},
                                    pigman_collector = {"HERE BE OINC FOR THOUST ROYAL MANURE", "FOR THY ROYAL PLOP PICKING", "THOU ART THE FINEST OF PLOP PICKERS"},
                                    pigman_banker = {"AN OINC FOR THY TROUBLE", "'TIS A KIND THING YOU DO", "THOU DO US HONOR"},
                                    pigman_florist = {"THOU ART THE FINEST OF PLOP PICKERS!", "HUMBLE THANKS, YOUR MAJESTY", "ACCEPTEST THEE MINE COIN?"},
                                    pigman_erudite = {"FAIR PRICE FOR FOUL DEED", "THY PLOP-PICKING IS MOST EXCELLENTEST", "THOU DO'ST US HONOR"},
                                    pigman_hatmaker = {"ACCEPTEST THEE MINE COIN?", "OUT, DAMNED PLOP", "THOU ARE THE MOST EXCELLENTEST OF PLOP PICKERS"},
                                    pigman_professor = {"THOUST MILK OF PIGGY KINDNESS", "SUCH STUFF AS PLOP IS MADE ON", "FOR THY TROUBLES"},
                                    pigman_hunter = {"PLOP AND CIRCUMSTANCE", "FOR POUND OF PLOP", "MOST EXCELLENT PICKINGS"},
                                    },
    CITY_PIG_TALK_PAYTAX = {        DEFAULT = {"TAKETH THINE TAX","NEED'ST THOU MINE TAX", "TAKEST THOU MINE TAX", "MANY THANKS UNTO YOU"}},
    CITY_PIG_TALK_PROTECT = {        DEFAULT = {"MOST FOUL! MOST FOUL!", "TAKE ARMS! TAKE ARMS!", "THOU WRETCH", "THOU COWARD!"}},
    CITY_PIG_TALK_EXTINGUISH = {    DEFAULT = {"OUT OUT, BRIEF FIRES!", "FIRE IS'T BAD!", "YON FIRE BE OUT!"}},
    CITY_PIG_TALK_STAYOUT = {        DEFAULT = {"MOST UNWELCOME", "AWAY, YOU CUR!", "BE'ST THEE GONE!", "FIE ON THEE, VILLAIN!"}},
    CITY_PIG_TALK_FLEE = {
                                    DEFAULT = {"ROGUE!", "PEASANT SLAVE!", "O HORRIBLE!", "O STRANGE"},
                                    pigman_beautician = {"O HORRIBLE!", "O STRANGE!", "MOST HORRIBLE"},
                                    pigman_mechanic = {"MOST NOTABLE COWARD", "FLEE!", "AVAST!"},
                                    pigman_mayor = {"THAT WAY MADNESS LIES!", "NO MORE OF THAT!", "CRY MERCY"},
                                    pigman_royalguard = {"KILL, KILL, KILL, KILL", "FARE THEE WELL!", "ONCE MORE UNTO THE BREACH!"},
                                    pigman_royalguard_2 = {"TO ARMS!", "I DASH YOU TO PIECES!", "THE GAME IS UP!"},
                                    pigman_shopkeep = {"FOUL!", "LESS THAN FAIR!", "WOE IS ME!"},
                                    pigman_storeowner = {"PIGS BE UP IN ARMS", "'TIS A WILD PIG CHASE", "WHAT A PIECE OF WORK!"},
                                    pigman_farmer = {"THOU LILY-LIVERED UNPIG!", "LIE LOW!", "O MISERY!"},
                                    pigman_miner = {"IF YOU PRICK US, WE BLEED!", "'TIS RUIN'D!", "A POX ON'T!"},
                                    pigman_collector = {"I AM TOO MUCH ON THE RUN!", "FLEE, FIE, FO, FUM!", "SOMETHING ROTTEN!"},
                                    pigman_banker = {"ADIEU, ADIEU!", "REMEMBER ME!", "FIE ON THEE!"},
                                    pigman_florist = {"S'WOUNDS!", "ZOUNDS!", "COWARD!"},
                                    pigman_erudite = {"A PLAGUE ON YOUR HOUSES!", "THOU'RT MAD!", "AWAY FROM ME!"},
                                    pigman_hatmaker = {"RUINOUS!", "HARK! NO MORE!", "CUR!"},
                                    pigman_professor = {"MOST FOUL!", "NOT FAIR!", "LEAVE ME!"},
                                    pigman_hunter = {"TAKETH THEM AWAY!", "FIE ON THEE!", "TOIL AND TROUBLE!"},
                                    },
    CITY_PIG_TALK_RUN_FROM_SPIDER = {
                                    DEFAULT = {"SPIDER IS'T BAD!", "LIKETH NAUGHT YON SPIDER!", "GO'ST THOU AWAY!"},
                                    pigman_beautician = {"O MONSTROUS!", "O HORRIBLE!", "MOST VEXING!"},
                                    pigman_mayor = {"GET-ETH THEE AWAY!", "ALAS!! ALACK!", "I HATE-ETH THEE, SPIDERS!"},
                                    pigman_mechanic = {"O MONSTROUS THING!", "WRECK-ETH NAUGHT OUR STUFFS", "GO'ST THOU AWAY!"},
                                    pigman_royalguard = {"PROTECT-ETH THE CITY!", "SPIDERS NAUGHT WELCOME!", "GET THEE GONE!"},
                                    pigman_royalguard_2 = {"PROTECT-ETH THE CITY", "SQUASH-ETH THE SPIDERS!", "GET THEE GONE!"},
                                    pigman_shopkeep = {"PROTECT-ETH MINE STORE!", "GET-ETH THEE GONE!", "GO-EST AWAY!"},
                                    pigman_storeowner = {"EEK! SNORT! AVAST!", "MOST VEXING!", "O HORRIBLE!"},
                                    pigman_farmer = {"O MONSTROUS THING!", "SPIDERS NAUGHT WELCOME!", "MOST VEXING!"},
                                    pigman_miner = {"GO-ETH THOU AWAY!", "GET THEE GONE!", "THOU AREN'ST WELCOME HENCE"},
                                    pigman_collector = {"GET THEE GONE!", "THOU ART BAD GUY!!", "MOST VEXING!"},
                                    pigman_banker = {"FOUL! FOUL! MOST FOUL!", "MONSTROUS THING!", "GET THEE GONE!!"},
                                    pigman_florist = {"SPIDER IS'T BAD!", "O MONSTROUS!!", "O HORROR!"},
                                    pigman_erudite = {"GET THEE GONE!", "AWAY! AWAY!!", "EEK!"},
                                    pigman_hatmaker = {"CREEP NAUGHT HENCH!", "GO'ST THOU AWAY!", "GUARD!"},
                                    pigman_professor = {"GET-ETH THEE AWAY!", "ALAS! ALACK!", "GET THEE GONE!"},
                                    pigman_hunter = {"I HATE-ETH THEE!", "LIKE-ETH THEE NAUGHT!", "EEK! SNORT! AVAST!!"},
                                    },
    CITY_PIG_TALK_HELP_CHOP_WOOD = {
                                    DEFAULT = {"TAKETH THAT TREE!", "I SMASH-ETH YON TREE!", "I PUNCH-ETH TREE!"},
                                    pigman_beautician = {"I SHALL CHOP-ETH!", "YON TREE NEEDS CHOPPIN'!",},
                                    pigman_mechanic = {"SHALL I COMPARE TREE TO SUMMER'S DAY?", "WORK-ETH, WORK-ETH, WORK-ETH",},
                                    pigman_mayor = {"WHAT PIECE OF WORK IS CHOPPING", "FALL, TREE!",},
                                    pigman_royalguard = {"I TAKETH DOWN YON TREE", "I CHOPTING", "I GOOD FRIEND, I CHOPT TREE"},
                                    pigman_royalguard_2 = {"CHOP'T CHOP'T", "I AXE THEE!", "FAIR TREE SHALT FALL!"},
                                    pigman_shopkeep = {"'TIS HARD WORK", "I SMASH-ETH", "I SMASH THEE"},
                                    pigman_storeowner = {"SMASH-ETH! SMASH-ETH", "DOTH HARD WORK!", "HAVE AT THEE TREE!"},
                                    pigman_farmer = {"THIS TREE DOTH CHOP'T", "I TOIL", "CHOP'T CHOP'T!"},
                                    pigman_miner = {"YON TREE IS'T CHOP'T", "'TIS EASIER THAN MINING", "YON TREE IS'T DONE FOR!"},
                                    pigman_collector = {"'TIS HARD WORK", "WHAT A PIECE OF WORK IS CHOPPING",},
                                    pigman_banker = {"MINE HOOVES GET-ETH DIRTY", "FALL, TREE!",},
                                    pigman_florist = {"CHOP'T, CHOP'T", "SMASHINGS!", "TOIL, TOIL"},
                                    pigman_erudite = {"I HELP-ETH", "FALL, TREE!", "I AXE THEE!"},
                                    pigman_hatmaker = {"YON TREE SHALL FALL!", "THUS FALL-ETH THY TREE",},
                                    pigman_professor = {"WITH MINE LAST BREATH I CHOP AT THEE!", "CHOP'T CHOP'T", "HAVE AT THEE TREE"},
                                    pigman_hunter = {"THUS FALL THE TREE", "I BID THEE FALL!", "I WIN!"},
                                    },
    CITY_PIG_TALK_ATTEMPT_TRADE = {
                                    DEFAULT = {"WHAT HAS'T THEE?", "NEED'ST THEE WARES?"},
                                    pigman_beautician = {"THEE HAS'T FEATHERS?", "THEE HAS'T BIRDY FEATHERS?", "HAS'T THEE PRETTY FEATHERS?"},
                                    pigman_mechanic = {"THINE NEED'ST REPAIRS?", "BRING FORTH YON REPAIRS", "THEE HAS'T REFINED GOODS?"},
                                    pigman_mayor = {"NEED'ST THOU A HOME?", "DEEDS BE IN YON CITY HALL", "THY WANT'ST HOME IN HAMLET?"},
                                    pigman_shopkeep = {"GET THEE TO SOME SHRUBBERY!", "HAS'T THEE CLIPPINGS?", "HAS'T THEE SHRUB STUFFS?"},
                                    pigman_storeowner = {"GET THEE TO SOME SHRUBBERY!", "HAS'T THEE CLIPPINGS?", "HAS'T THEE SHRUB STUFFS?"},
                                    pigman_farmer = {"HAS'T THOU GRASS?", "SELL'ST ME THINE GRASS PARTS", "ME WANT'ST GRASS STUFFS"},
                                    pigman_miner = {"HAS'T THOU A ROCK?", "ME PAY'ST FOR ROCKS", "I GIVETH OINC FOR THY ROCK"},
                                    pigman_collector = {"HAS'T THOU STRANGE THINGS?", "I BUYEST THING O' STRANGENESS", "SELLEST ME THINE WANT WEIRD STUFF?"},
                                    pigman_banker = {"HAST THOU JEWELS?", "I WILL'ST BUYEST JEWELS FROM THEE", "I PAYST OINCS FOR JEWELS"},
                                    pigman_florist = {"HAS'T THOU PLOP?", "PETALS FOR MINE SHOP?", "ME LIKE'ST PRETTY FLOWER", "ME LIKE'ST SMELLY PLOP"},
                                    pigman_erudite = {"HAS'T THOU DARK MAGICS?", "HAS'T THOU FUEL O' NIGHTMARE?", "SELL'ST ME THY DARK MAGICS STUFFS"},
                                    pigman_hatmaker = {"HAST THOU SILK?", "I NEED'TH SILK", "SELLEST ME THINE SILK"},
                                    pigman_professor = {"RELICS?", "HAS'T THOU RELICS?", "PAY'ST THOU OINCS FOR RELICS"},
                                    pigman_hunter = {"HAS'T THOU HOUNDS TOOTH?", "SELLETH THEE HOUNDS TOOTH?", "I BUY'ST TOOTH O' THE HOUNDS"},
                                    },
    CITY_PIG_TALK_PANIC = {
                                    DEFAULT = {"O HORRIBLE", "AAAAAAAAAH!!", "AVAST!", "NO LIKETH", "HURLEYBURLY!"},
                                    pigman_beautician = {"EVIL 'TIS AFOOT", "SOMETHING WICKED THIS WAY COMES!", "O HORRORS"},
                                    pigman_mechanic = {"ADIEU!", "I AM TOO MUCH IN THE FEAR", "MOST FOUL! MOST FOUL!"},
                                    pigman_mayor = {"MOST HORRIBLE", "O' CURSED SPITE", "THIS BE MADNESS"},
                                    pigman_royalguard = {"ONCE MORE INTO THE BREACH!", "GUARDS PROTECT THEE!", "AVAST! AVAIL!"},
                                    pigman_royalguard_2 = {"ONCE MORE INTO THE BREACH!", "GUARDS PROTECT THEE!", "AVAST! AVAIL!"},
                                    pigman_shopkeep = {"O HORROR! O HORROR! O HORROR!", "O SLINGS AND ARROWS!", "O OUTRAGEOUS FORTUNE!"},
                                    pigman_storeowner = {"HEIGH, MY HEARTS!", "A PLAGUE UPON IT!", "ALL LOST!"},
                                    pigman_farmer = {"ALL IS'T LOST!", "ADIEU! ADIEU!", "I EXEUNT!"},
                                    pigman_miner = {"I GET ME GONE!", "O, WOE THE DAY!", "'TIS THE END!"},
                                    pigman_collector = {"BAD THINGS ARE NIGH!", "ME PROTEST SO MUCH!", "I WANT'ST NOT TO DIE!"},
                                    pigman_banker = {"O MONSTROUS!", "O STRANGE!", "HELP'TH ME!"},
                                    pigman_florist = {"OUT! OUT!", "TAKE ARMS!", "SOMETHING WICKED THIS WAY COMES!"},
                                    pigman_erudite = {"O CURSE'D SPITE!", "GO AWAY'TH!", "MOST UNKIND!"},
                                    pigman_hatmaker = {"OUT! OUT!", "SAVETH ME!", "MOST HORRIBLE! MOST STRANGE!"},
                                    pigman_professor = {"CRY YOU MERCY!", "MOST HORRIBLE! MOST STRANGE!", "IT COMETH FOR US!"},
                                    pigman_hunter = {"SOUND AND FURY!", "HOWL, HOWL, HOWL, HOWL!", "ALL IS'T LOST!"},
                                    },
    CITY_PIG_TALK_PANICFIRE = {        DEFAULT = {"IT BURN-ETH!", "FIRE BURN AND PIGGY BUBBLES", "FIGHT FIRE WITH WATER!", "SOMETHING FIREY THIS WAY COMES!", "FIRE FIRE FIRE"}},
    CITY_PIG_TALK_FIND_MEAT = {
                                    DEFAULT = {"IS'T MEAT!", "'TIS MEAT I SEE BEFORE ME?!", "I EAT'TH!", "FOOD TIME IS NIGH!"},
                                    pigman_beautician = {"MEAT BE THE FOOD OF LOVE", "I HATH STOMACH FOR IT", "VERILY I EAT",},
                                    pigman_mechanic = {"THIS MEAT I SEE BEFORE ME?", "WELL SERVED", "SOMETHING YUMMY THIS WAY COMES"},
                                    pigman_mayor = {"'TIS A DISH FIT FOR PIGS", "GIVE'ST MAYOR MINE DUE"},
                                    pigman_royalguard = {"EAT OR NOT TO EAT, THERE BE NO QUESTION", "MEATS FOR'ST PIGGY"},
                                    pigman_royalguard_2 = {"TO MINE OWN BELLY BE TRUE!", "'TIS MEAT! 'TIS FOOD!", "HUZZA!"},
                                    pigman_shopkeep = {"TO MINE OWN BELLY BE TRUE", "ALLS WELL THAT ENDS IN BELLY",},
                                    pigman_storeowner = {"'TIS EATS!", "I EATS!", "SOMETHING YUMMY THIS WAY COMES"},
                                    pigman_farmer = {"MMMM...MEAT MOST FOUL!", "FOR MINE FAT PAUNCH!", "BELLY BURN, AND MEAT BUBBLE"},
                                    pigman_miner = {"MEAT BE THE SOUL OF FOOD", "WOULD IT WERE IN MY BELLY", "MARRY THOUGH I LOVETH FOODS!"},
                                    pigman_collector = {"'TIS SLOP! 'TIS FOOD!", "WHENCE COME THIS FOOD?", "PRITHEE, LET ME EAT!"},
                                    pigman_banker = {"THE FOOD'S THE THING", "ZOUNDS, FOR MINE FAT PAUNCH!", "WHENCE COMES THIS FOOD?!"},
                                    pigman_florist = {"MARRY, 'TIS MEAT!", "ALACK THE DAY,'TIS MEAT!"},
                                    pigman_erudite = {"AY, THERE'S THE GRUB!", "INTO THE BOWELS OF MY BELLY", "MEAT GOETH IN MINE BELLY!"},
                                    pigman_hatmaker = {"MINE BELLY NOT PROTEST TOO MUCH", "SIRRAH! MY FOOD!", "NOT SALAD DAYS!"},
                                    pigman_professor = {"MMM... MEAT THRUST UPON ME", "WHYFORE ART THERE GROUND MEAT?"},
                                    pigman_hunter = {"A POUND OF FLESH!", "'TIS GOOD, 'TIS GOOD INDEED!", "MUCH ADO ABOUT MEAT!"},
                                    },
    CITY_PIG_TALK_FIND_MONEY = {
                                    DEFAULT = {"'TIS SHINY THING!", "ALL THAT GLITTERS IS GOLD!", "YEA, THO I HAST SHINY THING!", "I GO FORTH AND BUY'ST THINGS"},
                                    pigman_beautician = {"OINC HAST PRETTYNESS!", "'TIS PRETTIES", "OINC HATH WORTH"},
                                    pigman_mechanic = {"LIKEST OINCS!", "PUT'ST OINC IN MINE POCKET", "CAN'ST ME BUY'ST STUFFS"},
                                    pigman_mayor = {"MINE-ETH!", "IS'T BUY'ST VOTES", "GIVE MAYOR MINE DUE"},
                                    pigman_royalguard = {"OUTRAGEOUS FORTUNE!", "ME KEEP'TH", "PUT MONEY IN MINE PURSE!"},
                                    pigman_royalguard_2 = {"MINE OINC BE TRUE!", "FORTUNE SMILE 'PON ME"},
                                    pigman_shopkeep = {"IT SUFFICETH", "ME TAKETH!", "SOMETHING SHINY THIS WAY COMES"},
                                    pigman_storeowner = {"MARRY!", "ME LIKETH", "WILL SCREW THIS TO STICKING-PLACE", "ME TAKE'ST!"},
                                    pigman_farmer = {"MOST EXCELLENT FANCY", "'TIS FOR HONEST DAYS WORK", "WHATFORE ART THIS?"},
                                    pigman_miner = {"MINE'ST!", "A POUND OF OINC", "'TIS MINE"},
                                    pigman_collector = {"YEA, THO I HAST SHINY THING!", "MINE OWN PURSE BE TRUE",},
                                    pigman_banker = {"A POUND OF OINC!", "MARRY, 'TIS COIN!", "'TIS LOST OINC FOR MINE PURSE"},
                                    pigman_florist = {"HATH LOVELINESS", "'TIS PRETTY!", "ALL THAT GLITTERS IS GOLD"},
                                    pigman_erudite = {"CATCHETH MINE EYE", "HAST VALUE", "'TIS SHININESS"},
                                    pigman_hatmaker = {"ME LIKETH!", "PUT MONEY IN MINE PURSE", "WHATFORE ART THIS?"},
                                    pigman_professor = {"OUTRAGEOUS FORTUNE!", "WANT MONEYS", "CATCHETH MINE EYE"},
                                    pigman_hunter = {"'TIS MINE!", "FORTUNE SMILE 'PON ME!"},
                                    },
    CITY_PIG_TALK_FORGIVE_PLAYER = {DEFAULT = {"I SHOW QUALITY OF MERCY", "ALL IS'T FORGIVEN", "HEARTILY I FORGIVEST THEE", "A POUND OF OINCS HATH SUFFICETH"}},
    CITY_PIG_TALK_NOT_ENOUGH = {    DEFAULT = {"I WANT-ETH MORE", "DOTH NOT SUFFICETH", "I REQUIRETH MORE", "NEEDETH MORE"}}, -- NEW
    CITY_PIG_TALK_EAT_MEAT = {        DEFAULT = {"NOM-ETH NOM-ETH, NOM-ETH", "O FOOD! O SLOP!", "MUNCH'D, AND MUNCH'D, AND MUNCH'D"}},
    CITY_PIG_TALK_GO_HOME = {
                                    DEFAULT = {"ANON! ADIEU!", "I GET ME TO BED!"},
                                    pigman_beautician = {"MOST HUMBLY I LEAVES", "I SLEEP", "PERCHANCE I DREAMS"},
                                    pigman_mechanic = {"FARES'T THEE WELL", "MY KINGDOM FOR SOME JAMMIES", "GOOD EVENTIME"},
                                    pigman_mayor = {"FAIR ME WELL", "I MAKE ME BEDFELLOWS", "MY DREAMS MAY COME"},
                                    pigman_shopkeep = {"GET ME TO A BEDDY-BYES", "I GO MY CHAMBERS", "NIGHTY NIGHTS, SWEET UNPIGS"},
                                    pigman_storeowner = {"I SEE WHAT DREAMS MAY COME", "ADIEU ADIEU", "REMEMBER ME"},
                                    pigman_farmer = {"GOODETH NIGHT NIGHT", "PARTING SUCH SWEET SORROW", "TIL IT BE MORROW"},
                                    pigman_miner = {"TIL TOMORROW AND TOMORROW AND TOMORROW", "I SLUMBER'DING", "TO SLEEP OR NOT TO SLEEP?"},
                                    pigman_collector = {"GOOD NIGHT UNTO YOU ALL", "SWEET GOOD NIGHT!", "I BID ADIEU TO YOUS"},
                                    pigman_banker = {"ADIEU, ADIEU REMEMBERS ME", "FARE THEE WELL", "GOOD PIGS, LET'S RETIRE"},
                                    pigman_florist = {"GENTLE NIGHTY-NIGHTS", "ONCE MORE UNTO MY JAMMIES", "ANON, GOOD NIGHT"},
                                    pigman_erudite = {"NOW IS NIGHTTIMES OF OUR DISCONTENT", "I BID ADIEUS", "UNTIL THE MORROW"},
                                    pigman_hatmaker = {"WHEREFORE ART MY JAMMIES?", "ALAS, I DEPART", "I BID THEE NIGHTY NIGHTS"},
                                    pigman_professor = {"LIGHT THROUGH MY WINDOW BREAKS", "TIS WITCHING TIME OF NIGHT", "I TAKING MY LEAVE"},
                                    pigman_hunter = {"ME DREAM A DREAM TONIGHT", "MY TOO TIRED FLESH GOES SLEEPIES", "SEE YOU ON THE MORROW"},
                                    },
    CITY_PIG_TALK_FIX = {
                                    DEFAULT = {"ALL FIX'D!", "I DO'ST GOOD FIXINGS!"},
                                    pigman_beautician = {"I FIXETH NOT", "GET THEE TO A MECHANIC"},
                                    pigman_mechanic = {"I MAKETH NICE NICE", "BUILD, BUILD", "I USETH MINE HAMMER GOOD"},
                                    pigman_mayor = {"MAYOR SHALL NOT FIXETH","I FIXETH NOT", "GET THEE TO A MECHANIC"},
                                    },
    CITY_PIG_GUARD_TALK_TORCH = {    DEFAULT = {"BURN BRIGHT THE TORCHES!", "LIGHT THE TORCHES!", "BURN, TORCHES, CLEAR AND BRIGHT!"}},
    CITY_PIG_GUARD_TALK_FIGHT = {    DEFAULT = {"I STAB AT THEE!", "HAVE AT THEE!", "AWAY, CUR! AWAY!"}},
    CITY_PIG_GUARD_TALK_GOHOME = {    DEFAULT = {"STAND HO!", "WHOFORE IS THAT?", "WHATFORE THAT?", "WHAT HO!"}},
    CITY_PIG_GUARD_TALK_LOOKATWILSON = {
                                    DEFAULT = {"MAKE NOT TROUBLES", "WHOFORE GO'ST THERE?", "TRESPASS NOT!",}},
    CITY_PIG_GUARD_LIGHT_TORCH = {    DEFAULT = {"ME LIGHT A FIERY TORCH", "TORCHES, TORCHES!", "CURFEW'S RUNGETH"}},
    CITY_PIG_TALK_REFUSE_GIFT = {    DEFAULT = {"HAVE THEE %s? WILL PAY"}},
    CITY_PIG_TALK_REFUSE_GIFT_DELAY = {
                                    DEFAULT = {"COMES'T BACK IN %s DAYS"}},
    CITY_PIG_TALK_REFUSE_GIFT_DELAY_TOMORROW = {
                                    DEFAULT = {"COME'ST BACK ON THE MORROW"}},
    CITY_PIG_TALK_REFUSE_PURPLEGEM = {
                                    DEFAULT = {"NAY! HAST THE SCARY BAD MAGICS!", "TAKETH IT AWAY!"}},
    CITY_PIG_TALK_RELIC_GIFT = {    DEFAULT = {"TAKEST TO YON MUSEUM", "THE ACADEMY BE THE PLACE FOR IT"}},            -- \"THE STY\"
    CITY_PIG_TALK_TAKE_GIFT = {        DEFAULT = {"MANY THANKS, GIVES'T THOU MORE %s PLEASE"}},
    CITY_PIG_TALK_GIVE_REWARD = {    DEFAULT = {"A WORTHY JOB. TAKE THEE REWARD", "'TIS NOBLE JOB THEE DO", "A FINE JOB"}},
    CITY_PIG_TALK_GIVE_TRINKET_REWARD = {
                                    DEFAULT = {"OH, HOW LOVELY! TAKE THIS GIFT"}},
    CITY_PIG_TALK_REFUSE_TRINKET_GIFT = {
                                    DEFAULT = {"NO MORE JUNK, THANK YOU"}},
    CITY_PIG_TALK_REFUSE_PRICELESS_GIFT = {
                                    DEFAULT = {"NO 'TIS PRICELESS!","IT IS FOUND! MUST FIND QUEEN","I CANNOT TAKE, BELONG TO ROYALTY"}},
    CITY_PIG_TALK_GIVE_RELIC_REWARD = {
                                    DEFAULT = {"MOST EXCELLENT!", "IS'T TREASURE!", "FROM YON OLDEN TIMES!"}},
    CITY_PIG_GUARD_TALK_ANGRY_PLAYER = {
                                    DEFAULT = {"HAS'T THEE RETURNED?!", "CUR! VILLAIN!", "OUT! FLEE!", "YOU A SEA OF TROUBLES!"}},
    CITY_PIG_GUARD_TALK_RESCUE = {    DEFAULT = { "I HELPEST THOU!", "O! THOU STUCK’DED", "NEED’ST HELP?" }},
    CITY_PIG_SHOPKEEPER_NOT_ENOUGH = {"THY LACKETH THE OINCS", "GET THEE MORE OINCS"},
    CITY_PIG_SHOPKEEPER_DONT_HAVE = {"BRINGETH THEE ITEM", "THOU NEED'ST ITEM", "OINCS NOT SUFFICETH, ONLY ITEM"},
    CITY_PIG_SHOPKEEPER_SALE = {"MY THANKS", "A FINE EXCHANGE", "MANY THANKS", "'TIS GOOD STUFF"},

    CITY_PIG_SHOPKEEPER_ROBBED = {"WHOFORE HAST DONE THIS?!", "ROBBED! ROBBED! ROBBED!","OH THE PIGANITY!", "REVENGE!"},

    CITY_PIG_SHOPKEEPER_GREETING = {
                                    DEFAULT = {"WHAT SAY THOUST?","THOU LOOK'ST FOR THINGS?","I HATH THEE WARES","BUY'ST THOU STUFFS TODAY?"},
                                    pigman_mayor_shopkeep = {"NEED'ST THOU A HOUSE?", "NEED'ST GUARD?", "WANT'ST THOU TO DWELL'ETH HERE?",},
                                    pigman_beautician = {"LOOKETH AT MINE MEDICINES", "THOU NEED'ST MEDICINES?", "NEED'ST THINGS FOR BOO-BOOS?"},
                                    pigman_mechanic = {"HAS'T THOU THINGS TO FIX?", "I FIXETH", "I FIXETH BROKEN THING", "YOU NEEDETH FIXINGS?"},
                                    pigman_miner = {"SELLETH ROCKS?", "I LIKETH ROCKS", "SELLEST ME THINE ROCKS",},
                                    pigman_collector = {"HAST THOU STRANGE THINGS?", "I DEALETH WITH THINGS O' STRANGENESS", "WANTS THOU STRANGE THINGS?"},
                                    pigman_banker = {"HAST THOU JEWELS?", "ME GIVETH OINCS FOR JEWELS", "ME LIKETH SPARKLY JEWELS"},
                                    pigman_florist = {"THOU NEEDS OF SEEDS?", "NEEDETH STUFFS FOR PLANTINGS?", "HAST THOU PLOP?", "HAST THOU PETALS?"},
                                    pigman_erudite = {"NEEDETH MAGIC THINGS?", "I SELL MAGIC THINGS?", "I SELLEST THINGS BAD DREAMS ARE MADE ON"},
                                    pigman_hatmaker = {"HATS? NEED'ST THOU HATS?", "NEEDST THING TO COVER THINE HEAD?", "BUY'ST THY HATS FROM ME"},
                                    pigman_professor = {"IN NEED'ST OF OLD THINGS?", "I LIKETH RELICS FROM YON TEMPLES", "NEED'ST THOU RELICS?",},
                                    pigman_hunter = {"IN NEED O' WEAPONS", "I SELL'ST SMASHY THINGS", "NEEDST THOU MURDERING THINGS?"},
                                },


    CITY_PIG_TALK_FIESTA = {        DEFAULT = {"HUZZAH! HOORAY","'TIS SWINE FIESTA DAYS!","BAD GUYS GO-ETH AWAY","PIGGIES COME OUT-ETH TO PLAY!"}},
    CITY_PIG_TALK_APORKALYPSE_REWARD = {
                                    DEFAULT = {"THOU SAVETH US!","TAKEST THOU REWARD!","THOU IS'T GOOD!","APORKALYPSE 'TIS DONE!"}},

    GROUNDED_WILBA_TALK = { "WILBA LOST'DED MAMA'S CROWN", "MAMA PUNISH'DED WILBA", "MAMA WANT'TH HER CROWN BACK'DED", "FINDETH YON CROWN?"},
    GROUNDED_WILBA_THANKS = { "MANY THANKS, UNPIG", "WILBA SHALT TAKETH YON GIFT", "GIVE'ST THOU TO ME?", "WILBA DESERV'DETH THIS"},
    GROUNDED_WILBA_REFUSE = { "'TIS NAUGHT WILBA'S", "GIVE'ST THEE TO MAMA", "THOU FIND'DED YON CROWN O' MAMA'S!!"},
    WEREWILBA_SPEECH = {"GRRRR", "ARRROOOO!", "GROWRR", "BARK! BARK!", "WOOF"},

    --"WELCOME","LOOKING FOR THING?","I HAVE WARES","YOU BUY TODAY?"},

    CITY_PIG_SHOPKEEPER_CLOSING = {"IS'T THE TIME O' CLOSINGS","COME BACK ON THE 'MORROW","ME CLOSETH SHOP", "ADIEU, ADIEU, REMEMBERS ME", "ME EXEUNT"},

    CITY_PIG_COLLECTOR_TRADE = "ODDITIES",
    CITY_PIG_BANKER_TRADE = "JEWELS",
    CITY_PIG_BEAUTICIAN_TRADE = "FEATHERS",
    CITY_PIG_FLORIST_TRADE = "PETALS",
    CITY_PIG_ERUDITE_TRADE = "NIGHTMARE FUEL",
    CITY_PIG_HUNTER_TRADE = "HOUND'S TOOTH",
    CITY_PIG_MAYOR_TRADE = "GOLD",
    CITY_PIG_MECHANIC_TRADE = "REFINED GOODS",
    CITY_PIG_PROFESSOR_TRADE = "RELICS",
    CITY_PIG_HATMAKER_TRADE = "SILK",
    CITY_PIG_QUEEN_TRADE = "ROYAL BELONGINGS",
    --CITY_PIG_GUARD_TRADE = "SPEARS",
    CITY_PIG_STOREOWNER_TRADE = "HEDGE CUTTINGS",
    CITY_PIG_FARMER_TRADE = "GRASS",
    CITY_PIG_MINER_TRADE = "ROCKS",
    CITY_PIG_SHOPKEEP_TRADE = "GOODS",
    CITY_PIG_USHER_TRADE = "BERRIES",

    QUEENPIGNAMES = {"Queen Malfalfa"},

    CITYPIGNAMES =
    {
        UNISEX = {
            "Melbourne",
            "Peel",
            "Derby",
            "Palmerston",
            "Gladstone",
            "Disraeli",
            "Salisbury",
            "Kensington",
            "Conroy",
            "Greville",
            "Hastings",
            "Aberdeen",
            "Talbot",
            "Thames",
            "Stockton",
            "Darlington",
        },

        FEMALE =
        {
            "Elizabeth",
            "Alexandrina",
            "Alice",
            "Agnes",
            "Arabella",
            "Belle",
            "Beryl",
            "Briar",
            "Beatrice",
            "Catherine",
            "Charlotte",
            "Della",
            "Ebba",
            "Edith",
            "Flora",
            "Florence",
            "Georgette",
            "Henrietta",
            "Luella",
            "Lilian",
            "Louise",
            "Ottilie",
            "Ophelia",
            "Sophronia",
        },
        MALE =
        {
            "William",
            "Clarence",
            "Frederick",
            "Edward",
            "George",
            "Charles",
            "Leopold",
            "Albert",
            "Alfred",
            "Arthur",
            "Ewart",
            "Herbert",
            "Henry",
            "Charley",
            "Douglas",
            "Edison",
            "Edmund",
            "Larkin",
            "Oliver",
            "Merritt",
            "Sterling",
            "Tesla",
            "Thaddeus",
            "Wellington",
            "Gulliver",
        },
    },

    MANDRAKEMANNAMES =
    {
        "Bambuseae",
        "Fabaceae",
        "Betula",
        "Rubus",
        "Daucus carota",
        "Brassica oleracea",
        "Castanea",
        "Trifolium",
        "Cucumis sativus",
        "Cornus",
        "Juniperus",
        "Asclepias",
        "Quercus",
        "Allium",
        "Pisum sativum",
        "Cirsium arvense",
        "Thymus",
    },

    MANDRAKEMAN_BATTLECRY = {
        "ROT!",
        "SOIL!",
        "COMPOST!",
        "MOLD!"
    },

    MANDRAKEMAN_MANDRAKE_BATTLECRY = {
        "THEIF!",
        "ROBBER!",
        "CROOK!",
        "CHEAT!"
    },

    MANDRAKEMAN_GIVEUP = {
        "WHAT DOING?",
        "TIRED",
        "SLEEPY",
        "WORN"
    },

    PORKLAND_SANDBOXINTROS =
    {
        ONE = "Nice two point landing...",
        TWO = "Out of ten that is.",
    },

    PORKLAND_SANDBOXINTROS_WORMWOOD =
    {
        ONE = "Get moving, tree.",
        TWO = "Chop, chop!",
    },
    UI = {
        COOKBOOK = {
            FOOD_EFFECTS_ANTIHISTAMINE = "Clear the airway",
            FOOD_EFFECTS_SPEED_BOOST = "Accelerates movement",
        },
        CRAFTING_FILTERS = {
            ARCHAEOLOGY = "Treasure Hunting",
            NAUTICAL = "Nautical",
        },
        CUSTOMIZATIONSCREEN = {
            ASPARAGUS = "Asparagus",
            ASPARAGUS_REGROWTH = "Asparagus",
            DEEP_JUNGLE_FERN_NOISE = "Jungle Floor Ferns",
            DUNGBEETLE_SETTING = "Dung Beetle",
            DUNGPILE = "Dung Pile",
            LOST_RELICS = "Lost Relics",
            FOG = "Fog",
            GLOWFLYCYCLE = "Glowfly Cycle",
            GLOWFLY_SETTING = "Glowfly",
            GRASS_TALL = "Tall Grass",
            GRASS_TALL_PATCH = "Infected Tall Grass",
            HANGING_VINE_PATCH = "Hanging Vine",
            HANGING_VINE_SETTING = "Hanging Vine",
            HAYFEVER = "Hayfever",
            HUMID = "Humid",
            JUNGLE_BORDER_VINE = "Jungle Canopy Vines",
            LUSH = "Lush",
            PANGOLDEN = "Pangolden",
            PEAGAWK = "Peagawk",
            PIKO_SETTING = "Piko",
            POG_SETTING = "Pog",
            HIPPOPOTAMOOSE_SETTING = "Hippopotamoose",
            PL_CLOCKTYPE = "Clock Type",
            POISON = "Poison",
            PORKLAND_SEASON_START = "Hamlet Starting Season",
            PRESETLEVELDESC = {
                PORKLAND = "A deeply dangerous jungle?",
            },
            PRESETLEVELS = {
                PORKLAND = "Hamlet",
            },
            PUGALISK_FOUNTAIN = "Fountain of Youth",
            TEMPERATE = "Temperate",
            WEEVOLE_SETTING = "Weevole",
        },
        SANDBOXMENU = {
            PORKLAND = "Porkland Start",
            CHOOSEWORLD = "Choose World",
            CLOCKTYPE_DEFAULT = "Default",
            CLOCKTYPE_PORKLAND = "Plateau",
            HUMID = "Humid",
            LOCATIONTABNAME = {
                PORKLAND = "Hamlet",
            },
            LUSH = "Lush",
            PORKLAND_DEFAULT = "Temperate",
            TEMPERATE = "Temperate",
        },
        CRAFTING_STATION_FILTERS = {
            CITY = "City Planning",
        },
        SERVERLISTINGSCREEN = {
            SEASONS = {
                APORKALYPSE = "Aporkalypse",
                HUMID = "Humid",
                LUSH = "Lush",
                TEMPERATE = "Temperate",
            },
        },
    },
}
