return {
    ACTIONS = {
        DISEMBARK = {
            GENERIC = "Exit",
        },
        EMBARK = {
            GENERIC = "Drive",
            SURF = "Ride",
        },
        FISH = {
            GENERIC = "Fish",
            RETRIEVE = "Retrieve",
        },
        HACK = "Hack",
        PAN = "Pan",
        PICK = {
            DIGIN = "Dig in",
        },
        REPAIRBOAT = "Repair",
        RETRIEVE = "Retrieve",
        SHEAR = "Shear",
        SMELT = "Smelt",
        TAKEFROMSHELF = "Retrieve",
    },
    NAMES = {
        ALLOY = "Alloy",
        ANTQUEEN_THRONE = "Stalacmite Throne",
        APORKALYPSE_CLOCK = "Aporkalypse Calendar",
        ARMOR_METALPLATE = "Tin Suit",
        ARMOR_WEEVOLE = "Weevole Mantle",
        ASPARAGUS_PLANTED = "Asparagus",
        BALLPEIN_HAMMER = "Ball Pein Hammer",
        BASEFAN = "Oscillating Fan",
        BILL = "Platapine",
        BILL_QUILL = "Platapine Quill",
        BOATREPAIRKIT = "Boat Repair Kit",
        BOAT_CARGO = "Cargo Boat",
        BOAT_CORK = "Cork Bowl Canoe",
        BOAT_LOGRAFT = "Log Raft",
        BOAT_ROW = "Row Boat",
        BOAT_TORCH = "Boat Torch",
        BONESTAFF = "Pugalisk Wand",
        CHITIN = "Chitin",
        COFFEE = "Coffee",
        COFFEEBEANS = "Coffee Beans",
        COFFEEBEANS_COOKED = "Roasted Coffee Beans",
        CUTNETTLE = "Nettle",
        DUNGBALL = "Dung Ball",
        DUNGBEETLE = "Dung Beetle",
        DUNGPILE = "Dung Pile",
        FLOWER_RAINFOREST = "Exotic Flower",
        FROGLEGS_POISON = "Poison Dartfrog Legs",
        FROGLEGS_POISON_COOKED = "Cooked Dartfrog Legs",
        FROG_POISON = "Poison Dartfrog",
        GLOWFLY = "Glowfly",
        GLOWFLY_COCOON = "Glowfly Cocoon",
        GOLDENMACHETE = "Luxury Machete",
        GOLDPAN = "Gold Pan",
        GOLD_DUST = "Gold Dust",
        GRABBING_VINE = "Hanging Vine",
        GRASS_TALL = "Tall Grass",
        HALBERD = "Halberd",
        HANGING_VINE = "Hanging Vine",
        HIPPOPOTAMOOSE = "Hippopotamoose",
        HIPPO_ANTLER = "Hippopotamoose Antler",
        ICEDTEA = "Iced Tea",
        IRON = "Iron Ore",
        LILYPAD = "Lily Pad",
        LOTUS = "Lotus Plant",
        LOTUS_FLOWER = "Lotus Flower",
        LOTUS_FLOWER_COOKED = "Cooked Lotus Root",
        MACHETE = "Machete",
        MANDRAKEHOUSE = "Mandrake Hill",
        MANDRAKEMAN = "Elder Mandrake",
        PANGOLDEN = "Pangolden",
        PEAGAWK = "Peagawk",
        PEAGAWKFEATHER = "Peagawk Plume",
        PEAGAWK_BUSH = "Blinkbush",
        PIG_RUINS_ARTICHOKE = "Crumbling Carved Stone",
        PIG_RUINS_EXTRACTED = "Chiseled Stone",
        PIG_RUINS_HEAD = "Crumbling Visage",
        PIG_RUINS_IDOL = "Tempting Idol",
        PIG_RUINS_MUSHROOM = "The Jeweled Truffle",
        PIG_RUINS_PIG = "Crumbling Icon",
        PIG_RUINS_PLAQUE = "Eroding Totem",
        PIG_RUINS_SOW = "The Blue Sow",
        PIKO = "Piko",
        PIKO_ORANGE = "Orange Piko",
        PUGALISK = "Pugalisk",
        PUGALISK_CORPSE = "Petrifying Bones",
        PUGALISK_FOUNTAIN = "Fountain of Youth",
        PUGALISK_RUINS_PILLAR = "Teetering Pillar",
        PUGALISK_SKULL = "Pugalisk Skull",
        PUGALISK_TRAP_DOOR = "Ominous Carving",
        RABID_BEETLE = "Rabid Beetle",
        RELIC_1 = "Lost Idol",
        RELIC_2 = "Lost Totem",
        RELIC_3 = "Relic Fragment",
        RELIC_4 = "The Blue Sow",
        RELIC_5 = "The Jeweled Truffle",
        SAIL_SNAKESKIN = "Snakeskin Sail",
        SEDIMENTPUDDLE = "Sparkling Pool",
        SHEARS = "Shears",
        SMELTER = "Smelter",
        SNAKEBONESOUP = "Snake Bone Soup",
        SNAKESKIN = "Snakeskin",
        SNAKE_BONE = "Snake Bone",
        SUNKEN_RELIC = "Sunken Object",
        TEA = "Tea",
        TEATREE = "Tea Tree",
        TEATREE_NUT = "Seed Pod",
        TEATREE_NUT_COOKED = "Cooked Seed Pod",
        TEATREE_NUT_SAPLING = "Tea Tree Sapling",
        TREE_PILLAR = "Great Leafy Stalk",
        WEEVOLE = "Weevole",
        WEEVOLE_CARAPACE = "Weevole Carapace",
    },
    RECIPE_DESC = {
        ARMOR_METALPLATE = "Strong and sturdy.",
        ARMOR_WEEVOLE = "Kinda gross, but surprisingly strong.",
        BASEFAN = "Relieves hay fever, keeps you dry.",
        BOATREPAIRKIT = "Stay afloat in that boat!",
        BOAT_CARGO = "Hoarding at sea!",
        BOAT_CORK = "Good for portage and tough as porridge.",
        BOAT_LOGRAFT = "Boat at your own risk.",
        BOAT_ROW = "Row, row, row your boat!",
        BOAT_TORCH = "See, at sea.",
        BONESTAFF = "Wield the gaze of the Pugalisk!",
        GOLDENMACHETE = "Hack stuff in STYLE!",
        GOLDPAN = "Pans gold actually.",
        HALBERD = "Pointy and hurty.",
        MACHETE = "Hack stuff!",
        SAIL_SNAKESKIN = "Heavy duty wind catcher.",
        SHEARS = "Cut your way into adventure.",
        SMELTER = "Turn Iron into Alloy.",
    },
    UI = {
        COOKBOOK = {
            FOOD_EFFECTS_ANTIHISTAMINE = "Clear the airway",
            FOOD_EFFECTS_SPEED_BOOST = "Accelerates movement",
        },
        CRAFTING_FILTERS = {
            ARCHAEOLOGY = "Treasure Hunting",
            NAUTICAL = "Nautical",
        },
        CUSTOMIZATIONSCREEN = {
            PRESETLEVELS = {PORKLAND = "Hamlet",},
            PRESETLEVELDESC = {PORKLAND = "A deeply dangerous jungle?",},
            ASPARAGUS = "Asparagus",
            ASPARAGUS_REGROWTH = "Asparagus",
            BILL_SETTING = "Platapine",
            DEEP_JUNGLE_FERN_NOISE = "Jungle Floor Ferns",
            DUNGBEETLE_SETTING = "Dung Beetle",
            DUNGPILE = "Dung Pile",
            FOG = "Fog",
            FROG_POISON_SETTING = "Poison Dartfrog",
            GLOWFLYCYCLE = "Glowfly Cycle",
            GLOWFLY_SETTING = "Glowfly",
            GRASS_TALL = "Tall Grass",
            GRASS_TALL_BUNCHES = "Tall Grass Fields",
            HANGING_VINE_PATCH = "Hanging Vine",
            HANGING_VINE_SETTING = "Hanging Vine",
            HAYFEVER = "Hayfever",
            HIPPOPOTAMOOSE = "Hippopotamoose",
            HIPPOPOTAMOOSE_SETTING = "Hippopotamoose",
            HUMID = "Humid",
            JUNGLE_BORDER_VINE = "Jungle Canopy Vines",
            LOST_RELICS = "Lost Relics",
            LOTUS = "lotus",
            LUSH = "Lush",
            MANDRAKEMAN_SETTING = "Elder Mandrake",
            MOSQUITO_SETTING = "Mosquito",
            PANGOLDEN = "Pangolden",
            PEAGAWK = "Peagawk",
            PIKO_SETTING = "Piko",
            PL_CLOCKTYPE = "Clock Type",
            POISON = "Poison",
            PORKLAND_SEASON_START = "Hamlet Starting Season",
            PRESETLEVELDESC = {
                PORKLAND = "A deeply dangerous jungle?",
            },
            PRESETLEVELS = {
                PORKLAND = "Hamlet",
            },
            PUGALISK_FOUNTAIN = "Fountain of Youth",
            RUINED_SCULPTURES = "Ruined Sculptures",
            TEMPERATE = "Temperate",
            WEEVOLE_SETTING = "Weevole",
        },
        SANDBOXMENU = {
            CHOOSEWORLD = "Choose World",
            CLOCKTYPE_DEFAULT = "Default",
            CLOCKTYPE_PORKLAND = "Plateau",
            HUMID = "Humid",
            LOCATIONTABNAME = {
                PORKLAND = "Hamlet",
            },
            LUSH = "Lush",
            PORKLAND_DEFAULT = "Temperate",
            TEMPERATE = "Temperate",
        },
        SERVERLISTINGSCREEN = {
            SEASONS = {
                APORKALYPSE = "Aporkalypse",
                HUMID = "Humid",
                LUSH = "Lush",
                TEMPERATE = "Temperate",
            },
        },
    },
}
