return {
    ACTIONS = {
        HACK = "Hack",
        PAN = "Pan",
        PICK = {
            DIGIN = "Dig in",
        },
        SHEAR = "Shear",
        SMELT = "Smelt",
    },
    NAMES = {
        ALLOY = "Alloy",
        APORKALYPSE_CLOCK = "Aporkalypse Calendar",
        ARMOR_METALPLATE = "Tin Suit",
        ARMOR_WEEVOLE = "Weevole Mantle",
        ASPARAGUS_PLANTED = "Asparagus",
        BASEFAN = "Oscillating Fan",
        CHITIN = "Chitin",
        CUTNETTLE = "Nettle",
        DUNGBALL = "Dung Ball",
        DUNGBEETLE = "Dung Beetle",
        DUNGPILE = "Dung Pile",
        FLOWER_RAINFOREST = "Exotic Flower",
        GLOWFLY = "Glowfly",
        GLOWFLY_COCOON = "Glowfly Cocoon",
        GOLDENMACHETE = "Luxury Machete",
        GOLDPAN = "Gold Pan",
        GOLD_DUST = "Gold Dust",
        GRABBING_VINE = "Hanging Vine",
        GRASS_TALL = "Tall Grass",
        HALBERD = "Halberd",
        HANGING_VINE = "Hanging Vine",
        IRON = "Iron Ore",
        MACHETE = "Machete",
        PANGOLDEN = "Pangolden",
        PEAGAWK = "Peagawk",
        PEAGAWKFEATHER = "Peagawk Plume",
        PEAGAWK_BUSH = "Blinkbush",
        PIKO = "Piko",
        PIKO_ORANGE = "Orange Piko",
        RABID_BEETLE = "Rabid Beetle",
        SEDIMENTPUDDLE = "Sparkling Pool",
        SHEARS = "Shears",
        SMELTER = "Smelter",
        TEATREE = "Tea Tree",
        TEATREE_NUT = "Seed Pod",
        TEATREE_NUT_COOKED = "Cooked Seed Pod",
        TEATREE_SAPLING = "Tea Tree Sapling",
        TREE_PILLAR = "Great Leafy Stalk",
        WEEVOLE = "Weevole",
        WEEVOLE_CARAPACE = "Weevole Carapace",
    },
    RECIPE_DESC = {
        ARMOR_METALPLATE = "Strong and sturdy.",
        ARMOR_WEEVOLE = "Kinda gross, but surprisingly strong.",
        BASEFAN = "Relieves hay fever, keeps you dry.",
        GOLDENMACHETE = "Hack stuff in STYLE!",
        GOLDPAN = "Pans gold actually.",
        HALBERD = "Pointy and hurty.",
        MACHETE = "Hack stuff!",
        SHEARS = "Cut your way into adventure.",
        SMELTER = "Turn Iron into Alloy.",
    },
    UI = {
        CUSTOMIZATIONSCREEN = {
            ASPARAGUS = "Asparagus",
            ASPARAGUS_REGROWTH = "Asparagus",
            DEEP_JUNGLE_FERN_NOISE = "Jungle Floor Ferns",
            DUNGBEETLE_SETTING = "Dung Beetle",
            DUNGPILE = "Dung Pile",
            FOG = "Fog",
            GLOWFLYCYCLE = "Glowfly Cycle",
            GLOWFLY_SETTING = "Glowfly",
            GRASS_TALL = "Tall Grass",
            GRASS_TALL_PATCH = "Infected Tall Grass",
            HANGING_VINE_PATCH = "Hanging Vine",
            HANGING_VINE_SETTING = "Hanging Vine",
            HAYFEVER = "Hayfever",
            HUMID = "Humid",
            JUNGLE_BORDER_VINE = "Jungle Canopy Vines",
            LUSH = "Lush",
            PANGOLDEN = "Pangolden",
            PEAGAWK = "Peagawk",
            PEAGAWK_SETTING = "Peagawk",
            PL_CLOCKTYPE = "Clock Type",
            POISON = "Poison",
            PORKLAND_SEASON_START = "Porkland Starting Season",
            TEMPERATE = "Temperate",
            WEEVOLE_SETTING = "Weevole",
        },
        SANDBOXMENU = {
            CHOOSEWORLD = "Choose World",
            CLOCKTYPE_DEFAULT = "Default",
            CLOCKTYPE_PORKLAND = "Plateau",
            HUMID = "Humid",
            LOCATIONTABNAME = {
                PORKLAND = "Porkland",
            },
            LUSH = "Lush",
            PORKLAND_DEFAULT = "Temperate",
            TEMPERATE = "Temperate",
        },
        SERVERLISTINGSCREEN = {
            SEASONS = {
                APORKALYPSE = "Aporkalypse",
                HUMID = "Humid",
                LUSH = "Lush",
                TEMPERATE = "Temperate",
            },
        },
    },
}
