return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "She's floating just fine right now.",
        },
        USEDOOR = {
            GENERIC = "It won't open.",
            LOCKED = "It's locked.",
        },
    },
    ANNOUCE_BATS = "I don't like the look of this.",
    ANNOUNCE_BOAT_DAMAGED = "I think I sprung a leak.",
    ANNOUNCE_BOAT_SINKING = "I seem to be sinking.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I need to get to land!",
    ANNOUNCE_DEHUMID = {
        "Ah, so much better.",
    },
    ANNOUNCE_HAYFEVER = "My nose feels.. itchy.",
    ANNOUNCE_HAYFEVER_OFF = "I don't want to claw my eyes out anymore.",
    ANNOUNCE_PICKPOOP = {
        "Eugg!",
        "Gross!",
        "Ick!",
        "I got some on my hands!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Its hide is too tough!",
        "A tough nut to crack.",
        "Break, darn you!",
    },
    ANNOUNCE_SNEEZE = "AHHH CHOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is so heavy.",
        "This %s is too hot.",
    },
    ANNOUNCE_WAVE_BOOST = "Weeeee!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Bereft of life.",
            GENERIC = "Science could not have done this.",
            SLEEPING = "Shhh. It's sleeping.",
        },
        ALLOY = "Ahoy there, alloy!",
        ALOE = "Scientifical and nutritional.",
        ALOE_COOKED = "I cooked it!",
        ALOE_PLANTED = "A plant with many uses.",
        ALOE_SEEDS = "It's an aloe seed.",
        ANCIENT_HULK = "I regret causing that.",
        ANCIENT_ROBOTS_ASSEMBLY = "It's not quite done yet.",
        ANCIENT_ROBOT_CLAW = "Careful, it's armed!",
        ANCIENT_ROBOT_HEAD = "I'm heading out of here!",
        ANCIENT_ROBOT_LEG = "Not a leg to stand on.",
        ANCIENT_ROBOT_RIBS = "All that iron should be mine.",
        ANTCHEST = "Takes its sweet time making honey.",
        APORKALYPSE_CLOCK = "Looks scientifically apocalyptic.",
        ARMOR_METALPLATE = "Science says I'm safe in here.",
        ARMOR_WEEVOLE = "Yeesh. This is kinda creepy.",
        ASPARAGUS_PLANTED = "I should pick those!",
        BALLPEIN_HAMMER = "It's a tiny little hammer.",
        BASEFAN = "Fan-tastic.",
        BILL = {
            DEAD = "Haha. It's dead.",
            GENERIC = "A spinny spiny sort.",
            SLEEPING = "Good. It's sleeping.",
        },
        BILL_QUILL = "It's boring.",
        BOATREPAIRKIT = "This will add some float to my boat.",
        BOAT_CARGO = "It has room for all my stuff!",
        BOAT_CORK = "An accident waiting to happen.",
        BOAT_LOGRAFT = "This looks... sort of boat-like...",
        BOAT_ROW = "It runs on elbow grease.",
        BOAT_TORCH = "This'll keep my hands free.",
        BONESTAFF = "Sends shivers down my spine.",
        BRAMBLESPIKE = "An overly complicated spiky thing.",
        BRAMBLE_BULB = "A bulbous bulb. Should be good for something.",
        BRAMBLE_CORE = "It's pretty, but is it worth the trouble?",
        BURR = "Something's inside, I just know it!",
        BURR_SAPLING = "It looks tenacious.",
        CHITIN = "Bug coating.",
        CITY_LAMP = {
            GENERIC = "Plain fire. No science involved.",
            ON = "Lusterless.",
        },
        CLAWPALMTREE = "I'm in-tree-ged.",
        CLAWPALMTREE_SAPLING = "Science at work.",
        COFFEE = "Smells delicious and energizing!",
        COFFEEBEANS = "They could use some roasting.",
        COFFEEBEANS_COOKED = "Heat definitely improved them.",
        CORK = "Science says it floats.",
        CORKCHEST = "A pest protector.",
        CUTNETTLE = "Science says the sharp edges are good for my lungs.",
        DISARMING_KIT = "A trap for traps!",
        DUNGBALL = "Most definitely poop.",
        DUNGBEETLE = {
            DEAD = "Dung for.",
            GENERIC = "She's on a roll.",
            SLEEPING = "She's pooped.",
            UNDUNGED = "She needs to get her dung together.",
        },
        DUNGPILE = {
            GENERIC = "It's a pile of dung.",
            PICKED = "Dung and dung.",
        },
        FLOWER_RAINFOREST = "It smells vaguely tolerable.",
        FROGLEGS_POISON = "Looks noxious.",
        FROGLEGS_POISON_COOKED = "Tainted fricassee.",
        FROG_POISON = {
            DEAD = "Lifeless.",
            GENERIC = "A pernicious amphibian.",
            SLEEPING = "Looks like it's hibernating.",
        },
        GLOWFLY = {
            DEAD = "Lights out forever.",
            GENERIC = "A light aflight.",
            SLEEPING = "Out like a light.",
        },
        GLOWFLY_COCOON = "Snug as a bug.",
        GOLDENMACHETE = "Hack in style!",
        GOLDPAN = "Critics panned it.",
        GOLD_DUST = "Aw... it's hardly worth anything.",
        GRABBING_VINE = "Always hanging around.",
        GRASS_TALL = {
            BURNING = "A grass fire!",
            GENERIC = "It's too tough to pick with my hands.",
            PICKED = "Looks like I got it all.",
        },
        HALBERD = "Now I can't be caught off-guard.",
        HANGING_VINE = "Always hanging around.",
        HIPPOPOTAMOOSE = "Large and pointy-headed.",
        HIPPO_ANTLER = "This ought to be of some use.",
        ICEDTEA = "I scream for iced tea.",
        INFUSED_IRON = "Metal touched with science.",
        IRON = "Isn't it ironic?",
        KINGFISHER = {
            DEAD = "Perished.",
            GENERIC = "What a pointy bill!",
            SLEEPING = "In a slumber.",
        },
        LAWNORNAMENT = {
            BURNING = "Take that, gratuitous decoration!",
            BURNT = "Well, it's gone now.",
            GENERIC = "A bit of ornamentation.",
        },
        LIFEPLANT = "Sure likes looking at itself.",
        LILYPAD = "It's full of science. I can tell.",
        LIVING_ARTIFACT = "It's alive. ALIVE!",
        LOTUS = "The science is blooming well this season.",
        LOTUS_FLOWER = "A lovely science flower.",
        LOTUS_FLOWER_COOKED = "A delicacy.",
        MACHETE = "I like the cut of this blade.",
        MAGNIFYING_GLASS = "Science awaits!",
        MANDRAKEHOUSE = "It looks... screamy.",
        MANDRAKEMAN = "Large and screamy.",
        MEAN_FLYTRAP = {
            DEAD = "Cadaverous.",
            GENERIC = "Plants shouldn't move! That's just science!",
            SLEEPING = "Sleep well, horrible plant.",
        },
        METALPLATEHAT = "Protects my brains.",
        NECTAR_POD = "I could use this to make honey.",
        OINC = "It's gotta be worth something.",
        OINC10 = "I'm rich!",
        OINC100 = "A coin worth my gentlemanly stature.",
        PANGOLDEN = "It likes rich food.",
        PARROT_BLUE = {
            DEAD = "An ex-parrot.",
            GENERIC = "An azure bird.",
            SLEEPING = "It's just resting.",
        },
        PEAGAWK = {
            DEAD = "Dead-eyed.",
            GENERIC = "That bush is alive!",
            SLEEPING = "It's getting some shut-eye.",
        },
        PEAGAWKFEATHER = "Still blinking.",
        PEAGAWK_BUSH = "Look! An iris bush.",
        PIGEON = {
            DEAD = "It has passed.",
            GENERIC = "It's only carrying a couple diseases.",
            SLEEPING = "It's fast asleep.",
        },
        PIGHOUSE_CITY = {
            BURNING = "That house is on fire!",
            GENERIC = "Both a house, and a home.",
        },
        PIGHOUSE_FARM = {
            BURNING = "That farm is on fire!",
            GENERIC = "It's a peaceful life.",
        },
        PIGHOUSE_MINE = {
            BURNING = "The mine is on fire!",
            GENERIC = "I have no quarry with them.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "I didn't vote for him.",
            SLEEPING = "Typical. Sleeping on the job.",
        },
        PIGMAN_QUEEN = "She looks bossy.",
        PIG_GUARD_TOWER = {
            BURNING = "The tower is on fire!",
            GENERIC = "It's surprisingly sturdy.",
        },
        PIG_PALACE = "Majestic.",
        PIG_RUINS_ANT = "An abstract insect or something.",
        PIG_RUINS_ARTICHOKE = "Arti-choked.",
        PIG_RUINS_HEAD = "Looks like a headache.",
        PIG_RUINS_IDOL = "These ruins have been ruined.",
        PIG_RUINS_MUSHROOM = "A vivid display of... their love.",
        PIG_RUINS_PLAQUE = "I could probably sell that to one of those pigs.",
        PIG_RUINS_SOW = "A superb local art craft.",
        PIG_SHOP_CITYHALL = {
            BURNING = "It wasn't me.",
            GENERIC = "The local lawmaker.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Who would do that?!",
            GENERIC = "I'm a Gentleman Politician now.",
        },
        PIKO = {
            DEAD = "I feel kinda bad.",
            GENERIC = "He's a bit of a nut job.",
            SLEEPING = "Probably dreaming of trees.",
        },
        PIKO_ORANGE = {
            DEAD = "I feel kinda bad.",
            GENERIC = "For some reason I'm craving tea.",
            SLEEPING = "Probably dreaming of trees.",
        },
        PUGALISK = "Scientifically speaking, it shouldn't exist.",
        PUGALISK_CORPSE = "Petrifying.",
        PUGALISK_FOUNTAIN = "I prefer fountains of knowledge.",
        PUGALISK_RUINS_PILLAR = "Defying the laws of science.",
        PUGALISK_SKULL = "A numbskull.",
        PUGALISK_TRAP_DOOR = "Well that looks ominous.",
        RABID_BEETLE = {
            DEAD = "A late beetle.",
            GENERIC = "Looks deranged.",
            SLEEPING = "In a slumber.",
        },
        RADISH = "It looks radishing.",
        RADISH_COOKED = "I wonder if this makes it taste better.",
        RADISH_PLANTED = "It's trying to hide.",
        RADISH_SEEDS = "It's a radish seed.",
        RAINFORESTTREE = {
            BURNING = "It's done for.",
            BURNT = "Burnt up.",
            CHOPPED = "Not sure what it is. I'm stumped.",
            GENERIC = "A tropical tree.",
        },
        REEDS_WATER = "Aquatic reeds.",
        RELIC_1 = {
            GENERIC = "A priceless piece of history.",
            SUNKEN = "Ancient litter.",
        },
        RELIC_2 = {
            GENERIC = "The relic of an ancient culture.",
            SUNKEN = "It's green and submarine.",
        },
        RELIC_3 = {
            GENERIC = "Looks valuable.",
            SUNKEN = "I'll have to fish it out.",
        },
        RELIC_4 = {
            GENERIC = "A regal relic.",
            SUNKEN = "Something fishy down there.",
        },
        RELIC_5 = {
            GENERIC = "It's an old fancy feast.",
            SUNKEN = "I found something.",
        },
        ROOTTRUNK_CHILD = "It rooted out all my things!",
        SAIL_SNAKESKIN = "Scale it and sail it!",
        SCORPION = {
            DEAD = "It's dead. Good.",
            GENERIC = "That better not be poisonous.",
            SLEEPING = "Now'd be a good time to smush it.",
        },
        SEDIMENTPUDDLE = "Pool's gold.",
        SHEARS = "Shear-ly delightful.",
        SMELTER = {
            BURNT = "The smelter got smelted.",
            COOKING_SHORT = "This is going to take a while.",
            DONE = "It's done!",
            EMPTY = "I smelt that!",
        },
        SNAKEBONESOUP = "The best way to serve snake.",
        SNAKEOIL = "The label says \"Jay's Wondrous Snake Oil!\"",
        SNAKESKIN = "I'm intrigued AND repelled.",
        SNAKE_AMPHIBIOUS = "Agh! Stay away!",
        SNAKE_BONE = "Ha ha, snake. I have your bone.",
        SPIDER_MONKEY = {
            DEAD = "That's that.",
            GENERIC = "That thing is rather large!",
            SLEEPING = "I don't want to wake it.",
        },
        SPIDER_MONKEY_NEST = "I do not want to see what lives in there.",
        SPIDER_MONKEY_TREE = "Wooden.",
        TEA = "Tea time!",
        TEATREE = "What a lovely tree.",
        TEATREE_NUT = "Stops the seasonal sneezing.",
        TEATREE_NUT_COOKED = "Take that, tiny tree!",
        TEATREE_NUT_SAPLING = "It's a little puny.",
        TOUCAN = "I tou-can't catch him.",
        TREE_PILLAR = "It totally blocks out the sun.",
        TUBERTREE = "An axe won't cut it.",
        TUBER_BLOOM_CROP = "It's a blooming tuber!",
        TUBER_BLOOM_CROP_COOKED = "Did I cook the flower too?",
        TUBER_CROP = "Too bad tuber.",
        TUBER_CROP_COOKED = "I wonder if it's still poisonous?",
        VAMPIREBAT = {
            DEAD = "I feel a bit safer.",
            GENERIC = "I'd prefer to keep all of my blood.",
            SLEEPING = "Hopefully it won't get up again.",
        },
        VAMPIREBATCAVE = "A den of bloodsuckers.",
        VENOMGLAND = "Only poison can cure poison.",
        VENUS_STALK = "I bet I could find a use for it.",
        VINE = "Maybe I can tie stuff up with this.",
        WALKINGSTICK = "Perfect for a gentleman scientist.",
        WATERDROP = "Water you think it does?",
        WEEVOLE = "Whee!",
        WEEVOLE_CARAPACE = "I'll be careful with this carapace.",
    },
}
