return {
    ANNOUNCE_DEHUMID = {
        "Ah, so much better.",
    },
    ANNOUNCE_HAYFEVER = "My nose feels.. itchy.",
    ANNOUNCE_HAYFEVER_OFF = "I don't want to claw my eyes out anymore.",
    ANNOUNCE_PICKPOOP = {
        "Eugg!",
        "Gross!",
        "Ick!",
        "I got some on my hands!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Its hide is too tough!",
        "A tough nut to crack.",
        "Break, darn you!"
    },
    ANNOUNCE_SNEEZE = "AHHH CHOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is so heavy.",
        "This %s is too hot.",
    },
    DESCRIBE = {
        ALLOY = "Ahoy there, alloy!",
        APORKALYPSE_CLOCK = "Looks scientifically apocalyptic.",
        ARMOR_METALPLATE = "Science says I'm safe in here.",
        ARMOR_WEEVOLE = "Yeesh. This is kinda creepy.",
        ASPARAGUS_PLANTED = "I should pick those!",
        BASEFAN = "Fan-tastic.",
        BONESTAFF = "Sends shivers down my spine.",
        CHITIN = "Bug coating.",
        COFFEE = "Smells delicious and energizing!",
        COFFEEBEANS = "They could use some roasting.",
        COFFEEBEANS_COOKED = "Heat definitely improved them.",
        CUTNETTLE = "Science says the sharp edges are good for my lungs.",
        DUNGBALL = "Most definitely poop.",
        DUNGBEETLE = {
            DEAD = "Dung for.",
            GENERIC = "She's on a roll.",
            SLEEPING = "She's pooped.",
            UNDUNGED = "She needs to get her dung together.",
        },
        DUNGPILE = {
            GENERIC = "It's a pile of dung.",
            PICKED = "Dung and dung.",
        },
        FLOWER_RAINFOREST = "It smells vaguely tolerable.",
        GLOWFLY = {
            DEAD = "Lights out forever.",
            GENERIC = "A light aflight.",
            SLEEPING = "Out like a light.",
        },
        GLOWFLY_COCOON = "Snug as a bug.",
        GOLDENMACHETE = "Hack in style!",
        GOLDPAN = "Critics panned it.",
        GOLD_DUST = "Aw... it's hardly worth anything.",
        GRABBING_VINE = "Always hanging around.",
        GRASS_TALL = {
            BURNING = "A grass fire!",
            GENERIC = "It's too tough to pick with my hands.",
            PICKED = "Looks like I got it all.",
        },
        HALBERD = "Now I can't be caught off-guard.",
        HANGING_VINE = "Always hanging around.",
        ICEDTEA = "I scream for iced tea.",
        IRON = "Isn't it ironic?",
        MACHETE = "I like the cut of this blade.",
        PANGOLDEN = "It likes rich food.",
        PEAGAWK = {
            DEAD = "Dead-eyed.",
            GENERIC = "That bush is alive!",
            SLEEPING = "It's getting some shut-eye.",
        },
        PEAGAWKFEATHER = "Still blinking.",
        PEAGAWK_BUSH = "Look! An iris bush.",
        PIKO = {
            DEAD = "I feel kinda bad.",
            GENERIC = "He's a bit of a nut job.",
            SLEEPING = "Probably dreaming of trees.",
        },
        PIKO_ORANGE = {
            DEAD = "I feel kinda bad.",
            GENERIC = "For some reason I'm craving tea.",
            SLEEPING = "Probably dreaming of trees.",
        },
        PUGALISK = "Scientifically speaking, it shouldn't exist.",
        PUGALISK_CORPSE = "Petrifying.",
        PUGALISK_FOUNTAIN = "I prefer fountains of knowledge.",
        PUGALISK_RUINS_PILLAR = "Defying the laws of science.",
        PUGALISK_SKULL = "A numbskull.",
        PUGALISK_TRAP_DOOR = "Well that looks ominous.",
        RABID_BEETLE = {
            DEAD = "A late beetle.",
            GENERIC = "Looks deranged.",
            SLEEPING = "In a slumber.",
        },
        SEDIMENTPUDDLE = "Pool's gold.",
        SHEARS = "Shear-ly delightful.",
        SMELTER = {
            BURNT = "The smelter got smelted.",
            COOKING_SHORT = "This is going to take a while.",
            DONE = "It's done!",
            EMPTY = "I smelt that!",
        },
        SNAKE_BONE = "Ha ha, snake. I have your bone.",
        SNAKEBONESOUP = "The best way to serve snake.",
        TEA = "Tea time!",
        TEATREE = "What a lovely tree.",
        TEATREE_NUT = "Stops the seasonal sneezing.",
        TEATREE_NUT_COOKED = "Take that, tiny tree!",
        TEATREE_NUT_SAPLING = "It's a little puny.",
        TREE_PILLAR = "It totally blocks out the sun.",
        WEEVOLE = "Whee!",
        WEEVOLE_CARAPACE = "I'll be careful with this carapace.",
    },
}
