return {
    ANNOUNCE_DEHUMID = {
        "Ahhh. The season has turned.",
    },
    ANNOUNCE_HAYFEVER = "Evidence would suggest it's allergy season.",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Evidentaly, it's no longer allergy season.",
    ANNOUNCE_PICKPOOP = {
        "What's that?",
        "Oh! That's interesting!",
        "I found something!",
    },
    ANNOUNCE_SNEEZE = "aH-CHOOOOOOOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s really weighs me down.",
        "The humid air is making this %s heavy.",
    },
    DESCRIBE = {
        ALLOY = "Ah, refined metal. As good as any factory could produce.",
        ANTQUEEN_THRONE = "Theoretically, the queen would be sitting on a reserve of valuables.",
        APORKALYPSE_CLOCK = "Wonderful! I wonder if I could make the world end sooner.",
        ARMOR_METALPLATE = "The riveting in this suit is quite sophisticated.",
        ARMOR_WEEVOLE = "Exoskeleton armor to protect my endoskeleton.",
        ASPARAGUS_PLANTED = "A cluster of edible spring vegetables!",
        BALLPEIN_HAMMER = "A diminutive tool, ideal for negotiating the removal of gems.",
        BASEFAN = "Magnificent! What a marvel of engineering!",
        CHITIN = "Wonderful! The exoskeleton of a deceased insect!",
        CUTNETTLE = "A large leaf nettle plant native to these parts. Also it smells funny.",
        DUNGBALL = "Excellent! The act of rolling has picked up a motley of paraphernalia.",
        DUNGBEETLE = {
            DEAD = "Expired. But it appears that is a recent occurrence.",
            GENERIC = "Such agility! The way he's able to navigate on that sphere of poop!",
            SLEEPING = "A dormant dung dancer.",
            UNDUNGED = "Presumably, he's seeking a replacement for his poop sphere.",
        },
        DUNGPILE = {
            GENERIC = "Some creature has produced an excessive amount of excrement!",
            PICKED = "The road of discovery has many hurdles.",
        },
        FLOWER_RAINFOREST = "Curious. Picking these has a positive effect on my psyche.",
        GLOWFLY = {
            DEAD = "Cadaverous.",
            GENERIC = "The luminous oculus on this pterygota is inspiring!",
            SLEEPING = "Evidently, its bioluminescence is dormant too.",
        },
        GLOWFLY_COCOON = "It appears to be undergoing some kind of transubstantiation.",
        GOLDENMACHETE = "Gold is so plentiful here I can use it in household tools.",
        GOLDPAN = "I do hope the holes were meant to be there.",
        GOLD_DUST = "Evidently, it's the preferred sustenance of those long nosed quadrupeds.",
        GRABBING_VINE = "Kleptomaniac vegetation. How wonderful!",
        GRASS_TALL = {
            BURNING = "Evidently, grass here has the same flammability qualities as at home.",
            GENERIC = "The obstinacy of this grass requires something sharper than my hands.",
            PICKED = "Previously experience suggests this will grow back.",
        },
        HALBERD = "A marvelously versatile instrument capable of causing incredible harm!",
        HANGING_VINE = "Kleptomaniac vegetation. How wonderful!",
        IRON = "Marvelous! Iron is invaluable for manufacturing the tools I need!",
        MACHETE = "A pragmatic tool for slashing objects.",
        PANGOLDEN = "Evidently, it poops gold. Fascinating!",
        PEAGAWK = {
            DEAD = "Evidently, it didn't see that coming.",
            GENERIC = "Curious. Can it see out of all of those ocular quills?",
            SLEEPING = "Perhaps I can now pluck one of its ocular quills.",
        },
        PEAGAWKFEATHER = "Theoretically, there's an intact nervous system that keeps the eye moving.",
        PEAGAWK_BUSH = {
            GENERIC = "I'm experiencing the inescapable perception that I'm being watched.",
            SLEEPING = "That insight that spied on me was gone.",
        },
        PIG_RUINS_ARTICHOKE = "An elegant depiction of a giant vegetable.",
        PIG_RUINS_HEAD = "Evidence would suggest he's an important figure in the pig's past.",
        PIG_RUINS_IDOL = "Theoretically, it can be detached from its base.",
        PIG_RUINS_PLAQUE = "Evidently, I'll need something to sever it from the base.",
        RABID_BEETLE = {
            DEAD = "An occurrance of invertebrate respiratory failure.",
            GENERIC = "Evidently, it acquires facial hair when it matures.",
            SLEEPING = "It's respiratory structures are vibrating.",
        },
        SEDIMENTPUDDLE = "Evidence would suggest there's gold down there!",
        SHEARS = "Cutting implements constructed from raw metal.",
        SMELTER = {
            BURNT = "Smelting is a dangerous business in here.",
            COOKING_SHORT = "I can't wait to watch more about the properties of these metals.",
            DONE = "Done already? Remarkable!",
            EMPTY = "Magnificent! Perhaps I can build a factory here as well.",
        },
        TREE_PILLAR = "The circumference of this tree's trunk is unusually large.",
        WEEVOLE = "What a wonderfully persistent species of insect!",
        WEEVOLE_CARAPACE = "Excellent! It's the exoskeleton of a hexapod invertebrate!",
    },
}
