return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "This vessel has already been repaired to its optimum level.",
        },
    },
    ANNOUCE_BATS = "Bats! I recognize the silhouette.",
    ANNOUNCE_BOAT_DAMAGED = "I'll need to repair this boat promptly.",
    ANNOUNCE_BOAT_SINKING = "Gaining water, rapidly.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "After all my triumphs, I've met defeat!",
    ANNOUNCE_DEHUMID = {
        "Ahhh. The season has turned.",
    },
    ANNOUNCE_HAYFEVER = "Evidence would suggest it's allergy season.",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Evidentaly, it's no longer allergy season.",
    ANNOUNCE_PICKPOOP = {
        "What's that?",
        "Oh! That's interesting!",
        "I found something!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That was the wrong spot.",
        "It must have a weakness!",
        "The scales are much too thick there.",
    },
    ANNOUNCE_SNEEZE = "aH-CHOOOOOOOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s really weighs me down.",
        "The humid air is making this %s heavy.",
    },
    ANNOUNCE_WAVE_BOOST = "Woo hoo! Wave mechanics!",
    DESCRIBE = {
        ALLOY = "Ah, refined metal. As good as any factory could produce.",
        ANCIENT_HULK = "A wonderful automaton of ancient technology brought back to life!",
        ANCIENT_ROBOTS_ASSEMBLY = "Fascinating! What will transpire once it is all assembled?",
        ANCIENT_ROBOT_CLAW = "The metacarpus of an automaton. I must find the rest!",
        ANCIENT_ROBOT_HEAD = "Who built this beautiful cranium? I have many questions!",
        ANCIENT_ROBOT_LEG = "A leg! A beautiful mechanical leg!",
        ANCIENT_ROBOT_RIBS = "The carapace of a beautiful automaton!",
        APORKALYPSE_CLOCK = "Wonderful! I wonder if I could make the world end sooner.",
        ARMOR_METALPLATE = "The riveting in this suit is quite sophisticated.",
        ARMOR_WEEVOLE = "Exoskeleton armor to protect my endoskeleton.",
        ASPARAGUS_PLANTED = "A cluster of edible spring vegetables!",
        BASEFAN = "Magnificent! What a marvel of engineering!",
        BILL = {
            DEAD = "Dead. But rigor mortis has yet to set in.",
            GENERIC = "Incredible! It's spinning at subsonic speeds!",
            SLEEPING = "Theoretically, all that spinning has tuckered him out.",
        },
        BILL_QUILL = "Surprisingly hardy. Theoretically, it could be used as a tool.",
        BOATREPAIRKIT = "Strange. Where did the glue come from?",
        BOAT_CARGO = "A top-notch transporter of goods across bodies of water.",
        BOAT_CORK = "Theoretically, it works. Though I won't predict for how long.",
        BOAT_LOGRAFT = "The dispersal of weight should keep me briefly afloat.",
        BOAT_ROW = "A sufficient ship for my mundane explorative tasks.",
        BOAT_TORCH = "The fortunate angle of this stick makes for an ideal hanging device.",
        BONESTAFF = "Another vanguard device I could use to bring the world to a new age!",
        CHITIN = "Wonderful! The exoskeleton of a deceased insect!",
        COFFEE = "Interesting. Caffeinated beverages have a heightened effect here.",
        COFFEEBEANS = "I will need to roast it before I can consume it without ill effect.",
        COFFEEBEANS_COOKED = "Has an ephemeral effect on my adrenal gland.",
        CUTNETTLE = "A large leaf nettle plant native to these parts. Also it smells funny.",
        DISARMING_KIT = "An aid in negotiating those violent booby traps.",
        DUNGBALL = "Excellent! The act of rolling has picked up a motley of paraphernalia.",
        DUNGBEETLE = {
            DEAD = "Expired. But it appears that is a recent occurrence.",
            GENERIC = "Such agility! The way he's able to navigate on that sphere of poop!",
            SLEEPING = "A dormant dung dancer.",
            UNDUNGED = "Presumably, he's seeking a replacement for his poop sphere.",
        },
        DUNGPILE = {
            GENERIC = "Some creature has produced an excessive amount of excrement!",
            PICKED = "The road of discovery has many hurdles.",
        },
        FLOWER_RAINFOREST = "Curious. Picking these has a positive effect on my psyche.",
        FROGLEGS_POISON = "Observations lead me to conclude this will cause me harm.",
        FROGLEGS_POISON_COOKED = "Relatively less detrimental than before.",
        FROG_POISON = {
            DEAD = "Based on observations, I can reasonably deduce it is dead.",
            GENERIC = "It's reasonable to conclude that this amphibian means me harm.",
            SLEEPING = "A dozing dendrobatidae.",
        },
        GLOWFLY = {
            DEAD = "Cadaverous.",
            GENERIC = "The luminous oculus on this pterygota is inspiring!",
            SLEEPING = "Evidently, its bioluminescence is dormant too.",
        },
        GLOWFLY_COCOON = "It appears to be undergoing some kind of transubstantiation.",
        GOLDENMACHETE = "Gold is so plentiful here I can use it in household tools.",
        GOLDPAN = "I do hope the holes were meant to be there.",
        GOLD_DUST = "Evidently, it's the preferred sustenance of those long nosed quadrupeds.",
        GRABBING_VINE = "Kleptomaniac vegetation. How wonderful!",
        GRASS_TALL = {
            BURNING = "Evidently, grass here has the same flammability qualities as at home.",
            GENERIC = "The obstinacy of this grass requires something sharper than my hands.",
            PICKED = "Previously experience suggests this will grow back.",
        },
        HALBERD = "A marvelously versatile instrument capable of causing incredible harm!",
        HANGING_VINE = "Kleptomaniac vegetation. How wonderful!",
        HIPPOPOTAMOOSE = "Its jubilant jumping creates such wickedly wonderful waves!",
        HIPPO_ANTLER = "The skull extension of a semiaquatic antlered animal.",
        ICEDTEA = "Evidence would suggest my tea got cold.",
        INFUSED_IRON = "Ferrous metal infused with a kind of ancient arcane technology.",
        IRON = "Marvelous! Iron is invaluable for manufacturing the tools I need!",
        LILYPAD = "Fascinating! It contains a small ecosystem of animals.",
        LIVING_ARTIFACT = "An ancient war machine! I must appraise its funtionality!",
        LOTUS = "Ah. A water based plant with attractive flowers. I should pick it.",
        LOTUS_FLOWER = "Theoretically, it's edible. Though I should cook it to avoid stomach problems.",
        LOTUS_FLOWER_COOKED = "A salubrious plant capable of boosting mental wellness.",
        MACHETE = "A pragmatic tool for slashing objects.",
        MANDRAKEHOUSE = "Evidence would suggest it belongs to some sort of vegetation based humanoid.",
        MANDRAKEMAN = "He appears to be influenced by this world's satellite. Intriguing!",
        METALPLATEHAT = "Incredibly durable. Though incredibly dense as well.",
        PANGOLDEN = "Evidently, it poops gold. Fascinating!",
        PEAGAWK = {
            DEAD = "Evidently, it didn't see that coming.",
            GENERIC = "Curious. Can it see out of all of those ocular quills?",
            SLEEPING = "Perhaps I can now pluck one of its ocular quills.",
        },
        PEAGAWKFEATHER = "Theoretically, there's an intact nervous system that keeps the eye moving.",
        PEAGAWK_BUSH = {
            GENERIC = "I'm experiencing the inescapable perception that I'm being watched.",
            SLEEPING = "That insight that spied on me was gone.",
        },
        PIKO = {
            DEAD = "Recently demised.",
            GENERIC = "The amazing storage space of their small cheeks defies all laws of physics!",
            SLEEPING = "Evidently, tired from a day of scurrying. And stealing.",
        },
        PIKO_ORANGE = {
            DEAD = "Recently demised.",
            GENERIC = "Smells of tea. Perhaps a consequence of its proximity to tea trees?",
            SLEEPING = "Evidently, tired from a day of scurrying. And stealing.",
        },
        PUGALISK = "What a wonderfully calamitous creature! I need to study it more!",
        PUGALISK_CORPSE = "The skeletal remains of an alluring beast. I must dig them up!",
        PUGALISK_FOUNTAIN = "Evidence would suggest it has restorative properties.",
        PUGALISK_RUINS_PILLAR = "A pillar of nominal size and shape.",
        PUGALISK_SKULL = "The cranium has retained some of the beasts' incredible hypnotic power.",
        PUGALISK_TRAP_DOOR = "Intriguing. This requires further investigation.",
        RABID_BEETLE = {
            DEAD = "An occurrance of invertebrate respiratory failure.",
            GENERIC = "Evidently, it acquires facial hair when it matures.",
            SLEEPING = "It's respiratory structures are vibrating.",
        },
        REEDS_WATER = "Good for paper, if it is anything like its earthly counterparts.",
        SAIL_SNAKESKIN = "Theoretically, it's reliable despite its patchy appearance.",
        SEDIMENTPUDDLE = "Evidence would suggest there's gold down there!",
        SHEARS = "Cutting implements constructed from raw metal.",
        SMELTER = {
            BURNT = "Smelting is a dangerous business in here.",
            COOKING_SHORT = "I can't wait to watch more about the properties of these metals.",
            DONE = "Done already? Remarkable!",
            EMPTY = "Magnificent! Perhaps I can build a factory here as well.",
        },
        SNAKEBONESOUP = "The skeletal remains should add some calcium to my diet.",
        SNAKESKIN = "The repellant properties of this skin are inspiring!",
        SNAKE_BONE = "The skeletal remains of a carnivorous reptile.",
        TEA = "A rodent based broth that tastes remarkably like tea!",
        TEATREE = "Theoretically, its smell attracts those small rodents. Intriguing...",
        TEATREE_NUT = "My stomach condition prevents me from partaking in its health benefits.",
        TEATREE_NUT_COOKED = "Of a chewy consistency. Evidently, it's good for you.",
        TEATREE_NUT_SAPLING = "Displays the same rapid growth rate of the other trees here.",
        TREE_PILLAR = "The circumference of this tree's trunk is unusually large.",
        WEEVOLE = "What a wonderfully persistent species of insect!",
        WEEVOLE_CARAPACE = "Excellent! It's the exoskeleton of a hexapod invertebrate!",
    },
}
