return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It doesn't need any work.",
        },
        SHOP = {
            CANTPAY = "Yeesh. Everything's so expensive here.",
            GENERIC = "I guess it's not for sale.",
        },
        USEDOOR = {
            GENERIC = "It's not opening!",
            LOCKED = "Aw... it's locked.",
        },
    },
    ANNOUCE_ALARMOVER = "Glad that's over.",
    ANNOUCE_BATS = "Chill out, flying dudes!",
    ANNOUCE_OTHERWORLD_DEED = "Aw. It's not for around here.",
    ANNOUCE_UNDERLEAFCANOPY = "Who turned out the lights?",
    ANNOUNCE_BOAT_DAMAGED = "My floater's been dinged!",
    ANNOUNCE_BOAT_SINKING = "This thing is letting on water.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I won't be floating much longer...",
    ANNOUNCE_DEHUMID = {
        "Ah... A nice cool breeze.",
    },
    ANNOUNCE_GAS_DAMAGE = "Kaff! Kaff! Kaff!",
    ANNOUNCE_HAYFEVER = "Allergy season.",
    ANNOUNCE_HAYFEVER_OFF = "Hey! I feel better!",
    ANNOUNCE_HOUSE_DOOR = "Need a piece of paper first.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "I found a door!",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Nope. Nothing here.",
    ANNOUNCE_MYSTERY_FOUND = "There's definitely something here.",
    ANNOUNCE_MYSTERY_NOREWARD = "Aww...there's nothing here.",
    ANNOUNCE_NOTHING_FOUND = "Nothing yet.",
    ANNOUNCE_PICKPOOP = {
        "Dude!",
        "Grody!",
        "Blah!",
        "This stinks!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That part won't break.",
        "Too tough.",
        "Come on! Everything has a weak spot!",
    },
    ANNOUNCE_ROOM_STUCK = "I don't wanna be stuck inside!",
    ANNOUNCE_SNEEZE = "ahhh... ahhhh...ahhhhhCHOOO!",
    ANNOUNCE_SUITUP = "Surf's up!",
    ANNOUNCE_TAXDAY = "Time to get paid for chilling.",
    ANNOUNCE_TOOLCORRODED = "Dude! My tool just fell apart!",
    ANNOUNCE_TOO_HUMID = {
        "Ugh. This %s is soooo muggy.",
        "This %s is really warm.",
    },
    ANNOUNCE_TURFTOOHARD = "Naw. That's too hard.",
    ANNOUNCE_WAVE_BOOST = "Surf's up!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Still gross.",
            GENERIC = "I don't feel like being eaten right now.",
            SLEEPING = "I could almost like them when they're asleep.",
        },
        ALLOY = "Hope this is worth all the trouble.",
        ALOE = "Aloe's good for everything.",
        ALOE_COOKED = "Yummy!",
        ALOE_PLANTED = "Hey little aloe plant.",
        ALOE_SEEDS = "You mean I gotta plant these myself?",
        ANCIENT_HERALD = "That dude looks scary.",
        ANCIENT_HULK = "I'm the same way when I wake up from a long nap.",
        ANCIENT_REMNANT = "It's got a weird vibe to it.",
        ANCIENT_ROBOTS_ASSEMBLY = "I don't wanna know what it does when it's all together.",
        ANCIENT_ROBOT_CLAW = "Yeesh. Don't wanna high five that.",
        ANCIENT_ROBOT_HEAD = "There's no shoulders for this head.",
        ANCIENT_ROBOT_LEG = "I think I had a pair of boots like that.",
        ANCIENT_ROBOT_RIBS = "Just stay asleep little guy.",
        ANTCHEST = "It makes all the honey for me!",
        ANTCOMBHOME = "Looks like a home for the bug-dudes.",
        ANTHILL = "I bet it took a ton of work to dig that.",
        ANTIVENOM = "This'll make the sickness go away.",
        ANTMAN = {
            DEAD = "That bugs me.",
            GENERIC = "Hey, bug-dude!",
            SLEEPING = "Like a bug-dude in a rug, dude.",
        },
        ANTMAN_WARRIOR = "Aggh! Leave me alone!",
        ANTMAN_WARRIOR_EGG = "Hope it stays in that egg.",
        ANTMASKHAT = "Sorry bug-dude.",
        ANTQUEEN_CHAMBERS = "Is there a bed in there?",
        ANTQUEEN_THRONE = "I think there's stuff stuck in there.",
        ANTSUIT = "Nice threads!",
        ANT_CAVE_LANTERN = "Sweet light!",
        APORKALYPSE_CLOCK = "I hate clocks.",
        ARMORVORTEXCLOAK = "Keeps the shadows from harshin' my mellow.",
        ARMOR_METALPLATE = "I feel like a soda can.",
        ARMOR_SNAKESKIN = "I guess snakes aren't so bad.",
        ARMOR_WEEVOLE = "Ew. It's all creepy-crawly.",
        ASPARAGUS_PLANTED = "Food!",
        BALLPEIN_HAMMER = "Aw... it's a cute little hammer.",
        BAMBOO = "This looks pretty float-atious.",
        BANDITHAT = "I look a little too shady in this.",
        BANDITMAP = "A map to where that dude put all the stuff he stole.",
        BANDITTREASURE = "I found it!",
        BASEFAN = "A nice breeze.",
        BATHAT = "Kinda grody.",
        BILL = {
            DEAD = "Aw...",
            GENERIC = "Hey little barbed dude.",
            SLEEPING = "I'll just sneak by.",
        },
        BILL_QUILL = "Yeouch. Looks sharp!",
        BLUNDERBUSS = "A bit of overkill.",
        BOATREPAIRKIT = "Surfboard maintenance is essential!",
        BOAT_CARGO = "This surfboard sure has a lot of pockets.",
        BOAT_CORK = "I've definitely seen better boats.",
        BOAT_LOGRAFT = "Seriously?",
        BOAT_ROW = "Awww, rowing? Ugh.",
        BOAT_TORCH = "Night-surfing. I love it!",
        BONESTAFF = "That's one way to win a staring contest.",
        BRAMBLESPIKE = "Yeouch. I'm staying away from those.",
        BRAMBLE_BULB = "Now what do I do with this?",
        BRAMBLE_CORE = "So beautiful it's almost worth the effort.",
        BUGREPELLENT = "For those bugs that bug me.",
        BURR = "There's a plant in you, I just know it!",
        BURR_SAPLING = {
            BURNING = "Bogus!",
            GENERIC = "Aww...cute!",
            PICKED = "Nothing growing yet.",
            WITHERED = "You look tired.",
        },
        CANDLEHAT = "Sweet. Now my hands are free.",
        CAVE_EXIT_ROC = "I bet it's a way out.",
        CHITIN = "Probably wouldn't make a good surfboard.",
        CITY_HAMMER = "It's like a big eraser.",
        CITY_LAMP = {
            GENERIC = "Thanks for keeping me safe, light!",
            ON = "Pretty sure that's a lamp.",
        },
        CLAWPALMTREE = "Kinda pretty in an ugly sorta way.",
        CLAWPALMTREE_SAPLING = "That was a lot of work for a little tree.",
        CLIPPINGS = "All my hard work.",
        COCONADE = {
            BURNING = "This will make a big splash!",
            GENERIC = "Just holding it makes me feel powerful.",
        },
        COFFEE = "Smells amazing!",
        COFFEEBEANS = "Come to mama!",
        COFFEEBEANS_COOKED = "Peppy!",
        CONSTRUCTION_PERMIT = "Cool! I can make a bedroom.",
        CORK = "Bet this'll float.",
        CORKCHEST = "Should keep my stuff all corked up safe.",
        CORK_BAT = "Pretty lightweight.",
        CURTAIN_DOOR = "Nice and cozy.",
        CUTLASS = "It's been awhile since I held one of these.",
        CUTNETTLE = "Whew! Really cleans your sinuses!",
        DECO_ANTIQUITIES_BEEFALO = "That just makes me sad.",
        DECO_ANTIQUITIES_WALLFISH = "Aw. Poor little fishy.",
        DECO_CAVE_BAT_BURROW = "Looks pretty creepy.",
        DECO_CAVE_BEAM_ROOM = "A good sturdy beam.",
        DECO_CHAIR_BENCH = "I could sleep on that!",
        DECO_CHAIR_CLASSIC = "Yes! I could sit on this!",
        DECO_CHAIR_CORNER = "Dude. I could totally sit on this.",
        DECO_CHAIR_FOOTREST = "A place to put your feet up.",
        DECO_CHAIR_HORNED = "I'm sittin' on that!",
        DECO_CHAIR_LOUNGE = "I could totally fall asleep on that.",
        DECO_CHAIR_MASSAGER = "Nope.",
        DECO_CHAIR_OTTOMAN = "I like it!",
        DECO_CHAIR_ROCKING = "My grandma had one of these.",
        DECO_CHAIR_STUFFED = "Sweet! A nice comfy chair.",
        DECO_CHAISE = "Can I sleep on it?",
        DECO_LAMP_2EMBROIDERED = "Two lights?! Whoo!",
        DECO_LAMP_2FRINGES = "Two lights?! Whoo!",
        DECO_LAMP_2UPTURNS = "Two lights?! Whoo!",
        DECO_LAMP_ADJUSTABLE = "Oooh. This one's adjustable.",
        DECO_LAMP_BELLSHADE = "Hey there, fancy lamp.",
        DECO_LAMP_CANDELABRA = "Who's gonna light those?",
        DECO_LAMP_CERAMIC = "Hey there, rosy lamp.",
        DECO_LAMP_CRYSTALS = "Hey there, fancy lamp.",
        DECO_LAMP_DOWNBRIDGE = "Looks a little down.",
        DECO_LAMP_EDISON = "Hey, it's a light.",
        DECO_LAMP_ELIZABETHAN = "Hey there, fancy lamp.",
        DECO_LAMP_FRINGE = "Hey there, little lamp.",
        DECO_LAMP_GLASS = "Hey there, fancy lamp.",
        DECO_LAMP_GOTHIC = "Hey there, fancy lamp.",
        DECO_LAMP_HOOFSPA = "Hey there, fancy lamp.",
        DECO_LAMP_ORB = "Hey there, fancy lamp.",
        DECO_LAMP_RIGHTANGLES = "Hey there, fancy lamp.",
        DECO_LAMP_SPOOL = "Kinda ho hum, but I'm not picky.",
        DECO_LAMP_STAINGLASS = "Hey there, tiffany lamp.",
        DECO_LAMP_UPTURN = "Hey there, fancy lamp.",
        DECO_MARBLE = "A fancy way to keep the roof up.",
        DECO_MARBLE_CORNERBEAM = "A fancy way to keep the roof up.",
        DECO_MILLINERY = "Keeps the roof up.",
        DECO_PLANTHOLDER_BASIC = "Hey there, plant.",
        DECO_PLANTHOLDER_BIRDCAGE = "Hey there, hanging plant.",
        DECO_PLANTHOLDER_BONSAI = "I love it!",
        DECO_PLANTHOLDER_DISHGARDEN = "Hey there, little plants.",
        DECO_PLANTHOLDER_DRACEANA = "Hey there, spiky plant.",
        DECO_PLANTHOLDER_FANCY = "It's a fancy pants plant.",
        DECO_PLANTHOLDER_FERN = "Hey there, hanging fern.",
        DECO_PLANTHOLDER_FERNSTAND = "Hey there, ferny plant.",
        DECO_PLANTHOLDER_MARBLE = "Hey there, fancy plant.",
        DECO_PLANTHOLDER_ORCHID = "Ohhh. Pretty...",
        DECO_PLANTHOLDER_PALM = "Hey there, leafy plant.",
        DECO_PLANTHOLDER_PHILODENDRON = "Hey there, little plants.",
        DECO_PLANTHOLDER_PITCHERS = "Hey there, hanging plant.",
        DECO_PLANTHOLDER_PLANTPET = "Awww... it's a pet plant.",
        DECO_PLANTHOLDER_TERRARIUM = "Aww... they got a little home.",
        DECO_PLANTHOLDER_TRAPS = "Hey there, snappy plant.",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "Holidays! My favorite time of year!",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "Looks like it could use a nap.",
        DECO_PLANTHOLDER_WIP = "Hey there, little bush.",
        DECO_PLANTHOLDER_XEROGRAPHICA = "Hey there, hanging plant.",
        DECO_PLANTHOLDER_ZZ = "Hey there, skinny plant.",
        DECO_ROUND = "Keeps the roof up.",
        DECO_RUINS_BEAM_ROOM = "A good sturdy beam.",
        DECO_RUINS_ENDSWELL = "I wish... this wasn't so creepy.",
        DECO_RUINS_FOUNTAIN = "What's the harm in wishing?",
        DECO_TABLE_BANKER = "A kinda boring table.",
        DECO_TABLE_CHESS = "I could play checkers on here.",
        DECO_TABLE_CRATE = "I got this in my place at home.",
        DECO_TABLE_DIY = "Meh. It'll do.",
        DECO_TABLE_RAW = "Meh. It'll do.",
        DECO_TABLE_ROUND = "I could eat off there.",
        DECO_WALLORNAMENT_AXE = "Meh. Not my style.",
        DECO_WALLORNAMENT_BLACK_CAT = "Aww. Cute cat...",
        DECO_WALLORNAMENT_CAPE = "Stylish.",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Pretty homey.",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Good for the feng shui.",
        DECO_WALLORNAMENT_GEARS_ART = "Really makes you think.",
        DECO_WALLORNAMENT_HUNT = "Kinda aggressive.",
        DECO_WALLORNAMENT_MOSAIC = "Must've taken some time to make.",
        DECO_WALLORNAMENT_NO_SMOKING = "Lotta rules.",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "Really makes you think, don't it.",
        DECO_WALLORNAMENT_PHOTO = "Looks like a nice enough kid.",
        DECO_WALLORNAMENT_WREATH = "Christmas already?",
        DECO_WOOD = "Keeps the roof up.",
        DECO_WOOD_CORNERBEAM = "Keeps the roof up.",
        DEED = "Huh. Never thought I'd own a house.",
        DEMOLITION_PERMIT = "Seems like a shame to wreck all that work I did.",
        DISARMING_KIT = "Those traps won't get me anymore.",
        DISGUISEHAT = "Ha! It's kinda cute!",
        DUG_NETTLE = "Planting this sounds like hard work.",
        DUNGBALL = "Should've leashed it.",
        DUNGBEETLE = {
            DEAD = "Aww... All dunged out.",
            GENERIC = "It's a grade-A dung surfer.",
            SLEEPING = "That's the right attitude.",
            UNDUNGED = "Someone's grubbing.",
        },
        DUNGPILE = {
            GENERIC = "Mushburger.",
            PICKED = "Nothing left.",
        },
        FABRIC = "Where did my sticks go? I've been bamboozled!",
        FEATHER_THUNDER = "Pretty feather.",
        FEIJOADA = "Mmm... you can still taste the dirt.",
        FLOWER_RAINFOREST = "I love these.",
        FROGLEGS_POISON = "I don't know why, but I don't think I should eat those yet.",
        FROGLEGS_POISON_COOKED = "Looks a little tastier.",
        FROG_POISON = {
            DEAD = "It croaked.",
            GENERIC = "Killer colors, froggy-dude.",
            SLEEPING = "You keep dreaming.",
        },
        GASCLOUD = "Harsh.",
        GASMASKHAT = "Out with the bad air, in with the good.",
        GLOWFLY = {
            DEAD = "I wish it hadn't died.",
            GENERIC = "I could lay down and watch them all night.",
            SLEEPING = "Lights out!",
        },
        GLOWFLY_COCOON = "I need a sleeping bag like that.",
        GNAT = "Ick! Stay away!",
        GNATMOUND = "Like an apartment building for bugs.",
        GOLDENMACHETE = "I can hack in style.",
        GOLDPAN = "You mean I gotta work for my gold?",
        GOLD_DUST = "Fairy dust!",
        GRABBING_VINE = "That seems dangerous.",
        GRASS_TALL = {
            BURNING = "It'd probably be a lot of work to put it out.",
            GENERIC = "It's too much work to pick it with my hands.",
            PICKED = "I deserve a nap after that.",
        },
        GUMMY_CAKE = "It's cake!",
        HALBERD = "You could poke an eye out on this thing!",
        HANGING_VINE = "That seems dangerous.",
        HARDSHELL_TACOS = "I prefer corn based tacos.",
        HEDGE = {
            BURNING = "Who did that?",
            BURNT = "Wiped out.",
            GENERIC = "Nice hedge!",
            SHAVEABLE = "It needs a trim, but that would take work.",
        },
        HEDGE_BLOCK_ITEM = "Why am I lugging this around?",
        HEDGE_CONE_ITEM = "This needs to go on the ground.",
        HEDGE_LAYERED_ITEM = "Where am I going to put this?",
        HIPPOPOTAMOOSE = "You look large and in charge.",
        HIPPO_ANTLER = "Woah. It's a big one!",
        HOGUSPORKUSATOR = "Look at that - pigs can fly!",
        ICEDTEA = "Ah... hits the spot.",
        INFUSED_IRON = "Whoa. It's got a weird glow.",
        INTERIOR_FLOOR_CHECK = "I could play checkers on this.",
        INTERIOR_FLOOR_GARDENSTONE = "Now I can feel the grass in my toes.",
        INTERIOR_FLOOR_GEOMETRICTILES = "Nice floor!",
        INTERIOR_FLOOR_HERRINGBONE = "Cool!",
        INTERIOR_FLOOR_HEXAGON = "Nice floor.",
        INTERIOR_FLOOR_HOOF_CURVY = "Bet those pigs would like this.",
        INTERIOR_FLOOR_MARBLE = "Ohh. Fancy floor.",
        INTERIOR_FLOOR_OCTAGON = "It's a floor. I'll take it.",
        INTERIOR_FLOOR_PLAID_TILE = "Ohh. Fancy floor.",
        INTERIOR_FLOOR_SHAG_CARPET = "Feels good on my tootsies.",
        INTERIOR_FLOOR_SHEET_METAL = "Harsh.",
        INTERIOR_FLOOR_TRANSITIONAL = "Meh, good enough.",
        INTERIOR_FLOOR_WOOD = "Nice wood flooring.",
        INTERIOR_FLOOR_WOODPANELS = "Nice floor!",
        INTERIOR_WALL_CHECKERED = "I could play checkers on this.",
        INTERIOR_WALL_CIRCLES = "I like it!",
        INTERIOR_WALL_FLORAL = "It's a wall. I'll take it.",
        INTERIOR_WALL_FULLWALL_MOULDING = "I like it!",
        INTERIOR_WALL_HARLEQUIN = "It's a wall. I'll take it.",
        INTERIOR_WALL_MARBLE = "I like it!",
        INTERIOR_WALL_MAYORSOFFICE = "Looks like something a big shot would have on their wall.",
        INTERIOR_WALL_PEAGAWK = "Pretty walls!",
        INTERIOR_WALL_PLAIN_DS = "I'm not fancy.",
        INTERIOR_WALL_PLAIN_ROG = "I'm not fancy.",
        INTERIOR_WALL_ROPE = "Ship shape.",
        INTERIOR_WALL_SUNFLOWER = "Aww. Sweet...",
        INTERIOR_WALL_UPHOLSTERED = "Ohhh... soft.",
        INTERIOR_WALL_WOOD = "It's a wall. I'll take it.",
        IRON = "This has gotta be good for something.",
        IRON_DOOR = "A door. I should go through it.",
        JELLYBUG = "You sure do have a lot of energy.",
        JELLYBUG_COOKED = "Not too appetizing but if I'm hungry enough...",
        KEY_TO_CITY = "Sweet. I can build my own personal city!",
        KINGFISHER = {
            DEAD = "Aww... That's bogus.",
            GENERIC = "Gnarly beak,dude.",
            SLEEPING = "How do you sleep like that without falling over?",
        },
        LAVAPOOL = "It's like a gooey campfire!",
        LAWNORNAMENT = {
            BURNING = "Who would do such a thing?",
            BURNT = "Aww...Just a pile of ashes now.",
            GENERIC = "Looks heavy.",
        },
        LIFEPLANT = "Whoa! It's all sparkly.",
        LILYPAD = "Looks like a waterbed to me.",
        LIVING_ARTIFACT = "That looks cool. What does it do?",
        LOTUS = "Those'd make a great surfboard pattern.",
        LOTUS_FLOWER = "Pretty!",
        LOTUS_FLOWER_COOKED = "Mmmm...Tasty.",
        MACHETE = "What a hack job.",
        MAGNIFYING_GLASS = "It's amazing what you'll find if you look close enough.",
        MANDRAKEHOUSE = "I wonder how they get any sleep.",
        MANDRAKEMAN = "Hey there, noisy dude!",
        MEAN_FLYTRAP = {
            DEAD = "Can't say I'm too sorry.",
            GENERIC = "Find something else to eat, please.",
            SLEEPING = "They're better this way.",
        },
        MEATED_NETTLE = "The meat helps cover the medicine smell.",
        METALPLATEHAT = "Keeps my noggin safe.",
        NECTAR_POD = "I wonder if I can make honey out of this.",
        NETTLE = {
            DEFAULT = "Whew! That's a strong smell.",
            EMPTY = "It'll grow back eventually.",
            MOIST = "Water really makes it happy.",
            WITHERED = "Nah. Not the right dirt for it.",
        },
        NETTLELOSANGE = "Yeesh. Smells like medicine.",
        OBSIDIAN = "Ouch, you're hot!",
        OINC = "Heads I take a nap, tails I go to bed.",
        OINC10 = "Money can't buy happiness. Only naps can.",
        OINC100 = "I can retire now!",
        ORGANIC_DOOR = "Hope it's not still alive.",
        OX_FLUTE = "I'm gonna play some sweet jams on this baby.",
        OX_HORN = "I'm glad it's not attached to anything.",
        PANGOLDEN = "Shiny.",
        PARROT_BLUE = {
            DEAD = "Ex-parrot-dude.",
            GENERIC = "Beautiful plumage, parrot-dude!",
            SLEEPING = "Shagged out.",
        },
        PEAGAWK = {
            DEAD = "Dang. It's dead.",
            GENERIC = "Beautiful eyes, dude!",
            SLEEPING = "You need to shut all your eyes to get proper shut-eye!",
        },
        PEAGAWKFEATHER = "Nature makes such pretty things.",
        PEAGAWK_BUSH = "What a cool looking bush!",
        PEDESTAL_KEY = "Wonder what it opens.",
        PHEROMONESTONE = "Now I can commune with nature!",
        PIGBANDIT = "Not cool! He's tryin' to steal my stuff!",
        PIGCROWNHAT = "This is way too much responsibility for me.",
        PIGEON = {
            DEAD = "I hope he died in his sleep.",
            GENERIC = "They're sort of cute.",
            SLEEPING = "Wish I was with you, buddy.",
        },
        PIGGHOST = "I don't want no trouble.",
        PIGHOUSE_CITY = {
            BURNING = "Aww... Where they gonna sleep now?",
            GENERIC = "One of those pigdudes' houses.",
        },
        PIGHOUSE_FARM = {
            BURNING = "That happened fast!",
            GENERIC = "Farm life ain't for me.",
        },
        PIGHOUSE_MINE = {
            BURNING = "That's some inferno.",
            GENERIC = "They work too hard in there.",
        },
        PIGMAN_BANKER = {
            GENERIC = "But can money buy you naps, banker man?",
            SLEEPING = "I guess money can buy you naps.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "You look great, dudess!",
            SLEEPING = "She looks great even while they sleep.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "Got any cool stuff?",
            SLEEPING = "I kinda like him better this way.",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "You sell magic stuff, right?",
            SLEEPING = "Wish I could join her.",
        },
        PIGMAN_FARMER = {
            GENERIC = "How are you, farmer-pig-dude?",
            SLEEPING = "Work hard. Sleep hard.",
        },
        PIGMAN_FLORIST = {
            GENERIC = "I always wanted to grow flowers.",
            SLEEPING = "Flowers always put me to sleep too.",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "Cool hats!",
            SLEEPING = "My kind of lady.",
        },
        PIGMAN_HUNTER = {
            GENERIC = "Harsh. You got a lot of weapons.",
            SLEEPING = "Awww, he looks so peaceful.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "I'm not much of an establishment gal.",
            SLEEPING = "Must be a stress nap.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "Hey, you any good at waxing a board?",
            SLEEPING = "I'm right there with you, dude.",
        },
        PIGMAN_MINER = {
            GENERIC = "You work too hard.",
            SLEEPING = "That's more like it.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "Whoa, dude. You are old.",
            SLEEPING = "I don't blame him.",
        },
        PIGMAN_QUEEN = "Afternoon, queenie.",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Oohhh. Looking tough.",
            SLEEPING = "Catch some \"Z\"s while you can!",
        },
        PIGMAN_ROYALGUARD_2 = {
            GENERIC = "Chill out, pig dude.",
            SLEEPING = "I've been there, buddy.",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "Anything good today?",
            SLEEPING = "Dream on, buddy.",
        },
        PIGMAN_USHER = {
            GENERIC = "Looks like he could use a nap.",
            SLEEPING = "Hey, when you gotta sleep, you gotta sleep.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Who'da thought stone would burn so fast?",
            GENERIC = "See anything good up there?",
        },
        PIG_PALACE = "Snazzy!",
        PIG_RUINS_ARTICHOKE = "Artichoke art!",
        PIG_RUINS_CREEPING_VINES = "Geez. These vines are everywhere.",
        PIG_RUINS_DART_STATUE = "Nope. Not trusting that.",
        PIG_RUINS_DART_TRAP = "I'm gonna stay away from those.",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "I should take a peek inside.",
            LOCKED = "It's closed for now.",
        },
        PIG_RUINS_ENTRANCE2 = "I should take a peek inside.",
        PIG_RUINS_ENTRANCE3 = "I should take a peek inside.",
        PIG_RUINS_ENTRANCE4 = "I should take a peek inside.",
        PIG_RUINS_ENTRANCE5 = "I should take a peek inside.",
        PIG_RUINS_ENTRANCE_SMALL = "I should take a peek inside.",
        PIG_RUINS_EXIT = "Found the exit!",
        PIG_RUINS_EXIT2 = "Found the way out!",
        PIG_RUINS_EXIT4 = "I should take a peek.",
        PIG_RUINS_HEAD = "A little bit creepy.",
        PIG_RUINS_IDOL = "How do I get that top part off?",
        PIG_RUINS_PLAQUE = "It'll take some work to get that top part off.",
        PIG_RUINS_PRESSURE_PLATE = "Nah. Not stepping there.",
        PIG_RUINS_SPEAR_TRAP = "Little holes in the ground. Huh.",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "Good. They can't get me anymore.",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Yeesh. Those look sharp.",
        PIG_RUINS_TORCH = "That's a good place for that.",
        PIG_RUINS_TORCH_WALL = "That's a good place for that.",
        PIG_SCEPTER = "I guess it's important to the pig dudes.",
        PIG_SHOP_ACADEMY = {
            BURNING = "Well at least it burns well.",
            GENERIC = "Boring.",
        },
        PIG_SHOP_ANTIQUITIES = {
            BURNING = "Well, someone will put it out.",
            GENERIC = "Lotta weird stuff in there.",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "That's a bummer.",
            GENERIC = "Magic always makes things easier.",
        },
        PIG_SHOP_BANK = {
            BURNING = "That's too bad.",
            GENERIC = "Where the money is.",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "Bummer.",
            GENERIC = "That's where that big shot pig works.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Dang.",
            GENERIC = "Never thought I'd have a job.",
        },
        PIG_SHOP_DELI = {
            BURNING = "Harsh.",
            GENERIC = "Grub!",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "Bummer.",
            GENERIC = "I love that place.",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "Dude! That had all the good stuff.",
            GENERIC = "I could always pick up a thing or two.",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "Harsh.",
            GENERIC = "I could use a good hat for the beach.",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "Aww... That place was real chill.",
            GENERIC = "They got stuff for my bumps and bruises.",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "Where am I gonna get my grub now?",
            GENERIC = "Always ready to veg out.",
        },
        PIG_SHOP_TINKER = {
            BURNING = "Oops. Gettin' kinda toasty.",
            GENERIC = "I wonder if there's a blueprint for a bed in there.",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "Heinous.",
            GENERIC = "Whoa. Some heavy gear in there.",
        },
        PIKO = {
            DEAD = "No! Little buddy!",
            GENERIC = "It's a little buddy!",
            SLEEPING = "I wish I could join you, buddy.",
        },
        PIKO_ORANGE = {
            DEAD = "No! Little buddy!",
            GENERIC = "Oh, I get it.",
            SLEEPING = "I wish I could join you, buddy.",
        },
        PILLAR_DOOR = "That bat's not gonna attack, is he?",
        PITHHAT = "A hard hat!",
        PLATE_DOOR = "Little harsh.",
        PLAYERHOUSE_CITY = {
            BURNT = "That sucks.",
            FORSALE = "I wish I could afford a home.",
            SOLD = "A place to sleep at night! And during the day.",
        },
        PLAYER_HOUSE_BRICK = "Kinda heavy lugging this around.",
        PLAYER_HOUSE_BRICK_CRAFT = "All I need is a roof and a place to sleep and I'm happy.",
        PLAYER_HOUSE_COTTAGE = "You mean I gotta build it myself?",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Hey if I can sleep in it, I'm good.",
        PLAYER_HOUSE_GOTHIC = "Well, at least I'll have a cool place when I'm done.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "You mean I gotta build this myself?",
        PLAYER_HOUSE_MANOR = "Yeesh. Is it worth all the hard work?",
        PLAYER_HOUSE_MANOR_CRAFT = "I wish this was already built.",
        PLAYER_HOUSE_TUDOR = "Can we pretend I already built this already?",
        PLAYER_HOUSE_TUDOR_CRAFT = "As long as the bed's not made of stone.",
        PLAYER_HOUSE_TURRET = "This better be worth it.",
        PLAYER_HOUSE_TURRET_CRAFT = "How big are the bedrooms?",
        PLAYER_HOUSE_VILLA = "I thought someone else was gonna build this for me.",
        PLAYER_HOUSE_VILLA_CRAFT = "I can sleep in luxury. But I gotta build it first.",
        POG = {
            APORKALYPSE = "I'm gonna go over here until you calm down, okay?",
            FOLLOWER = "Aw, I like you too!",
            GENERIC = "Hey little dude, wanna hang?",
            SLEEPING = "Sleep tight little dude.",
        },
        POISONBALM = "Getting poisoned is such a bummer.",
        PORKLAND_INTRO_BALLOON = "Thanks for the ride, balloon!",
        PORKLAND_INTRO_BASKET = "Well, that's useless now.",
        PORKLAND_INTRO_FLAGS = "Was there a party or something?",
        PORKLAND_INTRO_SANDBAG = "Naw. Too heavy.",
        PORKLAND_INTRO_SUITCASE = "Aw. Can't use it.",
        PORKLAND_INTRO_TRUNK = "It's destroyed now.",
        PROP_DOOR = "Wonder where that leads?",
        PUGALISK = "Calm down, dude!",
        PUGALISK_CORPSE = "Yeesh. Nasty.",
        PUGALISK_FOUNTAIN = "I could be this young forever!",
        PUGALISK_RUINS_PILLAR = "Don't fall down on me!",
        PUGALISK_SKULL = "He deserved it.",
        PUGALISK_TRAP_DOOR = "Nah. I'll leave it.",
        RABID_BEETLE = {
            DEAD = "That's a bummer.",
            GENERIC = "Dude, you need to chill!",
            SLEEPING = "That's it. Now just stay asleep.",
        },
        RADISH = "Radish-ical!",
        RADISH_COOKED = "Mmmm...",
        RADISH_PLANTED = "A radish. Rad!",
        RADISH_SEEDS = "Should I plant these or eat 'em like this?",
        RAINFORESTTREE = {
            BURNING = "That's a drag.",
            BURNT = "Hope it didn't suffer.",
            CHOPPED = "Sorry, tree.",
            GENERIC = "You're a beauty!",
        },
        RAINFORESTTREE_ROT = "Yeesh. How'd it get like that?",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "Totally blown out.",
            SCAFFOLD = "Someone's hard at work. Glad it's not me.",
        },
        REEDS_WATER = "It'd be a lot of effort to go get them.",
        RELIC_1 = {
            GENERIC = "I should return this to the pig-dudes.",
            SUNKEN = "Someone dropped their ancient action figure.",
        },
        RELIC_2 = {
            GENERIC = "Cool! What is it?",
            SUNKEN = "Someone should fish that out.",
        },
        RELIC_3 = {
            GENERIC = "Someone would probably want this.",
            SUNKEN = "Huh. Who would drop that in the water?",
        },
        RELIC_4 = {
            GENERIC = "Woah. Looks fancy.",
            SUNKEN = "There's something shiny down there.",
        },
        RELIC_5 = {
            GENERIC = "Not your regular old relic.",
            SUNKEN = "Is it worth fishing that out?",
        },
        ROCK_ANTCAVE = "That rocks.",
        ROCK_BASALT = "A rock. That robot made it.",
        ROCK_FLIPPABLE = "What's under there?",
        ROC_HEAD = "How's the weather up there?",
        ROC_LEG = "Nice gams!",
        ROC_NEST_BRANCH1 = "Just a branch.",
        ROC_NEST_BRANCH2 = "Just a branch.",
        ROC_NEST_BUSH = "Must've taken a lot of work to make this.",
        ROC_NEST_DEBRIS1 = "Hey stick!",
        ROC_NEST_DEBRIS2 = "How's it going, stick?",
        ROC_NEST_DEBRIS3 = "What's up, stick?",
        ROC_NEST_DEBRIS4 = "Stay cool, stick!",
        ROC_NEST_EGG1 = "I didn't break it.",
        ROC_NEST_EGG2 = "Where's the bird?",
        ROC_NEST_EGG3 = "I'm not cleaning that up.",
        ROC_NEST_EGG4 = "Looks kinda old.",
        ROC_NEST_HOUSE = "Maybe I could move in.",
        ROC_NEST_RUSTY_LAMP = "Huh. Doesn't even work.",
        ROC_NEST_TREE1 = "How'd that get here?",
        ROC_NEST_TREE2 = "A nice tree-climbing tree.",
        ROC_NEST_TRUNK = "Harsh.",
        ROC_ROBIN_EGG = "What's inside?!",
        ROC_TAIL = "Reminds me of a wave I carved one time.",
        ROOTTRUNK = "Now I don't gotta go far to get all my stuff.",
        ROUND_DOOR = "Is that pig gonna eat me?",
        ROYAL_GALLERY = "Ooh. Looks expensive.",
        RO_BIN = "Hey, wanna carry all my stuff?",
        RO_BIN_GIZZARD_STONE = "Still a little goopy.",
        RUG_BEARD = "Ew.",
        RUG_BRAID = "I've made these before.",
        RUG_CATCOON = "Aww...sorry little guy.",
        RUG_CRIME = "Yeesh.",
        RUG_FUR = "Aww. Something died for this rug.",
        RUG_HEDGEHOG = "No animals were harmed in the making of this rug.",
        RUG_HOOFPRINT = "This one's got fancy pig feet on it.",
        RUG_METAL = "Meh. It could be softer.",
        RUG_NAILBED = "Harsh.",
        RUG_OCTAGON = "Soft on my feets.",
        RUG_OVAL = "A rosy little rug.",
        RUG_PORCUPUSS = "Aww... sorry little guy.",
        RUG_RECTANGLE = "A big rosy rug.",
        RUG_ROUND = "Kinda gives me the willies!",
        RUG_RUBBERMAT = "Rubbery.",
        RUG_SQUARE = "Soft on my feets.",
        RUG_SWIRL = "Meh. It could be softer.",
        RUG_TILES = "How geometric.",
        RUG_WEB = "Kinda sticky.",
        RUG_WORMHOLE = "Does it work?",
        SAIL_SNAKESKIN = "Why bother when I have my board?",
        SAND = "I like it between my toes and nowhere else.",
        SCORPION = {
            DEAD = "Ugh. Gnarly.",
            GENERIC = "Too close, scary dude!",
            SLEEPING = "It kinda looks almost peaceful like that.",
        },
        SECURITYCONTRACT = "Sweet. I can hire my own guard with this.",
        SEDIMENTPUDDLE = "There's sparkly things down there!",
        SHEARS = "What am I supposed to do with these?",
        SHELF_ADJUSTABLE = "Fancy place to put stuff.",
        SHELF_AFRAME = "Fancy place to put stuff.",
        SHELF_BASIC = "A place to put my stuff.",
        SHELF_CINDERBLOCKS = "I have this in my place at home.",
        SHELF_CRATES = "I have this in my place at home.",
        SHELF_FLOATING = "A place to put my stuff.",
        SHELF_FRIDGE = "Reduce, reuse, recycle.",
        SHELF_GLASS = "Seems breakable.",
        SHELF_HATTREE = "A place to put stuff.",
        SHELF_HOOKS = "Fancy place to put stuff.",
        SHELF_HUTCH = "Fancy place to put stuff.",
        SHELF_INDUSTRIAL = "I guess it works alright.",
        SHELF_LADDER = "I can put my stuff on there.",
        SHELF_MARBLE = "Fancy place to put stuff.",
        SHELF_METAL = "That oughta keep my stuff off the ground.",
        SHELF_MIDCENTURY = "A fancy place to put stuff.",
        SHELF_PALLET = "I have this in my place at home.",
        SHELF_PIPE = "A place to put stuff.",
        SHELF_WALLMOUNT = "Fancy place to put stuff.",
        SHELF_WOOD = "I can put my stuff on there.",
        SLUGBUG = "Take it easy.",
        SLUGBUG_COOKED = "Doesn't look very tasty.",
        SMASHINGPOT = "Looks breakable.",
        SMELTER = {
            BURNT = "This is what you get for trying too hard.",
            COOKING_SHORT = "It burns itself red.",
            DONE = "Well done, bro.",
            EMPTY = "I'll just let that do all the work for me.",
        },
        SNAKEBONESOUP = "Nice warm soup.",
        SNAKEOIL = "I wasn't born yesterday.",
        SNAKESKIN = "I could make a scaly bikini out of this!",
        SNAKESKINHAT = "Raindrops keep falling on my hat.",
        SNAKE_AMPHIBIOUS = "Leave me alone!",
        SNAKE_BONE = "Sorry, little snake dude.",
        SPIDER_MONKEY = {
            DEAD = "Dude! It's dead!",
            GENERIC = "Yeesh!",
            SLEEPING = "Shh. Don't wake the scary monkey.",
        },
        SPIDER_MONKEY_NEST = "As long as they stay over there, I'm good.",
        SPIDER_MONKEY_TREE = "Hang ten, little spider monkey things.",
        SPRINKLER = "Does all my watering for me.",
        STEAMEDHAMSANDWICH = "It's fast food.",
        STONE_DOOR = "A door. I should go through it.",
        SWINGING_LIGHT1 = "It's a light. I'll take it.",
        SWINGING_LIGHT_BASIC_BULB = "Meh. I'm not picky.",
        SWINGING_LIGHT_BASIC_METAL = "I'm not picky.",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "Who's gonna light all those?",
        SWINGING_LIGHT_DERBY = "Nice hat, light!",
        SWINGING_LIGHT_FLORAL_BLOOMER = "A pretty light for the ceiling.",
        SWINGING_LIGHT_FLORAL_BULB = "Ohh. Fancy.",
        SWINGING_LIGHT_FLORAL_SCALLOP = "A pretty little light.",
        SWINGING_LIGHT_PENDANT_CHERRIES = "A light with a cherry on top.",
        SWINGING_LIGHT_ROPE_1 = "It's a light. I'll take it.",
        SWINGING_LIGHT_ROPE_2 = "It's a light. I'll take it.",
        SWINGING_LIGHT_TOPHAT = "Nice hat, light!",
        TEA = "Caffeine!",
        TEATREE = "Hey little tree!",
        TEATREE_NUT = "I heard it's good for allergies.",
        TEATREE_NUT_COOKED = "A good meal for little effort.",
        TEATREE_NUT_SAPLING = "One day you'll be big and strong.",
        THUNDERBIRD = "Yeesh. Take it easy owl-dude.",
        THUNDERBIRDNEST = "It's that owl-dude's home.",
        THUNDERHAT = "Love the hat.",
        TOPIARY = "Rad.",
        TOUCAN = "You could catch waves with a nose like that!",
        TRAWLNET = "Lootin' and cruisin'.",
        TRAWLNETDROPPED = {
            GENERIC = "A sack of sea goodies!",
            SOON = "Just a little more trawlin'...",
            SOONISH = "I wonder what it grabbed up...",
        },
        TREE_PILLAR = "What a great tree!",
        TRINKET_GIFTSHOP_1 = "I should give this to someone.",
        TRINKET_GIFTSHOP_3 = "Could I send this back home?",
        TRINKET_GIFTSHOP_4 = "Ha!",
        TUBERTREE = "Totally tubular.",
        TUBER_BLOOM_CROP = "'Tis the season for tubers.",
        TUBER_BLOOM_CROP_COOKED = "Oh. I was hoping for some fries.",
        TUBER_CROP = "Doesn't look like it's ripe.",
        TUBER_CROP_COOKED = "Can I eat it now?",
        TUNACAN = "Whoa! Righteous non-spoilage!",
        TURF_COBBLEROAD = "Rocky road. Mmmm...",
        TURF_DEEPRAINFOREST = "Green dirt.",
        TURF_DEEPRAINFOREST_NOCANOPY = "Ground for planting jungle stuff.",
        TURF_FIELDS = "Turfy dirt.",
        TURF_FOUNDATION = "Solid dirt.",
        TURF_GASJUNGLE = "Purply dirt.",
        TURF_LAWN = "Grassy dirt.",
        TURF_MOSS = "Mushy dirt.",
        TURF_PAINTED = "It's like a pretty beach.",
        TURF_PIGRUINS = "Solid.",
        TURF_PLAINS = "I like the swirls.",
        TURF_RAINFOREST = "Green dirt.",
        VAMPIREBAT = {
            DEAD = "Dang!",
            GENERIC = "Don't get aggro on me now.",
            SLEEPING = "It'd be great if you could just stay asleep.",
        },
        VAMPIREBATCAVE = "I don't get good vibes from that place.",
        VENOMGLAND = "What a terrible gland.",
        VENUS_STALK = "Gnarly.",
        VINE = "Good for lashing stuff down.",
        WALKINGSTICK = "It's my lazy stick.",
        WALLCRACK_RUINS = "I think there's something through there.",
        WALL_PIG_RUINS = "A old wall.",
        WATERDROP = "Huh. Kinda looks like a little seed.",
        WEEVOLE = "Annoying little guys.",
        WEEVOLE_CARAPACE = "Ew. Bug skin.",
        WINDOW_GREENHOUSE = "All the beauty of the outside. All the convenience of the inside.",
        WINDOW_LARGE_SQUARE = "Little square for my taste.",
        WINDOW_LARGE_SQUARE_CURTAIN = "Lets in the light.",
        WINDOW_ROUND = "I'm not picky.",
        WINDOW_ROUND_BURLAP = "Meh. It'll do.",
        WINDOW_ROUND_CURTAINS_NAILS = "Lets in the light.",
        WINDOW_SMALL_PEAKED = "I can see through there.",
        WINDOW_SMALL_PEAKED_CURTAIN = "Lets in the light.",
        WINDOW_TALL = "Lets in the light.",
        WINDOW_TALL_CURTAIN = "Lets in the light.",
        WOOD_DOOR = "A door. I should go through it.",
    },
}
