return {
    ANNOUNCE_DEHUMID = {
        "Ah... A nice cool breeze.",
    },
    ANNOUNCE_HAYFEVER = "Allergy season.",
    ANNOUNCE_HAYFEVER_OFF = "Hey! I feel better!",
    ANNOUNCE_PICKPOOP = {
        "Dude!",
        "Grody!",
        "Blah!",
        "This stinks!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That part won't break.",
        "Too tough.",
        "Come on! Everything has a weak spot!"
    },
    ANNOUNCE_SNEEZE = "ahhh... ahhhh...ahhhhhCHOOO!",
    ANNOUNCE_TOO_HUMID = {
        "Ugh. This %s is soooo muggy.",
        "This %s is really warm.",
    },
    DESCRIBE = {
        ALLOY = "Hope this is worth all the trouble.",
        APORKALYPSE_CLOCK = "I hate clocks.",
        ARMOR_METALPLATE = "I feel like a soda can.",
        ARMOR_WEEVOLE = "Ew. It's all creepy-crawly.",
        ASPARAGUS_PLANTED = "Food!",
        BASEFAN = "A nice breeze.",
        BONESTAFF = "That's one way to win a staring contest.",
        CHITIN = "Probably wouldn't make a good surfboard.",
        COFFEE = "Smells amazing!",
        COFFEEBEANS = "Come to mama!",
        COFFEEBEANS_COOKED = "Peppy!",
        CUTNETTLE = "Whew! Really cleans your sinuses!",
        DUNGBALL = "Should've leashed it.",
        DUNGBEETLE = {
            DEAD = "Aww... All dunged out.",
            GENERIC = "It's a grade-A dung surfer.",
            SLEEPING = "That's the right attitude.",
            UNDUNGED = "Someone's grubbing.",
        },
        DUNGPILE = {
            GENERIC = "Mushburger.",
            PICKED = "Nothing left.",
        },
        FLOWER_RAINFOREST = "I love these.",
        GLOWFLY = {
            DEAD = "I wish it hadn't died.",
            GENERIC = "I could lay down and watch them all night.",
            SLEEPING = "Lights out!",
        },
        GLOWFLY_COCOON = "I need a sleeping bag like that.",
        GOLDENMACHETE = "I can hack in style.",
        GOLDPAN = "You mean I gotta work for my gold?",
        GOLD_DUST = "Fairy dust!",
        GRABBING_VINE = "That seems dangerous.",
        GRASS_TALL = {
            BURNING = "It'd probably be a lot of work to put it out.",
            GENERIC = "It's too much work to pick it with my hands.",
            PICKED = "I deserve a nap after that.",
        },
        HALBERD = "You could poke an eye out on this thing!",
        HANGING_VINE = "That seems dangerous.",
        ICEDTEA = "Ah... hits the spot.",
        IRON = "This has gotta be good for something.",
        MACHETE = "What a hack job.",
        PANGOLDEN = "Shiny.",
        PEAGAWK = {
            DEAD = "Dang. It's dead.",
            GENERIC = "Beautiful eyes, dude!",
            SLEEPING = "You need to shut all your eyes to get proper shut-eye!",
        },
        PEAGAWKFEATHER = "Nature makes such pretty things.",
        PEAGAWK_BUSH = "What a cool looking bush!",
        PIKO = {
            DEAD = "No! Little buddy!",
            GENERIC = "It's a little buddy!",
            SLEEPING = "I wish I could join you, buddy.",
        },
        PIKO_ORANGE = {
            DEAD = "No! Little buddy!",
            GENERIC = "Oh, I get it.",
            SLEEPING = "I wish I could join you, buddy.",
        },
        PUGALISK = "Calm down, dude!",
        PUGALISK_CORPSE = "Yeesh. Nasty.",
        PUGALISK_FOUNTAIN = "I could be this young forever!",
        PUGALISK_RUINS_PILLAR = "Don't fall down on me!",
        PUGALISK_SKULL = "He deserved it.",
        PUGALISK_TRAP_DOOR = "Nah. I'll leave it.",
        RABID_BEETLE = {
            DEAD = "That's a bummer.",
            GENERIC = "Dude, you need to chill!",
            SLEEPING = "That's it. Now just stay asleep.",
        },
        SEDIMENTPUDDLE = "There's sparkly things down there!",
        SHEARS = "What am I supposed to do with these?",
        SMELTER = {
            BURNT = "This is what you get for trying too hard.",
            COOKING_SHORT = "It burns itself red.",
            DONE = "Well done, bro.",
            EMPTY = "I'll just let that do all the work for me.",
        },
        SNAKE_BONE = "Sorry, little snake dude.",
        SNAKEBONESOUP = "Nice warm soup.",
        TEA = "Caffeine!",
        TEATREE = "Hey little tree!",
        TEATREE_NUT = "I heard it's good for allergies.",
        TEATREE_NUT_COOKED = "A good meal for little effort.",
        TEATREE_NUT_SAPLING = "One day you'll be big and strong.",
        TREE_PILLAR = "What a great tree!",
        WEEVOLE = "Annoying little guys.",
        WEEVOLE_CARAPACE = "Ew. Bug skin.",
    },
}
