return {
    ACTIONFAIL = {
        USEDOOR = {
            GENERIC = "How do I get in?",
            LOCKED = "They wouldn't let me in.",
        },
    },
    ANNOUCE_ALARMOVER = "What other monsters are waiting for us?",
    ANNOUCE_BATS = "This doesn't seem to be a good sign.",
    ANNOUCE_OTHERWORLD_DEED = "It's not around, but we'll find it!",
    ANNOUCE_UNDERLEAFCANOPY = "Such a lush forest, no light can get in.",
    ANNOUNCE_BOAT_DAMAGED = "I wonder if there's a badge for boat maintenance.",
    ANNOUNCE_BOAT_SINKING = "We may need to repair this soon, haha...",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I-I don't think I can swim my way back!",
    ANNOUNCE_DEHUMID = {
        "Still more comfortable this way.",
    },
    ANNOUNCE_GAS_DAMAGE = "cough! The air here is wrong!",
    ANNOUNCE_HAYFEVER = "There's something in the air...my nose is itching.",
    ANNOUNCE_HAYFEVER_OFF = "My nose is so much better and it's finally gone!",
    ANNOUNCE_HOUSE_DOOR = "We have to get approval from the government.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "A chamber! There's a chamber of secrets!",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "This is really a wall.",
    ANNOUNCE_MYSTERY_FOUND = "Look what I found!",
    ANNOUNCE_MYSTERY_NOREWARD = "I didn't find anything.",
    ANNOUNCE_NOTHING_FOUND = "Ms.Wheeler! It doesn't work!",
    ANNOUNCE_PICKPOOP = {
        "Pine Pioneers must be hardworking...but...",
        "This is really unhygienic!",
        "do not come! Woby!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "As hard as metal!",
        "It has invulnerable scales!",
        "Is it like this all over its body?",
    },
    ANNOUNCE_ROOM_STUCK = "We'll be trapped in this room!",
    ANNOUNCE_SNEEZE = "Ah Choo!",
    ANNOUNCE_SUITUP = "I am the metal man!",
    ANNOUNCE_TAXDAY = "The day has come for administrative fees.",
    ANNOUNCE_TOOLCORRODED = "The quality of these tools is really not that great.",
    ANNOUNCE_TOO_HUMID = {
        "I'm bored.",
        "%s is not breathable at all.",
    },
    ANNOUNCE_TURFTOOHARD = "This land is not suitable for camping.",
    ANNOUNCE_WAVE_BOOST = "Woohoo!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Will it grow back?",
            GENERIC = "A real piranha! And he can run!",
            SLEEPING = "Piranha actually needs sleep too.",
        },
        ALLOY = "It's steel! Look at the steel I made!",
        ALOE = "Aloe vera is also used for food.",
        ALOE_COOKED = "It should be more delicious this way.",
        ALOE_PLANTED = "I know this! It's aloe vera! There are many good uses.",
        ALOE_SEEDS = "Woby, do you see a good spot to plant these?",
        ANCIENT_HERALD = "Are you a bringer of destruction?",
        ANCIENT_HULK = "War automation! It's real!",
        ANCIENT_REMNANT = "All that's left of that poor shadow monster.",
        ANCIENT_ROBOTS_ASSEMBLY = "They're assembling themselves! What will it become in the end?",
        ANCIENT_ROBOT_CLAW = "Can it be installed on WX?",
        ANCIENT_ROBOT_HEAD = "A giant robot head!",
        ANCIENT_ROBOT_LEG = "A leg. I wonder are they come from the same giant?",
        ANCIENT_ROBOT_RIBS = "A machine ant?",
        ANTCHEST = "These ants also know how to make honey!",
        ANTQUEEN_THRONE = "Woby! Get off that!",
        APORKALYPSE_CLOCK = "Oh no! It's a doomsday prophecy!",
        ARMORVORTEXCLOAK = "Ha ha! We look horrible!",
        ARMOR_METALPLATE = "Nothing can hurt me with this on!",
        ARMOR_SNAKESKIN = "Wearing hunted animal skins, that's some real survivor stuff!",
        ARMOR_WEEVOLE = "Are we really going to wear it?",
        ASPARAGUS_PLANTED = "Miss Winona might like it, pick some.",
        BALLPEIN_HAMMER = "I can now take those cute little figurines home.",
        BASEFAN = "Ah, it's so comfortable, Woby, you can also enjoy it.",
        BILL = {
            DEAD = "Too bad. I was hoping to make a new friend.",
            GENERIC = "Guys! Look at this strange creature!",
            SLEEPING = "Sleeping...",
        },
        BILL_QUILL = "This thorn is really long.",
        BLUNDERBUSS = "It's exploding in there. Cool!",
        BOATREPAIRKIT = "I'll need to maintain Woby's boat as well.",
        BOAT_CARGO = "You can fit almost all your camping goods in there!",
        BOAT_CORK = "Rainforest rafting, oh yeah!",
        BOAT_LOGRAFT = "Just like the ones we used to make to cross rivers!",
        BOAT_ROW = "We're getting better at carving boats.",
        BOAT_TORCH = "It's important to have good visibility while sailing.",
        BONESTAFF = "I can't help but want to look into its eyes...",
        BRAMBLESPIKE = "It's all right. I'll be careful, Mr. Wilson.",
        BRAMBLE_BULB = "I am the great southern plantkiller.",
        BRAMBLE_CORE = "The overgrown monstrosity of the jungle's depths.",
        BURR = "Which seed germinates fastest?",
        BURR_SAPLING = {
            BURNING = "Forest fire!",
            GENERIC = "One day it will grow into a towering tree.",
            PICKED = "Who did this?",
            WITHERED = "I didn't know it would still be like this.",
        },
        CHITIN = "Check out the pattern on this! Woby!",
        CITY_LAMP = {
            GENERIC = "全靠它让街道保持明亮。",
            ON = "是路灯。",
        },
        CLAWPALMTREE = "Imagine if it were a real paw!",
        CLAWPALMTREE_SAPLING = "There will be more claws here soon!",
        COFFEE = "Mom would kill me if she caught me drinking this.",
        COFFEEBEANS = "I wish these were cocoa beans.",
        COFFEEBEANS_COOKED = "Smells great!",
        CORK = "Also a firewood!",
        CORKCHEST = "My mother also does this when she doesn't want me to touch something.",
        CUTNETTLE = "Ow! It got me.",
        DECO_CHAIR_BENCH = "Don't bite it, Woby!",
        DECO_CHAIR_CLASSIC = "Don't bite it, Woby!",
        DECO_CHAIR_CORNER = "Don't bite it, Woby!",
        DECO_CHAIR_FOOTREST = "Don't bite it, Woby!",
        DECO_CHAIR_HORNED = "Don't bite it, Woby!",
        DECO_CHAIR_LOUNGE = "Don't bite it, Woby!",
        DECO_CHAIR_MASSAGER = "Don't bite it, Woby!",
        DECO_CHAIR_OTTOMAN = "Don't bite it, Woby!",
        DECO_CHAIR_ROCKING = "Don't bite it, Woby!",
        DECO_CHAIR_STUFFED = "Don't bite it, Woby!",
        DECO_WALLORNAMENT_AXE = "It looks like Lucy!",
        DISARMING_KIT = "Adventure activities, cool!",
        DUG_NETTLE = "Warby! Let’s find a good place to plant it back!",
        DUNGBALL = "How did she... nevermind.",
        DUNGBEETLE = {
            DEAD = "Hello?",
            GENERIC = "I need a very huge bottle to hold her!",
            SLEEPING = "She is sleeping.",
            UNDUNGED = "She's not with that dung ball. Good timing.",
        },
        DUNGPILE = {
            GENERIC = "What giant creature left this?",
            PICKED = "Eww!",
        },
        FEATHER_THUNDER = "Does it retain that energy?",
        FLOWER_RAINFOREST = "oh! That's the kind of flower in jungle adventure stories.",
        FROGLEGS_POISON = "I think it's highly toxic.",
        FROGLEGS_POISON_COOKED = "Is this safe?",
        FROG_POISON = {
            DEAD = "Don't touch it. Woby.",
            GENERIC = "The more beautiful the creatures, the more poisonous they are.",
            SLEEPING = "Don't touch it. Woby.",
        },
        GASMASKHAT = "This is so cool.",
        GLOWFLY = {
            DEAD = "Oh, dead.",
            GENERIC = "Whoa, look at the light they emit!",
            SLEEPING = "it is sleeping.",
        },
        GLOWFLY_COCOON = "A cocoon, what could be inside?",
        GNAT = "Cool! But... maybe we should back off a little bit?",
        GNATMOUND = "What might live inside?",
        GOLDENMACHETE = "Hack in style!",
        GOLDPAN = "Are you ready? Woby.",
        GOLD_DUST = "Smallest gold are still gold.",
        GRABBING_VINE = "What kind of monster up there?",
        GRASS_TALL = {
            BURNING = "Hey! Brush fires will destroy rainforests!",
            GENERIC = "A lush patch of grass. Must be a lot of bugs in it.",
            PICKED = "Collect again after a while.",
        },
        HALBERD = "A huge ax!",
        HANGING_VINE = "What kind of monster up there?",
        HIPPOPOTAMOOSE = "So it will be a... a hippo... hippopotalope!",
        HIPPO_ANTLER = "That'll make a decent bugle.",
        ICEDTEA = "It just got better.",
        INFUSED_IRON = "These lines shone with a strange light.",
        IRON = "Is that iron?",
        KINGFISHER = {
            DEAD = "Oh, what a shame.",
            GENERIC = "That incisive beak is definitely unfamiliar.",
            SLEEPING = "Shhh, be quiet.",
        },
        LAWNORNAMENT = {
            BURNING = "No fires on the lawn!",
            BURNT = "Now we are in big trouble.",
            GENERIC = "Bring more variety to the city.",
        },
        LIFEPLANT = "it's beautiful!",
        LILYPAD = "Look how big it is! I really want to stand up and take a look!",
        LIVING_ARTIFACT = "Indestructible mechanical armor!",
        LOTUS = "Sis Walani says that's edible...",
        LOTUS_FLOWER = "A flower floating in the water.",
        LOTUS_FLOWER_COOKED = "Woby! Look these holes!",
        MACHETE = "I like the cut of this blade.",
        MAGNIFYING_GLASS = "This way I can get a better look at those little guys.",
        MANDRAKEHOUSE = "Is this where the magic happens?",
        MANDRAKEMAN = "Warby! That big carrot over there has a face!",
        MEAN_FLYTRAP = {
            DEAD = "Will it grow back?",
            GENERIC = "I really want to transplant them into our lawn.",
            SLEEPING = "Piranha actually needs sleep too.",
        },
        MEATED_NETTLE = "This is only a little better.",
        METALPLATEHAT = "It looks so funny.",
        NECTAR_POD = "I know! Bees use them to make honey.",
        NETTLE = {
            DEFAULT = "This must be some kind of herb!",
            EMPTY = "Completed. No idea how long it will take for it to grow back.",
            MOIST = "It seems very happy.",
            WITHERED = "No, this is not a good place.",
        },
        NETTLELOSANGE = "Ugh, bitter and spicy.",
        OBSIDIAN = "I'd better be careful not to cut myself with this.",
        OINC = "My pocket money.",
        OINC10 = "My little money.",
        OINC100 = "A huge sum of money from me.",
        PANGOLDEN = "A born gold rusher.",
        PARROT_BLUE = {
            DEAD = "Oh, what a shame.",
            GENERIC = "The blue parrot from the story!",
            SLEEPING = "Shhh, be quiet.",
        },
        PEAGAWK = {
            GENERIC = "Wow, how many eyes are there?",
            SLEEPING = "Woby, we might be able to gather his feathers while he's asleep.",
        },
        PEAGAWKFEATHER = "method is valid.",
        PEAGAWK_BUSH = "This bird can't fly, but turns into a bush!",
        PIGEON = {
            DEAD = "Oh, what a shame.",
            GENERIC = "Mr. Maxwell advised us not to feed them.",
            SLEEPING = "Shhh, be quiet.",
        },
        PIGGHOST = "Woby! Can you see that?",
        PIGHOUSE_CITY = {
            BURNING = "Is anyone in there? Help them!",
            GENERIC = "Community service is a must for a Pinetree Pioneer.",
        },
        PIGHOUSE_FARM = {
            BURNING = "Poor farmers.",
            GENERIC = "I have a feeling Wurt's not gonna like there",
        },
        PIGHOUSE_MINE = {
            BURNING = "Firemen! Firemen!",
            GENERIC = "I have a feeling Wurt's not gonna like there",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "A collector! Would you mind showing Woby and me your oddities?",
            SLEEPING = "Sir, don't sleep on the floor!",
        },
        PIGMAN_HUNTER = {
            GENERIC = "Good day, Mr. Hunter.",
            SLEEPING = "He must be exhausted.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Are you Mr. Mayor?",
            SLEEPING = "Mr. Mayor fell asleep on the ground.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "His glasses told me he was very knowledgeable.",
            SLEEPING = "professor? How are you?",
        },
        PIGMAN_QUEEN = "She was dressed so gorgeously, but she smelled...",
        PIGMAN_ROYALGUARD = {
            GENERIC = "It is responsible for protecting the town.",
            SLEEPING = "Hey! Don't be lazy!",
        },
        PIG_GUARD_TOWER = {
            BURNING = "烧着了！快来帮忙！",
            GENERIC = "这一定是骑士居住的地方。",
        },
        PIG_PALACE = "This must be their palace!",
        PIG_RUINS_ARTICHOKE = "Is this a bamboo shoot or something?",
        PIG_RUINS_HEAD = "Warby! It's bigger than you!",
        PIG_RUINS_IDOL = "Look what we found, Warby!",
        PIG_RUINS_MUSHROOM = "Wow, a carved stone...mushroom?",
        PIG_RUINS_PLAQUE = "It's a totem!",
        PIG_RUINS_SOW = "Very royal.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Fire! Firefighters are coming this way!",
            GENERIC = "This must be their government department!",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Pay attention to fire safety! What did I say!",
            GENERIC = "This is where we will work from now on! Warby!",
        },
        PIG_SHOP_DELI = {
            BURNING = "What a shame, I really like their ham.",
            GENERIC = "The deli! We should buy some for Wolfgang.",
        },
        PIKO = {
            DEAD = "Poor little guy.",
            GENERIC = "I want to know what they usually do?",
            SLEEPING = "It fell asleep.",
        },
        PIKO_ORANGE = {
            DEAD = "Poor little guy.",
            GENERIC = "I must catch it!",
            SLEEPING = "It fell asleep.",
        },
        POG = {
            APORKALYPSE = "I thought we'd be friends forever!",
            FOLLOWER = "Follow me to sweet home.",
            GENERIC = "And you can't find your home?",
            SLEEPING = "Have a nice dream.",
        },
        POISONBALM = "I'll gladly take a balm over a syrup...",
        PORKLAND_INTRO_BALLOON = "It's a shame I didn't hold on longer.",
        PORKLAND_INTRO_BASKET = "That was the end of the first balloon trip.",
        PORKLAND_INTRO_FLAGS = "Signaling flag.",
        PORKLAND_INTRO_SANDBAG = "Ms. Wheeler. What's this used for?",
        PORKLAND_INTRO_SUITCASE = "At least we can exclude Mr. Maxwell.",
        PORKLAND_INTRO_TRUNK = "At least we can exclude Mr. Maxwell.",
        PROP_DOOR = "Let's go! Woby!",
        PUGALISK = "It's a basilisk! Don't look into its eyes!",
        PUGALISK_CORPSE = "It was you who made the first move, please don't blame me!",
        PUGALISK_FOUNTAIN = "It'll Woby stay with us forever!",
        PUGALISK_RUINS_PILLAR = "I'm afraid it won't last much longer.",
        PUGALISK_SKULL = "Basilisk's head.",
        PUGALISK_TRAP_DOOR = "What kind of monster is this painting?",
        RABID_BEETLE = {
            DEAD = "Oh, dead.",
            GENERIC = "Wow, look how active they are!",
            SLEEPING = "it's sleeping,",
        },
        RADISH = "Is it possible for this carrot to turn into a mouse?",
        RADISH_COOKED = "right. This is cooked water radish.",
        RADISH_PLANTED = "Now we have more water radishes. yeah.",
        RADISH_SEEDS = "Woby, do you see a good spot to plant these?",
        RAINFORESTTREE = {
            BURNING = "Forest fire!",
            BURNT = "This is why fire safety is important.",
            CHOPPED = "We borrowed some wood.",
            GENERIC = "A tropical trees, nature is really amazing!",
        },
        RAINFORESTTREE_ROT = "It doesn't look healthy.",
        REEDS_WATER = "A pretty normal thing to see in a pool.",
        RELIC_1 = "A small pig statue.",
        RELIC_2 = "What do you think they will write? Warby?",
        RELIC_3 = "A huge nose.",
        RELIC_4 = "Maybe Wilba knows her.",
        RELIC_5 = "Looks precious.",
        ROCK_BASALT = "Stone created by robots.",
        ROCK_FLIPPABLE = "Guess what's underneath?",
        ROOTTRUNK_CHILD = "Just like Mr. Maxwell's magic!",
        RUG_BEARD = "That's a...very curious collection.",
        SAIL_SNAKESKIN = "The snakes wouldn't end up like this if they didn't try to eat me!",
        SCORPION = {
            DEAD = "Ouch...we killed it.",
            GENERIC = "Where is my trap?",
            SLEEPING = "It's asleep, good chance.",
        },
        SEDIMENTPUDDLE = "Is that gold in there?",
        SHEARS = "Gardener's little helper.",
        SMELTER = {
            BURNT = "It's uh... extra done!",
            COOKING_SHORT = "What's going on here? I want to take a closer look.",
            DONE = "Check out what we've come up with!",
            EMPTY = "A lrage iron pot. got it? Iron pot.",
        },
        SNAKEBONESOUP = "What a spicy spine.",
        SNAKEOIL = "Come on, even a child wouldn't fall for this...",
        SNAKESKIN = "It's slick. We might be able to use this for something.",
        SNAKESKINHAT = "Can I make Woby a little, matching one?",
        SNAKE_AMPHIBIOUS = "This snake is highly venomous, so you must seek medical attention immediately!",
        SNAKE_BONE = "What a huge bone.",
        SPIDER_MONKEY = {
            DEAD = "It's not moving.",
            GENERIC = "So you are that giant spider and... bigfoot!",
            SLEEPING = "Do you think it's fast asleep? Woby?",
        },
        SPIDER_MONKEY_NEST = "Home to the spider bigfoot.",
        SPIDER_MONKEY_TREE = "It would have to be a giant spider to do that!",
        SPRINKLER = "It will take care of our lawn!",
        TEA = "It's tea time now! Woby!",
        TEATREE = "Hey, is there a squirrel in the tree?",
        TEATREE_NUT = "Mom used to try this on me.",
        TEATREE_NUT_COOKED = "It actually tastes pretty good this way.",
        TEATREE_NUT_SAPLING = "We are still a long way from a cozy squirrel home.",
        THUNDERBIRD = "Watch that flickering electric light!",
        THUNDERBIRDNEST = "This is where they live.",
        THUNDERHAT = "Don't let me shock you.",
        TOUCAN = "Okay, that one's definitely unfamiliar.",
        TREE_PILLAR = "Such a big tree, even werebeaver can't eat it all.",
        TUBERTREE = "A parsnip?",
        TUBER_BLOOM_CROP = "开花的块茎。",
        TUBER_BLOOM_CROP_COOKED = "看起来相当诱人。",
        TUBER_CROP = "我想知道现在的它是什么味道的？",
        TUBER_CROP_COOKED = "看起来也不差。",
        TUNACAN = "Not catching it yourself takes the joy out of it.",
        TURF_COBBLEROAD = "Some road.",
        TURF_DEEPRAINFOREST = "A patch of ground.",
        TURF_DEEPRAINFOREST_NOCANOPY = "A patch of ground.",
        TURF_FIELDS = "A patch of ground.",
        TURF_FOUNDATION = "Some Foundation.",
        TURF_GASJUNGLE = "A patch of ground.",
        TURF_LAWN = "A patch of ground.",
        TURF_MOSS = "A patch of ground.",
        TURF_PAINTED = "A patch of ground.",
        TURF_PIGRUINS = "A patch of ground.",
        TURF_PLAINS = "A patch of ground.",
        TURF_RAINFOREST = "A patch of ground.",
        VAMPIREBAT = {
            DEAD = "Will it be resurrected?",
            GENERIC = "vampire!",
            SLEEPING = "Shh. Don't wake it up.",
        },
        VAMPIREBATCAVE = "A vampire's lair.",
        VENOMGLAND = "It's brimming with venom... Haha...",
        VENUS_STALK = "I think that's their stomach are.",
        VINE = "Foraged vines, perfect for kindling and crafting.",
        WALKINGSTICK = "Now I get a wood leg too.",
        WALL_PIG_RUINS = "The ancients...the ancient pigs built it.",
        WATERDROP = "Are those inside those seeds?",
        WEEVOLE = "Hey! Got you!",
        WEEVOLE_CARAPACE = "Let's put it away, it might be useful.",
        WINDOW_GREENHOUSE = "Can we go out and play?",
        WINDOW_LARGE_SQUARE = "Can we go out and play?",
        WINDOW_LARGE_SQUARE_CURTAIN = "Can we go out and play?",
        WINDOW_ROUND = "Can we go out and play?",
        WINDOW_ROUND_BURLAP = "Can we go out and play?",
        WINDOW_ROUND_CURTAINS_NAILS = "Can we go out and play?",
        WINDOW_SMALL_PEAKED = "Can we go out and play?",
        WINDOW_SMALL_PEAKED_CURTAIN = "Can we go out and play?",
        WINDOW_TALL = "Can we go out and play?",
        WINDOW_TALL_CURTAIN = "Can we go out and play?",
    },
}
