return {
    ANNOUCE_BATS = "This doesn't seem to be a good sign.",
    ANNOUNCE_BOAT_DAMAGED = "I wonder if there's a badge for boat maintenance.",
    ANNOUNCE_BOAT_SINKING = "We may need to repair this soon, haha...",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I-I don't think I can swim my way back!",
    ANNOUNCE_DEHUMID = {
        "Still more comfortable this way.",
    },
    ANNOUNCE_HAYFEVER = "There's something in the air...my nose is itching.",
    ANNOUNCE_HAYFEVER_OFF = "My nose is so much better and it's finally gone!",
    ANNOUNCE_PICKPOOP = {
        "Pine Pioneers must be hardworking...but...",
        "This is really unhygienic!",
        "do not come! Woby!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "As hard as metal!",
        "It has invulnerable scales!",
        "Is it like this all over its body?",
    },
    ANNOUNCE_SNEEZE = "Ah Choo!",
    ANNOUNCE_TOO_HUMID = {
        "I'm bored.",
        "%s is not breathable at all.",
    },
    ANNOUNCE_WAVE_BOOST = "Woohoo!",
    DESCRIBE = {
        ALLOY = "It's steel! Look at the steel I made!",
        ANCIENT_HULK = "War automation! It's real!",
        ANCIENT_ROBOTS_ASSEMBLY = "They're assembling themselves! What will it become in the end?",
        ANCIENT_ROBOT_CLAW = "Can it be installed on WX?",
        ANCIENT_ROBOT_HEAD = "A giant robot head!",
        ANCIENT_ROBOT_LEG = "A leg. I wonder are they come from the same giant?",
        ANCIENT_ROBOT_RIBS = "A machine ant?",
        APORKALYPSE_CLOCK = "Oh no! It's a doomsday prophecy!",
        ARMOR_METALPLATE = "Nothing can hurt me with this on!",
        ARMOR_WEEVOLE = "Are we really going to wear it?",
        ASPARAGUS_PLANTED = "Miss Winona might like it, pick some.",
        BASEFAN = "Ah, it's so comfortable, Woby, you can also enjoy it.",
        BILL = {
            DEAD = "Too bad. I was hoping to make a new friend.",
            GENERIC = "Guys! Look at this strange creature!",
            SLEEPING = "Sleeping...",
        },
        BILL_QUILL = "This thorn is really long.",
        BOATREPAIRKIT = "I'll need to maintain Woby's boat as well.",
        BOAT_CARGO = "You can fit almost all your camping goods in there!",
        BOAT_CORK = "Rainforest rafting, oh yeah!",
        BOAT_LOGRAFT = "Just like the ones we used to make to cross rivers!",
        BOAT_ROW = "We're getting better at carving boats.",
        BOAT_TORCH = "It's important to have good visibility while sailing.",
        BONESTAFF = "I can't help but want to look into its eyes...",
        CHITIN = "Check out the pattern on this! Woby!",
        COFFEE = "Mom would kill me if she caught me drinking this.",
        COFFEEBEANS = "I wish these were cocoa beans.",
        COFFEEBEANS_COOKED = "Smells great!",
        CUTNETTLE = "Ow! It got me.",
        DISARMING_KIT = "Adventure activities, cool!",
        DUNGBALL = "How did she... nevermind.",
        DUNGBEETLE = {
            DEAD = "Hello?",
            GENERIC = "I need a very huge bottle to hold her!",
            SLEEPING = "She is sleeping.",
            UNDUNGED = "She's not with that dung ball. Good timing.",
        },
        DUNGPILE = {
            GENERIC = "What giant creature left this?",
            PICKED = "Eww!",
        },
        FLOWER_RAINFOREST = "oh! That's the kind of flower in jungle adventure stories.",
        FROGLEGS_POISON = "I think it's highly toxic.",
        FROGLEGS_POISON_COOKED = "Is this safe?",
        FROG_POISON = {
            DEAD = "Don't touch it. Woby.",
            GENERIC = "The more beautiful the creatures, the more poisonous they are.",
            SLEEPING = "Don't touch it. Woby.",
        },
        GLOWFLY = {
            DEAD = "Oh, dead.",
            GENERIC = "Whoa, look at the light they emit!",
            SLEEPING = "it is sleeping.",
        },
        GLOWFLY_COCOON = "A cocoon, what could be inside?",
        GOLDENMACHETE = "Hack in style!",
        GOLDPAN = "Are you ready? Woby.",
        GOLD_DUST = "Smallest gold are still gold.",
        GRABBING_VINE = "What kind of monster up there?",
        GRASS_TALL = {
            BURNING = "Hey! Brush fires will destroy rainforests!",
            GENERIC = "A lush patch of grass. Must be a lot of bugs in it.",
            PICKED = "Collect again after a while.",
        },
        HALBERD = "A huge ax!",
        HANGING_VINE = "What kind of monster up there?",
        HIPPOPOTAMOOSE = "So it will be a... a hippo... hippopotalope!",
        HIPPO_ANTLER = "That'll make a decent bugle.",
        ICEDTEA = "It just got better.",
        INFUSED_IRON = "These lines shone with a strange light.",
        IRON = "Is that iron?",
        LILYPAD = "Look how big it is! I really want to stand up and take a look!",
        LIVING_ARTIFACT = "Indestructible mechanical armor!",
        LOTUS = "Sis Walani says that's edible...",
        LOTUS_FLOWER = "A flower floating in the water.",
        LOTUS_FLOWER_COOKED = "Woby! Look these holes!",
        MACHETE = "I like the cut of this blade.",
        MANDRAKEHOUSE = "Is this where the magic happens?",
        MANDRAKEMAN = "Warby! That big carrot over there has a face!",
        METALPLATEHAT = "It looks so funny.",
        PANGOLDEN = "A born gold rusher.",
        PEAGAWK = {
            GENERIC = "Wow, how many eyes are there?",
            SLEEPING = "Woby, we might be able to gather his feathers while he's asleep.",
        },
        PEAGAWKFEATHER = "method is valid.",
        PEAGAWK_BUSH = "This bird can't fly, but turns into a bush!",
        PIKO = {
            DEAD = "Poor little guy.",
            GENERIC = "I want to know what they usually do?",
            SLEEPING = "It fell asleep.",
        },
        PIKO_ORANGE = {
            DEAD = "Poor little guy.",
            GENERIC = "I must catch it!",
            SLEEPING = "It fell asleep.",
        },
        PUGALISK = "It's a basilisk! Don't look into its eyes!",
        PUGALISK_CORPSE = "It was you who made the first move, please don't blame me!",
        PUGALISK_FOUNTAIN = "It'll Woby stay with us forever!",
        PUGALISK_RUINS_PILLAR = "I'm afraid it won't last much longer.",
        PUGALISK_SKULL = "Basilisk's head.",
        PUGALISK_TRAP_DOOR = "What kind of monster is this painting?",
        RABID_BEETLE = {
            DEAD = "Oh, dead.",
            GENERIC = "Wow, look how active they are!",
            SLEEPING = "it's sleeping,",
        },
        REEDS_WATER = "A pretty normal thing to see in a pool.",
        SAIL_SNAKESKIN = "The snakes wouldn't end up like this if they didn't try to eat me!",
        SEDIMENTPUDDLE = "Is that gold in there?",
        SHEARS = "Gardener's little helper.",
        SMELTER = {
            BURNT = "It's uh... extra done!",
            COOKING_SHORT = "What's going on here? I want to take a closer look.",
            DONE = "Check out what we've come up with!",
            EMPTY = "A lrage iron pot. got it? Iron pot.",
        },
        SNAKEBONESOUP = "What a spicy spine.",
        SNAKESKIN = "It's slick. We might be able to use this for something.",
        SNAKE_BONE = "What a huge bone.",
        TEA = "It's tea time now! Woby!",
        TEATREE = "Hey, is there a squirrel in the tree?",
        TEATREE_NUT = "Mom used to try this on me.",
        TEATREE_NUT_COOKED = "It actually tastes pretty good this way.",
        TEATREE_NUT_SAPLING = "We are still a long way from a cozy squirrel home.",
        TREE_PILLAR = "Such a big tree, even werebeaver can't eat it all.",
        WEEVOLE = "Hey! Got you!",
        WEEVOLE_CARAPACE = "Let's put it away, it might be useful.",
    },
}
