return {
    ANNOUNCE_DEHUMID = {
        "Still more comfortable this way.",
    },
    ANNOUNCE_HAYFEVER = "There's something in the air...my nose is itching.",
    ANNOUNCE_HAYFEVER_OFF = "My nose is so much better and it's finally gone!",
    ANNOUNCE_PICKPOOP = {
        "Pine Pioneers must be hardworking...but...",
        "This is really unhygienic!",
        "do not come! Warby!",
    },
    ANNOUNCE_SNEEZE = "Ah Choo!",
    ANNOUNCE_TOO_HUMID = {
        "I'm bored.",
        "%s is not breathable at all.",
    },
    DESCRIBE = {
        ALLOY = "It's steel! Look at the steel I made!",
        APORKALYPSE_CLOCK = "Oh no! It's a doomsday prophecy!",
        ARMOR_METALPLATE = "Nothing can hurt me with this on!",
        ARMOR_WEEVOLE = "Are we really going to wear it?",
        ASPARAGUS_PLANTED = "Miss Winona might like it, pick some.",
        BALLPEIN_HAMMER = "I can now take those cute little figurines home.",
        BASEFAN = "Ah, it's so comfortable, Warby, you can also enjoy it.",
        CHITIN = "Check out the pattern on this! Warby!",
        CUTNETTLE = "Ow! It got me.",
        DUNGBALL = "How did she... nevermind.",
        DUNGBEETLE = {
            DEAD = "Hello?",
            GENERIC = "I need a very huge bottle to hold her!",
            SLEEPING = "She is sleeping.",
            UNDUNGED = "She's not with that dung ball. Good timing.",
        },
        DUNGPILE = {
            GENERIC = "What giant creature left this?",
            PICKED = "Eww!",
        },
        FLOWER_RAINFOREST = "oh! That's the kind of flower in jungle adventure stories.",
        GLOWFLY = {
            DEAD = "Oh, dead.",
            GENERIC = "Whoa, look at the light they emit!",
            SLEEPING = "it is sleeping.",
        },
        GLOWFLY_COCOON = "A cocoon, what could be inside?",
        GOLDENMACHETE = "Hack in style!",
        GOLDPAN = "Are you ready? Woby.",
        GOLD_DUST = "Smallest gold are still gold.",
        GRABBING_VINE = "What kind of monster up there?",
        GRASS_TALL = {
            BURNING = "Hey! Brush fires will destroy rainforests!",
            GENERIC = "A lush patch of grass. Must be a lot of bugs in it.",
            PICKED = "Collect again after a while.",
        },
        HALBERD = "A huge ax!",
        HANGING_VINE = "What kind of monster up there?",
        IRON = "Is that iron?",
        MACHETE = "I like the cut of this blade.",
        PANGOLDEN = "A born gold rusher.",
        PEAGAWK = {
            GENERIC = "Wow, how many eyes are there?",
            SLEEPING = "Warby, we might be able to gather his feathers while he's asleep.",
        },
        PEAGAWKFEATHER = "method is valid.",
        PEAGAWK_BUSH = "This bird can't fly, but turns into a bush!",
        PIG_RUINS_HEAD = "Warby! It's bigger than you!",
        PIG_RUINS_IDOL = "Look what we found, Warby!",
        PIG_RUINS_PLAQUE = "It's a totem!",
        RABID_BEETLE = {
            DEAD = "Oh, dead.",
            GENERIC = "Wow, look how active they are!",
            SLEEPING = "it's sleeping,",
        },
        SEDIMENTPUDDLE = "Is that gold in there?",
        SHEARS = "Gardener's little helper.",
        SMELTER = {
            BURNT = "It's uh... extra done!",
            COOKING_SHORT = "What's going on here? I want to take a closer look.",
            DONE = "Check out what we've come up with!",
            EMPTY = "A lrage iron pot. got it? Iron pot.",
        },
        TREE_PILLAR = "Such a big tree, even werebeaver can't eat it all.",
        WEEVOLE = "Hey! Got you!",
        WEEVOLE_CARAPACE = "Let's put it away, it might be useful.",
    },
}
