return {
    ANNOUNCE_DEHUMID = {
        "Ha, feeling better.",
    },
    ANNOUNCE_HAYFEVER = "Don't these plants do anything else but pollinate all over the place?",
    ANNOUNCE_HAYFEVER_OFF = "Whoops! it is finally over!",
    ANNOUNCE_SNEEZE = "Ah Choo!",
    ANNOUNCE_TOO_HUMID = {
        "Wearing %s is a shame.",
        "This terrible weather... I really shouldn't be wearing %s.",
    },
    DESCRIBE = {
        ALLOY = "Strong refined metal.",
        ANNOUNCE_PICKPOOP = {
            "Why would I do that?",
            "There must be something wrong with my mind.",
            "(Retching)",
        },
        APORKALYPSE_CLOCK = "Keeping track of their movements...very clever idea.",
        ARMOR_METALPLATE = "I still prefer magic.",
        ARMOR_WEEVOLE = "It doesn't smell that great, but there's no time to dwell on that much.",
        ASPARAGUS_PLANTED = "I should pick some and go back to eat.",
        BASEFAN = "Very interesting structure, but unfortunately not refined enough.",
        CHITIN = "I don't understand what's the point of this?",
        COFFEE = "Perfect for those long nights at the workshop back home.",
        COFFEEBEANS = "A quick roasting will get me something good to sip on.",
        COFFEEBEANS_COOKED = "I could pop these in my mouth or take the time to boil them.",
        CUTNETTLE = "This keeps us breathing smoothly.",
        DUNGBALL = "I won't touch it.",
        DUNGBEETLE = {
            DEAD = "She ends up being part of those.",
            GENERIC = "That's gross.",
            SLEEPING = "She is resting.",
            UNDUNGED = "She'll find another one.",
        },
        DUNGPILE = {
            GENERIC = "It's definitely not worth any of my time.",
            PICKED = "Let's just get it over with.",
        },
        FLOWER_RAINFOREST = "Why am I wasting time staring at it?",
        GLOWFLY = {
            DEAD = "Maybe that's for the best.",
            GENERIC = "I still like them the way they are now.",
            SLEEPING = "Sleep well now.",
        },
        GLOWFLY_COCOON = "We'd better get out of here before it breaks out of its cocoon.",
        GOLDENMACHETE = "What else do you do with gold in a jungle island?",
        GOLDPAN = "I dread to think how long this will take.",
        GOLD_DUST = "I need to collect lot of them.",
        GRABBING_VINE = "I really hope it was just a regular plant.",
        GRASS_TALL = {
            BURNING = "This is not good.",
            GENERIC = "Grasses this tough are indeed uncommon.",
            PICKED = "Over time, it will grow back.",
        },
        HALBERD = "I'm not planning on murdering grove of trees.",
        HANGING_VINE = "I really hope it was just a regular plant.",
        ICEDTEA = "Right on time, Now I can taste it.",
        IRON = "An essential material for accurate timepieces.",
        MACHETE = "It's for chopping, simple as that.",
        PANGOLDEN = "It has an extravagant recipe.",
        PEAGAWK = {
            GENERIC = "See no evil!",
            SLEEPING = "Shouldn't it be looking at me?",
        },
        PEAGAWKFEATHER = "It's hard to see.",
        PEAGAWK_BUSH = "What a clever disguise.",
        PIKO = {
            DEAD = "They are quiet... forever.",
            GENERIC = "It better not mess with my stuff.",
            SLEEPING = "It's kind of cute if they just quiet.",
        },
        PIKO_ORANGE = {
            DEAD = "They are quiet... forever.",
            GENERIC = "Is this a rare coat color?",
            SLEEPING = "It's kind of cute if they just quiet.",
        },
        RABID_BEETLE = {
            DEAD = "There is one less pest in the world.",
            GENERIC = "vermin! go away!",
            SLEEPING = "Huh, I can take a breath.",
        },
        SEDIMENTPUDDLE = "Water isn't the only thing reflecting sunlight here.",
        SHEARS = "I won't waste my time on this.",
        SMELTER = {
            BURNT = "We've made the most of it.",
            COOKING_SHORT = "Good thing it won't take me too much time.",
            DONE = "Got it!",
            EMPTY = "Melt the metals together.",
        },
        TEA = "It's always tea time, somewhere.",
        TEATREE = "I have some impression of the shape of these leaves.",
        TEATREE_NUT = "A crude way to combat pollen in the air.",
        TEATREE_NUT_COOKED = "I appreciate the attempt, but this is just waste of time.",
        TEATREE_SAPLING = "I should come back after it grows up.",
        TREE_PILLAR = "Thankfully it doesn't completely block the sun.",
        WEEVOLE = "I remember it biting.",
        WEEVOLE_CARAPACE = "Evil, exudes a strange smell.",
    },
}
