return {
    ANNOUNCE_DEHUMID = {
        "Ha, feeling better.",
    },
    ANNOUNCE_HAYFEVER = "Don't these plants do anything else but pollinate all over the place?",
    ANNOUNCE_HAYFEVER_OFF = "Whoops! it is finally over!",
    ANNOUNCE_PICKPOOP = {
        "Why would I do that?",
        "There must be something wrong with my mind.",
        "(Retching)",
    },
    ANNOUNCE_SNEEZE = "Ah Choo!",
    ANNOUNCE_TOO_HUMID = {
        "Wearing %s is a shame.",
        "This terrible weather... I really shouldn't be wearing %s.",
    },
    DESCRIBE = {
        ALLOY = "Strong refined metal.",
        ANTQUEEN_THRONE = "Let's see what treasure she's hiding.",
        APORKALYPSE_CLOCK = "Keeping track of their movements...very clever idea.",
        ARMOR_METALPLATE = "I still prefer magic.",
        ARMOR_WEEVOLE = "It doesn't smell that great, but there's no time to dwell on that much.",
        ASPARAGUS_PLANTED = "I should pick some and go back to eat.",
        BALLPEIN_HAMMER = "Fine work, I am best at fine work.",
        BASEFAN = "Very interesting structure, but unfortunately not refined enough.",
        CHITIN = "I don't understand what's the point of this?",
        CUTNETTLE = "This keeps us breathing smoothly.",
        DUNGBALL = "I won't touch it.",
        DUNGBEETLE = {
            DEAD = "She ends up being part of those.",
            GENERIC = "That's gross.",
            SLEEPING = "She is resting.",
            UNDUNGED = "She'll find another one.",
        },
        DUNGPILE = {
            GENERIC = "It's definitely not worth any of my time.",
            PICKED = "Let's just get it over with.",
        },
        FLOWER_RAINFOREST = "Why am I wasting time staring at it?",
        GLOWFLY = {
            DEAD = "Maybe that's for the best.",
            GENERIC = "I still like them the way they are now.",
            SLEEPING = "Sleep well now.",
        },
        GLOWFLY_COCOON = "We'd better get out of here before it breaks out of its cocoon.",
        GOLDENMACHETE = "What else do you do with gold in a jungle island?",
        GOLDPAN = "I dread to think how long this will take.",
        GOLD_DUST = "I need to collect lot of them.",
        GRABBING_VINE = "I really hope it was just a regular plant.",
        GRASS_TALL = {
            BURNING = "This is not good.",
            GENERIC = "Grasses this tough are indeed uncommon.",
            PICKED = "Over time, it will grow back.",
        },
        HALBERD = "I'm not planning on murdering grove of trees.",
        HANGING_VINE = "I really hope it was just a regular plant.",
        IRON = "An essential material for accurate timepieces.",
        MACHETE = "It's for chopping, simple as that.",
        PANGOLDEN = "It has an extravagant recipe.",
        PEAGAWK = {
            GENERIC = "See no evil!",
            SLEEPING = "Shouldn't it be looking at me?",
        },
        PEAGAWKFEATHER = "It's hard to see.",
        PEAGAWK_BUSH = "What a clever disguise.",
        PIG_RUINS_ARTICHOKE = "Stones carved into vegetables.",
        PIG_RUINS_HEAD = "Huge stone pig face.",
        PIG_RUINS_IDOL = "I thought it would be deeper...oh, that's another one.",
        PIG_RUINS_MUSHROOM = "This is it, and I can exchange it for great rewards.",
        PIG_RUINS_PIG = "What is it laughing at?",
        PIG_RUINS_PLAQUE = "I'm curious what it means, but forget it.",
        PIG_RUINS_SOW = "This one comes in a unique colorway.",
        RABID_BEETLE = {
            DEAD = "There is one less pest in the world.",
            GENERIC = "vermin! go away!",
            SLEEPING = "Huh, I can take a breath.",
        },
        RELIC_1 = "Not everyone can span a long time.",
        RELIC_2 = "It must have been the work of an ancient pig man.",
        RELIC_3 = "Big stone nose.",
        RELIC_4 = "Let's go get the reward quickly.",
        RELIC_5 = "This is it, and I can exchange it for great rewards.",
        SEDIMENTPUDDLE = "Water isn't the only thing reflecting sunlight here.",
        SHEARS = "I won't waste my time on this.",
        SMELTER = {
            BURNT = "We've made the most of it.",
            COOKING_SHORT = "Good thing it won't take me too much time.",
            DONE = "Got it!",
            EMPTY = "Melt the metals together.",
        },
        TREE_PILLAR = "Thankfully it doesn't completely block the sun.",
        WEEVOLE = "I remember it biting.",
        WEEVOLE_CARAPACE = "Evil, exudes a strange smell.",
    },
}
