return {
    ACTIONFAIL = {
        USEDOOR = {
            GENERIC = "We are not welcome here now.",
            LOCKED = "I must have left my keys somewhere...",
        },
    },
    ANNOUCE_ALARMOVER = "We are safe, for now.",
    ANNOUCE_BATS = "Why do things always keep causing trouble for us?",
    ANNOUCE_OTHERWORLD_DEED = "This address is too far away.",
    ANNOUCE_UNDERLEAFCANOPY = "They're lurking here! I need light!",
    ANNOUNCE_BOAT_DAMAGED = "My boat's damaged...",
    ANNOUNCE_BOAT_SINKING = "Ack! This doesn't seem seaworthy at all anymore!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I'm not meeting my end drowning in the middle of nowhere!",
    ANNOUNCE_DEHUMID = {
        "Ha, feeling better.",
    },
    ANNOUNCE_GAS_DAMAGE = "Ahem! Ho-cough cough cough!",
    ANNOUNCE_HAYFEVER = "Don't these plants do anything else but pollinate all over the place?",
    ANNOUNCE_HAYFEVER_OFF = "Whoops! it is finally over!",
    ANNOUNCE_HOUSE_DOOR = "Permission must be obtained first.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "Come here! The secret door is here.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Uh. Nope. Not here.",
    ANNOUNCE_MYSTERY_FOUND = "Hey, there's really something here.",
    ANNOUNCE_MYSTERY_NOREWARD = "What a waste of time.",
    ANNOUNCE_NOTHING_FOUND = "The distance is too much for it.",
    ANNOUNCE_PICKPOOP = {
        "Why would I do that?",
        "There must be something wrong with my mind.",
        "(Retching)",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Not here. Wrong place.",
        "You can't get through here.",
        "Where... where is it?",
    },
    ANNOUNCE_ROOM_STUCK = "Nobody wanna to stay in this room forever.",
    ANNOUNCE_SNEEZE = "Ah Choo!",
    ANNOUNCE_SUITUP = "Just matter of TIME!!!",
    ANNOUNCE_TAXDAY = "Tick tock. Is time for tax. Citizens hurry up.",
    ANNOUNCE_TOOLCORRODED = "Well, it's not designed to be used in this environment.",
    ANNOUNCE_TOO_HUMID = {
        "Wearing %s is a shame.",
        "This terrible weather... I really shouldn't be wearing %s.",
    },
    ANNOUNCE_TURFTOOHARD = "I don’t know how much time this will waste.",
    ANNOUNCE_WAVE_BOOST = "Wh-whoa!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Uprooted.",
            GENERIC = "This is an obvious trap.",
            SLEEPING = "Let's just walk over there.",
        },
        ALLOY = "Strong refined metal.",
        ALOE = "This is good stuff.",
        ALOE_COOKED = "Eat it while it's hot.",
        ALOE_PLANTED = "Let's take it off, it might be the last one.",
        ALOE_SEEDS = "Why waste time growing them when I can just eat them now?",
        ANCIENT_HERALD = "It not coming for me doesn't mean I'm okay with these!",
        ANCIENT_HULK = "It better be worth it!",
        ANCIENT_REMNANT = "Um... I have a new theory about nightmare fuel.",
        ANCIENT_ROBOTS_ASSEMBLY = "Why I'm doing this again?",
        ANCIENT_ROBOT_CLAW = "I think it was the tail... But doesn't it look more like a hand?",
        ANCIENT_ROBOT_HEAD = "We'd better not do that in its face.",
        ANCIENT_ROBOT_LEG = "We better stay away from it before ready.",
        ANCIENT_ROBOT_RIBS = "A giant metal rib.",
        ANTCHEST = "Wow, I originally wanted to speed up time.",
        ANTIVENOM = "It's simply a must-have around here.",
        ANTQUEEN_THRONE = "Let's see what treasure she's hiding.",
        APORKALYPSE_CLOCK = "Keeping track of their movements...very clever idea.",
        ARMORVORTEXCLOAK = "Cover yourself with shattered spacetime.",
        ARMOR_METALPLATE = "I still prefer magic.",
        ARMOR_SNAKESKIN = "I suppose this is a good use for those nasty snakes.",
        ARMOR_WEEVOLE = "It doesn't smell that great, but there's no time to dwell on that much.",
        ASPARAGUS_PLANTED = "I should pick some and go back to eat.",
        BALLPEIN_HAMMER = "Delicate work. Delicate is my specialty.",
        BAMBOO = "I could think of a few uses for these later.",
        BASEFAN = "Very interesting structure, but unfortunately not refined enough.",
        BILL = {
            DEAD = "I had to hand clock it.",
            GENERIC = "stop! I still want to use those flowers!",
            SLEEPING = "Just sleeping.",
        },
        BILL_QUILL = "Hmm...I'll find a good use for it.",
        BLUNDERBUSS = "Oh...that's not a good sign.",
        BOATREPAIRKIT = "Repairing takes a lot shorter than building a whole new boat from the scratch.",
        BOAT_CARGO = "I'll save so much time if I don't have to go back to fetch my things!",
        BOAT_CORK = "Is this the only thing standing between us and the cold water?",
        BOAT_LOGRAFT = "I don't have time. If it floats, it's enough.",
        BOAT_ROW = "Rowing takes forever! Surely I can install something on it?",
        BOAT_TORCH = "This will keep me safe, nice and hands-free.",
        BONESTAFF = "Freeze all enemies stand in my way.",
        BRAMBLESPIKE = "They block my way.",
        BRAMBLE_BULB = "Maybe there are some ways to take advantage of it.",
        BRAMBLE_CORE = "I'm not sure it's worth my time.",
        BURR = "An aggressive tree kid.",
        BURR_SAPLING = {
            BURNING = "That's the childhood's end for it.",
            GENERIC = "It take a long long time.",
            PICKED = "What did I do to it?",
            WITHERED = "It needs shade... to create shade.",
        },
        CHITIN = "I don't understand what's the point of this?",
        CITY_LAMP = {
            GENERIC = "Now that's a way to save time!",
            ON = "I wonder if that helps save fuel?",
        },
        CLAWPALMTREE = "It rather looks like a hand.",
        CLAWPALMTREE_SAPLING = "It just takes a moment now.",
        COCONADE = {
            BURNING = "It's about to blow, quick!",
            GENERIC = "This seems like a bad idea...",
        },
        COFFEE = "Perfect for those long nights at the workshop back home.",
        COFFEEBEANS = "A quick roasting will get me something good to sip on.",
        COFFEEBEANS_COOKED = "I could pop these in my mouth or take the time to boil them.",
        COI = "That's a fish alright.",
        COI_COOKED = "If only I had a bit of vinegar to go with it.",
        CORK = "It came from a tree, as you'd expect.",
        CORKCHEST = "To keep those puppies from messing with my things.",
        CURTAIN_DOOR = "To another room.",
        CUTLASS = "It's definitely sharp, if only I could apply shadow magic to it...",
        CUTNETTLE = "This keeps us breathing smoothly.",
        DECO_ANTIQUITIES_BEEFALO = "Stay at their best moment.",
        DECO_ANTIQUITIES_WALLFISH = "Stay at their best moment.",
        DECO_CAVE_BAT_BURROW = "There is an indescribable smell down there.",
        DECO_CAVE_BEAM_ROOM = "It keeps the earth from falling on our heads.",
        DECO_CHAIR_BENCH = "It's time for a proper break.",
        DECO_CHAIR_CLASSIC = "Classic, never out of date.",
        DECO_CHAIR_CORNER = "It's time for a proper break.",
        DECO_CHAIR_FOOTREST = "It's time for a proper break.",
        DECO_CHAIR_HORNED = "It's time for a proper break.",
        DECO_CHAIR_LOUNGE = "It's time for a proper break.",
        DECO_CHAIR_MASSAGER = "I don't know what it is, but it makes me feel dangerous.",
        DECO_CHAIR_OTTOMAN = "It's time for a proper break.",
        DECO_CHAIR_ROCKING = "It's time for a proper break.",
        DECO_CHAIR_STUFFED = "It's time for a proper break.",
        DECO_CHAISE = "It's time for a proper break.",
        DECO_LAMP_2EMBROIDERED = "It's not as bad as the rumor has it.",
        DECO_LAMP_2FRINGES = "It's not as bad as the rumor has it.",
        DECO_LAMP_2UPTURNS = "It's not as bad as the rumor has it.",
        DECO_LAMP_ADJUSTABLE = "It's not as bad as the rumor has it.",
        DECO_LAMP_BELLSHADE = "It's not as bad as the rumor has it.",
        DECO_LAMP_CANDELABRA = "It's not as bad as the rumor has it.",
        DECO_LAMP_CERAMIC = "It's not as bad as the rumor has it.",
        DECO_LAMP_CRYSTALS = "It's not as bad as the rumor has it.",
        DECO_LAMP_DOWNBRIDGE = "It's not as bad as the rumor has it.",
        DECO_LAMP_EDISON = "It's not as bad as the rumor has it.",
        DECO_LAMP_ELIZABETHAN = "It's not as bad as the rumor has it.",
        DECO_LAMP_FRINGE = "It's not as bad as the rumor has it.",
        DECO_LAMP_GLASS = "It's not as bad as the rumor has it.",
        DECO_LAMP_GOTHIC = "It's not as bad as the rumor has it.",
        DECO_LAMP_HOOFSPA = "It's not as bad as the rumor has it.",
        DECO_LAMP_ORB = "It's not as bad as the rumor has it.",
        DECO_LAMP_RIGHTANGLES = "It's not as bad as the rumor has it.",
        DECO_LAMP_SPOOL = "It's not as bad as the rumor has it.",
        DECO_LAMP_STAINGLASS = "It's not as bad as the rumor has it.",
        DECO_LAMP_UPTURN = "It's not as bad as the rumor has it.",
        DECO_MARBLE = "It supports the building.",
        DECO_MARBLE_CORNERBEAM = "It supports the building.",
        DECO_MILLINERY = "It supports the building.",
        DECO_PLANTHOLDER_BASIC = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_BIRDCAGE = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_BONSAI = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_DISHGARDEN = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_DRACEANA = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_FANCY = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_FERN = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_FERNSTAND = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_MARBLE = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_ORCHID = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_PALM = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_PHILODENDRON = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_PITCHERS = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_PLANTPET = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_TERRARIUM = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_TRAPS = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "This season again.",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "This season again.",
        DECO_PLANTHOLDER_WIP = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_XEROGRAPHICA = "Even workshop needs a bit of style.",
        DECO_PLANTHOLDER_ZZ = "Even workshop needs a bit of style.",
        DECO_ROUND = "It supports the building.",
        DECO_RUINS_BEAM_ROOM = "It keeps the bricks from falling on our heads.",
        DECO_RUINS_BEAM_ROOM_BLUE = "It keeps the bricks from falling on our heads.",
        DECO_TABLE_BANKER = "A table. Will wonders never cease.",
        DECO_TABLE_CHESS = "I don't have time for this, too bad.",
        DECO_TABLE_CRATE = "A table. Will wonders never cease.",
        DECO_TABLE_DIY = "A table. Will wonders never cease.",
        DECO_TABLE_RAW = "A table. Will wonders never cease.",
        DECO_TABLE_ROUND = "A table. Will wonders never cease.",
        DECO_WALLORNAMENT_AXE = "An axe.",
        DECO_WALLORNAMENT_BLACK_CAT = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_CAPE = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_GEARS_ART = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_HUNT = "Two spears.",
        DECO_WALLORNAMENT_MOSAIC = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_NO_SMOKING = "I don't want to smell that when I'm working.",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_PHOTO = "Don't leave the wall empty.",
        DECO_WALLORNAMENT_WREATH = "Don't leave the wall empty.",
        DECO_WOOD = "It supports the building.",
        DECO_WOOD_CORNERBEAM = "It supports the building.",
        DISARMING_KIT = "So I can worry about a little less.",
        DUG_NETTLE = "It requires special soil to grow, what is it...",
        DUNGBALL = "I won't touch it.",
        DUNGBEETLE = {
            DEAD = "She ends up being part of those.",
            GENERIC = "That's gross.",
            SLEEPING = "She is resting.",
            UNDUNGED = "She'll find another one.",
        },
        DUNGPILE = {
            GENERIC = "It's definitely not worth any of my time.",
            PICKED = "Let's just get it over with.",
        },
        FABRIC = "I missed fabric...",
        FEATHER_THUNDER = "A fun little gadget.",
        FLOWER_RAINFOREST = "Why am I wasting time staring at it?",
        FROGLEGS_POISON = "You can't eat this.",
        FROGLEGS_POISON_COOKED = "Is it safe after roasting...?",
        FROG_POISON = {
            DEAD = "It's you or me.",
            GENERIC = "You'll never catch me. Frogs.",
            SLEEPING = "Look at him sleeping away.",
        },
        GASMASKHAT = "Gives me more time in the gas.",
        GLOWFLY = {
            DEAD = "Maybe that's for the best.",
            GENERIC = "I still like them the way they are now.",
            SLEEPING = "Sleep well now.",
        },
        GLOWFLY_COCOON = "We'd better get out of here before it breaks out of its cocoon.",
        GNAT = "It reaches new heights in annoyingness.",
        GNATMOUND = "Dirty and messy.",
        GOLDENMACHETE = "What else do you do with gold in a jungle island?",
        GOLDPAN = "I dread to think how long this will take.",
        GOLD_DUST = "I need to collect lot of them.",
        GRABBING_VINE = "I really hope it was just a regular plant.",
        GRASS_TALL = {
            BURNING = "This is not good.",
            GENERIC = "Grasses this tough are indeed uncommon.",
            PICKED = "Over time, it will grow back.",
        },
        HALBERD = "I'm not planning on murdering grove of trees.",
        HANGING_VINE = "I really hope it was just a regular plant.",
        HIPPOPOTAMOOSE = "They have a knack for wasting time.",
        HIPPO_ANTLER = "Excellent quality clock decoration.",
        ICEDTEA = "Right on time, Now I can taste it.",
        INFUSED_IRON = "If I could use it on my pocket watch...",
        IRON = "An essential material for accurate timepieces.",
        IRON_DOOR = "To another room.",
        KINGFISHER = {
            DEAD = "Do I really have to stare at this dead bird?",
            GENERIC = "Some kind of bird that catches fish.",
            SLEEPING = "It is asleep.",
        },
        LAVAPOOL = "It seems like a quick way to burn myself.",
        LAWNORNAMENT = {
            BURNING = "Hey! That's my lawn!",
            BURNT = "I hope I can still get a refund.",
            GENERIC = "Really not bad.",
        },
        LIFEPLANT = "This is no ordinary flower.",
        LILYPAD = "I don't think this shortcut can be taken.",
        LIVING_ARTIFACT = "That's it! Perfect way to take advantage!",
        LOTUS = "Those buds look familiar...",
        LOTUS_FLOWER = "I hope that's more than dinner tonight.",
        LOTUS_FLOWER_COOKED = "It better be worth my time cooking it.",
        MACHETE = "It's for chopping, simple as that.",
        MAGNIFYING_GLASS = "Sometimes one of glasses isn't enough.",
        MANDRAKEHOUSE = "Looks screaming enough.",
        MANDRAKEMAN = "Stop shouting!",
        MEAN_FLYTRAP = {
            DEAD = "It won't continue to grow.",
            GENERIC = "I don't like the look of this grass.",
            SLEEPING = "It's sleeping.",
        },
        MEATED_NETTLE = "This is definitely a reversal of priorities.",
        METALPLATEHAT = "Nice, but way too heavy for a hat.",
        NECTAR_POD = "Not honey yet, I'm too soon.",
        NETTLE = {
            DEFAULT = "That's it, that's the taste.",
            EMPTY = "All right, I'll see you in three days.",
            MOIST = "Why would anyone prefer wet to dry?",
            WITHERED = "This soil is not suitable for it.",
        },
        NETTLELOSANGE = "This makes it much easier to eat.",
        OBSIDIAN = "If I had sharp enough cutting tools, this could go well as a watch crystal.",
        OINC = "Hopefully this will be worth my time.",
        OINC10 = "What should I buy?",
        OINC100 = "Is there truffle on this? I've never looked closely before!",
        ORGANIC_DOOR = "To another room.",
        OX_FLUTE = "It's much faster than waiting for it to rain for sure.",
        OX_HORN = "I should pocket it for some high-degree tinkering later.",
        PANGOLDEN = "They have an extravagant recipe.",
        PARROT_BLUE = {
            DEAD = "Do I really have to stare at this dead bird?",
            GENERIC = "Aren't they red?",
            SLEEPING = "They also have to sleep.",
        },
        PEAGAWK = {
            GENERIC = "See no evil!",
            SLEEPING = "Shouldn't it be looking at me?",
        },
        PEAGAWKFEATHER = "It's hard to see.",
        PEAGAWK_BUSH = "What a clever disguise.",
        PIGEON = {
            DEAD = "Do I really have to stare at this dead pigeon?",
            GENERIC = "That's a pigeon.",
            SLEEPING = "I guess they doesn't have anything better to do.",
        },
        PIGGHOST = "A scruffy soul.",
        PIGHOUSE_CITY = {
            BURNING = "I think it's about time too.",
            GENERIC = "I really hope this is I finally get back to the right time.",
        },
        PIGHOUSE_FARM = {
            BURNING = "I think it's about time too.",
            GENERIC = "I'm sure I've seen it in... Oh, that's the other one.",
        },
        PIGHOUSE_MINE = {
            BURNING = "I think it's about time too.",
            GENERIC = "I'm sure I've seen it in... Oh, that's the other one.",
        },
        PIGMAN_BANKER = {
            GENERIC = "Hah, moneybags.",
            SLEEPING = "Sleeping.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "Too bad it doesn't work on me.",
            SLEEPING = "Best not wake her.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "I fancy myself a collector, sometimes.",
            SLEEPING = "Long day?",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "You call THAT magic?",
            SLEEPING = "Maybe I could wake them...",
        },
        PIGMAN_FARMER = {
            GENERIC = "So that's who gets all the food!",
            SLEEPING = "Gotta keep your strength up.",
        },
        PIGMAN_FLORIST = {
            GENERIC = "Plants are too slow for me.",
            SLEEPING = "Does she dream of magic flowers?",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "I wonder if they could work with nightmare fuel?",
            SLEEPING = "That looks comfortable.",
        },
        PIGMAN_HUNTER = {
            GENERIC = "What do you hunt, I wonder?",
            SLEEPING = "Must have been a long day.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Yeah. You gonna re-elected. Wait, who are you again?",
            SLEEPING = "Cherish your leisure.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "There they are!",
            SLEEPING = "Hey, you're needed! Wake up!",
        },
        PIGMAN_MINER = {
            GENERIC = "I'd say they're hard workers, but I hardly see them work.",
            SLEEPING = "Don't you have a home to sleep in?",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "Woah, you look like you need some help.",
            SLEEPING = "Just sleeping, thank goodness.",
        },
        PIGMAN_QUEEN = "She actually very cold-blooded if you get to know her.",
        PIGMAN_ROYALGUARD = {
            GENERIC = "What fancy armor!.",
            SLEEPING = "Hey, you're meant to be guarding!",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "People in the service industry deserve respect.",
            SLEEPING = "I shouldn't be intruding.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Aww...",
            GENERIC = "Now that'd be useful.",
        },
        PIG_PALACE = "It's so beautiful. Let's go in.",
        PIG_RUINS_ARTICHOKE = "Stones carved into vegetables.",
        PIG_RUINS_HEAD = "Huge stone pig face.",
        PIG_RUINS_IDOL = "I thought it would be deeper...oh, that's another one.",
        PIG_RUINS_MUSHROOM = "This is it, and I can exchange it for great rewards.",
        PIG_RUINS_PLAQUE = "I'm curious what it means, but forget it.",
        PIG_RUINS_SOW = "This one comes in a unique colorway.",
        PIG_SHOP_ACADEMY = {
            BURNING = "Down it goes.",
            GENERIC = "A study of the old world.",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "I should have seen that coming.",
            GENERIC = "I wonder if any of them have experimented with time magic?",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "Why does this happen?",
            GENERIC = "Yes, it's on this street.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Ah, yes, this will happen...",
            GENERIC = "My office, I don’t know how long it will last.",
        },
        PIG_SHOP_DELI = {
            BURNING = "This is a bit over the top.",
            GENERIC = "It’s nice so I don’t have to spend time cooking it myself.",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "It's up like a tinderbox.",
            GENERIC = "How nice, a plant shop!",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "All that useful stuff, wasted!",
            GENERIC = "Just regular ol' things.",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "Aww, that's a shame.",
            GENERIC = "A nice hat can lift any mood!",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "Oh dear.",
            GENERIC = "It could be nice to slow down and relax.",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "Not even their ice is helping.",
            GENERIC = "Ah, fresh meat and veggies.",
        },
        PIG_SHOP_TINKER = {
            BURNING = "Alas, what a pity.",
            GENERIC = "A workshop where we can exchange our experiences.",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "This wouldn't have happened if they used magic.",
            GENERIC = "A good stopgap.",
        },
        PIKO = {
            DEAD = "They are quiet... forever.",
            GENERIC = "It better not mess with my stuff.",
            SLEEPING = "It's kind of cute if they just quiet.",
        },
        PIKO_ORANGE = {
            DEAD = "They are quiet... forever.",
            GENERIC = "Is this a rare coat color?",
            SLEEPING = "It's kind of cute if they just quiet.",
        },
        PILLAR_DOOR = "To another room.",
        PLATE_DOOR = "To another room.",
        POG = {
            APORKALYPSE = "Is all nice things most shattered?",
            FOLLOWER = "How adorable!",
            GENERIC = "Don't be fooled by their cute appearance.",
            SLEEPING = "It's resting.",
        },
        POISONBALM = "What a quick alternative to the classic antidote medicine!",
        PORKLAND_INTRO_BALLOON = "It has a big hole and is no longer usable.",
        PORKLAND_INTRO_BASKET = "Ah, it's all my fault...why didn't I think of it sooner?",
        PORKLAND_INTRO_FLAGS = "Some simple little decorations.",
        PORKLAND_INTRO_SANDBAG = "Used for counterweight.",
        PORKLAND_INTRO_SUITCASE = "There's only a \"W\" on it. What a recognizable mark.",
        PORKLAND_INTRO_TRUNK = "There's only a \"W\" on it. Realy helpful mark.",
        PROP_DOOR = "Just go through it. What's to be afraid of?",
        PUGALISK = "We finally have a battle!",
        PUGALISK_CORPSE = "Part of it is stuck under there.",
        PUGALISK_FOUNTAIN = "Oh...just put it here, at your fingertips.",
        PUGALISK_RUINS_PILLAR = "Hope I don't fall down when I walk under it.",
        PUGALISK_SKULL = "A natural container of excellent magic.",
        PUGALISK_TRAP_DOOR = "You don't want to know what's down there.",
        RABID_BEETLE = {
            DEAD = "There is one less pest in the world.",
            GENERIC = "vermin! go away!",
            SLEEPING = "Huh, I can take a breath.",
        },
        RADISH = "I Said. It must be a turnip.",
        RADISH_COOKED = "Got it. I hope it worthy.",
        RADISH_PLANTED = "It's a turnip. I can't be wrong,",
        RADISH_SEEDS = "Why waste time growing them when I can just eat them now?",
        RAINFORESTTREE = {
            BURNING = "This is the way it end.",
            BURNT = "What a shame.",
            CHOPPED = "It's too late to say anything now.",
            GENERIC = "Pretty. So what?",
        },
        RAINFORESTTREE_ROT = "This is not a good situation to live.",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "It's all broken.",
            SCAFFOLD = "Probably about time that gets fixed.",
        },
        REEDS_WATER = "Seem I'm have to wade into this.",
        RELIC_1 = "Not everyone can span a long time.",
        RELIC_2 = "It must have been the work of an ancient pig man.",
        RELIC_3 = "Big stone nose.",
        RELIC_4 = "Let's go get the reward quickly.",
        RELIC_5 = "What a strange look.",
        ROCK_BASALT = "A very ordinary stone.",
        ROCK_FLIPPABLE = "Just open it. What's to be afraid of?",
        ROOTTRUNK = "It's hard to imagine how extensive the root system is.",
        ROUND_DOOR = "To another room.",
        RUG_BEARD = "Disgusting!",
        RUG_BRAID = "A fine carpet.",
        RUG_CATCOON = "A real carpet.",
        RUG_CRIME = "Is't already happened?",
        RUG_FUR = "A real carpet.",
        RUG_HEDGEHOG = "Thankfully it's not real.",
        RUG_HOOFPRINT = "A fine carpet.",
        RUG_METAL = "A plate metal laid on the ground.",
        RUG_NAILBED = "Thankfully it's not real.",
        RUG_OCTAGON = "A fine carpet.",
        RUG_OVAL = "A fine carpet.",
        RUG_PORCUPUSS = "Thankfully it's not real.",
        RUG_RECTANGLE = "A giant carpet.",
        RUG_ROUND = "No one like to be peep.",
        RUG_RUBBERMAT = "A fine carpet.",
        RUG_SQUARE = "A fine carpet.",
        RUG_SWIRL = "A fine carpet.",
        RUG_TILES = "A fine carpet.",
        RUG_WEB = "Thankfully it's not real.",
        RUG_WORMHOLE = "Thankfully it's not real.",
        SAIL_SNAKESKIN = "There's no need to make a flag if the sail is colorful. Not that I need one.",
        SAND = "Sand. You do tend to find a lot of it around here.",
        SCORPION = {
            DEAD = "Why it's still there?",
            GENERIC = "A cunning creature.",
            SLEEPING = "No matter what kind of poison you are, you will get tired sometimes.",
        },
        SEDIMENTPUDDLE = "Water isn't the only thing reflecting sunlight here.",
        SHEARS = "I won't waste my time on this.",
        SHELF_ADJUSTABLE = "A good place to stack my creation.",
        SHELF_AFRAME = "A good place to stack my creation.",
        SHELF_BASIC = "A good place to stack my creation.",
        SHELF_CINDERBLOCKS = "A good place to stack my creation.",
        SHELF_CRATES = "A good place to stack my creation.",
        SHELF_FLOATING = "A good place to stack my creation.",
        SHELF_FRIDGE = "A good place to stack my creation.",
        SHELF_GLASS = "A good place to stack my creation.",
        SHELF_HATTREE = "A good place to stack my creation.",
        SHELF_HOOKS = "A good place to stack my creation.",
        SHELF_HUTCH = "A good place to stack my creation.",
        SHELF_INDUSTRIAL = "A good place to stack my creation.",
        SHELF_LADDER = "A good place to stack my creation.",
        SHELF_MARBLE = "A good place to stack my creation.",
        SHELF_METAL = "A good place to stack my creation.",
        SHELF_MIDCENTURY = "A good place to stack my creation.",
        SHELF_PALLET = "A good place to stack my creation.",
        SHELF_PIPE = "A good place to stack my creation.",
        SHELF_WALLMOUNT = "A good place to stack my creation.",
        SHELF_WOOD = "A good place to stack my creation.",
        SMELTER = {
            BURNT = "We've made the most of it.",
            COOKING_SHORT = "Good thing it won't take me too much time.",
            DONE = "Got it!",
            EMPTY = "Melt the metals together.",
        },
        SNAKEBONESOUP = "I doubt it's worth my time.",
        SNAKEOIL = "So many timelines and I've still not figured out what this is for.",
        SNAKESKIN = "Whew... It's not attached to a snake this time around.",
        SNAKESKINHAT = "If it keeps me from dying to wetness-induced pneumonia, I'll be happy.",
        SNAKE_AMPHIBIOUS = "Snake. Why did it have to be snake?",
        SNAKE_BONE = "It's too big for a clock.",
        SPIDER_MONKEY = {
            DEAD = "Dust to dust.",
            GENERIC = "I'm not stupid, it's definitely a made-up creature.",
            SLEEPING = "Enjoy your dreams.",
        },
        SPIDER_MONKEY_NEST = "I thought they were all destroyed at the beginning of time.",
        SPIDER_MONKEY_TREE = "A particularly bad colorful tree.",
        SPRINKLER = "Save me valuable time.",
        STONE_DOOR = "To another room.",
        SUNKEN_RELIC = "Trouble! I really don’t want to go into the water!",
        SWINGING_LIGHT1 = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_BASIC_BULB = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_BASIC_METAL = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_DERBY = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_FLORAL_BLOOMER = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_FLORAL_BULB = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_FLORAL_SCALLOP = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_PENDANT_CHERRIES = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_ROPE_1 = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_ROPE_2 = "Make sure there's no place for them to hide.",
        SWINGING_LIGHT_TOPHAT = "Make sure there's no place for them to hide.",
        TEA = "It's always tea time, somewhere.",
        TEATREE = "I have some impression of the shape of these leaves.",
        TEATREE_NUT = "A crude way to combat pollen in the air.",
        TEATREE_NUT_COOKED = "I appreciate the attempt, but this is just waste of time.",
        TEATREE_NUT_SAPLING = "I should come back after it grows up.",
        THUNDERBIRD = "It's whole body says \"stay back\".",
        THUNDERBIRDNEST = "I can't imagine lying on that.",
        THUNDERHAT = "I prefer lightning hit me there.",
        TOUCAN = "What's it supposed to do with a beak so large?",
        TRAWLNET = "At least it's faster than fishing for treasure myself.",
        TRAWLNETDROPPED = {
            GENERIC = "Now to check if that was worth the time.",
            SOON = "It will sink in nearly no time at all.",
            SOONISH = "I'd best empty it before it sinks by itself.",
        },
        TREE_PILLAR = "Thankfully it doesn't completely block the sun.",
        TUBERTREE = "We need specialized tools to cut it down.",
        TUBER_BLOOM_CROP = "You can eat it now.",
        TUBER_BLOOM_CROP_COOKED = "Well, a staple meal that is rare here.",
        TUBER_CROP = "It's not ready to eat yet.",
        TUBER_CROP_COOKED = "Even after treatment it is highly toxic.",
        TUNACAN = "Hmm, this lunch was packed with its own temporally-isolated pocket.",
        TURF_COBBLEROAD = "A road to where, exactly?",
        TURF_DEEPRAINFOREST = "Why am I wasting time staring at the ground?",
        TURF_DEEPRAINFOREST_NOCANOPY = "Why am I wasting time staring at the ground?",
        TURF_FIELDS = "Why am I wasting time staring at the ground?",
        TURF_FOUNDATION = "Why am I wasting time staring at the ground?",
        TURF_GASJUNGLE = "Why am I wasting time staring at the ground?",
        TURF_LAWN = "Why am I wasting time staring at the ground?",
        TURF_MOSS = "Why am I wasting time staring at the ground?",
        TURF_PAINTED = "Why am I wasting time staring at the ground?",
        TURF_PIGRUINS = "Why am I wasting time staring at the ground?",
        TURF_PLAINS = "Why am I wasting time staring at the ground?",
        TURF_RAINFOREST = "Why am I wasting time staring at the ground?",
        VAMPIREBAT = {
            DEAD = "It learned the lesson.",
            GENERIC = "Oh botheration, monsters haunt me all the time.",
            SLEEPING = "How cozy.",
        },
        VAMPIREBATCAVE = "Going in there is asking for trouble.",
        VENOMGLAND = "I suppose I could ingest it as it is, it'd be better than poison...",
        VENUS_STALK = "It's still too early to be usable.",
        VINE = "It's a vine. I won't take the time to get sentimental about it.",
        WALKINGSTICK = "Okay, I'll bring it.",
        WALL_PIG_RUINS = "Part of ancient citadel.",
        WATERDROP = "There is a price to pay for escaping.",
        WEEVOLE = "I remember it biting.",
        WEEVOLE_CARAPACE = "Evil, exudes a strange smell.",
        WINDOW_GREENHOUSE = "Ensure plenty of sunlight.",
        WINDOW_LARGE_SQUARE = "A window.",
        WINDOW_LARGE_SQUARE_CURTAIN = "A window.",
        WINDOW_ROUND = "A window.",
        WINDOW_ROUND_BURLAP = "A window.",
        WINDOW_ROUND_CURTAINS_NAILS = "A window.",
        WINDOW_SMALL_PEAKED = "A window.",
        WINDOW_SMALL_PEAKED_CURTAIN = "A window.",
        WINDOW_TALL = "A window.",
        WINDOW_TALL_CURTAIN = "A window.",
        WOOD_DOOR = "To another room.",
    },
}
