return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It will not work.",
        },
        USEDOOR = {
            GENERIC = "It cannot be opened.",
            LOCKED = "Perhaps there is a way to unlock it.",
        },
    },
    ANNOUCE_ALARMOVER = "I think I'm safe now.",
    ANNOUCE_BATS = "Agh! Bats!",
    ANNOUCE_OTHERWORLD_DEED = "I don't recognize this place.",
    ANNOUCE_UNDERLEAFCANOPY = "It is dark here.",
    ANNOUNCE_BOAT_DAMAGED = "The vessel is damaged...",
    ANNOUNCE_BOAT_SINKING = "Oh no... I can't die on an empty stomach!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Into the soup!",
    ANNOUNCE_DEHUMID = {
        "Ah, I feel better now.",
    },
    ANNOUNCE_GAS_DAMAGE = "Hack! Cough! Smells like gas!",
    ANNOUNCE_HAYFEVER = "Ugh! My allergies!",
    ANNOUNCE_HAYFEVER_OFF = "I think... my nose has cleared!",
    ANNOUNCE_HOUSE_DOOR = "My dream kitchen awaits! After I get a permit.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "Mon dieu! A door!",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Nothing here.",
    ANNOUNCE_MYSTERY_FOUND = "Mon dieu! I have found something!",
    ANNOUNCE_MYSTERY_NOREWARD = "Disappointing.",
    ANNOUNCE_NOTHING_FOUND = "Nothing nearby, I'm afraid.",
    ANNOUNCE_PICKPOOP = {
        "Blech!",
        "Blagh!",
        "Beurk!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "If only I had a shell cracker!",
        "Won't break there.",
        "I need to find a weak spot.",
    },
    ANNOUNCE_ROOM_STUCK = "I'd be trapped here. Like juices in meat when you sear it.",
    ANNOUNCE_SNEEZE = "Atchoum!",
    ANNOUNCE_SUITUP = "Eat your heart out!",
    ANNOUNCE_TAXDAY = "Time to collect tips for my excellent service!",
    ANNOUNCE_TOOLCORRODED = "Huh. I wonder what made my tool fall apart.",
    ANNOUNCE_TOO_HUMID = {
        "Mon dieu! This %s is humid.",
        "Whew. This %s is hot.",
    },
    ANNOUNCE_TURFTOOHARD = "Can't move that.",
    ANNOUNCE_WAVE_BOOST = "Whoaaaa!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "I can't say I'm sad about this.",
            GENERIC = "Oh my, what big teeth you have.",
            SLEEPING = "Now is a good time to sneak past.",
        },
        ALLOY = "Metal cooked to perfection.",
        ALOE = "'Allo?",
        ALOE_COOKED = "I can add this to something.",
        ALOE_PLANTED = "A plant of many uses. And recipes.",
        ALOE_SEEDS = "Ah, a fine addition to any garden.",
        ANCIENT_HERALD = "Mon dieu! He is frightening.",
        ANCIENT_HULK = "Must be hungry after that long sleep.",
        ANCIENT_REMNANT = "Not a fan of the dark motif but it may prove useful.",
        ANCIENT_ROBOTS_ASSEMBLY = "Perhaps it would be best if I left it unfinished.",
        ANCIENT_ROBOT_CLAW = "I'm staying away from that guy.",
        ANCIENT_ROBOT_HEAD = "I hope he stays asleep.",
        ANCIENT_ROBOT_LEG = "Could I serve it up with roast potatoes?",
        ANCIENT_ROBOT_RIBS = "Not sure those ribs are good for BBQing.",
        ANTCHEST = "A honey maker!",
        ANTQUEEN_THRONE = "There are many cherries hidden in that fruit salad.",
        APORKALYPSE_CLOCK = "Like the knobs on a stove, it must be turned just right.",
        ARMORVORTEXCLOAK = "Marinated in darkness.",
        ARMOR_METALPLATE = "Like an armor made of tin cans.",
        ARMOR_SNAKESKIN = "Function, fashion, and four less living snakes.",
        ARMOR_WEEVOLE = "It still smells of bug.",
        ASPARAGUS_PLANTED = "I should snatch those up.",
        BALLPEIN_HAMMER = "This will tenderize jewels out of statues.",
        BASEFAN = "Good ventilation in the kitchen is an must.",
        BILL = {
            DEAD = "The other white meat.",
            GENERIC = "He could skewer me!",
            SLEEPING = "I'll just sneak by...",
        },
        BILL_QUILL = "It's sharp!",
        BLUNDERBUSS = "The meat is more tender if the death is quick.",
        BOATREPAIRKIT = "A most sensible traveling companion.",
        BOAT_CARGO = "For long distance hauls.",
        BOAT_CORK = "A shaky sea vessel.",
        BOAT_LOGRAFT = "These logs might be better suited to a fire...",
        BOAT_ROW = "Free me from the shackles of this island!",
        BOAT_TORCH = "It's a light so I might \"sea\".",
        BONESTAFF = "It's a refrigeration ray.",
        BRAMBLESPIKE = "Watch those thorns!",
        BRAMBLE_BULB = "Perhaps it would make a nice salad.",
        BRAMBLE_CORE = "It would make a beautiful centerpiece.",
        BURR = "A tiny seed inside.",
        BURR_SAPLING = {
            BURNING = "Can you eat burr?",
            GENERIC = "A fine specimen.",
            PICKED = "It's been harvested already.",
            WITHERED = "Needs some water.",
        },
        CHITIN = "Completely inedible.",
        CITY_LAMP = {
            GENERIC = "It's a small comfort.",
            ON = "What a quaint street lamp.",
        },
        CLAWPALMTREE = "A bit grotesque.",
        CLAWPALMTREE_SAPLING = "It feeds on fertilizer.",
        COFFEE = "Magnifique!",
        COFFEEBEANS = "Glorious!",
        COFFEEBEANS_COOKED = "Could use hot water...!",
        CORK = "If only there were a wine bottle to put this in.",
        CORKCHEST = "Pest control.",
        CUTNETTLE = "Great for clearing the sinuses!",
        DECO_CHAIR_BENCH = "A chair for when company comes over.",
        DECO_CHAIR_CLASSIC = "I wouldn't have to eat standing up!",
        DECO_CHAIR_CORNER = "A nice cozy chair.",
        DECO_CHAIR_FOOTREST = "A place to rest your plate.",
        DECO_CHAIR_HORNED = "Oh fancy!",
        DECO_CHAIR_LOUNGE = "For sleeping off a big meal.",
        DECO_CHAIR_MASSAGER = "I'd rather not.",
        DECO_CHAIR_OTTOMAN = "A place to rest your plate.",
        DECO_CHAIR_ROCKING = "Rocking!",
        DECO_CHAIR_STUFFED = "Ah... luxurious.",
        DISARMING_KIT = "Disarmingly simple to use.",
        DUNGBALL = "Non.",
        DUNGBEETLE = {
            DEAD = "Such is life.",
            GENERIC = "Not how I would spend my days.",
            SLEEPING = "Dormez bien, mon amie.",
            UNDUNGED = "She's fallen.",
        },
        DUNGPILE = {
            GENERIC = "The smell is so strong I can taste it.",
            PICKED = "That was not food safe.",
        },
        FLOWER_RAINFOREST = "Edible?",
        FROGLEGS_POISON = "It be best to cook these before eating.",
        FROGLEGS_POISON_COOKED = "Should I risk eating these now?",
        FROG_POISON = {
            DEAD = "Perhaps I can find a use for those legs.",
            GENERIC = "A beautiful species!",
            SLEEPING = "In temporary hibernation.",
        },
        GASMASKHAT = "I could use this in the smoke house.",
        GLOWFLY = {
            DEAD = "Such a shame. And not even edible.",
            GENERIC = "Light the way, mon amie.",
            SLEEPING = "May your dreams be full of light.",
        },
        GLOWFLY_COCOON = "It's wrapped itself like a cabbage roll.",
        GOLDENMACHETE = "Fancy slicer.",
        GOLDPAN = "I have better pans.",
        GOLD_DUST = "Perhaps that nosy fellow would like to eat this.",
        GRABBING_VINE = "How eerie.",
        GRASS_TALL = {
            BURNING = "Smells like a cookout!",
            GENERIC = "Too long to cut with my hands.",
            PICKED = "It will have to grow back.",
        },
        HALBERD = "I dislike fighting.",
        HANGING_VINE = "How eerie.",
        HIPPOPOTAMOOSE = "Those horns would make great roasting spits.",
        HIPPO_ANTLER = "It's too bad I couldn't use this to roast wieners on.",
        ICEDTEA = "Ah. Refreshing.",
        INFUSED_IRON = "Iron marinated in magic.",
        IRON = "I wonder what I could cook up with this.",
        KINGFISHER = {
            DEAD = "A shame it died so young.",
            GENERIC = "That beak would be excellent for spearing food.",
            SLEEPING = "In a food coma, perhaps.",
        },
        LAWNORNAMENT = {
            BURNING = "A fine place for a barbeque.",
            BURNT = "It's been deep fried.",
            GENERIC = "How charming!",
        },
        LIFEPLANT = "It looks hungry.",
        LILYPAD = "I doubt it has much flavor.",
        LIVING_ARTIFACT = "Will it help me be a better cook?",
        LOTUS = "Mmm, lotus root...",
        LOTUS_FLOWER = "I should cook something up with this.",
        LOTUS_FLOWER_COOKED = "A fine delicacy!",
        MACHETE = "I could chop many an onion with this!",
        MAGNIFYING_GLASS = "To see the finest details.",
        MANDRAKEHOUSE = "Those deafening root vegetables live in there.",
        MANDRAKEMAN = "Loud root vegetable.",
        MEAN_FLYTRAP = {
            DEAD = "If only it were edible...",
            GENERIC = "I'm not plant food!",
            SLEEPING = "I don't want to wake it.",
        },
        METALPLATEHAT = "I prefer a chef hat.",
        NECTAR_POD = "The ingredients for honey making.",
        OBSIDIAN = "Hot rock!",
        OINC = "I can purchase fresh groceries with this.",
        OINC10 = "Only the finest to eat tonight!",
        OINC100 = "Mon dieu! Think of the groceries this could buy!",
        PANGOLDEN = "Already has a nice golden braise.",
        PARROT_BLUE = {
            DEAD = "Demised.",
            GENERIC = "Hello Polly!",
            SLEEPING = "It's just resting.",
        },
        PEAGAWK = {
            DEAD = "A pointless death.",
            GENERIC = "Those feathers would make a nice table centerpiece.",
            SLEEPING = "Those eyes are unnerving.",
        },
        PEAGAWKFEATHER = "It's quite soft.",
        PEAGAWK_BUSH = "It's a bright blue bush.",
        PIGEON = {
            DEAD = "Squab?",
            GENERIC = "Pigeon pie? No, perhaps not.",
            SLEEPING = "Perhaps a feast of seeds has worn it out.",
        },
        PIGGHOST = "I've no quarrel with the dead.",
        PIGHOUSE_CITY = {
            BURNING = "Fricasseed.",
            GENERIC = "It's a simple life.",
        },
        PIGHOUSE_FARM = {
            BURNING = "A little too well-done!",
            GENERIC = "Farm fresh.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Blackened!",
            GENERIC = "Mining is a dangerous job.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "You know, you might benefit from a nice farmer's market here.",
            SLEEPING = "I too get drowsy after a good meal.",
        },
        PIGMAN_QUEEN = "What feasts she must have...",
        PIGMAN_ROYALGUARD = {
            GENERIC = "I'm not looking for trouble, mon amie.",
            SLEEPING = "Sleep well,  mon amie.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "It's been flambed!",
            GENERIC = "That's a tall tower!",
        },
        PIG_PALACE = "I wonder what the kitchen is like.",
        PIG_RUINS_ARTICHOKE = "Clearly a food loving culture dwelled here.",
        PIG_RUINS_HEAD = "I suppose pigs lived here once.",
        PIG_RUINS_IDOL = "Those pig fellows might like that.",
        PIG_RUINS_PLAQUE = "Just a pinch of statue.",
        PIG_SHOP_CITYHALL = {
            BURNING = "C'est horrible.",
            GENERIC = "A place of civic pride.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Fricasseed!",
            GENERIC = "I never thought of a life in politics.",
        },
        PIG_SHOP_DELI = {
            BURNING = "Mon dieu!",
            GENERIC = "Ah. Yes. A restaurant of sorts.",
        },
        PIKO = {
            DEAD = "An unfortunate end.",
            GENERIC = "Bonjour, mon amie.",
            SLEEPING = "Dreaming of nuts, no doubt.",
        },
        PIKO_ORANGE = {
            DEAD = "An unfortunate end.",
            GENERIC = "I prefer English Breakfast.",
            SLEEPING = "Dreaming of nuts, no doubt.",
        },
        POISONBALM = "I fear that it tastes as terrible as it smells.",
        PROP_DOOR = "Is there a kitchen in there?",
        PUGALISK = "Pardon me, Monsieur.",
        PUGALISK_CORPSE = "I can't roast this marrow.",
        PUGALISK_FOUNTAIN = "Locally sourced water, free of impurities.",
        PUGALISK_RUINS_PILLAR = "Not very hearty.",
        PUGALISK_SKULL = "I won't use this for soup.",
        PUGALISK_TRAP_DOOR = "I'm getting a bad feeling about that.",
        RABID_BEETLE = {
            DEAD = "A shame. Not even edible.",
            GENERIC = "It is like me when I am hungry.",
            SLEEPING = "What a curious way to sleep!",
        },
        RADISH = "I'm thinking a nice summer salad.",
        RADISH_COOKED = "Roasted with a touch of olive oil.",
        RADISH_PLANTED = "What ravishing radishes!",
        RADISH_SEEDS = "Nice fresh vegetables for a salad.",
        RAINFORESTTREE = {
            BURNING = "Perhaps I could smoke a nice cutlet on it?",
            BURNT = "A little too crispy for my taste.",
            CHOPPED = "Sacrificed for a barbeque pit.",
            GENERIC = "Ach! No mangoes!",
        },
        RAINFORESTTREE_ROT = "It's spoiled.",
        REEDS_WATER = "I can think of plenty of uses for those.",
        RELIC_1 = "What strange textures.",
        RELIC_2 = "An odd little fellow.",
        RELIC_3 = "I bet it picks up all sorts of aromas.",
        RELIC_4 = "This would make a pretty centerpiece.",
        RELIC_5 = "If only it were a real truffle.",
        ROCK_BASALT = "I could serve lunch on that rock.",
        ROCK_FLIPPABLE = "There may be some protein under there.",
        ROOTTRUNK_CHILD = "Mon dieu! What a wonderful time saver!",
        SAIL_SNAKESKIN = "Perhaps I'll sail to a land of spices.",
        SCORPION = {
            DEAD = "Such senseless violence.",
            GENERIC = "Fried scorpion? Too dangerous.",
            SLEEPING = "Currently harmless.",
        },
        SEDIMENTPUDDLE = "It's been seasoned with gold.",
        SHEARS = "Good for cutting hedges and grass.",
        SMELTER = {
            BURNT = "I'm better at cooking food than metal.",
            COOKING_SHORT = "The flavors are fusing.",
            DONE = "Fresh out of the oven! Be careful with the scalding.",
            EMPTY = "'Smelt' bad, if you ask me.",
        },
        SNAKEBONESOUP = "A slight variation on a cherished recipe.",
        SNAKEOIL = "Why can't you be olive oil?",
        SNAKESKIN = "Would make a haute apron.",
        SNAKESKINHAT = "Tres cool.",
        SNAKE_AMPHIBIOUS = "Yeeouch. I'll keep away from him.",
        SNAKE_BONE = "Bones always make for a good broth.",
        SPIDER_MONKEY = {
            DEAD = "Gone to the big banana grove in the sky.",
            GENERIC = "I've no interest in monkey business.",
            SLEEPING = "It's no harm to anyone right now.",
        },
        SPIDER_MONKEY_NEST = "I'll bet there's no kitchen in there.",
        SPIDER_MONKEY_TREE = "Those strange monkeys must hang out here.",
        TEA = "Tea! Oh how I missed you!",
        TEATREE = "I could to so many things with tea tree leaves.",
        TEATREE_NUT = "More useful as medicine than in my recipe.",
        TEATREE_NUT_COOKED = "Not the finest of fine foods.",
        TEATREE_NUT_SAPLING = "Keep growing. You'll get there.",
        THUNDERHAT = "Not a chef hat but good for a night out.",
        TOUCAN = "You are all nose.",
        TREE_PILLAR = "What a marvel.",
        TUBERTREE = "I do like tubers.",
        TUBER_BLOOM_CROP = "The perfect ripeness.",
        TUBER_BLOOM_CROP_COOKED = "Something I just whipped up.",
        TUBER_CROP = "Ah. It is not ripe yet.",
        TUBER_CROP_COOKED = "Not my best work.",
        TURF_COBBLEROAD = "It's like an ingredient for the road.",
        TURF_DEEPRAINFOREST = "It's like an ingredient for the ground.",
        TURF_DEEPRAINFOREST_NOCANOPY = "It's like an ingredient for the ground.",
        TURF_FIELDS = "It's like an ingredient for the ground.",
        TURF_FOUNDATION = "It's like an ingredient for the ground.",
        TURF_GASJUNGLE = "It's like an ingredient for the ground.",
        TURF_LAWN = "It's like an ingredient for the ground.",
        TURF_MOSS = "It's like an ingredient for the ground.",
        TURF_PAINTED = "It's like an ingredient for the ground.",
        TURF_PIGRUINS = "It's like an ingredient for the ruins.",
        TURF_PLAINS = "It's like an ingredient for the ground.",
        TURF_RAINFOREST = "It's like an ingredient for the ground.",
        VAMPIREBAT = {
            DEAD = "It has met its untimely end.",
            GENERIC = "I assure you, I taste horrible!",
            SLEEPING = "Peaceful for now.",
        },
        VAMPIREBATCAVE = "Not the best place to hide, I think.",
        VENOMGLAND = "The worst kind of gland!",
        VENUS_STALK = "Possesses a flavor reminiscent of artichoke hearts.",
        VINE = "Not a single grape on it...",
        WALKINGSTICK = "I'm out to forage!",
        WATERDROP = "The water of life.",
        WEEVOLE = "Shoo! Go away!",
        WEEVOLE_CARAPACE = "The crust of a bug.",
        WINDOW_GREENHOUSE = "If only I could grow greenhouse fresh produce.",
        WINDOW_LARGE_SQUARE = "Lets in lots of sun.",
        WINDOW_LARGE_SQUARE_CURTAIN = "A fine window.",
        WINDOW_ROUND = "Ah. The outside!",
        WINDOW_ROUND_BURLAP = "I'll have to change it later.",
        WINDOW_ROUND_CURTAINS_NAILS = "Flavorless decor.",
        WINDOW_SMALL_PEAKED = "Some sun.",
        WINDOW_SMALL_PEAKED_CURTAIN = "A fine window.",
        WINDOW_TALL = "Lets in lots of sun.",
        WINDOW_TALL_CURTAIN = "Yummy.",
    },
}
