return {
    ANNOUNCE_DEHUMID = {
        "Ah, I feel better now.",
    },
    ANNOUNCE_HAYFEVER = "Ugh! My allergies!",
    ANNOUNCE_HAYFEVER_OFF = "I think... my nose has cleared!",
    ANNOUNCE_PICKPOOP = {
        "Blech!",
        "Blagh!",
        "Beurk!",
    },
	ANNOUNCE_PUGALISK_INVULNERABLE = {
        "If only I had a shell cracker!",
        "Won't break there.",
        "I need to find a weak spot."
    },
    ANNOUNCE_SNEEZE = "Atchoum!",
    ANNOUNCE_TOO_HUMID = {
        "Mon dieu! This %s is humid.",
        "Whew. This %s is hot.",
    },
    DESCRIBE = {
        ALLOY = "Metal cooked to perfection.",
        APORKALYPSE_CLOCK = "Like the knobs on a stove, it must be turned just right.",
        ARMOR_METALPLATE = "Like an armor made of tin cans.",
        ARMOR_WEEVOLE = "It still smells of bug.",
        ASPARAGUS_PLANTED = "I should snatch those up.",
        BASEFAN = "Good ventilation in the kitchen is an must.",
        BONESTAFF = "It's a refrigeration ray.",
        CHITIN = "Completely inedible.",
        COFFEE = "Magnifique!",
        COFFEEBEANS = "Glorious!",
        COFFEEBEANS_COOKED = "Could use hot water...!",
        CUTNETTLE = "Great for clearing the sinuses!",
        DUNGBALL = "Non.",
        DUNGBEETLE = {
            DEAD = "Such is life.",
            GENERIC = "Not how I would spend my days.",
            SLEEPING = "Dormez bien, mon amie.",
            UNDUNGED = "She's fallen.",
        },
        DUNGPILE = {
            GENERIC = "The smell is so strong I can taste it.",
            PICKED = "That was not food safe.",
        },
        FLOWER_RAINFOREST = "Edible?",
        GLOWFLY = {
            DEAD = "Such a shame. And not even edible.",
            GENERIC = "Light the way, mon amie.",
            SLEEPING = "May your dreams be full of light.",
        },
        GLOWFLY_COCOON = "It's wrapped itself like a cabbage roll.",
        GOLDENMACHETE = "Fancy slicer.",
        GOLDPAN = "I have better pans.",
        GOLD_DUST = "Perhaps that nosy fellow would like to eat this.",
        GRABBING_VINE = "How eerie.",
        GRASS_TALL = {
            BURNING = "Smells like a cookout!",
            GENERIC = "Too long to cut with my hands.",
            PICKED = "It will have to grow back.",
        },
        HALBERD = "I dislike fighting.",
        HANGING_VINE = "How eerie.",
        ICEDTEA = "Ah. Refreshing.",
        IRON = "I wonder what I could cook up with this.",
        MACHETE = "I could chop many an onion with this!",
        PANGOLDEN = "Already has a nice golden braise.",
        PEAGAWK = {
            DEAD = "A pointless death.",
            GENERIC = "Those feathers would make a nice table centerpiece.",
            SLEEPING = "Those eyes are unnerving.",
        },
        PEAGAWKFEATHER = "It's quite soft.",
        PEAGAWK_BUSH = "It's a bright blue bush.",
        PIKO = {
            DEAD = "An unfortunate end.",
            GENERIC = "Bonjour, mon amie.",
            SLEEPING = "Dreaming of nuts, no doubt.",
        },
        PIKO_ORANGE = {
            DEAD = "An unfortunate end.",
            GENERIC = "I prefer English Breakfast.",
            SLEEPING = "Dreaming of nuts, no doubt.",
        },
        PUGALISK = "Pardon me, Monsieur.",
        PUGALISK_CORPSE = "I can't roast this marrow.",
        PUGALISK_FOUNTAIN = "Locally sourced water, free of impurities.",
        PUGALISK_RUINS_PILLAR = "Not very hearty.",
        PUGALISK_SKULL = "I won't use this for soup.",
        PUGALISK_TRAP_DOOR = "I'm getting a bad feeling about that.",
        RABID_BEETLE = {
            DEAD = "A shame. Not even edible.",
            GENERIC = "It is like me when I am hungry.",
            SLEEPING = "What a curious way to sleep!",
        },
        SEDIMENTPUDDLE = "It's been seasoned with gold.",
        SHEARS = "Good for cutting hedges and grass.",
        SMELTER = {
            BURNT = "I'm better at cooking food than metal.",
            COOKING_SHORT = "The flavors are fusing.",
            DONE = "Fresh out of the oven! Be careful with the scalding.",
            EMPTY = "'Smelt' bad, if you ask me.",
        },
        SNAKE_BONE = "Bones always make for a good broth.",
        SNAKEBONESOUP = "A slight variation on a cherished recipe.",
        TEA = "Tea! Oh how I missed you!",
        TEATREE = "I could to so many things with tea tree leaves.",
        TEATREE_NUT = "More useful as medicine than in my recipe.",
        TEATREE_NUT_COOKED = "Not the finest of fine foods.",
        TEATREE_NUT_SAPLING = "Keep growing. You'll get there.",
        TREE_PILLAR = "What a marvel.",
        WEEVOLE = "Shoo! Go away!",
        WEEVOLE_CARAPACE = "The crust of a bug.",
    },
}
