return {
    ANNOUNCE_DEHUMID = {
        "The haze has lifted.",
    },
    ANNOUNCE_HAYFEVER = "Mine nostrils chafe with itchiness!",
    ANNOUNCE_HAYFEVER_OFF = "The smoke has cleared!",
    ANNOUNCE_PICKPOOP = {
        "Alas!",
        "Alack!",
        "It disturbs mine soul!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "It is nigh on invulnerable!",
        "Its hide is unyielding!",
        "I shall beat you yet!"
    },
    ANNOUNCE_SNEEZE = "aaAAAH...cho!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is crushing my spirit.",
        "This %s burns like Sol.",
    },
    DESCRIBE = {
        ALLOY = "A metal worthy of the Sons of Ivaldi.",
        APORKALYPSE_CLOCK = "It controls Ragnarok!",
        ARMOR_METALPLATE = "Armor worthy of my deeds.",
        ARMOR_WEEVOLE = "Armor made from the skin of my enemy.",
        ASPARAGUS_PLANTED = "Useless vegetation!",
        BASEFAN = "Conquers the heat!",
        BONESTAFF = "Prepare to be stunned by my gaze!",
        CHITIN = "The feeble armor of the bug.",
        COFFEE = "Bitter and pulse-pounding.",
        COFFEEBEANS = "I take mine black.",
        COFFEEBEANS_COOKED = "It smells energizing.",
        CUTNETTLE = "Its smell has vanquish mine sinuses.",
        DUNGBALL = "What sickness is this?",
        DUNGBEETLE = {
            DEAD = "She has fallen in battle.",
            GENERIC = "A mounted foe!",
            SLEEPING = "May her dreams be as foul as the spheres she rides.",
            UNDUNGED = "She has been thrown from her foul mount!",
        },
        DUNGPILE = {
            GENERIC = "Surely this came from a giant's backside!",
            PICKED = "It has been picked through.",
        },
        FLOWER_RAINFOREST = "A blossom most lovely.",
        GLOWFLY = {
            DEAD = "Alas, it is dead.",
            GENERIC = "Fly free, small friend.",
            SLEEPING = "A slumber consumes it.",
        },
        GLOWFLY_COCOON = "It has armored itself for sleep.",
        GOLDENMACHETE = "I shall swing you with pride.",
        GOLDPAN = "It will vanquish the pieces of tiny gold!",
        GOLD_DUST = "Golden dust.",
        GRABBING_VINE = "Ropes hang from the heavens!",
        GRASS_TALL = {
            BURNING = "It burns!",
            GENERIC = "Surely it is the grass of Jotunheim!",
            PICKED = "I have defeated it!",
        },
        HALBERD = "Tis no spear, yet is still valorous!",
        HANGING_VINE = "Ropes hang from the heavens!",
        ICEDTEA = "It contains no the meat!",
        IRON = "Material for metalwork.",
        MACHETE = "A fine length of blade.",
        PANGOLDEN = "Surely a cousin of Gullinbursti!",
        PEAGAWK = {
            DEAD = "Even in death its eyes stare into my soul.",
            GENERIC = "It has the eyes of Odin.",
            SLEEPING = "I cannot tell if it is awake or sleep.",
        },
        PEAGAWKFEATHER = "A priceless beauty.",
        PEAGAWK_BUSH = "Do you think you can hide from me?",
        PIKO = {
            DEAD = "It has fallen.",
            GENERIC = "Do you crave battle?",
            SLEEPING = "It slumbers unwisely.",
        },
        PIKO_ORANGE = {
            DEAD = "It has fallen.",
            GENERIC = "It is made of meat!",
            SLEEPING = "It slumbers unwisely.",
        },
        PUGALISK = "Have at thee!",
        PUGALISK_CORPSE = "A token from the battlefield.",
        PUGALISK_FOUNTAIN = "A fountain of Idunn!",
        PUGALISK_RUINS_PILLAR = "Not worthy of Valhalla's halls.",
        PUGALISK_SKULL = "I have vanquished a mighty foe!",
        PUGALISK_TRAP_DOOR = "I'll not be fooled!",
        RABID_BEETLE = {
            DEAD = "It has died in battle.",
            GENERIC = "Evil beast. You have met your match!",
            SLEEPING = "Slumber consumes it!",
        },
        SEDIMENTPUDDLE = "Its tiny gold pieces will be mine!",
        SHEARS = "A weapon for use against a mighty hedge!",
        SMELTER = {
            BURNT = "My role is more warrior than artizan.",
            COOKING_SHORT = "Patience is an essential quality of a good fighter.",
            DONE = "Now make me a sharp edge!",
            EMPTY = "The tools of dwarves.",
        },
        SNAKE_BONE = "The bones of my enemy!",
        SNAKEBONESOUP = "A meaty broth!",
        TEA = "I shall not consume it!",
        TEATREE = "This tree is adequate.",
        TEATREE_NUT = "Its lack of meat offends me.",
        TEATREE_NUT_COOKED = "Even touched by fire, I will not consume it!",
        TEATREE_NUT_SAPLING = "A tree still weak with youth.",
        TREE_PILLAR = "Surely I stand before Yggdrasil!",
        WEEVOLE = "A pest upon this land!",
        WEEVOLE_CARAPACE = "The skin of my enemy.",
    },
}
