return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "My vessel is renewed!",
        },
    },
    ANNOUNCE_BOAT_DAMAGED = "My vessel is wounded!",
    ANNOUNCE_BOAT_SINKING = "The sea pulls me toward Hel!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "These black depths will soon claim me!",
    ANNOUNCE_DEHUMID = {
        "The haze has lifted.",
    },
    ANNOUNCE_HAYFEVER = "Mine nostrils chafe with itchiness!",
    ANNOUNCE_HAYFEVER_OFF = "The smoke has cleared!",
    ANNOUNCE_PICKPOOP = {
        "Alas!",
        "Alack!",
        "It disturbs mine soul!",
    },
    ANNOUNCE_SNEEZE = "aaAAAH...cho!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is crushing my spirit.",
        "This %s burns like Sol.",
    },
    ANNOUNCE_WAVE_BOOST = "Carry me forth!",
    DESCRIBE = {
        ALLOY = "A metal worthy of the Sons of Ivaldi.",
        APORKALYPSE_CLOCK = "It controls Ragnarok!",
        ARMOR_METALPLATE = "Armor worthy of my deeds.",
        ARMOR_WEEVOLE = "Armor made from the skin of my enemy.",
        ASPARAGUS_PLANTED = "Useless vegetation!",
        BASEFAN = "Conquers the heat!",
        BOATREPAIRKIT = "Most sensible cargo.",
        BOAT_CARGO = "A boat fit for a long journey.",
        BOAT_CORK = "More like a stage prop than a viking vessel.",
        BOAT_LOGRAFT = "You will not carry me far, but you will carry me.",
        BOAT_ROW = "Rowing is in my blood.",
        BOAT_TORCH = "The night sea is alight!",
        CHITIN = "The feeble armor of the bug.",
        COFFEE = "Bitter and pulse-pounding.",
        COFFEEBEANS = "I take mine black.",
        COFFEEBEANS_COOKED = "It smells energizing.",
        CUTNETTLE = "Its smell has vanquish mine sinuses.",
        DUNGBALL = "What sickness is this?",
        DUNGBEETLE = {
            DEAD = "She has fallen in battle.",
            GENERIC = "A mounted foe!",
            SLEEPING = "May her dreams be as foul as the spheres she rides.",
            UNDUNGED = "She has been thrown from her foul mount!",
        },
        DUNGPILE = {
            GENERIC = "Surely this came from a giant's backside!",
            PICKED = "It has been picked through.",
        },
        FLOWER_RAINFOREST = "A blossom most lovely.",
        GLOWFLY = {
            DEAD = "Alas, it is dead.",
            GENERIC = "Fly free, small friend.",
            SLEEPING = "A slumber consumes it.",
        },
        GLOWFLY_COCOON = "It has armored itself for sleep.",
        GOLDENMACHETE = "I shall swing you with pride.",
        GOLDPAN = "It will vanquish the pieces of tiny gold!",
        GOLD_DUST = "Golden dust.",
        GRABBING_VINE = "Ropes hang from the heavens!",
        GRASS_TALL = {
            BURNING = "It burns!",
            GENERIC = "Surely it is the grass of Jotunheim!",
            PICKED = "I have defeated it!",
        },
        HALBERD = "Tis no spear, yet is still valorous!",
        HANGING_VINE = "Ropes hang from the heavens!",
        ICEDTEA = "It contains no the meat!",
        IRON = "Material for metalwork.",
        LILYPAD = "A leaf of the water.",
        LOTUS = "Freya looks down upon this.",
        LOTUS_FLOWER = "It possesses Freya's great beauty.",
        MACHETE = "A fine length of blade.",
        PANGOLDEN = "Surely a cousin of Gullinbursti!",
        PEAGAWK = {
            DEAD = "Even in death its eyes stare into my soul.",
            GENERIC = "It has the eyes of Odin.",
            SLEEPING = "I cannot tell if it is awake or sleep.",
        },
        PEAGAWKFEATHER = "A priceless beauty.",
        PEAGAWK_BUSH = "Do you think you can hide from me?",
        PIKO = {
            DEAD = "It has fallen.",
            GENERIC = "Do you crave battle?",
            SLEEPING = "It slumbers unwisely.",
        },
        PIKO_ORANGE = {
            DEAD = "It has fallen.",
            GENERIC = "It is made of meat!",
            SLEEPING = "It slumbers unwisely.",
        },
        RABID_BEETLE = {
            DEAD = "It has died in battle.",
            GENERIC = "Evil beast. You have met your match!",
            SLEEPING = "Slumber consumes it!",
        },
        SAIL_SNAKESKIN = "A sail made of murder!",
        SEDIMENTPUDDLE = "Its tiny gold pieces will be mine!",
        SHEARS = "A weapon for use against a mighty hedge!",
        SMELTER = {
            BURNT = "My role is more warrior than artizan.",
            COOKING_SHORT = "Patience is an essential quality of a good fighter.",
            DONE = "Now make me a sharp edge!",
            EMPTY = "The tools of dwarves.",
        },
        SNAKESKIN = "A snake has slipped its skin. With a little help...",
        TEA = "I shall not consume it!",
        TEATREE = "This tree is adequate.",
        TEATREE_NUT = "Its lack of meat offends me.",
        TEATREE_NUT_COOKED = "Even touched by fire, I will not consume it!",
        TEATREE_NUT_SAPLING = "A tree still weak with youth.",
        TREE_PILLAR = "Surely I stand before Yggdrasil!",
        WEEVOLE = "A pest upon this land!",
        WEEVOLE_CARAPACE = "The skin of my enemy.",
    },
}
