return {
    ACTIONFAIL =
      {
        SHOP = {
            GENERIC = "Not for sale.",
            CANTPAY = "Hmmph. Overpriced if you ask me.",
        },
        USEDOOR =
         {
            GENERIC = "It refuses to open for me.",
            LOCKED = "I'll get it open somehow.",
          },
},
    -- PORKLAND SPEECH
    ANNOUCE_UNDERLEAFCANOPY = "It is wretchedly dark beneath the trees.",
    ANNOUCE_ALARMOVER = "I am safe once again.",
    ANNOUCE_BATS = "How apropos.",
    ANNOUCE_OTHERWORLD_DEED = "I suppose I could use it as a summer home.",
    ANNOUNCE_TOOLCORRODED = "This place is toxic to tools.",
    ANNOUNCE_TURFTOOHARD = "It's immovable.",
    ANNOUNCE_GAS_DAMAGE = "Hack! Cough! Ack!",

    ANNOUNCE_SNEEZE = "ah...CHOOOO!",
    ANNOUNCE_HAYFEVER = "Ugh. Allergies.",
    ANNOUNCE_HAYFEVER_OFF = "Ah... I can breathe again.",
    ANNOUNCE_PICKPOOP = {"Bah!","Ew!","Gah!","Filth!"},
    ANNOUNCE_TOO_HUMID = {"This %s is too much.","This %s is hotter than I like."},
    ANNOUNCE_DEHUMID = {"Ah! That feels better."},
    ANNOUNCE_PUGALISK_INVULNERABLE = {"That hide is too tough.", "That's not going to work.", "I need to be more strategic."},
    ANNOUNCE_MYSTERY_FOUND = "There's definitely something...",
    ANNOUNCE_MYSTERY_NOREWARD = "That was disappointing.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "You can't hide anything from me.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "That was a waste of my time.",
    ANNOUNCE_TAXDAY = "I require compensation for not destroying this town.",
    ANNOUNCE_HOUSE_DOOR = "Those bureaucratic pigs demand I have a permit first.",
    ANNOUNCE_ROOM_STUCK = "I don't want to be trapped forever. Again.",
    ANNOUNCE_NOTHING_FOUND = "This magical object isn't picking up anything nearby.",
    ANNOUNCE_SUITUP = "I AM SUPERIOR!",
    DESCRIBE = {
        MACHETE = "Truthfully I was always a hack.",
        GOLDENMACHETE = "I've always wanted to hack things in luxury.",
        VINE = "It's twisted and gnarled.",
        BAMBOO = "I have several ideas in mind for this.",
        FABRIC = "I've fashioned the bamboo into something useful.",
        ARMOR_SNAKESKIN = "Quite dapper!",
        SNAKESKIN = "The texture is delectable.",
        SNAKESKINHAT = "Quite dashing, actually.",
        SNAKESKINSAIL = "For ease of travel.",
        TURF_SNAKESKINFLOOR = "It appears to be some turf.",
        SNAKEOIL = "Perhaps I could turn a profit with this.",
        SNAKE_AMPHIBIOUS = "An amphibian after my own heart.",
        BOAT_TORCH = "Sailing at night seems unsafe, but this makes it somewhat better.",
        BOATREPAIRKIT = "It will hold off my vessel's inevitable decay.",
        CARGOBOAT = "Ah, plenty of room to breathe.",
        ROWBOAT = "Manually operated. A pity.",
        LOGRAFT = "It seems like there should be regulations against this.",
        VENOMGLAND = "Could this be the cure?",

        --PORKLAND SPEECH STARTS HERE
        PIG_PALACE = "A little garish for my taste.",
        PIGMAN_QUEEN = "She does not smell particularly royal.",
        PIG_SCEPTER = "I shall be a great leader.",
        PIGCROWNHAT = "I was meant to be king.",
        PIG_SHOP_FLORIST = {
            GENERIC = "Every breastpocket needs a fresh rose.",
            BURNING = "I'll have to get my roses elsewhere.",
        },
        PIG_SHOP_GENERAL = {
            GENERIC = "A common boutique to purchase common goods.",
            BURNING = "Generally, I'd say it's on fire.",
        },
        PIG_SHOP_HOOFSPA = {
            GENERIC = "Seems even filthy pigs need the occasional pampering.",
            BURNING = "A pity.",
        },
        PIG_SHOP_PRODUCE = {
            GENERIC = "A simple grocer.",
            BURNING = "I do fancy roast vegetables.",
        },
        PIG_SHOP_ARCANE = {
            GENERIC = "Ahh... more my style.",
            BURNING = "Agh! Put it out! Someone!",
        },
        PIG_SHOP_WEAPONS = {
            GENERIC = "Well, well, well...",
            BURNING = "Live by the sword, die by the flame.",
        },
        PIG_SHOP_HATSHOP = {
            GENERIC = "I may have use for a millinery.",
            BURNING = "Everything burns.",
        },
        PIG_SHOP_ACADEMY = {
            GENERIC = "Hmmm... The are a lot of artifacts in there.",
            BURNING = "Not my problem.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "Such stunning beauty.",
            SLEEPING = "She's definitely needs more beauty sleep.",
        },
        PIGMAN_ROYALGUARD = {
            GENERIC = "Move along.",
            SLEEPING = "Completely vulnerable.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "You do have some interesting objects in here.",
            SLEEPING = "Lazy.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "A man who understands the power of a tailored suit.",
            SLEEPING = "Those in power should sleep with one eye open.",
        },
        PIGMAN_BANKER = {
            GENERIC = "A distinguished fellow. Relatively speaking.",
            SLEEPING = "I imagine those Banker's hours are exhausting.",
        },
        PIGMAN_MINER = {
            GENERIC = "He is absolutely covered in soot.",
            SLEEPING = "Typical layabout.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "That is no gentleman.",
            SLEEPING = "He should fix his lethargy.",
        },
        PIGMAN_FARMER = {
            GENERIC = "He smells of farming and hard labor.",
            SLEEPING = "How can he sleep with the smell of manure everywhere?",
        },
        PIGMAN_FLORIST = {
            GENERIC = "She tends to the flowers.",
            SLEEPING = "Not required to sleep in the flowerbeds, I see.",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "That's the shopkeep.",
            SLEEPING = "Am I supposed to attend to myself?.",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "A gal after my own heart.",
            SLEEPING = "I hope you have nightmares.",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "I'm looking for something subtle, yet stylish.",
            SLEEPING = "How pedestrian.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "I better hurry this up, he looks like he could drop at any time.",
            SLEEPING = "Ugh.",
        },
        PIGMAN_HUNTER =
          {
            GENERIC = "I would like to peruse your deadliest weapons, please.",
            SLEEPING = "An incredible inconvenience.",
        },
        RECONSTRUCTION_PROJECT = {
            SCAFFOLD = "They're rebuilding, it seems.",
            RUBBLE = "Natural wear and tear.",
        },
        TREE_PILLAR = "This tree is unusually large.",
        PIGHOUSE_CITY = {
            GENERIC = "I presume it's a pigsty inside.",
            BURNING = "That will only lead to improvement.",
        },
        PIGHOUSE_MINE = {
            GENERIC = "Little pig, little pig, let me in.",
            BURNING = "It's in flames!",
        },
        PIGHOUSE_FARM = {
            GENERIC = "I've no interest in a commoner's domicile.",
            BURNING = "A flaming reminder of Life's inequities.",
        },
        PIG_GUARD_TOWER = {
            GENERIC = "There's an appeal in overseeing the masses.",
            BURNING = "A watchtower no more.",
        },
        CITY_LAMP = {
            GENERIC = "A welcome sign of civilization.",
            ON = "It eases my mind.", --off
        },
        DUNGBEETLE = {
            GENERIC = "What a filthy creature.",
            UNDUNGED = "Sans dungball, I see.",
            SLEEPING = "The time is right to strike.",
            DEAD = "It has come to a feculent end.",
        },
        DUNGBALL = "I refuse to touch that.",
        DUNGPILE = {
            GENERIC = "Blech.",
            PICKED = "That was simply undignified.",
        },
        PIGEON = {
            GENERIC = "Filthy.",
            SLEEPING = "Enjoy your grimy slumber.",
            DEAD = "As filthy in death as it was in life.",
        },
        SPIDER_MONKEY = {
            GENERIC = "I command you to stay back.",
            SLEEPING = "Now is the time to make my escape.",
            DEAD = "It has met its demise.",
        },
        SPIDER_MONKEY_TREE = "Filthy creatures reside within.",
        SPIDER_MONKEY_NEST = "I would rather not disturb it.",
        TOPIARY = "It is rather crudely cut.",
        LAWNORNAMENT = {
            GENERIC = "Ah, a touch of civility. What a welcome change.",
            BURNING = "Someone's a critic.",
            BURNT = "A waste of fine culture.",
        },
        HEDGE = {
            GENERIC = "Simple.",
            SHAVEABLE = "No one thought to trim this hedge?",
            BURNING = "I never tire of watching destruction.",
            BURNT = "A shame.",
        },
        RAINFORESTTREE = {
            GENERIC = "Like no tree I've seen before.",
            CHOPPED = "It's been chopped down.",
            BURNING = "It burns like any tree.",
            BURNT = "A blackened shell of its former self.",
        },
        FLOWER_RAINFOREST = "It's no rose.",
        HALBERD = "A blade as sharp as my wit.",
        CHICKEN = {
            GENERIC = "Foul fowl.",
            SLEEPING = "Dreadful bird dreaming dreadfully.",
            DEAD = "No one will grieve you, fowl beast.",
        },
        GRASS_TALL = {
            GENERIC = "Oh, joyous occasion. I've found grass.",
            PICKED = "I don't require any more grass, thank you.",
            BURNING = "Well, there you have it.",
        },
        GLOWFLY = {
            GENERIC = "Disgusting, but helpful.",
            SLEEPING = "That light is rather too lethargic.",
            DEAD = "Lights out.",
        },
        GLOWFLY_COCOON = "Ah, metamorphosis...",
        CHITIN = "We all have our defenses.",
        HANGING_VINE = "I know the ropes.",
        GRABBING_VINE = "I know the ropes.",
        VENUS_STALK = "All stalk and no action.",
        WALKINGSTICK = "Much easier on my knees.",
        ADULT_FLYTRAP = {
            GENERIC = "That's one handsome abomination.",
            SLEEPING = "A nefarious napper.",
            DEAD = "It's dead.",
        },
        MEAN_FLYTRAP = {
            GENERIC = "Do not tangle with me!",
            SLEEPING = "I must endeavor not to wake it.",
            DEAD = "Eradicated.",
        },
        SNAPDRAGON = {
            GENERIC = "I have no quarrel with you. Yet.",
            SLEEPING = "Good. I hope it stays asleep.",
            DEAD = "Everything dies, it seems.",
        },
        LILYPAD = "A massive pond leaf.",
        ZEB = {
            GENERIC = "I prefer pinstripes.",
            SLEEPING = "Seems better suited to laying down.",
            DEAD = "Expired.",
        },
        SCORPION = {
            GENERIC = "You'll not be stinging me.",
            SLEEPING = "Don't wake up, cur.",
            DEAD = "It has felt the cruel sting of death.",
        },
        PEAGAWK = {
            GENERIC = "What a regal-looking beast.",
            SLEEPING = "It is eye-dol.",
            DEAD = "It's beauty has been snuffed out forever.",
        },
        PEEKHEN = {
            GENERIC = "You look suspiciously like dinner.",
            SLEEPING = "It is much easier to kill like this.",
            DEAD = "Met a fine end.",
        },
        PEAGAWKFEATHERHAT = "This is a look only I can pull off.",
        PEAGAWK_BUSH = "I've my suspicions about that bush.",
        PEAGAWKFEATHER = "What finery.",
        PEAGAWKFEATHER_PRISM = "This would look great in a hat.",
        ANTMAN = {
            GENERIC = "What a hideous creature.",
            SLEEPING = "Still grotesque.",
            DEAD = "Serves it right for being so ugly.",
        },
        ANTHILL = "I've a mind to make a molehill of this.",
        ANTMASKHAT = "A hollowed out head. Don't ask where I got it.",
        ANTSUIT = "The indignities I've suffered...",
        ANTMAN_WARRIOR = "Such a grotesque display of aggression.",
         ANTCHEST = "They've done all the hard work.",
         NECTAR_POD = "Needs a suitable container to be turned into honey.",
        PHEROMONESTONE = "Now I can control those insects.",
        PIKO = {
            GENERIC = "Shoo, vermin.",
            SLEEPING = "The pest is asleep.",
            DEAD = "It has been exterminated.",
        },
        PIKO_ORANGE = {
            GENERIC = "Shoo, vermin.",
            SLEEPING = "The pest is asleep.",
            DEAD = "It has been exterminated.",
        },
        RELIC_1 = {
            GENERIC = "Someone might desire this.",
            SUNKEN = "Looks like a drowned man.",
        },
        RELIC_2 = {
            GENERIC = "This might catch a pretty penny.",
            SUNKEN = "I suppose I'll have to fish it out.",
        },
        RELIC_3 = {
             GENERIC = "Where's the rest of the face?",
             SUNKEN = "Must I get my hands dirty?",
        },
        RELIC_4 = "Looks regal.",
        RELIC_5 = "It's absurd what passes as valuable around here.",
        REEDS_WATER = "Those reeds could be cut.",
        LOTUS = "How dainty.",
        LOTUS_FLOWER = "I prefer blooms of a darker shade.",
        LOTUS_FLOWER_COOKED ="One makes due.",
        VAMPIREBAT = {
            GENERIC = "You're an impressive creation, aren't you?",
            SLEEPING = "Even creatures of the night must sleep.",
            DEAD = "Thoroughly defeated.",
        },
        VAMPIREBATCAVE = "Villainy lurks within.",
        FROGLEGS_POISON = "A delicacy, were it not poisoned.",
        FROGLEGS_POISON_COOKED = "Shall I risk it?",
        FROG_POISON =
          {
            GENERIC = "Rather handsome for an amphibian.",
            SLEEPING = "I should strike now while it slumbers.",
            DEAD = "Good. Now I don't have to do it.",
        },
        PIG_RUINS_TORCH_WALL = "A little light in this dreary place.",
        PIG_RUINS_TORCH = "A little light in this dreary place.",
        PIG_RUINS_ARTICHOKE = "What an odd choice of statuary.",
        PIG_RUINS_HEAD = "It's been beheaded.",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "Who knows where that leads.",
            LOCKED = "No one keeps me out for long.",
        },
        PIG_RUINS_EXIT = "At least there's an exit.",
        PIG_COIN = "How quaint.",
        OINC = "Petty change.",
        OINC10 = "What use have I for coin out here?",
        OINC100 = "Finally some reasonable pocket change.",
        RABID_BEETLE =
          {
            GENERIC = "What is he all worked up about?",
            SLEEPING = "A noisy sleeper.",
            DEAD = "The grim reaper has been here.",
        },
        PARROT_BLUE =
          {
            GENERIC = "Remarkable bird.",
            SLEEPING = "Pining for the fjords, no doubt.",
            DEAD = "Its metabolic processes are now history.",
        },
        KINGFISHER =
          {
            GENERIC = "A rather generous mandible.",
            SLEEPING = "Dormancy becomes it.",
            DEAD = "Met its demise.",
        },
        BURR = "A tenacious seed.",
        BURR_SAPLING = "I'm sure I have a use for this.",
        {
            BURNING = "Oh well.",
            WITHERED = "It needs to work on its appearance.",
            GENERIC = "I'm sure I have a use for this.",
            PICKED = "Everything of use has been picked from this.",
        },
        PIG_LATIN_1 = "It's in a primitive dialect, but I believe it says \"Light fires\"", -- light fires in pig latin
        DECO_RUINS_BEAM_ROOM ="Functional, but a little dull.",
        DECO_CAVE_BEAM_ROOM = "Functional, but a little dull.",
        DECO_CAVE_BAT_BURROW = "Rather dreary. I like it.",
        SMASHINGPOT = "It looks like it could fall apart at any time.",
        HIPPOPOTAMOOSE ="A dull sluggish beast.",
        PIGGHOST = "Do I know you?",
        ANTCOMBHOME = "Oh those hideous creatures are industrious, aren't they.",
        SECURITYCONTRACT = "Oh good, I can hire some help.",
        PLAYERHOUSE_CITY = {
            BURNT = "Someone will pay for that.",
            FORSALE = "Hmmm... Should I invest in real estate in this place?",
            SOLD = "An estate of my own."
        },
        JELLYBUG = "Excitable little creatures, aren't they?",
        JELLYBUG_COOKED = "Am I really this desperate for food?",
        SLUGBUG = "Loathsome.",
        SLUGBUG_COOKED = "Ugh!",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Supplies for making a quaint abode.",
        PLAYER_HOUSE_VILLA_CRAFT = "Materials for an acceptable domicile.",
        PLAYER_HOUSE_TUDOR_CRAFT = "Bits for a rather snug house.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "I suppose this has a bit of charm to it.",
        PLAYER_HOUSE_TURRET_CRAFT = "Rather small. But I'll build it anyway.",
        PLAYER_HOUSE_BRICK_CRAFT = "Should suit my needs.",
        PLAYER_HOUSE_MANOR_CRAFT = "Ah... materials for a home worthy of me.",
        CLIPPINGS = "I suppose I'm the domestic help now.",
        CUTNETTLE = "Useful.",
        NETTLE = {
            WITHERED = "It hates this dirt almost as much as I do.",
            MOIST = "Must be all that water.",
            EMPTY = "Well that does me no use.",
            DEFAULT = "Useful.",
        },
        DECO_RUINS_FOUNTAIN = "Shall I take a chance?",
        PUGALISK = "You're a little agitated.",
        SNAKE_BONE = "Oh, I like the look of this.",
        SNAKEBONESOUP = "It's a rather weak broth.",
        BANDITMAP = "Now I can steal from that little criminal.",
        BANDITTREASURE = "Hello...",
        BLUNDERBUSS = "A weapon after my own heart.",
        PUGALISK_FOUNTAIN = "I could restore my youthful glow.",
        PUGALISK_RUINS_PILLAR = "I don't trust it.",
        PUGALISK_TRAP_DOOR = "Ha! I'm not falling for that.",
        TEA = "A spot of tea.",
        TEATREE = "It's a tree. What did I expect.",
        TEATREE_NUT_SAPLING = "Oh, just grow already.",
        TEATREE_NUT = "I'll need this for hayfever season.",
        WALL_PIG_RUINS = "It's a wall. Let's not get too excited.",
        PIG_RUINS_DART_TRAP = "I'm not falling for that.",
        PIG_RUINS_SPEAR_TRAP = "Obviously something comes out of those.",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Deadly. I like it.",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "Useless now, aren't they?",
        PIG_RUINS_PRESSURE_PLATE = "Well, I'm not stepping there.",
        PIG_RUINS_DART_STATUE = "I'm familiar with traps. That is definitely a trap.",
        DISARMING_KIT = "This will deal with those pesky traps.",
        BALLPEIN_HAMMER = "For more subtler smashing jobs.",
        GOLD_DUST = "I suppose any gold is good gold.",
        ALOE = "I should eat it.",
        ALOE_COOKED = "I should eat it.",
        ALOE_PLANTED = "It's a plant with many medicinal uses.",
        ASPARAGUS = "We must always eat our vegetables.",
        ASPARAGUS_COOKED = "Smells terrible.",
        ASPARAGUS_PLANTED = "Food. Just growing out of the ground.",
        RADISH = "A reddish radish.",
        RADISH_COOKED = "It's at least halfway appetizing.",
        RADISH_PLANTED = "I see you, food!",
        SNAKE_AMPHIBIOUS = "An amphibian after my own heart.",
        GASMASKHAT = "This clears the vapors.",
        PITHHAT = "Protects my most important part.",
        BILL = {
            GENERIC = "A beautiful mutation.",
            SLEEPING = "A sleeping abomination.",
            DEAD = "It happens to the best of us.",
        },
        ROCK_ANTCAVE = "It's a rock.",
        ANT_CAVE_LANTERN = "Oh look, they discovered light.",
        PROP_DOOR = "All doors lead to doom.",
        PIKO_ORANGE = "How amusing.",
        TURF_PIGRUINS = "Solid enough ground.",
        TURF_RAINFOREST = "Fertile turf.",
        TURF_DEEPRAINFOREST = "Fertile turf.",
        TURF_LAWN = "Turf.",
        TURF_GASJUNGLE = "Turf.",
        TURF_MOSS = "Squishy.",
        TURF_FIELDS = "Turf.",
        TURF_FOUNDATION = "Provides a solid foundation.",
        TURF_COBBLEROAD = "A good cobble road.",
        MANDRAKEMAN = "Cease your babbling!",
        MANDRAKEHOUSE = "Ugh. That's a loud household.",
         -- HOME DECO ITEMS
        INTERIOR_FLOOR_MARBLE = "A nice solid floor.",
        INTERIOR_FLOOR_CHECK = "This feels homey.",
        INTERIOR_FLOOR_PLAID_TILE = "Tartan floor tile.",
        INTERIOR_FLOOR_SHEET_METAL = "Utilitarian flooring.",
        INTERIOR_FLOOR_WOOD = "Watch out for slivers.",
        INTERIOR_WALL_WOOD = "Some basic walls.",
        INTERIOR_WALL_CHECKERED = "A pleasant way to decorate your surroundings.",
        INTERIOR_WALL_FLORAL = "Could use some red.",
        INTERIOR_WALL_SUNFLOWER = "Well isn't that sweet.",
        INTERIOR_WALL_HARLEQUIN = "Well isn't that sweet.",
        DECO_CHAIR_CLASSIC = "A place to sit.",
        DECO_CHAIR_CORNER = "A place to sit.",
        DECO_CHAIR_BENCH = "A place for people to sit.",
        DECO_CHAIR_HORNED = "Not as good as my throne.",
        DECO_CHAIR_FOOTREST = "A place to rest my feet.",
        DECO_CHAIR_LOUNGE = "A place to sit.",
        DECO_CHAIR_MASSAGER = "Ohh. I like that!",
        DECO_CHAIR_STUFFED = "A comfy chair to sit on.",
        DECO_CHAIR_ROCKING = "An invigorating place to sit.",
        DECO_CHAIR_OTTOMAN = "A place to sit or rest my feet.",
        INTERIOR_FLOOR_GARDENSTONE = "A bit too outdoorsy.",
        INTERIOR_FLOOR_GEOMETRICTILES = "Has some charm to it.",
        INTERIOR_FLOOR_SHAG_CARPET = "It'll do.",
        INTERIOR_FLOOR_TRANSITIONAL = "It will need to be fixed.",
        INTERIOR_FLOOR_WOODPANELS = "Creaky. I like it.",
        INTERIOR_FLOOR_HERRINGBONE = "It'll do for now.",
        INTERIOR_FLOOR_HEXAGON = "Not bad.",
        INTERIOR_FLOOR_HOOF_CURVY = "Rather piggish.",
        INTERIOR_FLOOR_OCTAGON = "Really? Linoleum?",
        DECO_LAMP_FRINGE = "A little light.",
        DECO_LAMP_STAINGLASS = "A little light.",
        DECO_LAMP_DOWNBRIDGE = "A little light.",
        DECO_LAMP_2EMBROIDERED = "A couple lights.",
        DECO_LAMP_CERAMIC = "I like the decor.",
        DECO_LAMP_GLASS = "A little light.",
        DECO_LAMP_2FRINGES = "A couple of lights.",
        DECO_LAMP_CANDELABRA = "I like this.",
        DECO_LAMP_ELIZABETHAN = "A little light.",
        DECO_LAMP_GOTHIC = "A little light.",
        DECO_LAMP_ORB = "A little light.",
        DECO_LAMP_BELLSHADE = "A little light.",
        DECO_LAMP_CRYSTALS = "A little light.",
        DECO_LAMP_UPTURN = "A little light.",
        DECO_LAMP_2UPTURNS = "A couple of lights.",
        DECO_LAMP_SPOOL = "This could be improved.",
        DECO_LAMP_EDISON = "Missing everything but the bulb.",
        DECO_LAMP_ADJUSTABLE = "A versatile light.",
        DECO_LAMP_RIGHTANGLES = "A little light.",
        DECO_LAMP_HOOFSPA = "A little light.",
        DECO_CHAISE = "A chair to lounge in.",
        INTERIOR_WALL_PEAGAWK = "Well, at least the feathers are no longer staring at me.",
        INTERIOR_WALL_PLAIN_DS = "A little boring.",
        INTERIOR_WALL_PLAIN_ROG = "A little boring.",
        INTERIOR_WALL_ROPE = "A little too nautical for my tastes.",
        INTERIOR_WALL_CIRCLES = "Not bad, I suppose.",
        INTERIOR_WALL_MARBLE = "Fancy.",
        INTERIOR_WALL_MAYORSOFFICE = "Bureaucratic.",
        INTERIOR_WALL_FULLWALL_MOULDING = "Not bad, I suppose.",
        INTERIOR_WALL_UPHOLSTERED = "Plush.",
        DECO_PLANTHOLDER_BASIC = "It's a plant.",
        DECO_PLANTHOLDER_WIP = "It's a little bush.",
        DECO_PLANTHOLDER_FANCY = "It's a plant.",
        DECO_PLANTHOLDER_BONSAI = "It's a little tree.",
        DECO_PLANTHOLDER_DISHGARDEN = "It's a fancy plant holder.",
        DECO_PLANTHOLDER_PHILODENDRON = "It's a plant.",
        DECO_PLANTHOLDER_ORCHID = "I prefer roses.",
        DECO_PLANTHOLDER_DRACEANA = "It's a plant.",
        DECO_PLANTHOLDER_XEROGRAPHICA = "It's a plant.",
        DECO_PLANTHOLDER_BIRDCAGE = "A hanging plant.",
        DECO_PLANTHOLDER_PALM = "It's a plant.",
        DECO_PLANTHOLDER_ZZ = "It's a plant.",
        DECO_PLANTHOLDER_FERNSTAND = "A fern.",
        DECO_PLANTHOLDER_FERN = "A hanging fern.",
        DECO_PLANTHOLDER_TERRARIUM = "Caged plants.",
        DECO_PLANTHOLDER_PLANTPET = "A planted pet.",
        DECO_PLANTHOLDER_TRAPS = "I like these.",
        DECO_PLANTHOLDER_PITCHERS = "A hanging plant.",
        DECO_PLANTHOLDER_MARBLE = "Ooh. Fancy.",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "Someone should put it out of its misery.",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "How festive.",
        DECO_TABLE_ROUND = "A table.",
        DECO_TABLE_BANKER = "A practical table.",
        DECO_TABLE_DIY = "Crude.",
        DECO_TABLE_RAW = "Philistine.",
        DECO_TABLE_CRATE = "Boorish.",
        DECO_TABLE_CHESS = "I like this.",
        DECO_ANTIQUITIES_WALLFISH = "Lovely...",
        DECO_ANTIQUITIES_BEEFALO = "Interesting decor.",
        DECO_WALLORNAMENT_PHOTO = "Horrid boy...",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "I can hardly see myself.",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Such sentiment...",
        DECO_WALLORNAMENT_MOSAIC = "How bourgeois.",
        DECO_WALLORNAMENT_WREATH = "Shocking what passes for art around here.",
        DECO_WALLORNAMENT_AXE = "Lovely...",
        DECO_WALLORNAMENT_HUNT = "Interesting decor.",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "Handy chart for my alchemical experiments.",
        DECO_WALLORNAMENT_GEARS_ART = "Fanciful arrangement of clockwork.",
        DECO_WALLORNAMENT_CAPE = "How dramatic.",
        DECO_WALLORNAMENT_NO_SMOKING = "Lovely...",
        DECO_WALLORNAMENT_BLACK_CAT = "Ah, the memories...",
        WINDOW_ROUND_CURTAINS_NAILS = "A basic window.",
        WINDOW_ROUND_BURLAP = "Needs better drapery.",
        WINDOW_SMALL_PEAKED = "A window.",
        WINDOW_LARGE_SQUARE = "A way to see the outside world.",
        WINDOW_TALL = "A way to see the outside world.",
        WINDOW_LARGE_SQUARE_CURTAIN = "A way to see the outside world.",
        WINDOW_TALL_CURTAIN = "A way to see the outside world.",
        WINDOW_SMALL_PEAKED_CURTAIN = "The curtains are a nice touch.",
        WINDOW_GREENHOUSE = "All that sunshine and nothing to keep it out.",
        WINDOW_ROUND = "I could do better than this.",
        DECO_WOOD = "A pillar of strength.",
        DECO_MARBLE = "A pillar of strength.",
        DECO_MILLINERY  = "A pillar of strength.",
        DECO_ROUND      = "A pillar of strength.",
        DECO_WOOD_CORNERBEAM = "A pillar of strength.",
        DECO_MARBLE_CORNERBEAM = "A pillar of strength.",
        SWINGING_LIGHT_BASIC_BULB = "Well, that's boring.",
        SWINGING_LIGHT_FLORAL_BLOOMER = "A light.",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "A ceiling light.",
        SWINGING_LIGHT_ROPE_1 = "Well, that's boring.",
        SWINGING_LIGHT_ROPE_2 = "Well, that's boring.",
        SWINGING_LIGHT_FLORAL_BULB = "A ceiling light.",
        SWINGING_LIGHT_PENDANT_CHERRIES = "A light.",
        SWINGING_LIGHT_FLORAL_SCALLOP = "A ceiling light.",
        SWINGING_LIGHT_FLORAL_BLOOMER = "A ceiling light.",
        SWINGING_LIGHT_BASIC_METAL = "Utilitarian.",
        SWINGING_LIGHT_TOPHAT = "That's where I left my hat.",
        SWINGING_LIGHT_DERBY = "A place to hang your hat.",
        SWINGING_LIGHT1 = "A ceiling light.",
        RUG_ROUND = "Quit staring!",
        RUG_SQUARE = "A floor rug.",
        RUG_OVAL = "A rug after my own heart.",
        RUG_RECTANGLE = "A rug after my own heart.",
        RUG_FUR = "A dead thing that warms my feet.",
        RUG_HEDGEHOG = "An animal that warms my feet.",
        RUG_PORCUPUSS = "A dead thing that warms my feet.",
        RUG_HOOFPRINT = "How droll.",
        RUG_OCTAGON = "A floor rug.",
        RUG_SWIRL = "A floor rug.",
        RUG_CATCOON = "A dead thing that warms my feet.",
        RUG_RUBBERMAT = "Essential when dealing with... fluids.",
        RUG_WEB = "Rather sticky.",
        RUG_METAL = "Dangerous.",
        RUG_WORMHOLE = "Does it work?",
        RUG_BRAID = "A floor rug.",
        RUG_BEARD = "Ugh.",
        RUG_NAILBED = "Lovely...",
        RUG_CRIME = "Which unfortunate soul was that?",
        RUG_TILES = "How geometric.",
        SHELVES_WOOD = "Ah. A place to put my books.",
        SHELVES_CINDERBLOCKS = "Interesting choice of decor.",
        SHELVES_MARBLE = "I have the perfect book for that bookshelf.",
        SHELVES_MIDCENTURY = "Ah. A place to put my books.",
        SHELVES_GLASS = "Looks breakable.",
        SHELVES_LADDER = "Boorish.",
        SHELVES_HUTCH = "Ah. A place to put my books.",
        SHELVES_INDUSTRIAL = "Philistine.",
        SHELVES_ADJUSTABLE = "A place to put my books.",
        SHELVES_WALLMOUNT = "Stable enough.",
        SHELVES_AFRAME = "I suppose this works.",
        SHELVES_CRATES = "Interesting choice of decor.",
        SHELVES_FRIDGE = "Interesting choice of decor.",
        SHELVES_HOOKS = "Ah. A place to put my books.",
        SHELVES_PIPE = "I suppose this works.",
        SHELVES_HATTREE = "I suppose this works.",
        SHELVES_PALLET = "Interesting choice of decor.",
        SHELVES_BASIC = "A bit basic, but it'll do.",
           SHELVES_FLOATING = "Interesting choice of decor.",
           SHELVES_METAL = "A little industrial for my tastes.",
        WOOD_DOOR = "It's a door. You go through it.",
        STONE_DOOR = "A door to another room.",
        ORGANIC_DOOR = "A door to another room.",
        IRON_DOOR = "A door to another room.",
        PILLAR_DOOR = "Has a certain dramatic flare.",
        CURTAIN_DOOR = "It barely hides anything.",
        ROUND_DOOR = "A little like being eaten.",
        PLATE_DOOR = "Little too industrial.",
        ROCK_FLIPPABLE = "What will this unearth?",
        PLAYER_HOUSE_COTTAGE = "Materials for a quaint house.",
        PLAYER_HOUSE_VILLA = "Materials for an acceptable home.",
        PLAYER_HOUSE_TUDOR = "Materials for a snug little home.",
        PLAYER_HOUSE_MANOR = "Materials for a home worthy of a fine gentleman.",
        PLAYER_HOUSE_GOTHIC = "Materials for a house with some charm.",
        PLAYER_HOUSE_BRICK = "Materials for a functional home.",
        PLAYER_HOUSE_TURRET = "Materials for a small home.",

        BRAMBLESPIKE = "As thorny as a rose bush.",
        SUNKEN_RELIC = "How on earth will I fish that out?",
        IRON = "A solid mineral.",
        CLAWPALMTREE = "How handy...",
        DUG_NETTLE = "Do I look like a gardener?",
        THUNDERBIRD = "How dramatic.",
        THUNDERBIRDNEST = "Tempting...",
        FEATHER_THUNDER = "I should stick it in a cap.",
        THUNDERHAT = "Electrifying finery.",
        WEEVOLE = "Interminable pests.",
        WEEVOLE_CARAPACE = "Ugh.",
        ARMOR_WEEVOLE = "This is not a good look.",
        TUBERTREE = "An axe isn't going to cut it.",
        CORK = "A buoyant material.",
        CANDLEHAT = "The wax better not drip on my suit.",
        CORK_BAT = "Easy enough to carry.",
        LEATHER = "Soft. Malleable.",
        BAT_HIDE = "Who knew bat and pig skins were so similar?",
        ANCIENT_ROBOT_RIBS = "Well that looks interesting.",
        ANCIENT_ROBOT_CLAW = "Seems part of a whole.",
        ANCIENT_ROBOT_LEG = "I'd hate to see the rest of it.",
        ANCIENT_ROBOT_HEAD = "There's no head on his shoulders.",
        TEATREE_NUT_COOKED = "I'll eat it but I won't like it.",
        DEED = "Finally a roof over my head.",
        CONSTRUCTION_PERMIT = "More room for my acquisitions.",
        DEMOLITION_PERMIT = "I normally don't need a license for destruction.",
        BANDITHAT = "A nice hat to hide under.",
        PIGBANDIT = "He's after my money!",
        PIG_RUINS_CREEPING_VINES = "They're pressing in.",
        MAGNIFYING_GLASS = "Let's see what we can find.",
        CLAWPALMTREE_SAPLING = "You're on your own, tree.",
        CORKCHEST = "At least this'll keep those nosy critters out.",
        CORKBOAT = "Looks barely seaworthy.",
        SEDIMENTPUDDLE = "There's something sparkling inside there.",
        GOLDPAN = "Must I do everything myself?",
        PORKLAND_ENTRANCE = "Off to another adventure?",
        PORKLAND_EXIT = "An exit but not a way out.",
        POG = {
            GENERIC = "What do you want?",
            FOLLOWER = "Shoo. I do not like you.",
            SLEEPING = "Oh look. It is asleep.",
            APORKALYPSE = "Don't make me do something I'll regret.",
        },
        PANGOLDEN = "He has expensive tastes.",
        ROC_LEG = "This is why good foot hygiene is important.",
        ROC_HEAD = "Its got its head in the clouds.",
        ROC_TAIL = "Hate to see the end of that.",
        GNATMOUND = "Ugh. The horde home.",
        GNAT = "Horde horrible.",
        PORKLAND_INTRO = "He's new.",
        ROC_NEST_TREE1 = "It's seen better days.",
        ROC_NEST_TREE2 = "What could have uprooted that?",
        ROC_NEST_BUSH = "What a mess.",
        ROC_NEST_BRANCH1 = "What a mess.",
        ROC_NEST_BRANCH2 = "A big stick.",
        ROC_NEST_TRUNK = "I wonder what broke that?",
        ROC_NEST_HOUSE = "Who lives there?",
        ROC_NEST_RUSTY_LAMP = "It's seen brighter days.",
        ROC_NEST_EGG1 = "I'd hate to see what came out of there.",
        ROC_NEST_EGG2 = "Does no one clean up around here?",
        ROC_NEST_EGG3 = "Looks like it's been around for a while.",
        ROC_NEST_EGG4 = "Cracked.",
        ROC_ROBIN_EGG = "Is it a stone or an egg?",
        TUBER_CROP = "Looks unripe.",
        TUBER_BLOOM_CROP = "At least it's edible.",
        TUBER_CROP_COOKED = "Ugh. Should I even eat this?",
        TUBER_BLOOM_CROP_COOKED = "Looks... edible?",
        ALLOY = "Durable.",
        ARMOR_METALPLATE = "Not very pliant but it does the job.",
        METALPLATEHAT = "How very conquistadorian.",
        SMELTER = "Finally we're catching up to the Iron Age.",
        BUGREPELLENT = "This will put that horde in its place.",
        HOGUSPORKUSATOR = "Scientifically proving pigs can fly.",
        GASCLOUD = "That'll keep those bugs away.",
        SHEARS = "Aren't there gardeners for this sort of thing?",
        BATHAT = "How delightfully horrific.",

        WATERDROP = "What an invigorating little seed.",
        LIFEPLANT = "I do still prefer roses.",
        TRINKET_GIFTSHOP_1 = "Why would I want this horrible looking thing?",
        TRINKET_GIFTSHOP_3 = "A keepsake for the Boar-geoisie.",
        KEY_TO_CITY = "Building a city is a step down for me.",
        PEDESTAL_KEY = "This seems rather ornate.",
        ROYAL_GALLERY = "Is it really worth keeping that under glass?",
        APORKALYPSE_CLOCK = "I do like this...",
        ANCIENT_HERALD = "Ah. The end is nigh.",
        ASPARAGUSSOUP = "I suppose you can make soup from anything.",
        SPICYVEGSTINGER = "I do enjoy a drink.",
        FEIJOADA = "Am I hungry enough for this?",
        HARDSHELL_TACOS = "At least the shells are fresh.",
        GUMMY_CAKE = "Cake with the texture of tar.",
        STEAMEDHAMSANDWICH = "They're obviously grilled.",
        MEATED_NETTLE = "Meaty and medicinal.",
        ROC_NEST_DEBRIS1 = "How boring.",
        ROC_NEST_DEBRIS2 = "An ordinary stick. Droll.",
        ROC_NEST_DEBRIS3 = "A stick.",
        ROC_NEST_DEBRIS4 = "It's a stick.",
        ANTQUEEN = "A bit huffy.",
          ANTQUEEN_CHAMBERS = "All that for a bug?",
        ANTQUEEN_THRONE = "Might be something interesting in there.",
        ANTMAN_WARRIOR_EGG = "Where those pesky bugs hatch from.",
        PIG_SHOP_DELI = {
            GENERIC = "Finally some decent food.",
            BURNING = "A shame.",
        },
        PIG_SHOP_CITYHALL = {
            GENERIC = "I could run this place better.",
            BURNING = "Serves them right.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            GENERIC = "I deserve that.",
            BURNING = "This town has a vandal problem.",
        },
        PIG_GUARD_TOWER_PALACE = {
            GENERIC = "The lookout.",
            BURNING = "Humph.",
        },
        PIG_RUINS_PIG = "What's he got to smile about?",
        PIG_RUINS_IDOL = "Hmmm. How do I get that statue off?",
        PIG_RUINS_PLAQUE = "It must be worth something to those pigs.",

        BASEFAN = "Ah. Civilization.",
        SPRINKLER = "Good. Now I don't have to water by hand.",
        NETTLELOSANGE = "Medicinal.",
        ICEDTEA = "Refreshing.",
        TRINKET_GIFTSHOP_4 = "Really. Is that necessary?",
        WALLCRACK_RUINS = "That's not fooling anyone.",
        RAINFORESTTREE_ROT = "Looks unwell.",
        DEFLATED_BALLOON = "That's done.",
        DEFLATED_BALLOON_BASKET = "Good for nothing now.",
        SNAKE_FIRE = "A fiery little beastie.",
        DISGUISEHAT = "Doesn't fool me.",
        ALOE_SEEDS = "Such labor is beneath me.",
        ASPARAGUS_SEEDS = "Such labor is beneath me.",
        RADISH_SEEDS = "Such labor is beneath me.",
        CAVE_EXIT_ROC = "Those rocks are hiding something.",
        PORKLAND_INTRO_BASKET = "Good for nothing now.",
        PORKLAND_INTRO_BALLOON = "That's done.",
        PORKLAND_INTRO_TRUNK = "There's a 'W' monogrammed on it. It must be mine.",
        PORKLAND_INTRO_SUITCASE = "There's a 'W' monogrammed on it. It must be mine.",
        PORKLAND_INTRO_FLAGS = "Somebody really should clean around here.",
        PORKLAND_INTRO_SANDBAG = "Useless and heavy.",
        TURF_BEARD_HAIR = "A bit gauche for my tastes.",
        HIPPO_ANTLER = "Well, it'd make a good hat rack.",
        BILL_QUILL = "Sharp and pointed. Like me.",
        ANTLER = "Why would I want to call that bird?",
        ANTLER_CORRUPTED = "This should rid me of that giant pest.",
        PUGALISK_SKULL = "How very macabre.",
        PUGALISK_CORPSE = "Can't say I'm sad to see him dead.",
        BONESTAFF = "Penetrating.",
        CITY_HAMMER = "Destructive. I like it.",
        TURF_PAINTED  = "Sand.",
        TURF_PLAINS  = "Turf.",
        PIG_SHOP_BANK = {
          GENERIC = "Can I exchange this money for anything useful?",
          BURNING = "Serves them right.",
        },
         PIGMAN_USHER = {
          GENERIC = "A saccharine pig who likes his sweets.",
          SLEEPING = "A bunch of layabouts in this town.",
        },
        PIGMAN_ROYALGUARD_2 = {
          GENERIC = "Am I supposed to be intimidated?",
          SLEEPING = "Not very good at his job, is he.",
        },
        PIG_SHOP_ANTIQUITIES = {
          GENERIC = "Hmm... I may be in the market for some oddities.",
          BURNING = "Nothing I can do about that.",
        },
        PIG_RUINS_ENTRANCE2 = "Leads down into the depths.",
        PIG_RUINS_EXIT2 = "At least there's a way out.",
        PIG_RUINS_ENTRANCE3 = "Leads down into the depths.",
        PIG_RUINS_ENTRANCE4 = "This looks interesting.",
        PIG_RUINS_EXIT4 = "Let's see where that leads.",
        PIG_RUINS_ENTRANCE5 = "I like where this is going.",
        PIG_RUINS_ENTRANCE_SMALL = "Let's investigate..",
        RO_BIN = "Just useful enough to keep around. ",
        RO_BIN_GIZZARD_STONE = "Ugh. Really.",
        GIANTGRUB = "It's doing all my work for me.",
        DECO_RUINS_ENDSWELL = "Finally a chance to get something I wish for.",
        ----------reward update ------
        TURF_DEEPRAINFOREST_NOCANOPY = "Fertile turf.",
        BRAMBLE_CORE = "It's certainly protected itself.",
        BRAMBLE_BULB = "A seedy little thing.",
        ROOTTRUNK_CHILD = "Keeps my things just where I want them.",
        PIG_SHOP_TINKER = {
            GENERIC = "Full of schemes and plans. Like me.",
            BURNING = "He'll have to rebuild his own shop.",
        },
        ARMORVORTEXCLOAK = "It's like it was tailored just for me.",
        ANCIENT_REMNANT = "A potent fragment of a shadowy figure.",
        GOGGLESNORMALHAT = "I hardly see the need for these.",
        GOGGLESHEATHAT = "What kind of ridiculous person made these?",
        GOGGLESARMORHAT = "You're going to need that kind of armor if you can't see where you're going.",
        GOGGLESSHOOTHAT = "If they worked, I might consider wearing these.",
        THUMPER = "Does all my hard work for me.",
        TELEBRELLA = "It's like walking without the exertion.",
        TELIPAD = "I'm the rabbit and this is the hat.",
        TRUSTY_SHOOTER = "Normally I prefer instruments a little more destructive.",
        WHEELER_TRACKER = "Nothing can hide from me now.",
        ANCIENT_HULK = "So the technology CAN be brought back to life!",
        ROCK_BASALT = "That robot certainly leaves a mark.",
        LIVING_ARTIFACT = "Not exactly dapper, but how can I say no to this?",
        INFUSED_IRON = "Hello... Let's see what I can make with this.",
        TELEPORTATO_HAMLET_POTATO = "Ah, I was looking for this.",
        TELEPORTATO_HAMLET_RING = "Quaint, but it'll work.",
        TELEPORTATO_HAMLET_BOX = "Just the thing I was looking for.",
        TELEPORTATO_HAMLET_CRANK = "Yes, this will do nicely.",
        TELEPORTATO_HAMLET_BASE = "The foundation for something portentous.",
        ANCIENT_ROBOTS_ASSEMBLY = "Dare I complete it?",
        HEDGE_BLOCK_ITEM = "It's no good carrying this around everywhere.",
        HEDGE_CONE_ITEM = "Why isn't this in the ground?",
        HEDGE_LAYERED_ITEM = "Adds a touch of class to a garden.",
    },
    DESCRIBE_MYSTERY = "Did I hide something in there...?",
    DESCRIBE_NEARSIGHTED = "Causes blindness. How useful.",
}
