return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Not right now.",
        },
    },
    ANNOUNCE_BOAT_DAMAGED = "My vessel is sustaining damage.",
    ANNOUNCE_BOAT_SINKING = "I fear I've sprung a leak.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "After everything, is this how it ends?!",
    ANNOUNCE_DEHUMID = {
        "Ah! That feels better.",
    },
    ANNOUNCE_HAYFEVER = "Ugh. Allergies.",
    ANNOUNCE_HAYFEVER_OFF = "Ah... I can breathe again.",
    ANNOUNCE_PICKPOOP = {
        "Bah!",
        "Ew!",
        "Gah!",
        "Filth!",
    },
    ANNOUNCE_SNEEZE = "ah...CHOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is too much.",
        "This %s is hotter than I like.",
    },
    ANNOUNCE_WAVE_BOOST = "Truly!",
    DESCRIBE = {
        ALLOY = "Durable.",
        APORKALYPSE_CLOCK = "I do like this...",
        ARMOR_METALPLATE = "Not very pliant but it does the job.",
        ARMOR_WEEVOLE = "This is not a good look.",
        ASPARAGUS_PLANTED = "Food. Just growing out of the ground.",
        BASEFAN = "Ah. Civilization.",
        BOATREPAIRKIT = "It will hold off my vessel's inevitable decay.",
        BOAT_CARGO = "Ah, plenty of room to breathe.",
        BOAT_CORK = "Looks barely seaworthy.",
        BOAT_LOGRAFT = "It seems like there should be regulations against this.",
        BOAT_ROW = "Manually operated. A pity.",
        BOAT_TORCH = "Sailing at night seems unsafe, but this makes it somewhat better.",
        CHITIN = "We all have our defenses.",
        COFFEE = "I look forward to this.",
        COFFEEBEANS = "It's strange to see them this color.",
        COFFEEBEANS_COOKED = "Better than raw, but perhaps there's a better way to prepare them?",
        CUTNETTLE = "Useful.",
        DUNGBALL = "I refuse to touch that.",
        DUNGBEETLE = {
            DEAD = "It has come to a feculent end.",
            GENERIC = "What a filthy creature.",
            SLEEPING = "The time is right to strike.",
            UNDUNGED = "Sans dungball, I see.",
        },
        DUNGPILE = {
            GENERIC = "Blech.",
            PICKED = "That was simply undignified.",
        },
        FLOWER_RAINFOREST = "It's no rose.",
        GLOWFLY = {
            DEAD = "Lights out.",
            GENERIC = "Disgusting, but helpful.",
            SLEEPING = "That light is rather too lethargic.",
        },
        GLOWFLY_COCOON = "Ah, metamorphosis...",
        GOLDENMACHETE = "I've always wanted to hack things in luxury.",
        GOLDPAN = "Must I do everything myself?",
        GOLD_DUST = "I suppose any gold is good gold.",
        GRABBING_VINE = "I know the ropes.",
        GRASS_TALL = {
            BURNING = "Well, there you have it.",
            GENERIC = "Oh, joyous occasion. I've found grass.",
            PICKED = "I don't require any more grass, thank you.",
        },
        HALBERD = "A blade as sharp as my wit.",
        HANGING_VINE = "I know the ropes.",
        ICEDTEA = "Refreshing.",
        IRON = "A solid mineral.",
        LILYPAD = "A massive pond leaf.",
        LOTUS = "How dainty.",
        LOTUS_FLOWER = "I prefer blooms of a darker shade.",
        LOTUS_FLOWER_COOKED = "One makes due.",
        MACHETE = "Truthfully I was always a hack.",
        PANGOLDEN = "He has expensive tastes.",
        PEAGAWK = {
            DEAD = "It's beauty has been snuffed out forever.",
            GENERIC = "What a regal-looking beast.",
            SLEEPING = "It is eye-dol.",
        },
        PEAGAWKFEATHER = "What finery.",
        PEAGAWK_BUSH = "I've my suspicions about that bush.",
        PIKO = {
            DEAD = "It has been exterminated.",
            GENERIC = "Shoo, vermin.",
            SLEEPING = "The pest is asleep.",
        },
        PIKO_ORANGE = {
            DEAD = "It has been exterminated.",
            GENERIC = "How amusing.",
            SLEEPING = "The pest is asleep.",
        },
        RABID_BEETLE = {
            DEAD = "The grim reaper has been here.",
            GENERIC = "What is he all worked up about?",
            SLEEPING = "A noisy sleeper.",
        },
        SAIL_SNAKESKIN = "For ease of travel.",
        SEDIMENTPUDDLE = "There's something sparkling inside there.",
        SHEARS = "Aren't there gardeners for this sort of thing?",
        SMELTER = {
            BURNT = "Back to the Stone Age.",
            COOKING_SHORT = "Watch it! Don't let the fire go out.",
            DONE = "Difficult results.",
            EMPTY = "Finally we're catching up to the Iron Age.",
        },
        SNAKESKIN = "The texture is delectable.",
        TEA = "A spot of tea.",
        TEATREE = "It's a tree. What did I expect.",
        TEATREE_NUT = "I'll need this for hayfever season.",
        TEATREE_NUT_COOKED = "I'll eat it but I won't like it.",
        TEATREE_NUT_SAPLING = "Oh, just grow already.",
        TREE_PILLAR = "This tree is unusually large.",
        WEEVOLE = "Interminable pests.",
        WEEVOLE_CARAPACE = "Ugh.",
    },
}
