return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Not right now.",
        },
        USEDOOR = {
            GENERIC = "It refuses to open for me.",
            LOCKED = "I'll get it open somehow.",
        },
    },
    ANNOUCE_BATS = "How apropos.",
    ANNOUNCE_BOAT_DAMAGED = "My vessel is sustaining damage.",
    ANNOUNCE_BOAT_SINKING = "I fear I've sprung a leak.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "After everything, is this how it ends?!",
    ANNOUNCE_DEHUMID = {
        "Ah! That feels better.",
    },
    ANNOUNCE_HAYFEVER = "Ugh. Allergies.",
    ANNOUNCE_HAYFEVER_OFF = "Ah... I can breathe again.",
    ANNOUNCE_PICKPOOP = {
        "Bah!",
        "Ew!",
        "Gah!",
        "Filth!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That hide is too tough.",
        "That's not going to work.",
        "I need to be more strategic.",
    },
    ANNOUNCE_SNEEZE = "ah...CHOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is too much.",
        "This %s is hotter than I like.",
    },
    ANNOUNCE_WAVE_BOOST = "Truly!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "It's dead.",
            GENERIC = "That's one handsome abomination.",
            SLEEPING = "A nefarious napper.",
        },
        ALLOY = "Durable.",
        ALOE = "I should eat it.",
        ALOE_COOKED = "I should eat it.",
        ALOE_PLANTED = "It's a plant with many medicinal uses.",
        ALOE_SEEDS = "Such labor is beneath me.",
        ANCIENT_HULK = "So the technology CAN be brought back to life!",
        ANCIENT_ROBOTS_ASSEMBLY = "Dare I complete it?",
        ANCIENT_ROBOT_CLAW = "Seems part of a whole.",
        ANCIENT_ROBOT_HEAD = "There's no head on his shoulders.",
        ANCIENT_ROBOT_LEG = "I'd hate to see the rest of it.",
        ANCIENT_ROBOT_RIBS = "Well that looks interesting.",
        ANTCHEST = "They've done all the hard work.",
        APORKALYPSE_CLOCK = "I do like this...",
        ARMOR_METALPLATE = "Not very pliant but it does the job.",
        ARMOR_WEEVOLE = "This is not a good look.",
        ASPARAGUS_PLANTED = "Food. Just growing out of the ground.",
        BALLPEIN_HAMMER = "For more subtler smashing jobs.",
        BASEFAN = "Ah. Civilization.",
        BILL = {
            DEAD = "It happens to the best of us.",
            GENERIC = "A beautiful mutation.",
            SLEEPING = "A sleeping abomination.",
        },
        BILL_QUILL = "Sharp and pointed. Like me.",
        BOATREPAIRKIT = "It will hold off my vessel's inevitable decay.",
        BOAT_CARGO = "Ah, plenty of room to breathe.",
        BOAT_CORK = "Looks barely seaworthy.",
        BOAT_LOGRAFT = "It seems like there should be regulations against this.",
        BOAT_ROW = "Manually operated. A pity.",
        BOAT_TORCH = "Sailing at night seems unsafe, but this makes it somewhat better.",
        BONESTAFF = "Penetrating.",
        BRAMBLESPIKE = "As thorny as a rose bush.",
        BRAMBLE_BULB = "A seedy little thing.",
        BRAMBLE_CORE = "It's certainly protected itself.",
        BURR = "A tenacious seed.",
        BURR_SAPLING = "I'm sure I have a use for this.",
        CHITIN = "We all have our defenses.",
        CITY_LAMP = {
            GENERIC = "A welcome sign of civilization.",
            ON = "It eases my mind.",
        },
        CLAWPALMTREE = "How handy...",
        CLAWPALMTREE_SAPLING = "You're on your own, tree.",
        COFFEE = "I look forward to this.",
        COFFEEBEANS = "It's strange to see them this color.",
        COFFEEBEANS_COOKED = "Better than raw, but perhaps there's a better way to prepare them?",
        CORK = "A buoyant material.",
        CORKCHEST = "At least this'll keep those nosy critters out.",
        CUTNETTLE = "Useful.",
        DISARMING_KIT = "This will deal with those pesky traps.",
        DUNGBALL = "I refuse to touch that.",
        DUNGBEETLE = {
            DEAD = "It has come to a feculent end.",
            GENERIC = "What a filthy creature.",
            SLEEPING = "The time is right to strike.",
            UNDUNGED = "Sans dungball, I see.",
        },
        DUNGPILE = {
            GENERIC = "Blech.",
            PICKED = "That was simply undignified.",
        },
        FLOWER_RAINFOREST = "It's no rose.",
        FROGLEGS_POISON = "A delicacy, were it not poisoned.",
        FROGLEGS_POISON_COOKED = "Shall I risk it?",
        FROG_POISON = {
            DEAD = "Good. Now I don't have to do it.",
            GENERIC = "Rather handsome for an amphibian.",
            SLEEPING = "I should strike now while it slumbers.",
        },
        GLOWFLY = {
            DEAD = "Lights out.",
            GENERIC = "Disgusting, but helpful.",
            SLEEPING = "That light is rather too lethargic.",
        },
        GLOWFLY_COCOON = "Ah, metamorphosis...",
        GOLDENMACHETE = "I've always wanted to hack things in luxury.",
        GOLDPAN = "Must I do everything myself?",
        GOLD_DUST = "I suppose any gold is good gold.",
        GRABBING_VINE = "I know the ropes.",
        GRASS_TALL = {
            BURNING = "Well, there you have it.",
            GENERIC = "Oh, joyous occasion. I've found grass.",
            PICKED = "I don't require any more grass, thank you.",
        },
        HALBERD = "A blade as sharp as my wit.",
        HANGING_VINE = "I know the ropes.",
        HIPPOPOTAMOOSE = "A dull sluggish beast.",
        HIPPO_ANTLER = "Well, it'd make a good hat rack.",
        ICEDTEA = "Refreshing.",
        INFUSED_IRON = "Hello... Let's see what I can make with this.",
        IRON = "A solid mineral.",
        KINGFISHER = {
            DEAD = "Met its demise.",
            GENERIC = "A rather generous mandible.",
            SLEEPING = "Dormancy becomes it.",
        },
        LAWNORNAMENT = {
            BURNING = "Someone's a critic.",
            BURNT = "A waste of fine culture.",
            GENERIC = "Ah, a touch of civility. What a welcome change.",
        },
        LIFEPLANT = "I do still prefer roses.",
        LILYPAD = "A massive pond leaf.",
        LIVING_ARTIFACT = "Not exactly dapper, but how can I say no to this?",
        LOTUS = "How dainty.",
        LOTUS_FLOWER = "I prefer blooms of a darker shade.",
        LOTUS_FLOWER_COOKED = "One makes due.",
        MACHETE = "Truthfully I was always a hack.",
        MAGNIFYING_GLASS = "Let's see what we can find.",
        MANDRAKEHOUSE = "Ugh. That's a loud household.",
        MANDRAKEMAN = "Cease your babbling!",
        MEAN_FLYTRAP = {
            DEAD = "Eradicated.",
            GENERIC = "Do not tangle with me!",
            SLEEPING = "I must endeavor not to wake it.",
        },
        METALPLATEHAT = "How very conquistadorian.",
        NECTAR_POD = "Needs a suitable container to be turned into honey.",
        OINC = "Petty change.",
        OINC10 = "What use have I for coin out here?",
        OINC100 = "Finally some reasonable pocket change.",
        PANGOLDEN = "He has expensive tastes.",
        PARROT_BLUE = {
            DEAD = "Its metabolic processes are now history.",
            GENERIC = "Remarkable bird.",
            SLEEPING = "Pining for the fjords, no doubt.",
        },
        PEAGAWK = {
            DEAD = "It's beauty has been snuffed out forever.",
            GENERIC = "What a regal-looking beast.",
            SLEEPING = "It is eye-dol.",
        },
        PEAGAWKFEATHER = "What finery.",
        PEAGAWK_BUSH = "I've my suspicions about that bush.",
        PIGEON = {
            DEAD = "As filthy in death as it was in life.",
            GENERIC = "Filthy.",
            SLEEPING = "Enjoy your grimy slumber.",
        },
        PIGHOUSE_CITY = {
            BURNING = "That will only lead to improvement.",
            GENERIC = "I presume it's a pigsty inside.",
        },
        PIGHOUSE_FARM = {
            BURNING = "A flaming reminder of Life's inequities.",
            GENERIC = "I've no interest in a commoner's domicile.",
        },
        PIGHOUSE_MINE = {
            BURNING = "It's in flames!",
            GENERIC = "Little pig, little pig, let me in.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "A man who understands the power of a tailored suit.",
            SLEEPING = "Those in power should sleep with one eye open.",
        },
        PIGMAN_QUEEN = "She does not smell particularly royal.",
        PIG_GUARD_TOWER = {
            BURNING = "A watchtower no more.",
            GENERIC = "There's an appeal in overseeing the masses.",
        },
        PIG_PALACE = "A little garish for my taste.",
        PIG_RUINS_ARTICHOKE = "What an odd choice of statuary.",
        PIG_RUINS_HEAD = "It's been beheaded.",
        PIG_RUINS_IDOL = "Hmmm. How do I get that statue off?",
        PIG_RUINS_PLAQUE = "It must be worth something to those pigs.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Serves them right.",
            GENERIC = "I could run this place better.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "This town has a vandal problem.",
            GENERIC = "I deserve that.",
        },
        PIKO = {
            DEAD = "It has been exterminated.",
            GENERIC = "Shoo, vermin.",
            SLEEPING = "The pest is asleep.",
        },
        PIKO_ORANGE = {
            DEAD = "It has been exterminated.",
            GENERIC = "How amusing.",
            SLEEPING = "The pest is asleep.",
        },
        PUGALISK = "You're a little agitated.",
        PUGALISK_CORPSE = "Can't say I'm sad to see him dead.",
        PUGALISK_FOUNTAIN = "I could restore my youthful glow.",
        PUGALISK_RUINS_PILLAR = "I don't trust it.",
        PUGALISK_SKULL = "How very macabre.",
        PUGALISK_TRAP_DOOR = "Ha! I'm not falling for that.",
        RABID_BEETLE = {
            DEAD = "The grim reaper has been here.",
            GENERIC = "What is he all worked up about?",
            SLEEPING = "A noisy sleeper.",
        },
        RADISH = "A reddish radish.",
        RADISH_COOKED = "It's at least halfway appetizing.",
        RADISH_PLANTED = "I see you, food!",
        RADISH_SEEDS = "Such labor is beneath me.",
        RAINFORESTTREE = {
            BURNING = "It burns like any tree.",
            BURNT = "A blackened shell of its former self.",
            CHOPPED = "It's been chopped down.",
            GENERIC = "Like no tree I've seen before.",
        },
        REEDS_WATER = "Those reeds could be cut.",
        RELIC_1 = {
            GENERIC = "Someone might desire this.",
            SUNKEN = "Looks like a drowned man.",
        },
        RELIC_2 = {
            GENERIC = "This might catch a pretty penny.",
            SUNKEN = "I suppose I'll have to fish it out.",
        },
        RELIC_3 = {
            GENERIC = "Where's the rest of the face?",
            SUNKEN = "Must I get my hands dirty?",
        },
        RELIC_4 = "Looks regal.",
        RELIC_5 = "It's absurd what passes as valuable around here.",
        ROOTTRUNK_CHILD = "Keeps my things just where I want them.",
        SAIL_SNAKESKIN = "For ease of travel.",
        SCORPION = {
            DEAD = "It has felt the cruel sting of death.",
            GENERIC = "You'll not be stinging me.",
            SLEEPING = "Don't wake up, cur.",
        },
        SEDIMENTPUDDLE = "There's something sparkling inside there.",
        SHEARS = "Aren't there gardeners for this sort of thing?",
        SMELTER = {
            BURNT = "Back to the Stone Age.",
            COOKING_SHORT = "Watch it! Don't let the fire go out.",
            DONE = "Difficult results.",
            EMPTY = "Finally we're catching up to the Iron Age.",
        },
        SNAKEBONESOUP = "It's a rather weak broth.",
        SNAKEOIL = "Perhaps I could turn a profit with this.",
        SNAKESKIN = "The texture is delectable.",
        SNAKE_AMPHIBIOUS = "An amphibian after my own heart.",
        SNAKE_BONE = "Oh, I like the look of this.",
        SPIDER_MONKEY = {
            DEAD = "It has met its demise.",
            GENERIC = "I command you to stay back.",
            SLEEPING = "Now is the time to make my escape.",
        },
        SPIDER_MONKEY_NEST = "I would rather not disturb it.",
        SPIDER_MONKEY_TREE = "Filthy creatures reside within.",
        TEA = "A spot of tea.",
        TEATREE = "It's a tree. What did I expect.",
        TEATREE_NUT = "I'll need this for hayfever season.",
        TEATREE_NUT_COOKED = "I'll eat it but I won't like it.",
        TEATREE_NUT_SAPLING = "Oh, just grow already.",
        TOUCAN = "Colorful vermin.",
        TREE_PILLAR = "This tree is unusually large.",
        TUBERTREE = "An axe isn't going to cut it.",
        TUBER_BLOOM_CROP = "At least it's edible.",
        TUBER_BLOOM_CROP_COOKED = "Looks... edible?",
        TUBER_CROP = "Looks unripe.",
        TUBER_CROP_COOKED = "Ugh. Should I even eat this?",
        VAMPIREBAT = {
            DEAD = "Thoroughly defeated.",
            GENERIC = "You're an impressive creation, aren't you?",
            SLEEPING = "Even creatures of the night must sleep.",
        },
        VAMPIREBATCAVE = "Villainy lurks within.",
        VENOMGLAND = "Could this be the cure?",
        VENUS_STALK = "All stalk and no action.",
        VINE = "It's twisted and gnarled.",
        WALKINGSTICK = "Much easier on my knees.",
        WATERDROP = "What an invigorating little seed.",
        WEEVOLE = "Interminable pests.",
        WEEVOLE_CARAPACE = "Ugh.",
    },
}
