return {
    ANNOUNCE_DEHUMID = {
        "Whew! Not so hot anymore.",
    },
    ANNOUNCE_HAYFEVER = "Sniff. Sniff. We must have allergies.",
    ANNOUNCE_HAYFEVER_OFF = "Wow! I think our allergies are gone!",
    ANNOUNCE_PICKPOOP = {
        "Blah!",
        "Eww!",
        "Yucky!",
    },
	ANNOUNCE_PUGALISK_INVULNERABLE = {
        "I can't break it there!",
        "That part's too tough.",
        "It's not breaking!"
    },
    ANNOUNCE_SNEEZE = "a...choooOOOOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "Ugh. We're really baking in this %s.",
        "Wow! This %s is making us hot.",
    },
    DESCRIBE = {
        ALLOY = "Gosh. That's a lot of metal.",
        APORKALYPSE_CLOCK = "It's like a puzzle!",
        ARMOR_METALPLATE = "Sir Webber at your service!",
        ARMOR_WEEVOLE = "For when we need protection.",
        ASPARAGUS_PLANTED = "We should pick those.",
        BASEFAN = "That breeze feels nice on our fur.",
        BONESTAFF = "We could have a staring contest with that scary big snake.",
        CHITIN = "Hope no one's missing that.",
        COFFEE = "Bitter.",
        COFFEEBEANS = "These smell very... adult.",
        COFFEEBEANS_COOKED = "These make me feel funny.",
        CUTNETTLE = "These nettles smell really strong.",
        DUNGBALL = "Yuck!",
        DUNGBEETLE = {
            DEAD = "Awww.",
            GENERIC = "Is that... poop?",
            SLEEPING = "She dozed off.",
            UNDUNGED = "She fell off her poop ball.",
        },
        DUNGPILE = {
            GENERIC = "Oh, poop!",
            PICKED = "No poop.",
        },
        FLOWER_RAINFOREST = "This flower is neat!",
        GLOWFLY = {
            DEAD = "Oh no! It died!",
            GENERIC = "Nice little buggy bug.",
            SLEEPING = "Lights out.",
        },
        GLOWFLY_COCOON = "That looks cozy.",
        GOLDENMACHETE = "What a beautiful blade!",
        GOLDPAN = "Hey, now we can be prospectors.",
        GOLD_DUST = "Wow! I wonder if it's worth anything.",
        GRABBING_VINE = "Cool! Vines!",
        GRASS_TALL = {
            BURNING = "Fire!",
            GENERIC = "It's taller than we are!",
            PICKED = "It's been picked.",
        },
        HALBERD = "Swoosh!",
        HANGING_VINE = "Cool! Vines!",
        ICEDTEA = "Delicious!",
        IRON = "We could make all kinds of neat stuff with this.",
        MACHETE = "Hyah! Hyah!",
        PANGOLDEN = "I think he eats gold.",
        PEAGAWK = {
            DEAD = "I think it's dead.",
            GENERIC = "You've got more eyes than we do!",
            SLEEPING = "Now I can get a good look at its beautiful feathers.",
        },
        PEAGAWKFEATHER = "It's pretty.",
        PEAGAWK_BUSH = "Neat. A weird bush!",
        PIKO = {
            DEAD = "Aww. I liked him.",
            GENERIC = "He's a busy little guy.",
            SLEEPING = "All that running around must have worn him out.",
        },
        PIKO_ORANGE = {
            DEAD = "Aww. I liked him.",
            GENERIC = "I wonder if he likes tea parties.",
            SLEEPING = "All that running around must have worn him out.",
        },
        PUGALISK = "Agh! I think we made him angry!",
        PUGALISK_CORPSE = "We could probably make something out of these bones.",
        PUGALISK_FOUNTAIN = "We could stay a kid forever!",
        PUGALISK_RUINS_PILLAR = "It could fall at any minute.",
        PUGALISK_SKULL = "Kinda creepy.",
        PUGALISK_TRAP_DOOR = "Gotta look where we're going around here.",
        RABID_BEETLE = {
            DEAD = "Well, that's unfortunate.",
            GENERIC = "That guy's got a lot of energy!",
            SLEEPING = "Haha! A bug with a mustache!",
        },
        SEDIMENTPUDDLE = "It's full of sparkly stuff.",
        SHEARS = "It's for chores like trimming hedges or cutting grass.",
        SMELTER = {
            BURNT = "All burned up.",
            COOKING_SHORT = "Yeesh, that's hot!",
            DONE = "It's finished.",
            EMPTY = "Make material with material.",
        },
        SNAKE_BONE = "These are kinda sharp bones.",
        SNAKEBONESOUP = "Kinda tastes like chicken noodle.",
        TEA = "Let's have a tea party!",
        TEATREE = "Hey there, tea tree.",
        TEATREE_NUT = "It helps with our sneezes.",
        TEATREE_NUT_COOKED = "Yummy.",
        TEATREE_NUT_SAPLING = "It's gonna grow up big and strong.",
        TREE_PILLAR = "It's probably super old.",
        WEEVOLE = "Those bugs are annoying.",
        WEEVOLE_CARAPACE = "It's the outer part of those bugs.",
    },
}
