return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It's already in better shape than I am.",
        },
        USEDOOR = {
            GENERIC = "(sigh) Everything is closed to me.",
            LOCKED = "I could find a way in, but why bother.",
        },
    },
    ANNOUCE_ALARMOVER = "I live another day.",
    ANNOUCE_BATS = "The flying mammals of death have appeared.",
    ANNOUCE_OTHERWORLD_DEED = "This is for a house that's not even around here.",
    ANNOUCE_UNDERLEAFCANOPY = "Such gloom...",
    ANNOUNCE_BOAT_DAMAGED = "This vessel is damaged. I can relate.",
    ANNOUNCE_BOAT_SINKING = "I will soon face a watery grave.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I surrender myself to the depths!",
    ANNOUNCE_DEHUMID = {
        "The heat has lifted but my heart has not.",
    },
    ANNOUNCE_GAS_DAMAGE = "cough. I'm done for!",
    ANNOUNCE_HAYFEVER = "Ugh. Even my sinuses are suffering.",
    ANNOUNCE_HAYFEVER_OFF = "My sinuses are clear, but suffering continues.",
    ANNOUNCE_HOUSE_DOOR = "Expansion is out of reach until I get a permit.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "A doorway to doom.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Another disappointment.",
    ANNOUNCE_MYSTERY_FOUND = "There's something here.",
    ANNOUNCE_MYSTERY_NOREWARD = "I'm used to disappointment.",
    ANNOUNCE_NOTHING_FOUND = "Just as I suspected, everything is lost.",
    ANNOUNCE_PICKPOOP = {
        "Sigh.",
        "Ew.",
        "Everything is suffering.",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Sigh. It didn't work.",
        "Why do I bother?",
        "No use trying to break it there.",
    },
    ANNOUNCE_ROOM_STUCK = "I would be trapped forever in this desolate room.",
    ANNOUNCE_SNEEZE = "achoo! achoo! sniff.",
    ANNOUNCE_SUITUP = "I have become Death!",
    ANNOUNCE_TAXDAY = "Time to collect the taxes I imposed on my subjects.",
    ANNOUNCE_TOOLCORRODED = "Alas, death comes even to my tools.",
    ANNOUNCE_TOO_HUMID = {
        "This %s is heavier in the heat.",
        "This %s is too hot. It weighs on my soul.",
    },
    ANNOUNCE_TURFTOOHARD = "Life is too short to deal with such stubbornness.",
    ANNOUNCE_WAVE_BOOST = "Joy...",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Yet death still eludes me (sigh).",
            GENERIC = "Why can't you just leave me be?",
            SLEEPING = "May your dreams be as horrid as you.",
        },
        ALLOY = "Cold and hard, like my existence.",
        ALOE = "It dies so that others may live.",
        ALOE_COOKED = "Cooked cactus.",
        ALOE_PLANTED = "What is that doing here?",
        ALOE_SEEDS = "A tiny seed, full of hope.",
        ANCIENT_HERALD = "The end is nigh.",
        ANCIENT_HULK = "Like Abigail, it has been resurrected from a deep sleep.",
        ANCIENT_REMNANT = "Remnant of a doomsayer.",
        ANCIENT_ROBOTS_ASSEMBLY = "It lays half-dead.",
        ANCIENT_ROBOT_CLAW = "It clutches at my heart.",
        ANCIENT_ROBOT_HEAD = "Headed to death, like all of us.",
        ANCIENT_ROBOT_LEG = "A death stomper.",
        ANCIENT_ROBOT_RIBS = "An undead instrument of death.",
        ANTCHEST = "Still not as sweet as Abigail.",
        ANTQUEEN_THRONE = "There are mysteries hidden within there.",
        APORKALYPSE_CLOCK = "Clockwork for the end of times.",
        ARMORVORTEXCLOAK = "The depths of its darkness is unending.",
        ARMOR_METALPLATE = "Like a metal coffin that keeps me alive.",
        ARMOR_SNAKESKIN = "A jacket of dead flesh. Fashionable.",
        ARMOR_WEEVOLE = "Something died so that this armor may exist.",
        ASPARAGUS_PLANTED = "I should rip those out of the ground.",
        BALLPEIN_HAMMER = "For delicate smashing.",
        BASEFAN = "Alas the relief it brings is only temporary.",
        BILL = {
            DEAD = "Death is inescapable.",
            GENERIC = "A horror.",
            SLEEPING = "I wish it only nightmares.",
        },
        BILL_QUILL = "It's been separated from its animal.",
        BLUNDERBUSS = "An instrument of death.",
        BOATREPAIRKIT = "This could save a boat from destruction, and me with it.",
        BOAT_CARGO = "This transports more junk to nowhere.",
        BOAT_CORK = "I only hope when it sinks, the end will be quick.",
        BOAT_LOGRAFT = "This looks heavy, slow and dangerous.",
        BOAT_ROW = "I wonder how many leagues this can convey me?",
        BOAT_TORCH = "How illuminating.",
        BONESTAFF = "It penetrates into the soul.",
        BRAMBLESPIKE = "Thorny and painful, like life.",
        BRAMBLE_BULB = "Like most things in life, it wasn't worth the effort to get this.",
        BRAMBLE_CORE = "Beauty surrounded by pain and suffering.",
        BURR = "As tenacious as my melancholy.",
        BURR_SAPLING = "Not long for this world.",
        CHITIN = "This shell is poor protection from life's horrors.",
        CITY_LAMP = {
            GENERIC = "It cannot ward off the darkness forever.",
            ON = "A place to hold light.",
        },
        CLAWPALMTREE = "It claws at life.",
        CLAWPALMTREE_SAPLING = "It never gets any better than this, tree.",
        COFFEE = "Dark. Bitter...",
        COFFEEBEANS = "These look stimulating.",
        COFFEEBEANS_COOKED = "Who knew the will to live came in bean form?",
        CORK = "It floats. Like a dead body.",
        CORKCHEST = "Can I fill it with my soul?",
        CUTNETTLE = "I suppose these will cure blocked sinuses.",
        DECO_CHAIR_BENCH = "A place to sit and contemplate my demise.",
        DECO_CHAIR_CLASSIC = "A place to sit and contemplate my demise.",
        DECO_CHAIR_CORNER = "A place to sit and contemplate my demise.",
        DECO_CHAIR_FOOTREST = "A place for weary bones.",
        DECO_CHAIR_HORNED = "A place to sit and contemplate my demise.",
        DECO_CHAIR_LOUNGE = "A place to sit and contemplate my demise.",
        DECO_CHAIR_MASSAGER = "Perfect.",
        DECO_CHAIR_OTTOMAN = "A place for weary bones.",
        DECO_CHAIR_ROCKING = "A place to sit and contemplate my demise.",
        DECO_CHAIR_STUFFED = "A place to sit and contemplate my demise.",
        DISARMING_KIT = "I can outsmart the death traps.",
        DUNGBALL = "Grotesque.",
        DUNGBEETLE = {
            DEAD = "How I envy you.",
            GENERIC = "A symbol of the ugliness of this world.",
            SLEEPING = "Even the hideous sleep sounder than I.",
            UNDUNGED = "Alas, she has fallen from her grotesque perch.",
        },
        DUNGPILE = {
            GENERIC = "There's dreadfulness everywhere.",
            PICKED = "That was... unpleasant.",
        },
        FLOWER_RAINFOREST = "It, too, will wither and die one day.",
        FROGLEGS_POISON = "These poisonous legs will hasten my demise.",
        FROGLEGS_POISON_COOKED = "One can only hope the poison has not left.",
        FROG_POISON = {
            DEAD = "Better me than you.",
            GENERIC = "As grotesque as life itself.",
            SLEEPING = "I hope it has poisoned its own dreams.",
        },
        GASMASKHAT = "It filters air but not despair.",
        GLOWFLY = {
            DEAD = "Its light hath been extinguished forever.",
            GENERIC = "A small light in a dark world.",
            SLEEPING = "Having dark dreams, no doubt.",
        },
        GLOWFLY_COCOON = "If I could climb into a cocoon I would never emerge.",
        GOLDENMACHETE = "What a fancy blade to ruin bamboo with!",
        GOLDPAN = "Offers too much hope.",
        GOLD_DUST = "Death is not sparkly.",
        GRABBING_VINE = "The jungle's noose.",
        GRASS_TALL = {
            BURNING = "Death comes to everything.",
            GENERIC = "Alas, I'm too weak to pick it.",
            PICKED = "All things end.",
        },
        HALBERD = "A terrible weapon for a terrible world.",
        HANGING_VINE = "The jungle's noose.",
        HIPPOPOTAMOOSE = "Even you cannot cheer my heart.",
        HIPPO_ANTLER = "It's been severed from an animal head.",
        ICEDTEA = "Refreshing, but it still does not relieve my grief.",
        INFUSED_IRON = "Nothing surprises me anymore.",
        IRON = "Iron. Like my heart.",
        KINGFISHER = {
            DEAD = "Death knows no mercy.",
            GENERIC = "Thy sharp beak might impale me from the depths of the sea.",
            SLEEPING = "It slumbers, for now.",
        },
        LAWNORNAMENT = {
            BURNING = "Inevitable.",
            BURNT = "For the best.",
            GENERIC = "Decorum is only a mask.",
        },
        LIFEPLANT = "It longs for another life.",
        LILYPAD = "How calm it looks upon the water.",
        LIVING_ARTIFACT = "A death machine has been given life.",
        LOTUS = "It flourishes on the waves of sorrow.",
        LOTUS_FLOWER = "This beauty will also die.",
        LOTUS_FLOWER_COOKED = "Its death was tasty.",
        MACHETE = "This is a lot of blade.",
        MAGNIFYING_GLASS = "For a closer look at life's horrors.",
        MANDRAKEHOUSE = "Abigail lives in the ground too.",
        MANDRAKEMAN = "Another abomination.",
        MEAN_FLYTRAP = {
            DEAD = "If only I were so lucky.",
            GENERIC = "Consume me and be done with it.",
            SLEEPING = "A nightmare asleep and awake.",
        },
        METALPLATEHAT = "It'll protect my head but not my heart.",
        NECTAR_POD = "Is it even worth turning this to honey?",
        OBSIDIAN = "A stone forged of fire.",
        OINC = "What use is wealth?",
        OINC10 = "There are no riches in death.",
        OINC100 = "I can't spend it when I'm dead.",
        PANGOLDEN = "A fool and his gold.",
        PARROT_BLUE = {
            DEAD = "To squawk, to croon, no more.",
            GENERIC = "A parrot as blue as me.",
            SLEEPING = "It slumbers, for now.",
        },
        PEAGAWK = {
            DEAD = "Beautiful death.",
            GENERIC = "Many eyes witness many horrors in life.",
            SLEEPING = "Alas, only a momentary reprieve from life.",
        },
        PEAGAWKFEATHER = "I spy, with my little eye...",
        PEAGAWK_BUSH = "Just a bush...",
        PIGEON = {
            DEAD = "I don't blame you.",
            GENERIC = "A wretched creature.",
            SLEEPING = "What horrors does it dream of?",
        },
        PIGGHOST = "Do you know my sister Abigail?",
        PIGHOUSE_CITY = {
            BURNING = "Destruction wins again.",
            GENERIC = "Shelter won't save you from death.",
        },
        PIGHOUSE_FARM = {
            BURNING = "Doomed.",
            GENERIC = "I wish I could be happy with a pastoral existence.",
        },
        PIGHOUSE_MINE = {
            BURNING = "(sigh) Beautiful destruction.",
            GENERIC = "A home for otherworldly creatures.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "You busy yourself with trivial duties.",
            SLEEPING = "Dreams are just illusions.",
        },
        PIGMAN_QUEEN = "A life of aristocracy is a life empty of meaning.",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Nothing guards against encroaching darkness.",
            SLEEPING = "There's nothing to protect us now.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Life is hopeless.",
            GENERIC = "I bet one could see impending doom from there.",
        },
        PIG_PALACE = "Alas, too good for the likes me.",
        PIG_RUINS_ANT = "Monument to the ants.",
        PIG_RUINS_ARTICHOKE = "What a curious thing.",
        PIG_RUINS_HEAD = "Whoever built it has long gone.",
        PIG_RUINS_IDOL = "An artifact of a long dead culture.",
        PIG_RUINS_PLAQUE = "I could make money off its destruction.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Civil disobedience.",
            GENERIC = "Power corrupts.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Of course.",
            GENERIC = "Power has corrupted me.",
        },
        PIG_SHOP_DELI = {
            BURNING = "That was inevitable.",
            GENERIC = "Food for my belly, but not my soul.",
        },
        PIKO = {
            DEAD = "Even the innocent must die.",
            GENERIC = "Too naive to know pain.",
            SLEEPING = "Such a innocent sleep.",
        },
        PIKO_ORANGE = {
            DEAD = "Even the innocent must die.",
            GENERIC = "You exist to amuse others.",
            SLEEPING = "Such a innocent sleep.",
        },
        POISONBALM = "In case I don't want to succumb to poison. Unlikely.",
        PROP_DOOR = "All doors lead to doom.",
        PUGALISK = "You'll die just like everything else.",
        PUGALISK_CORPSE = "Life is fragile. Even for evil snakes.",
        PUGALISK_FOUNTAIN = "Why would I want to prolong my life?",
        PUGALISK_RUINS_PILLAR = "It's fragile, like life.",
        PUGALISK_SKULL = "Brings me no joy.",
        PUGALISK_TRAP_DOOR = "There's nothing more ominous than death.",
        RABID_BEETLE = {
            DEAD = "Lifeless.",
            GENERIC = "As rabid as death itself.",
            SLEEPING = "Sleep is not a permanent escape from life.",
        },
        RADISH = "The color of my blood.",
        RADISH_COOKED = "It can't taste any worse when it's cooked.",
        RADISH_PLANTED = "I feel like hiding in the ground, too.",
        RADISH_SEEDS = "Why bother?",
        RAINFORESTTREE = {
            BURNING = "It's facing its own mortality.",
            BURNT = "Expired.",
            CHOPPED = "A tree no more.",
            GENERIC = "A tree.",
        },
        RAINFORESTTREE_ROT = "It rots from within and without.",
        REEDS_WATER = "Reeds that grow drowning in the swamps of life.",
        RELIC_1 = "Everything is lost to time, eventually.",
        RELIC_2 = "The remains of a long dead age...",
        RELIC_3 = "A long forgotten relic.",
        RELIC_4 = "Looks like someone who died long ago.",
        RELIC_5 = "Even this doesn't cheer me up.",
        ROCK_BASALT = "A rock from the bowels of the earth.",
        ROCK_FLIPPABLE = "If only I could hide under a rock.",
        ROOTTRUNK_CHILD = "Saves my possessions. But it can't save my heart.",
        SAIL_SNAKESKIN = "Gross, but efficient.",
        SCORPION = {
            DEAD = "You had no purpose in life.",
            GENERIC = "One sting and it could be over.",
            SLEEPING = "I wish you horrid nightmares.",
        },
        SEDIMENTPUDDLE = "Contains unreachable shiny things.",
        SHEARS = "Can it shear my heart?",
        SMELTER = {
            BURNT = "It blazes with more passion than I know.",
            COOKING_SHORT = "They struggle in the fire and brimstone.",
            DONE = "Born of fire.",
            EMPTY = "Burn who are trapped in it...",
        },
        SNAKEBONESOUP = "A broth made from a dead animal.",
        SNAKEOIL = "This fills me with a sense of mistrust.",
        SNAKESKIN = "It shed its skin, with my assistance.",
        SNAKESKINHAT = "A hat of trophies, wrenched from the dead!",
        SNAKE_AMPHIBIOUS = "Snakes are everywhere.",
        SNAKE_BONE = "A reminder of my own mortality.",
        SPIDER_MONKEY = {
            DEAD = "I yearn for what you have.",
            GENERIC = "At least it will be a quick end.",
            SLEEPING = "I hope its nightmares are filled with horror.",
        },
        SPIDER_MONKEY_NEST = "Evil dwells within.",
        SPIDER_MONKEY_TREE = "Evil dwells inside.",
        TEA = "Abigail loved tea parties.",
        TEATREE = "I can sit under it and contemplate life's futility.",
        TEATREE_NUT = "Makes life barely more livable in allergy season.",
        TEATREE_NUT_COOKED = "I killed it to prolong my own life.",
        TEATREE_NUT_SAPLING = "Ah, to be young and full of promise.",
        THUNDERHAT = "Pretty.",
        TOUCAN = "It sings a tortured song.",
        TREE_PILLAR = "Ancient, and full of life.",
        TUBERTREE = "An axe won't kill it.",
        TUBER_BLOOM_CROP = "Pretty flower.",
        TUBER_BLOOM_CROP_COOKED = "Should I eat the flower too?",
        TUBER_CROP = "Will I be dead before it ripens?",
        TUBER_CROP_COOKED = "Perhaps I'm lucky and it's still poisoned.",
        TURF_COBBLEROAD = "Some road.",
        TURF_DEEPRAINFOREST = "Some ground.",
        TURF_DEEPRAINFOREST_NOCANOPY = "Some ground.",
        TURF_FIELDS = "Some ground.",
        TURF_FOUNDATION = "Some ground.",
        TURF_GASJUNGLE = "Some ground.",
        TURF_LAWN = "Some ground.",
        TURF_MOSS = "Some ground.",
        TURF_PAINTED = "Some ground.",
        TURF_PIGRUINS = "Some ground.",
        TURF_PLAINS = "Some ground.",
        TURF_RAINFOREST = "Some ground.",
        VAMPIREBAT = {
            DEAD = "Now you may kill no more.",
            GENERIC = "Take my heart's blood, I've no use for it.",
            SLEEPING = "I wish you nightmares.",
        },
        VAMPIREBATCAVE = "The maw of death itself.",
        VENOMGLAND = "Their dead drop the cure to their sickness.",
        VENUS_STALK = "Objects from a dead thing.",
        VINE = "Unruly life.",
        WALKINGSTICK = "For walking this weary world.",
        WATERDROP = "A drop of life in this bleak existence.",
        WEEVOLE = "Its sole existence is to annoy me.",
        WEEVOLE_CARAPACE = "Bits of bug carcass.",
        WINDOW_GREENHOUSE = "I prefer the dark and windowless depths of my soul.",
        WINDOW_LARGE_SQUARE = "A reminder of the outside.",
        WINDOW_LARGE_SQUARE_CURTAIN = "A reminder of the outside.",
        WINDOW_ROUND = "A cold harsh way to see the outside world.",
        WINDOW_ROUND_BURLAP = "A reminder of the outside.",
        WINDOW_ROUND_CURTAINS_NAILS = "A reminder of the outside.",
        WINDOW_SMALL_PEAKED = "A reminder of the outside.",
        WINDOW_SMALL_PEAKED_CURTAIN = "A reminder of the outside.",
        WINDOW_TALL = "A reminder of the outside.",
        WINDOW_TALL_CURTAIN = "A reminder of the outside.",
    },
}
