return {
    ANNOUNCE_DEHUMID = {
        "Whew. I forgot what it felt like to breathe.",
    },
    ANNOUNCE_HAYFEVER = "Allergiesch. What allergiesch?",
    ANNOUNCE_HAYFEVER_OFF = "My face stopped leaking. Allergy season must be over.",
    ANNOUNCE_PICKPOOP = {
        "Swell.",
        "Just great.",
        "I'll put this in my memoir.",
    },
    ANNOUNCE_SNEEZE = "AchooOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is suffocating.",
        "This %s is just too hot!",
    },
    DESCRIBE = {
        ALLOY = "Heavy metal made heavier.",
        ANTQUEEN_THRONE = "I bet she was guarding some kind of treasure.",
        APORKALYPSE_CLOCK = "If only I could turn time back to before I crashed here.",
        ARMOR_METALPLATE = "Oof. It's heavier than ballast.",
        ARMOR_WEEVOLE = "If only it had those bug wings.",
        ASPARAGUS_PLANTED = "That looks like food! Let's hope it tastes like food.",
        BALLPEIN_HAMMER = "So cute and convenient.",
        BASEFAN = "A plane propeller would be better.",
        CHITIN = "I'm going to need more of these.",
        CUTNETTLE = "Smells like relief.",
        DUNGBALL = "Huh. It's almost like nobody wants a ball of poop.",
        DUNGBEETLE = {
            DEAD = "Someone should write a eulogy. Not me, but someone.",
            GENERIC = "Swell. A giant bug on a giant ball of poop.",
            SLEEPING = "Just screaming to be stepped on.",
            UNDUNGED = "At least it smells a little better now.",
        },
        DUNGPILE = {
            GENERIC = "Normally I'm all for getting my hands dirty but...",
            PICKED = "What happens in the jungle, stays in the jungle.",
        },
        FLOWER_RAINFOREST = "You can never have too many flowers. Or projectiles.",
        GLOWFLY = {
            DEAD = "I guess it can't fly me out of here now.",
            GENERIC = "A flyer and a glower. My new best friend.",
            SLEEPING = "Wake up and glow for me!",
        },
        GLOWFLY_COCOON = "Aww... It's wrapped up all nice and cozy.",
        GOLDENMACHETE = "For the sophisticated adventurer.",
        GOLDPAN = "Swell. A pan with holes in it.",
        GOLD_DUST = "Hardly worth holding onto. If I could find more of it though...",
        GRABBING_VINE = "If I didn't know any better, I'd think that vine wants my stuff.",
        GRASS_TALL = {
            BURNING = "All those bugs have nowhere to hide now.",
            GENERIC = "Tall grass like that is going to need a machete.",
            PICKED = "It'll be overgrown in no time.",
        },
        HALBERD = "The must-have multi-tool for adventurers.",
        HANGING_VINE = "Vines. Gotta love 'em.",
        IRON = "Well it's not good balloon material.",
        MACHETE = "Machete. Designed for adventure.",
        PANGOLDEN = "I don't actually mind picking up his poop.",
        PEAGAWK = {
            DEAD = "I promise, I will go on without you!",
            GENERIC = "Has the eyesight for flying but not the wings for it.",
            SLEEPING = "Maybe I can just pluck out one of those feathers...",
        },
        PEAGAWKFEATHER = "Normally I don't mind feathers, but this one keeps staring at me.",
        PEAGAWK_BUSH = "Something's hiding in there.",
        PIG_RUINS_ARTICHOKE = "Strange thing to make a statue out of.",
        PIG_RUINS_HEAD = "Missing something... like its body.",
        PIG_RUINS_IDOL = "I'll need to get that totem free to take it back to the pigs.",
        PIG_RUINS_PIG = "Oooh! Look at those golden teeth!",
        PIG_RUINS_PLAQUE = "The pigs only want the top part. How do I get it free?",
        RABID_BEETLE = {
            DEAD = "Not too sorry about that.",
            GENERIC = "Probably just agitated because it can't fly well.",
            SLEEPING = "Quite the snorer.",
        },
        RELIC_1 = {
            GENERIC = "Looks like something the pig history buffs would like.",
            SUNKEN = "I'll need something to fish it out with.",
        },
        RELIC_2 = {
            GENERIC = "Pig history. Someone's bound to love this.",
            SUNKEN = "I'm hoping that's not a really big fish.",
        },
        RELIC_3 = {
            GENERIC = "This belongs in a museum.",
            SUNKEN = "How am I going to get it out of there?",
        },
        RELIC_4 = "Looks fancy. And royal. And it looks like a pig.",
        RELIC_5 = "Well it's valuable to someone.",
        SEDIMENTPUDDLE = "A sparkly pool. A little too sparkly.",
        SHEARS = "Time to do some yard work.",
        SMELTER = {
            BURNT = "No one ever accused me of being a good blacksmith.",
            COOKING_SHORT = "It'll be done in short order.",
            DONE = "Legendary adventurers forge legendary equipment, which sounds pretty good.",
            EMPTY = "It takes the heavy metal and makes it heavier.",
        },
        TREE_PILLAR = "That's a big tree.",
        WEEVOLE = "Aggravating bugs! A complete waste of wings.",
        WEEVOLE_CARAPACE = "Light enough to fire out the Pew-matic.",
    },
}
