return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It's not going to get fixed any more than it already is.",
        },
        USEDOOR = {
            GENERIC = "Swell. A door that won't open.",
            LOCKED = "I'll find a way to open it, somehow.",
        },
    },
    ANNOUCE_BATS = "Flying rats. This should be exciting.",
    ANNOUNCE_BOAT_DAMAGED = "Swell. I'm taking on water.",
    ANNOUNCE_BOAT_SINKING = "I'm up to my socks in seawater!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Is this the end of Maybelle Dorothea Wheeler?",
    ANNOUNCE_DEHUMID = {
        "Whew. I forgot what it felt like to breathe.",
    },
    ANNOUNCE_HAYFEVER = "Allergiesch. What allergiesch?",
    ANNOUNCE_HAYFEVER_OFF = "My face stopped leaking. Allergy season must be over.",
    ANNOUNCE_PICKPOOP = {
        "Swell.",
        "Just great.",
        "I'll put this in my memoir.",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Agh. It has to have a soft spot somewhere!",
        "No good, I need another way!",
        "Think, Wheeler, think!",
    },
    ANNOUNCE_SNEEZE = "AchooOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is suffocating.",
        "This %s is just too hot!",
    },
    ANNOUNCE_WAVE_BOOST = {
        "WOOHOO!!!",
        "I NEVER WANT THIS TO END!",
        "ADVENTUUUURE!",
    },
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "I'm not going to cry over that.",
            GENERIC = "Excuse me while I avoid you entirely.",
            SLEEPING = "Sleeping on the job. Not that I have a problem with that.",
        },
        ALLOY = "Heavy metal made heavier.",
        ANCIENT_HULK = "I probably should have let you sleep.",
        ANCIENT_ROBOTS_ASSEMBLY = "How much am I going to regret putting that all together?",
        ANCIENT_ROBOT_CLAW = "Where's the rest of you?",
        ANCIENT_ROBOT_HEAD = "Are you aware you're missing the rest of your body?",
        ANCIENT_ROBOT_LEG = "Well, it's better facing two left feet.",
        ANCIENT_ROBOT_RIBS = "I like it better when it's not awake.",
        APORKALYPSE_CLOCK = "If only I could turn time back to before I crashed here.",
        ARMOR_METALPLATE = "Oof. It's heavier than ballast.",
        ARMOR_WEEVOLE = "If only it had those bug wings.",
        ASPARAGUS_PLANTED = "That looks like food! Let's hope it tastes like food.",
        BALLPEIN_HAMMER = "So cute and convenient.",
        BASEFAN = "A plane propeller would be better.",
        BILL = {
            DEAD = "Spun himself to death.",
            GENERIC = "Excuse me while I avoid your quills.",
            SLEEPING = "Stay asleep so I can get that lotus flower.",
        },
        BILL_QUILL = "You could poke someone's eye out with this.",
        BOATREPAIRKIT = "Swell. Because cork is known for its durability.",
        BOAT_CARGO = "Now all my things can go adventuring with me.",
        BOAT_CORK = "About as stable as a cork balloon.",
        BOAT_LOGRAFT = "About as stable as a wooden balloon.",
        BOAT_ROW = "If only I had oars for my balloon.",
        BOAT_TORCH = "Open fire on a wooden boat. The most adventurous thing I've ever done.",
        BONESTAFF = "Look into its eye...",
        CHITIN = "I'm going to need more of these.",
        COFFEE = "Because there's no better time to be jumpy than when you're on an adventure.",
        COFFEEBEANS = "Small enough to fit in the Pew-matic.",
        COFFEEBEANS_COOKED = "I eat these all the time during overnight flights.",
        CUTNETTLE = "Smells like relief.",
        DISARMING_KIT = "Adventuring kit.",
        DUNGBALL = "Huh. It's almost like nobody wants a ball of poop.",
        DUNGBEETLE = {
            DEAD = "Someone should write a eulogy. Not me, but someone.",
            GENERIC = "Swell. A giant bug on a giant ball of poop.",
            SLEEPING = "Just screaming to be stepped on.",
            UNDUNGED = "At least it smells a little better now.",
        },
        DUNGPILE = {
            GENERIC = "Normally I'm all for getting my hands dirty but...",
            PICKED = "What happens in the jungle, stays in the jungle.",
        },
        FLOWER_RAINFOREST = "You can never have too many flowers. Or projectiles.",
        FROGLEGS_POISON = "How adventurous am I feeling today?",
        FROGLEGS_POISON_COOKED = "Meat on a stick. Well... a bone.",
        FROG_POISON = {
            DEAD = "Gotta be honest, I'm not going to miss you.",
            GENERIC = "Are you aware of how annoying you are?",
            SLEEPING = "Probably dreaming of stealing my stuff.",
        },
        GLOWFLY = {
            DEAD = "I guess it can't fly me out of here now.",
            GENERIC = "A flyer and a glower. My new best friend.",
            SLEEPING = "Wake up and glow for me!",
        },
        GLOWFLY_COCOON = "Aww... It's wrapped up all nice and cozy.",
        GOLDENMACHETE = "For the sophisticated adventurer.",
        GOLDPAN = "Swell. A pan with holes in it.",
        GOLD_DUST = "Hardly worth holding onto. If I could find more of it though...",
        GRABBING_VINE = "If I didn't know any better, I'd think that vine wants my stuff.",
        GRASS_TALL = {
            BURNING = "All those bugs have nowhere to hide now.",
            GENERIC = "Tall grass like that is going to need a machete.",
            PICKED = "It'll be overgrown in no time.",
        },
        HALBERD = "The must-have multi-tool for adventurers.",
        HANGING_VINE = "Vines. Gotta love 'em.",
        HIPPOPOTAMOOSE = "He likes making waves.",
        HIPPO_ANTLER = "Maybe I could use it as a hatrack. Or a hat.",
        ICEDTEA = "I prefer it cold anyway.",
        INFUSED_IRON = "Was it glowing like that before?",
        IRON = "Well it's not good balloon material.",
        KINGFISHER = {
            DEAD = "I'll miss him.",
            GENERIC = "What an aerodynamic beak!",
            SLEEPING = "Like me, it probably dreams of flying.",
        },
        LIFEPLANT = "You stay right there until I need you.",
        LILYPAD = "A little too heavy to use for a balloon.",
        LIVING_ARTIFACT = "An invitation to adventure.",
        LOTUS = "Almost worth getting my feet wet for that.",
        LOTUS_FLOWER = "Looks edible.",
        LOTUS_FLOWER_COOKED = "Not the first time I've eaten flowers.",
        MACHETE = "Machete. Designed for adventure.",
        MAGNIFYING_GLASS = "For finding the tiny hidden treasures. And burning stuff.",
        MANDRAKEHOUSE = "Have you ever seen anything scream \"adventure\" louder?",
        MANDRAKEMAN = "Mind not eating me, I have adventuring to do.",
        MEAN_FLYTRAP = {
            DEAD = "It died so young. So young and so horrible.",
            GENERIC = "I like you guys better when you're old and can't move around so much.",
            SLEEPING = "All tuckered out after a day of terrorizing.",
        },
        METALPLATEHAT = "Saves me head pain but gives me neck pain.",
        NECTAR_POD = "Now to find something that'll make this into something good.",
        OINC = "Good for buying projectiles. Or being projectiles.",
        OINC10 = "Moving up in the world.",
        OINC100 = "You know what Wheeler, you deserve a treat.",
        PANGOLDEN = "I don't actually mind picking up his poop.",
        PARROT_BLUE = {
            DEAD = "Rests in peace.",
            GENERIC = "Beautiful wings. Can I use 'em?",
            SLEEPING = "Sweet dreams.",
        },
        PEAGAWK = {
            DEAD = "I promise, I will go on without you!",
            GENERIC = "Has the eyesight for flying but not the wings for it.",
            SLEEPING = "Maybe I can just pluck out one of those feathers...",
        },
        PEAGAWKFEATHER = "Normally I don't mind feathers, but this one keeps staring at me.",
        PEAGAWK_BUSH = "Something's hiding in there.",
        PIGEON = {
            DEAD = "Always sad to see a fellow flyer go down.",
            GENERIC = "Fly! Fly away from here! And take me with you.",
            SLEEPING = "Probably having one of those flying dreams.",
        },
        PIGHOUSE_CITY = {
            BURNING = "Someone's having a bad day.",
            GENERIC = "As pig houses go, it's decent enough.",
        },
        PIGHOUSE_FARM = {
            BURNING = "They're not sleeping there tonight.",
            GENERIC = "I thought they would've built their home out of straw.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Huh. Wouldn't think stone would burn that well.",
            GENERIC = "Looks like they put all those rocks into building a house.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "In all my adventures, I've never been able to escape bureaucracy.",
            SLEEPING = "You'd think a fancy pig like him would have a home to go to.",
        },
        PIG_PALACE = "Ohh! A castle adventure. I love those.",
        PIG_RUINS_ARTICHOKE = "Strange thing to make a statue out of.",
        PIG_RUINS_HEAD = "Missing something... like its body.",
        PIG_RUINS_IDOL = "I'll need to get that totem free to take it back to the pigs.",
        PIG_RUINS_PLAQUE = "The pigs only want the top part. How do I get it free?",
        PIG_SHOP_CITYHALL = {
            BURNING = "That'll cost some tax dollars to fix.",
            GENERIC = "The big pig building in this small pond.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "My schedule just got wide open.",
            GENERIC = "Mayor by day, adventurer by night.",
        },
        PIKO = {
            DEAD = "Sad. It only wanted to steal things.",
            GENERIC = "Has more storage space in its cheeks than I do in my pockets.",
            SLEEPING = "At least it doesn't steal in its sleep.",
        },
        PIKO_ORANGE = {
            DEAD = "Sad. It only wanted to steal things.",
            GENERIC = "Has a strangely caffeinated smell.",
            SLEEPING = "At least it doesn't steal in its sleep.",
        },
        PUGALISK = "Time to use those dodging skills, Wheeler.",
        PUGALISK_CORPSE = "It conveniently dug its own grave.",
        PUGALISK_FOUNTAIN = "The legendary Fountain of Youth! I've found it.",
        PUGALISK_RUINS_PILLAR = "Looks sturdy enough.",
        PUGALISK_SKULL = "It's dead. Why do I feel like it's still staring at me?",
        PUGALISK_TRAP_DOOR = "That looks... ominous.",
        RABID_BEETLE = {
            DEAD = "Not too sorry about that.",
            GENERIC = "Probably just agitated because it can't fly well.",
            SLEEPING = "Quite the snorer.",
        },
        REEDS_WATER = "Definitely going to need more of these.",
        RELIC_1 = {
            GENERIC = "Looks like something the pig history buffs would like.",
            SUNKEN = "I'll need something to fish it out with.",
        },
        RELIC_2 = {
            GENERIC = "Pig history. Someone's bound to love this.",
            SUNKEN = "I'm hoping that's not a really big fish.",
        },
        RELIC_3 = {
            GENERIC = "This belongs in a museum.",
            SUNKEN = "How am I going to get it out of there?",
        },
        RELIC_4 = "Looks fancy. And royal. And it looks like a pig.",
        RELIC_5 = "Well it's valuable to someone.",
        SAIL_SNAKESKIN = "Too heavy for balloon material. Just right for a sail.",
        SCORPION = {
            DEAD = "I'll be honest, I don't care.",
            GENERIC = "Keep your stinger to yourself, mister!",
            SLEEPING = "I'll just sneak by...",
        },
        SEDIMENTPUDDLE = "A sparkly pool. A little too sparkly.",
        SHEARS = "Time to do some yard work.",
        SMELTER = {
            BURNT = "No one ever accused me of being a good blacksmith.",
            COOKING_SHORT = "It'll be done in short order.",
            DONE = "Legendary adventurers forge legendary equipment, which sounds pretty good.",
            EMPTY = "It takes the heavy metal and makes it heavier.",
        },
        SNAKEBONESOUP = "A good soup made from bad things.",
        SNAKEOIL = "I know it's a fake, but I still just have to try it!",
        SNAKESKIN = "Soft. Supple. Not currently attached to a snake. I like it!",
        SNAKE_AMPHIBIOUS = "Don't want to bother you. I'll just be on my way.",
        SNAKE_BONE = "No meat on this bone, but I bet it'd be good for a soup.",
        TEA = "You can barely taste the rodent.",
        TEATREE = "But how do I make tea from it?",
        TEATREE_NUT = "Good enough to eat. Or fire out the Pew-matic.",
        TEATREE_NUT_COOKED = "For chewing or pew-ing.",
        TEATREE_NUT_SAPLING = "It's a baby tree. It'll grow.",
        TOUCAN = "If you can fly with that big beak, maybe you can handle flying a person.",
        TREE_PILLAR = "That's a big tree.",
        VAMPIREBAT = {
            DEAD = "Grounded for good.",
            GENERIC = "A misuse of flying abilities.",
            SLEEPING = "If I could only steal its wings while its asleep.",
        },
        VAMPIREBATCAVE = "Those bats are wasting their time in a cave when they should be outside flying.",
        VENOMGLAND = "Swell. A sack of goop from an animal.",
        VENUS_STALK = "Hope this comes in handy. Otherwise that flytrap died for nothing.",
        VINE = "The kind of thing that would be more useful if I had a bunch of them.",
        WALKINGSTICK = "Dried flytrap stalks really put a spring in my step.",
        WATERDROP = "Another life of adventure!",
        WEEVOLE = "Aggravating bugs! A complete waste of wings.",
        WEEVOLE_CARAPACE = "Light enough to fire out the Pew-matic.",
    },
}
