return {
    ANNOUNCE_BOAT_DAMAGED = "Swell. I'm taking on water.",
    ANNOUNCE_BOAT_SINKING = "I'm up to my socks in seawater!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Is this the end of Maybelle Dorothea Wheeler?",
    ANNOUNCE_DEHUMID = {
        "Whew. I forgot what it felt like to breathe.",
    },
    ANNOUNCE_HAYFEVER = "Allergiesch. What allergiesch?",
    ANNOUNCE_HAYFEVER_OFF = "My face stopped leaking. Allergy season must be over.",
    ANNOUNCE_PICKPOOP = {
        "Swell.",
        "Just great.",
        "I'll put this in my memoir.",
    },
    ANNOUNCE_SNEEZE = "AchooOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is suffocating.",
        "This %s is just too hot!",
    },
    ANNOUNCE_WAVE_BOOST = {
        "WOOHOO!!!",
        "I NEVER WANT THIS TO END!",
        "ADVENTUUUURE!",
    },
    DESCRIBE = {
        ALLOY = "Heavy metal made heavier.",
        APORKALYPSE_CLOCK = "If only I could turn time back to before I crashed here.",
        ARMOR_METALPLATE = "Oof. It's heavier than ballast.",
        ARMOR_WEEVOLE = "If only it had those bug wings.",
        ASPARAGUS_PLANTED = "That looks like food! Let's hope it tastes like food.",
        BASEFAN = "A plane propeller would be better.",
        BOATREPAIRKIT = "Swell. Because cork is known for its durability.",
        BOAT_CARGO = "Now all my things can go adventuring with me.",
        BOAT_CORK = "About as stable as a cork balloon.",
        BOAT_LOGRAFT = "About as stable as a wooden balloon.",
        BOAT_ROW = "If only I had oars for my balloon.",
        BOAT_TORCH = "Open fire on a wooden boat. The most adventurous thing I've ever done.",
        CHITIN = "I'm going to need more of these.",
        COFFEE = "Because there's no better time to be jumpy than when you're on an adventure.",
        COFFEEBEANS = "Small enough to fit in the Pew-matic.",
        COFFEEBEANS_COOKED = "I eat these all the time during overnight flights.",
        CUTNETTLE = "Smells like relief.",
        DUNGBALL = "Huh. It's almost like nobody wants a ball of poop.",
        DUNGBEETLE = {
            DEAD = "Someone should write a eulogy. Not me, but someone.",
            GENERIC = "Swell. A giant bug on a giant ball of poop.",
            SLEEPING = "Just screaming to be stepped on.",
            UNDUNGED = "At least it smells a little better now.",
        },
        DUNGPILE = {
            GENERIC = "Normally I'm all for getting my hands dirty but...",
            PICKED = "What happens in the jungle, stays in the jungle.",
        },
        FLOWER_RAINFOREST = "You can never have too many flowers. Or projectiles.",
        GLOWFLY = {
            DEAD = "I guess it can't fly me out of here now.",
            GENERIC = "A flyer and a glower. My new best friend.",
            SLEEPING = "Wake up and glow for me!",
        },
        GLOWFLY_COCOON = "Aww... It's wrapped up all nice and cozy.",
        GOLDENMACHETE = "For the sophisticated adventurer.",
        GOLDPAN = "Swell. A pan with holes in it.",
        GOLD_DUST = "Hardly worth holding onto. If I could find more of it though...",
        GRABBING_VINE = "If I didn't know any better, I'd think that vine wants my stuff.",
        GRASS_TALL = {
            BURNING = "All those bugs have nowhere to hide now.",
            GENERIC = "Tall grass like that is going to need a machete.",
            PICKED = "It'll be overgrown in no time.",
        },
        HALBERD = "The must-have multi-tool for adventurers.",
        HANGING_VINE = "Vines. Gotta love 'em.",
        ICEDTEA = "I prefer it cold anyway.",
        IRON = "Well it's not good balloon material.",
        LILYPAD = "A little too heavy to use for a balloon.",
        MACHETE = "Machete. Designed for adventure.",
        PANGOLDEN = "I don't actually mind picking up his poop.",
        PEAGAWK = {
            DEAD = "I promise, I will go on without you!",
            GENERIC = "Has the eyesight for flying but not the wings for it.",
            SLEEPING = "Maybe I can just pluck out one of those feathers...",
        },
        PEAGAWKFEATHER = "Normally I don't mind feathers, but this one keeps staring at me.",
        PEAGAWK_BUSH = "Something's hiding in there.",
        PIKO = {
            DEAD = "Sad. It only wanted to steal things.",
            GENERIC = "Has more storage space in its cheeks than I do in my pockets.",
            SLEEPING = "At least it doesn't steal in its sleep.",
        },
        PIKO_ORANGE = {
            DEAD = "Sad. It only wanted to steal things.",
            GENERIC = "Has a strangely caffeinated smell.",
            SLEEPING = "At least it doesn't steal in its sleep.",
        },
        RABID_BEETLE = {
            DEAD = "Not too sorry about that.",
            GENERIC = "Probably just agitated because it can't fly well.",
            SLEEPING = "Quite the snorer.",
        },
        SAIL_SNAKESKIN = "Too heavy for balloon material. Just right for a sail.",
        SEDIMENTPUDDLE = "A sparkly pool. A little too sparkly.",
        SHEARS = "Time to do some yard work.",
        SMELTER = {
            BURNT = "No one ever accused me of being a good blacksmith.",
            COOKING_SHORT = "It'll be done in short order.",
            DONE = "Legendary adventurers forge legendary equipment, which sounds pretty good.",
            EMPTY = "It takes the heavy metal and makes it heavier.",
        },
        SNAKESKIN = "Soft. Supple. Not currently attached to a snake. I like it!",
        TEA = "You can barely taste the rodent.",
        TEATREE = "But how do I make tea from it?",
        TEATREE_NUT = "Good enough to eat. Or fire out the Pew-matic.",
        TEATREE_NUT_COOKED = "For chewing or pew-ing.",
        TEATREE_NUT_SAPLING = "It's a baby tree. It'll grow.",
        TREE_PILLAR = "That's a big tree.",
        WEEVOLE = "Aggravating bugs! A complete waste of wings.",
        WEEVOLE_CARAPACE = "Light enough to fire out the Pew-matic.",
    },
}
