return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Tip top!",
        },
        USEDOOR = {
            GENERIC = "I am unable to open this.",
            LOCKED = "Requires something to unlock it.",
        },
    },
    ANNOUCE_ALARMOVER = "The danger has passed.",
    ANNOUCE_BATS = "Desmodus rotundus!",
    ANNOUCE_OTHERWORLD_DEED = "I don't recognize where this is.",
    ANNOUCE_UNDERLEAFCANOPY = "The forest canopy has blocked the light.",
    ANNOUNCE_BOAT_DAMAGED = "My vessel is deteriorating!",
    ANNOUNCE_BOAT_SINKING = "I do believe this boat is sinking.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I had best head for shore! Now!",
    ANNOUNCE_DEHUMID = {
        "Ah... that breeze is nice.",
    },
    ANNOUNCE_GAS_DAMAGE = "Ahem. Cough. Ahem. Ahem.",
    ANNOUNCE_HAYFEVER = "Sniff sniff. Must be hayfever season.",
    ANNOUNCE_HAYFEVER_OFF = "Ahh... Finally I can breathe.",
    ANNOUNCE_HOUSE_DOOR = "I require a permit to build another wing.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "I've found a door.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Nothing here.",
    ANNOUNCE_MYSTERY_FOUND = "I have found something.",
    ANNOUNCE_MYSTERY_NOREWARD = "Failure is an important part of discovery.",
    ANNOUNCE_NOTHING_FOUND = "Nothing of what I seek is in my current surroundings.",
    ANNOUNCE_PICKPOOP = {
        "I never!",
        "Disgusting!",
        "What a horrid smell!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That spot won't break.",
        "There must be a better spot to hit it.",
        "It can't be completely invulnerable?",
    },
    ANNOUNCE_ROOM_STUCK = "I'd be trapped here. With all my books. At last...",
    ANNOUNCE_SNEEZE = "Ahh... CHOOOOOOOOO!",
    ANNOUNCE_SUITUP = "I'd rather be reading!",
    ANNOUNCE_TAXDAY = "Tax day! Time to collect for the public good.",
    ANNOUNCE_TOOLCORRODED = "My tool has deteriorated.",
    ANNOUNCE_TOO_HUMID = {
        "This %s is unbearable.",
        "This %s makes it too hot.",
    },
    ANNOUNCE_TURFTOOHARD = "It's too hard for me to move.",
    ANNOUNCE_WAVE_BOOST = "Prime oceanic oscillations!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "It has expired.",
            GENERIC = "This Dionaea has reached maturation.",
            SLEEPING = "I'm curious as to why it requires sleep.",
        },
        ALLOY = "Iron that has gone through metallic bonding.",
        ALOE = "Aloe. A plant with many uses.",
        ALOE_COOKED = "It's been known to have restorative properties.",
        ALOE_PLANTED = "That will certainly come in handy.",
        ALOE_SEEDS = "The seed to some kind of succulent.",
        ANCIENT_HERALD = "A harbinger of some sort.",
        ANCIENT_HULK = "It must be using some sort of ancient technology.",
        ANCIENT_REMNANT = "A material with metaphysical properties.",
        ANCIENT_ROBOTS_ASSEMBLY = "Appears to be only partially assembled.",
        ANCIENT_ROBOT_CLAW = "The paw of some metal goliath.",
        ANCIENT_ROBOT_HEAD = "The skull of an iron automata.",
        ANCIENT_ROBOT_LEG = "Appears to be a automaton appendage.",
        ANCIENT_ROBOT_RIBS = "An iron contraption.",
        ANTCHEST = "A particularly sticky facilitator of honey.",
        ANTCOMBHOME = "A fascinating insectoid habitat.",
        ANTMAN = {
            DEAD = "It has ceased functioning.",
            GENERIC = "They've developed an entirely unique language.",
            SLEEPING = "It is hibernating.",
        },
        ANTMAN_WARRIOR = "A particularly aggressive colony defender.",
        ANTMASKHAT = "This may be slightly unethical.",
        ANTQUEEN_THRONE = "I should like to examine that a little closer.",
        ANTSUIT = "A hollowed out arthropod.",
        ANT_CAVE_LANTERN = "What a curious light source!",
        APORKALYPSE_CLOCK = "Ah. Quite a complex form of clockwork.",
        ARMORVORTEXCLOAK = "So roomy. I can fit all my books in here.",
        ARMOR_METALPLATE = "What era is this design from?",
        ARMOR_SNAKESKIN = "Fauna-inspired rainwear.",
        ARMOR_WEEVOLE = "Armour made from bug exoskeleton.",
        ASPARAGUS_PLANTED = "Asparagus. Otherwise known as sparrow grass.",
        BALLPEIN_HAMMER = "I could use this for more delicate jobs.",
        BANDITHAT = "Perhaps it has hidden strengths.",
        BANDITMAP = "I do enjoy a good mystery.",
        BANDITTREASURE = "What delightful surprises are in there?",
        BASEFAN = "Restorative.",
        BATHAT = "Rather clever use of echolocation.",
        BILL = {
            DEAD = "It's deceased.",
            GENERIC = "Of the Ornithorhynchidae family I believe.",
            SLEEPING = "I won't wake it.",
        },
        BILL_QUILL = "An Ornithorhynchidae quill.",
        BLUNDERBUSS = "An historically accurate reproduction.",
        BOATREPAIRKIT = "Extends the life of aquatic vessels.",
        BOAT_CARGO = "I can store a few extra books aboard.",
        BOAT_CORK = "I suppose it's safe for a quick trip up the river.",
        BOAT_LOGRAFT = "Crude nautical transport.",
        BOAT_ROW = "My vessel for marine research.",
        BOAT_TORCH = "To better observe the nocturnal sea life.",
        BONESTAFF = "Contains a potent stare.",
        BRAMBLESPIKE = "It could be a member of the Rosaceae family.",
        BRAMBLE_BULB = "Pity I cannot replant it.",
        BRAMBLE_CORE = "It appears to spawn near those prickly vines.",
        BUGREPELLENT = "An efficient insecticide.",
        BURR = "It ought to grow into a full-fledged plant.",
        BURR_SAPLING = "It is growing well.",
        CANDLEHAT = "A portable reading light.",
        CHITIN = "The exoskeleton of an arthropod.",
        CITY_HAMMER = "The tool of a destructive civil engineer.",
        CITY_LAMP = {
            GENERIC = "Quite radiant.",
            ON = "A dormant street lamp.",
        },
        CLAWPALMTREE = "Some form of Arecaceae.",
        CLAWPALMTREE_SAPLING = "Requires quite a bit of care.",
        CLIPPINGS = "Surplus clippings to be used in bartering.",
        COFFEE = "I do love a cup of coffee and a good book.",
        COFFEEBEANS = "Very high in caffeine.",
        COFFEEBEANS_COOKED = "Ahh, that roast smells delightful.",
        CONSTRUCTION_PERMIT = "For a new wing to my library.",
        CORK = "Odd. Quercus suber material from a Arecaceae.",
        CORKCHEST = "It should keep the vermin out.",
        CORK_BAT = "A lightweight instrument for bludgeoning.",
        CUTNETTLE = "These are quite good for the sinuses.",
        DECO_CAVE_BAT_BURROW = "I believe there are bats within.",
        DECO_CAVE_BEAM_ROOM = "A functional beam.",
        DECO_CHAIR_BENCH = "A nice place to read a book.",
        DECO_CHAIR_CLASSIC = "A nice place to read a book.",
        DECO_CHAIR_CORNER = "A nice place to read a book.",
        DECO_CHAIR_FOOTREST = "A nice place to put up your feet.",
        DECO_CHAIR_HORNED = "A nice place to read a book.",
        DECO_CHAIR_LOUNGE = "A nice place to read a book.",
        DECO_CHAIR_MASSAGER = "I would avoid that.",
        DECO_CHAIR_OTTOMAN = "A nice place to put up your feet.",
        DECO_CHAIR_ROCKING = "A nice place to read a book.",
        DECO_CHAIR_STUFFED = "A nice place to read a book.",
        DECO_RUINS_BEAM_ROOM = "A functional beam.",
        DECO_RUINS_BEAM_ROOM_BLUE = "Appears stable.",
        DECO_RUINS_ENDSWELL = "Quite brackish water.",
        DECO_RUINS_FOUNTAIN = "Normally I don't like to take chances.",
        DEED = "Ah, somewhere to leave my extensive library.",
        DEMOLITION_PERMIT = "A permit for renovations. Perhaps a non-fiction section.",
        DISARMING_KIT = "Rather clever.",
        DISGUISEHAT = "Clever.",
        DUG_NETTLE = "I'll have to plant this.",
        DUNGBALL = "A perfectly spherical specimen of feces.",
        DUNGBEETLE = {
            DEAD = "A Scarabaeidae cadaver.",
            GENERIC = "Scarabaeidae with her droppings.",
            SLEEPING = "At rest.",
            UNDUNGED = "She's lost her dung.",
        },
        DUNGPILE = {
            GENERIC = "Scarabaeidae will make short work of it.",
            PICKED = "Odious, yet useful.",
        },
        FEATHER_THUNDER = "I could use this as a bookmark.",
        FLOWER_RAINFOREST = "Floral cross-pollination produces some fascinating specimens.",
        FROGLEGS_POISON = "Agalychnis callidryas is not poisonous, but it may not be Agalychnis callidryas.",
        FROGLEGS_POISON_COOKED = "I'm not convinced the poison has left.",
        FROG_POISON = {
            DEAD = "An amphibian carcass.",
            GENERIC = "Curious... Agalychnis callidryas should be arboreal, not aquatic.",
            SLEEPING = "It seems quite lethargic at this time of day.",
        },
        GASCLOUD = "A nimbus of contaminated air.",
        GASMASKHAT = "For investigating dangerous areas.",
        GLOWFLY = {
            DEAD = "Its existence has reached an end.",
            GENERIC = "A bioluminescent insecta.",
            SLEEPING = "Curious. Its bioluminescence requires wakefulness.",
        },
        GLOWFLY_COCOON = "Fascinating! It has moved on to the chrysalis stage.",
        GNAT = "A swarm of Culicidae Drosophila.",
        GNATMOUND = "Obviously the work of a eusocial insect.",
        GOLDENMACHETE = "The most malleable of metals, but let's see how it slices.",
        GOLDPAN = "This should be useful for finding valuable minerals.",
        GOLD_DUST = "Small particles of the shiniest element.",
        GRABBING_VINE = "Hanging vines from the forest canopy.",
        GRASS_TALL = {
            BURNING = "Illuminating!",
            GENERIC = "I need an implement for that.",
            PICKED = "That required not insignificant effort.",
        },
        HALBERD = "It is a cruel and versatile weapon.",
        HANGING_VINE = "Hanging vines from the forest canopy.",
        HEDGE = {
            BURNING = "Engulfed in flames.",
            BURNT = "The vestige of burnt shrubbery.",
            GENERIC = "What an excellent topiary!",
            SHAVEABLE = "I believe it could do with a trim.",
        },
        HIPPOPOTAMOOSE = "A Hippopotamidae Capreolinae!",
        HIPPO_ANTLER = "Belongs to a Hippoptamidae Capreolinae.",
        HOGUSPORKUSATOR = "A flying pig?! Absurd!",
        ICEDTEA = "Invigorating.",
        INFUSED_IRON = "Perhaps there is something I can build from this.",
        IRON = "Ferrum.",
        JELLYBUG = "Goodness! A walking Fabaceae!",
        JELLYBUG_COOKED = "I'm sure it contains plenty of protein.",
        KINGFISHER = {
            DEAD = "Lifeless.",
            GENERIC = "What a dear little Chloroceryle Amazona!",
            SLEEPING = "Sleeping.",
        },
        LAWNORNAMENT = {
            BURNING = "Enkindled.",
            BURNT = "Thoroughly carbonized.",
            GENERIC = "How lovely.",
        },
        LIFEPLANT = "Narcissus poeticus. Quite a beautiful one.",
        LILYPAD = "Goodness! They can grow quite large in the wild.",
        LIVING_ARTIFACT = "I further study ancient technology with this.",
        LOTUS = "Nelumbo nucifera. Quite beautiful.",
        LOTUS_FLOWER = "The blossom of Nelumbo nucifera. It's quite inspiring.",
        LOTUS_FLOWER_COOKED = "The health benefits are numerous.",
        MACHETE = "Used for hacking through the brush.",
        MAGNIFYING_GLASS = "A fine tool for discovery.",
        MANDRAKEHOUSE = "A subterranean home.",
        MANDRAKEMAN = "Is it Plantae or Animalia?",
        MEAN_FLYTRAP = {
            DEAD = "Now that it's dead, I see it was a quite fascinating specimen.",
            GENERIC = "Ambulatory Dionaea!",
            SLEEPING = "Thank goodness it's not a somnambulist.",
        },
        MEATED_NETTLE = "Medicinal nourishment, with added protein.",
        METALPLATEHAT = "It's similar to the Spanish colonials.",
        NECTAR_POD = "I wonder if this could somehow be turned to honey.",
        NETTLE = {
            DEFAULT = "These nettles make a fine sinus clearing home remedy.",
            EMPTY = "The nettles need time to grow back.",
            MOIST = "Ah. It does seem to like moisture.",
            WITHERED = "Appears to be the wrong soil for it.",
        },
        NETTLELOSANGE = "Medicinal nourishment.",
        OBSIDIAN = "A derivative of volcanic lava.",
        OINC = "I wish I could spend this on books.",
        OINC10 = "If only I could spend this on a lot of books.",
        OINC100 = "If only I could donate this to the library.",
        PANGOLDEN = "Aurum vermilingua.",
        PARROT_BLUE = {
            DEAD = "A late parrot.",
            GENERIC = "Psittaciformes Norwegianae, perhaps?",
            SLEEPING = "It appears to be just resting.",
        },
        PEAGAWK = {
            DEAD = "Lifeless.",
            GENERIC = "A strangely mutated Pavo Cristatus.",
            SLEEPING = "It's ocular plumage appears not to need sleep.",
        },
        PEAGAWKFEATHER = "Feather of the male Pavo Cristatus.",
        PEAGAWK_BUSH = "I have questions about that bush.",
        PHEROMONESTONE = "I will uncover the secrets of arthropod speech.",
        PIGBANDIT = "Quite rude!",
        PIGEON = {
            DEAD = "The remains of a disease carrying bird.",
            GENERIC = "A common grey specimen of the Columbidae family.",
            SLEEPING = "It is in a slumber.",
        },
        PIGGHOST = "A porcine phantasm!.",
        PIGHOUSE_CITY = {
            BURNING = "It has ignited.",
            GENERIC = "A more advanced version of pig domicile.",
        },
        PIGHOUSE_FARM = {
            BURNING = "In the process of oxidation.",
            GENERIC = "The abode of the humble farmer.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Oh dear, it's now a burning pyre.",
            GENERIC = "The a residence for miners.",
        },
        PIGMAN_BANKER = {
            GENERIC = "A pig concerned with monetary gain.",
            SLEEPING = "He looks to have dozed off.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "She looks like she has a healthy constitution.",
            SLEEPING = "In repose.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "I see you collect curiosities.",
            SLEEPING = "His lethargy seems to have gotten the best of him.",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "What cabalistic wares have you today?",
            SLEEPING = "What dreams may come...",
        },
        PIGMAN_FARMER = {
            GENERIC = "A farm toiling pig.",
            SLEEPING = "Dormant.",
        },
        PIGMAN_FLORIST = {
            GENERIC = "Concerned with horticultural needs.",
            SLEEPING = "Interesting. She appears to be dreaming.",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "Well, I certainly wouldn't have chosen that hat.",
            SLEEPING = "What a waste of time.",
        },
        PIGMAN_HUNTER = {
            GENERIC = "I suppose you enjoy killing things.",
            SLEEPING = "Does everyone sleep here?",
        },
        PIGMAN_MAYOR = {
            GENERIC = "I should like to document a pig election.",
            SLEEPING = "He appears quite dormant.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "The community handyman, I believe.",
            SLEEPING = "Asleep. I'm curious what that feels like.",
        },
        PIGMAN_MINER = {
            GENERIC = "These pigs extract resources from the earth.",
            SLEEPING = "In a slumber.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "How refreshing to deal with a mature adult.",
            SLEEPING = "I suppose that is to be expected.",
        },
        PIGMAN_QUEEN = "Clearly the monarch of this society.",
        PIGMAN_ROYALGUARD = {
            GENERIC = "One of the Queen's royal guards.",
            SLEEPING = "Fluttering eyelids indicate REM sleep.",
        },
        PIGMAN_ROYALGUARD_2 = {
            GENERIC = "Good day to you, sir.",
            SLEEPING = "Not very good at his job, is he.",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "I had better dust off my bartering skills.",
            SLEEPING = "Perhaps it is past her bedtime.",
        },
        PIGMAN_USHER = {
            GENERIC = "You may have all my sweets. I don't care for them.",
            SLEEPING = "Perhaps he's a somnambulist.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "It's engulfed in flames.",
            GENERIC = "A fortified tower for the Royal Guard.",
        },
        PIG_PALACE = "Quite an impressive display of Porcine Architecture.",
        PIG_RUINS_ARTICHOKE = "It must have had some significance to the pigs.",
        PIG_RUINS_CREEPING_VINES = "They're awfully clingy.",
        PIG_RUINS_DART_STATUE = "I do believe that trap is still active.",
        PIG_RUINS_DART_TRAP = "It appears to have a hole in its mouth.",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "There are archaeological discoveries to be had!",
            LOCKED = "I'll come back later.",
        },
        PIG_RUINS_ENTRANCE2 = "A place of some history.",
        PIG_RUINS_ENTRANCE3 = "The musty smell brings back fond memories of my library.",
        PIG_RUINS_ENTRANCE4 = "Appears to lack proper lighting.",
        PIG_RUINS_ENTRANCE5 = "Am I in an exploring mood?",
        PIG_RUINS_ENTRANCE_SMALL = "The entrance to a subterrestrial maze of ancient rooms.",
        PIG_RUINS_EXIT = "An exit is always welcome.",
        PIG_RUINS_EXIT2 = "An exit to the outside world.",
        PIG_RUINS_EXIT4 = "Perhaps it leads somewhere interesting.",
        PIG_RUINS_HEAD = "An early Porcine civilization once dwelt here.",
        PIG_RUINS_IDOL = "The top part would make an invaluable bartering tool.",
        PIG_RUINS_PLAQUE = "How do I separate it from the base?",
        PIG_RUINS_PRESSURE_PLATE = "That stone looks out of place.",
        PIG_RUINS_SPEAR_TRAP = "I'd be wise to avoid those.",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "No longer as dangerous as they once were.",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "That seems unsafe.",
        PIG_RUINS_TORCH = "It's an ancient pig fire brazier.",
        PIG_RUINS_TORCH_WALL = "Some light couldn't possibly hurt.",
        PIG_SHOP_ACADEMY = {
            BURNING = "Tsk! All that knowledge up in flames!",
            GENERIC = "Ah! At last a place of learning!",
        },
        PIG_SHOP_ANTIQUITIES = {
            BURNING = "Currently on fire.",
            GENERIC = "Holds a motley of strange objects in there.",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "It's engulfed in flames.",
            GENERIC = "A shop for items of an esoteric nature.",
        },
        PIG_SHOP_BANK = {
            BURNING = "I'm familiar with destructive fires.",
            GENERIC = "Contains coins of different denominations. Should be quite interesting.",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "I hope they rebuild.",
            GENERIC = "The home of an elected official.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Pity.",
            GENERIC = "My place of work.",
        },
        PIG_SHOP_DELI = {
            BURNING = "That's a pity.",
            GENERIC = "I do hope their food is fresh.",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "The structure is undergoing rapid oxidation.",
            GENERIC = "This shop trades in local flora.",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "A fine example of combustion.",
            GENERIC = "A place to purchase goods.",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "Does this village have a fire brigade?",
            GENERIC = "I could use head accoutrement.",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "Conflagration!",
            GENERIC = "Contains First Aid items in there.",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "This structure is burning ferociously.",
            GENERIC = "A delightful place to pick up groceries.",
        },
        PIG_SHOP_TINKER = {
            BURNING = "I know the sorrow of losing so much knowledge to fire.",
            GENERIC = "An excellent resource.",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "The weapons are aflame.",
            GENERIC = "A boutique for items of brutality.",
        },
        PIKO = {
            DEAD = "I feel a touch of grief at its passing.",
            GENERIC = "A charming mammalian fuzzball.",
            SLEEPING = "It is asleep.",
        },
        PIKO_ORANGE = {
            DEAD = "I feel a touch of grief at its passing.",
            GENERIC = "An amusingly named mammalian fuzzball.",
            SLEEPING = "It is asleep.",
        },
        PITHHAT = "Historically accurate and functionally imperative.",
        PLAYERHOUSE_CITY = {
            BURNT = "Goodness!",
            FORSALE = "A fine domicile.",
            SOLD = "A place to put my library.",
        },
        PLAYER_HOUSE_BRICK = "Bricks to build a solid home.",
        PLAYER_HOUSE_BRICK_CRAFT = "Bricks to build a solid home.",
        PLAYER_HOUSE_COTTAGE = "Materials for a quaint cottage.",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Materials for a quaint cottage.",
        PLAYER_HOUSE_GOTHIC = "Materials for an ornamental house.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "Materials for an ornamental house.",
        PLAYER_HOUSE_MANOR = "Components for a rather large manor.",
        PLAYER_HOUSE_MANOR_CRAFT = "Components for a rather large manor.",
        PLAYER_HOUSE_TUDOR = "Supplies for a home.",
        PLAYER_HOUSE_TUDOR_CRAFT = "Supplies for a home.",
        PLAYER_HOUSE_TURRET = "Ingredients for a roof over my head.",
        PLAYER_HOUSE_TURRET_CRAFT = "Ingredients for a roof over my head.",
        PLAYER_HOUSE_VILLA = "Elements to build a house.",
        PLAYER_HOUSE_VILLA_CRAFT = "Elements to build a house.",
        POISONBALM = "A natural antidote for most venoms.",
        PORKLAND_INTRO_BALLOON = "Pity. I did like riding in that.",
        PORKLAND_INTRO_BASKET = "No longer useful, I'm afraid.",
        PORKLAND_INTRO_FLAGS = "Useless now.",
        PORKLAND_INTRO_SANDBAG = "There's no use for it now.",
        PORKLAND_INTRO_SUITCASE = "Not much use now, I'm afraid.",
        PORKLAND_INTRO_TRUNK = "Monogrammed with the initial 'W'.",
        PROP_DOOR = "I wonder what lies within?",
        PUGALISK = "Not like any Pythonidae I've ever seen.",
        PUGALISK_CORPSE = "An interesting specimen.",
        PUGALISK_FOUNTAIN = "I could do with a little rejuvenating.",
        PUGALISK_RUINS_PILLAR = "Precarious.",
        PUGALISK_SKULL = "Belongs to some kind of Pythonidae.",
        PUGALISK_TRAP_DOOR = "I suspect that may be a trap.",
        RABID_BEETLE = {
            DEAD = "Expired.",
            GENERIC = "Certainly not a species I know of!",
            SLEEPING = "Dormant.",
        },
        RADISH = "Of the Brassicaceae family, I believe.",
        RADISH_COOKED = "A bit spicy for my taste.",
        RADISH_PLANTED = "Radish plants work quite well as a companion plant.",
        RADISH_SEEDS = "Ah. I shall plant these first chance I get.",
        RAINFORESTTREE = {
            BURNING = "Fire!",
            BURNT = "The remnants of a roaring fire.",
            CHOPPED = "It had to be done.",
            GENERIC = "A thriving example of tropical flora!",
        },
        RAINFORESTTREE_ROT = "Consumed by some kind of sickness.",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "This will require reconstruction.",
            SCAFFOLD = "The reconstruction effort has begun.",
        },
        REEDS_WATER = "I could make paper from those.",
        RELIC_1 = "A priceless piece of Porcine history.",
        RELIC_2 = "I must return it to the pigs.",
        RELIC_3 = "This belongs in the hoofs of the culture from which it originated.",
        RELIC_4 = "Looks distinctly regal.",
        RELIC_5 = "Quite a unique specimen.",
        ROCK_ANTCAVE = "A stalagmite.",
        ROCK_BASALT = "An igneous rock formation.",
        ROCK_FLIPPABLE = "The most interesting insects are found under rocks.",
        ROOTTRUNK_CHILD = "A complex root system appears to allow the passage of goods.",
        SAIL_SNAKESKIN = "A sail of serpent hide.",
        SCORPION = {
            DEAD = "Deceased.",
            GENERIC = "Scorpiones. But I'm not sure of which subspecies.",
            SLEEPING = "Dormant, thank goodness.",
        },
        SECURITYCONTRACT = "Now I can hire my own security.",
        SEDIMENTPUDDLE = "Contains some lustrous sentiment.",
        SHEARS = "A useful tool for horticultural purposes.",
        SLUGBUG = "A gastropod I've never seen before.",
        SLUGBUG_COOKED = "I'm dubious about its nutritional value.",
        SMASHINGPOT = "A pot that appears smashable.",
        SMELTER = {
            BURNT = "Is anyone hurt?",
            COOKING_SHORT = "The metal is melting into liquid state.",
            DONE = "Recooling and done.",
            EMPTY = "A metalsmithing tool.",
        },
        SNAKEBONESOUP = "A hearty broth.",
        SNAKEOIL = "The usefulness of this substance remains uncertain.",
        SNAKESKIN = "A layer of snake.",
        SNAKESKINHAT = "Rain repellent headwear!",
        SNAKE_AMPHIBIOUS = "Looks like a breed of Agkistrodon.",
        SNAKE_BONE = "Interesting specimen.",
        SPIDER_MONKEY = {
            DEAD = "Quite dead.",
            GENERIC = "An Arachnid Hominidae, if I'm not mistaken.",
            SLEEPING = "It is sleeping, thank goodness.",
        },
        SPIDER_MONKEY_NEST = "The nest of the Arachnid Hominidae.",
        SPIDER_MONKEY_TREE = "A tree frequented by the Arachnid Hominidae.",
        SPRINKLER = "Some much needed hydration.",
        TEA = "Give me tea and a good book.",
        TEATREE = "A fine example of Camellia Sinensis.",
        TEATREE_NUT = "A good antihistamine.",
        TEATREE_NUT_COOKED = "I'd prefer a proper cup of tea.",
        TEATREE_NUT_SAPLING = "It's growing nicely.",
        THUNDERBIRD = "A Strigiformes! How shocking!",
        THUNDERBIRDNEST = "The nest of a Strigiformes.",
        THUNDERHAT = "I'm not usually one for hats.",
        TOPIARY = "A high level of artistry.",
        TOUCAN = "A species known for its brightly colored bill.",
        TREE_PILLAR = "Certainly from an old growth tree.",
        TUBERTREE = "It's too tough for an axe.",
        TUBER_BLOOM_CROP = "It should still be cooked.",
        TUBER_BLOOM_CROP_COOKED = "Cooked tubers are a staple in many cultures.",
        TUBER_CROP = "It's rather poisonous when it's not ripe.",
        TUBER_CROP_COOKED = "I suspect the poison has not been cooked out.",
        TURF_COBBLEROAD = "The ground. You step on it.",
        TURF_DEEPRAINFOREST = "The ground. You step on it.",
        TURF_DEEPRAINFOREST_NOCANOPY = "The ground. You step on it.",
        TURF_FIELDS = "The ground. You step on it.",
        TURF_FOUNDATION = "The ground. You step on it.",
        TURF_GASJUNGLE = "The ground. You step on it.",
        TURF_LAWN = "The ground. You step on it.",
        TURF_MOSS = "The ground. You step on it.",
        TURF_PAINTED = "The ground. You step on it.",
        TURF_PIGRUINS = "The ground. You step on it..",
        TURF_PLAINS = "The ground. You step on it.",
        TURF_RAINFOREST = "The ground. You step on it.",
        VAMPIREBAT = {
            DEAD = "Dead.",
            GENERIC = "A Mammalian Hematophagous of exceptional proportions.",
            SLEEPING = "It is quite dormant.",
        },
        VAMPIREBATCAVE = "The natural habitat of a the Mammalian Hematophagous.",
        VENOMGLAND = "A useful substance for poison prevention.",
        VENUS_STALK = "Salvaged from that terrible creature.",
        VINE = "A common jungle vine.",
        WALKINGSTICK = "Improves one's posture.",
        WALLCRACK_RUINS = "I do believe a mystery lies beyond that.",
        WALL_PIG_RUINS = "I should like to study this if I had more time.",
        WATERDROP = "It appears seed-like.",
        WEEVOLE = "A Coleoptera. And an annoying one at that.",
        WEEVOLE_CARAPACE = "The exoskeleton of a Coleoptera.",
        WINDOW_GREENHOUSE = "Ideal for facilitating some of my botanical activities.",
        WINDOW_LARGE_SQUARE = "A window to the outside.",
        WINDOW_LARGE_SQUARE_CURTAIN = "A window to the outside.",
        WINDOW_ROUND = "Industrialized sight seeing.",
        WINDOW_ROUND_BURLAP = "It could use some better drapery.",
        WINDOW_ROUND_CURTAINS_NAILS = "A window to the outside.",
        WINDOW_SMALL_PEAKED = "A window to the outside.",
        WINDOW_SMALL_PEAKED_CURTAIN = "A window to the outside.",
        WINDOW_TALL = "A window to the outside.",
        WINDOW_TALL_CURTAIN = "A window to the outside.",
    },
}
