return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Tip top!",
        },
        USEDOOR = {
            GENERIC = "I am unable to open this.",
            LOCKED = "Requires something to unlock it.",
        },
    },
    ANNOUCE_BATS = "Desmodus rotundus!",
    ANNOUNCE_BOAT_DAMAGED = "My vessel is deteriorating!",
    ANNOUNCE_BOAT_SINKING = "I do believe this boat is sinking.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "I had best head for shore! Now!",
    ANNOUNCE_DEHUMID = {
        "Ah... that breeze is nice.",
    },
    ANNOUNCE_HAYFEVER = "Sniff sniff. Must be hayfever season.",
    ANNOUNCE_HAYFEVER_OFF = "Ahh... Finally I can breathe.",
    ANNOUNCE_PICKPOOP = {
        "I never!",
        "Disgusting!",
        "What a horrid smell!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That spot won't break.",
        "There must be a better spot to hit it.",
        "It can't be completely invulnerable?",
    },
    ANNOUNCE_SNEEZE = "Ahh... CHOOOOOOOOO!",
    ANNOUNCE_TOO_HUMID = {
        "This %s is unbearable.",
        "This %s makes it too hot.",
    },
    ANNOUNCE_WAVE_BOOST = "Prime oceanic oscillations!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "It has expired.",
            GENERIC = "This Dionaea has reached maturation.",
            SLEEPING = "I'm curious as to why it requires sleep.",
        },
        ALLOY = "Iron that has gone through metallic bonding.",
        ANCIENT_HULK = "It must be using some sort of ancient technology.",
        ANCIENT_ROBOTS_ASSEMBLY = "Appears to be only partially assembled.",
        ANCIENT_ROBOT_CLAW = "The paw of some metal goliath.",
        ANCIENT_ROBOT_HEAD = "The skull of an iron automata.",
        ANCIENT_ROBOT_LEG = "Appears to be a automaton appendage.",
        ANCIENT_ROBOT_RIBS = "An iron contraption.",
        APORKALYPSE_CLOCK = "Ah. Quite a complex form of clockwork.",
        ARMOR_METALPLATE = "What era is this design from?",
        ARMOR_WEEVOLE = "Armour made from bug exoskeleton.",
        ASPARAGUS_PLANTED = "Asparagus. Otherwise known as sparrow grass.",
        BALLPEIN_HAMMER = "I could use this for more delicate jobs.",
        BASEFAN = "Restorative.",
        BILL = {
            DEAD = "It's deceased.",
            GENERIC = "Of the Ornithorhynchidae family I believe.",
            SLEEPING = "I won't wake it.",
        },
        BILL_QUILL = "An Ornithorhynchidae quill.",
        BOATREPAIRKIT = "Extends the life of aquatic vessels.",
        BOAT_CARGO = "I can store a few extra books aboard.",
        BOAT_CORK = "I suppose it's safe for a quick trip up the river.",
        BOAT_LOGRAFT = "Crude nautical transport.",
        BOAT_ROW = "My vessel for marine research.",
        BOAT_TORCH = "To better observe the nocturnal sea life.",
        BONESTAFF = "Contains a potent stare.",
        CHITIN = "The exoskeleton of an arthropod.",
        COFFEE = "I do love a cup of coffee and a good book.",
        COFFEEBEANS = "Very high in caffeine.",
        COFFEEBEANS_COOKED = "Ahh, that roast smells delightful.",
        CUTNETTLE = "These are quite good for the sinuses.",
        DISARMING_KIT = "Rather clever.",
        DUNGBALL = "A perfectly spherical specimen of feces.",
        DUNGBEETLE = {
            DEAD = "A Scarabaeidae cadaver.",
            GENERIC = "Scarabaeidae with her droppings.",
            SLEEPING = "At rest.",
            UNDUNGED = "She's lost her dung.",
        },
        DUNGPILE = {
            GENERIC = "Scarabaeidae will make short work of it.",
            PICKED = "Odious, yet useful.",
        },
        FLOWER_RAINFOREST = "Floral cross-pollination produces some fascinating specimens.",
        FROGLEGS_POISON = "Agalychnis callidryas is not poisonous, but it may not be Agalychnis callidryas.",
        FROGLEGS_POISON_COOKED = "I'm not convinced the poison has left.",
        FROG_POISON = {
            DEAD = "An amphibian carcass.",
            GENERIC = "Curious... Agalychnis callidryas should be arboreal, not aquatic.",
            SLEEPING = "It seems quite lethargic at this time of day.",
        },
        GLOWFLY = {
            DEAD = "Its existence has reached an end.",
            GENERIC = "A bioluminescent insecta.",
            SLEEPING = "Curious. Its bioluminescence requires wakefulness.",
        },
        GLOWFLY_COCOON = "Fascinating! It has moved on to the chrysalis stage.",
        GOLDENMACHETE = "The most malleable of metals, but let's see how it slices.",
        GOLDPAN = "This should be useful for finding valuable minerals.",
        GOLD_DUST = "Small particles of the shiniest element.",
        GRABBING_VINE = "Hanging vines from the forest canopy.",
        GRASS_TALL = {
            BURNING = "Illuminating!",
            GENERIC = "I need an implement for that.",
            PICKED = "That required not insignificant effort.",
        },
        HALBERD = "It is a cruel and versatile weapon.",
        HANGING_VINE = "Hanging vines from the forest canopy.",
        HIPPOPOTAMOOSE = "A Hippopotamidae Capreolinae!",
        HIPPO_ANTLER = "Belongs to a Hippoptamidae Capreolinae.",
        ICEDTEA = "Invigorating.",
        INFUSED_IRON = "Perhaps there is something I can build from this.",
        IRON = "Ferrum.",
        KINGFISHER = {
            DEAD = "Lifeless.",
            GENERIC = "What a dear little Chloroceryle Amazona!",
            SLEEPING = "Sleeping.",
        },
        LIFEPLANT = "Narcissus poeticus. Quite a beautiful one.",
        LILYPAD = "Goodness! They can grow quite large in the wild.",
        LIVING_ARTIFACT = "I further study ancient technology with this.",
        LOTUS = "Nelumbo nucifera. Quite beautiful.",
        LOTUS_FLOWER = "The blossom of Nelumbo nucifera. It's quite inspiring.",
        LOTUS_FLOWER_COOKED = "The health benefits are numerous.",
        MACHETE = "Used for hacking through the brush.",
        MAGNIFYING_GLASS = "A fine tool for discovery.",
        MANDRAKEHOUSE = "A subterranean home.",
        MANDRAKEMAN = "Is it Plantae or Animalia?",
        MEAN_FLYTRAP = {
            DEAD = "Now that it's dead, I see it was a quite fascinating specimen.",
            GENERIC = "Ambulatory Dionaea!",
            SLEEPING = "Thank goodness it's not a somnambulist.",
        },
        METALPLATEHAT = "It's similar to the Spanish colonials.",
        NECTAR_POD = "I wonder if this could somehow be turned to honey.",
        OINC = "I wish I could spend this on books.",
        OINC10 = "If only I could spend this on a lot of books.",
        OINC100 = "If only I could donate this to the library.",
        PANGOLDEN = "Aurum vermilingua.",
        PARROT_BLUE = {
            DEAD = "A late parrot.",
            GENERIC = "Psittaciformes Norwegianae, perhaps?",
            SLEEPING = "It appears to be just resting.",
        },
        PEAGAWK = {
            DEAD = "Lifeless.",
            GENERIC = "A strangely mutated Pavo Cristatus.",
            SLEEPING = "It's ocular plumage appears not to need sleep.",
        },
        PEAGAWKFEATHER = "Feather of the male Pavo Cristatus.",
        PEAGAWK_BUSH = "I have questions about that bush.",
        PIGEON = {
            DEAD = "The remains of a disease carrying bird.",
            GENERIC = "A common grey specimen of the Columbidae family.",
            SLEEPING = "It is in a slumber.",
        },
        PIGHOUSE_CITY = {
            BURNING = "It has ignited.",
            GENERIC = "A more advanced version of pig domicile.",
        },
        PIGHOUSE_FARM = {
            BURNING = "In the process of oxidation.",
            GENERIC = "The abode of the humble farmer.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Oh dear, it's now a burning pyre.",
            GENERIC = "The a residence for miners.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "I should like to document a pig election.",
            SLEEPING = "He appears quite dormant.",
        },
        PIGMAN_QUEEN = "Clearly the monarch of this society.",
        PIG_PALACE = "Quite an impressive display of Porcine Architecture.",
        PIG_RUINS_ARTICHOKE = "It must have had some significance to the pigs.",
        PIG_RUINS_HEAD = "An early Porcine civilization once dwelt here.",
        PIG_RUINS_IDOL = "The top part would make an invaluable bartering tool.",
        PIG_RUINS_PLAQUE = "How do I separate it from the base?",
        PIG_SHOP_CITYHALL = {
            BURNING = "I hope they rebuild.",
            GENERIC = "The home of an elected official.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Pity.",
            GENERIC = "My place of work.",
        },
        PIKO = {
            DEAD = "I feel a touch of grief at its passing.",
            GENERIC = "A charming mammalian fuzzball.",
            SLEEPING = "It is asleep.",
        },
        PIKO_ORANGE = {
            DEAD = "I feel a touch of grief at its passing.",
            GENERIC = "An amusingly named mammalian fuzzball.",
            SLEEPING = "It is asleep.",
        },
        PUGALISK = "Not like any Pythonidae I've ever seen.",
        PUGALISK_CORPSE = "An interesting specimen.",
        PUGALISK_FOUNTAIN = "I could do with a little rejuvenating.",
        PUGALISK_RUINS_PILLAR = "Precarious.",
        PUGALISK_SKULL = "Belongs to some kind of Pythonidae.",
        PUGALISK_TRAP_DOOR = "I suspect that may be a trap.",
        RABID_BEETLE = {
            DEAD = "Expired.",
            GENERIC = "Certainly not a species I know of!",
            SLEEPING = "Dormant.",
        },
        REEDS_WATER = "I could make paper from those.",
        RELIC_1 = "A priceless piece of Porcine history.",
        RELIC_2 = "I must return it to the pigs.",
        RELIC_3 = "This belongs in the hoofs of the culture from which it originated.",
        RELIC_4 = "Looks distinctly regal.",
        RELIC_5 = "Quite a unique specimen.",
        SAIL_SNAKESKIN = "A sail of serpent hide.",
        SCORPION = {
            DEAD = "Deceased.",
            GENERIC = "Scorpiones. But I'm not sure of which subspecies.",
            SLEEPING = "Dormant, thank goodness.",
        },
        SEDIMENTPUDDLE = "Contains some lustrous sentiment.",
        SHEARS = "A useful tool for horticultural purposes.",
        SMELTER = {
            BURNT = "Is anyone hurt?",
            COOKING_SHORT = "The metal is melting into liquid state.",
            DONE = "Recooling and done.",
            EMPTY = "A metalsmithing tool.",
        },
        SNAKEBONESOUP = "A hearty broth.",
        SNAKEOIL = "The usefulness of this substance remains uncertain.",
        SNAKESKIN = "A layer of snake.",
        SNAKE_AMPHIBIOUS = "Looks like a breed of Agkistrodon.",
        SNAKE_BONE = "Interesting specimen.",
        TEA = "Give me tea and a good book.",
        TEATREE = "A fine example of Camellia Sinensis.",
        TEATREE_NUT = "A good antihistamine.",
        TEATREE_NUT_COOKED = "I'd prefer a proper cup of tea.",
        TEATREE_NUT_SAPLING = "It's growing nicely.",
        TOUCAN = "A species known for its brightly colored bill.",
        TREE_PILLAR = "Certainly from an old growth tree.",
        VAMPIREBAT = {
            DEAD = "Dead.",
            GENERIC = "A Mammalian Hematophagous of exceptional proportions.",
            SLEEPING = "It is quite dormant.",
        },
        VAMPIREBATCAVE = "The natural habitat of a the Mammalian Hematophagous.",
        VENOMGLAND = "A useful substance for poison prevention.",
        VENUS_STALK = "Salvaged from that terrible creature.",
        VINE = "A common jungle vine.",
        WALKINGSTICK = "Improves one's posture.",
        WATERDROP = "It appears seed-like.",
        WEEVOLE = "A Coleoptera. And an annoying one at that.",
        WEEVOLE_CARAPACE = "The exoskeleton of a Coleoptera.",
    },
}
