return {
	DESCRIBE = {
		ARMOR_WEEVOLE = "ADVENTURE CLOTHES FROM ANNOYING BUGS",
		ASPARAGUS_PLANTED = "HATH A FUNNY HAT",
		GOLDENMACHETE = "'TIS SHINY TOOL O' SLASHINGS",
		GRASS_TALL = {
			BURNING = "FWOOSH'DING",
			GENERIC = "AS LONG AS THE DAY IS MERRY",
			PICKED = "THE LONG AND SHORT OF IT",
		},
		MACHETE = "YON SLASHY TOOL",
		PEAGAWK = {
			DEAD = "IS'T EYES LOOKED IS'T LAST",
			GENERIC = "WHAT A ROGUE AND PEASANT SLAVE AM EYE-BIRD!",
			SLEEPING = "O GENTLE SLEEP!",
		},
		PEAGAWKFEATHER = "IS'T A BIRD THING O' PRETTY",
		PEAGAWK_BUSH = "'TIS NAUGHT A BUSH",
		SHEARS = "FOR THE CUTTINGS OF THE SHRUBS",
		WEEVOLE = "GO AWAY BUGS",
		WEEVOLE_CARAPACE = "WILBA BEAT ANNOYING BUGS",
	},
}