return {
    ANNOUNCE_DEHUMID = {
        "WILBA HAS'T COOLED",
        "AHH. WILBA 'TIS BETTER",
    },
    ANNOUNCE_TOO_HUMID = {
        "WILBA AM TOO MUCH I' THE HEAT",
        "THE AIR 'TIS FULL OF HEAT",
    },
    DESCRIBE = {
        APORKALYPSE_CLOCK = "TIME AND THE HOUR RUNS THROUGH IT",
        ARMOR_WEEVOLE = "ADVENTURE CLOTHES FROM ANNOYING BUGS",
        ASPARAGUS_PLANTED = "HATH A FUNNY HAT",
        FLOWER_RAINFOREST = "MANY COLOR'D FLOWERS FOR WILBA",
        GLOWFLY = {
            DEAD = "'TIS SQUISH'DED",
            GENERIC = "IS'T A BUG O' GLOWY BUTT",
            SLEEPING = "O GENTLE SLEEP!",
        },
        GLOWFLY_COCOON = "WRAPP'DED IN A BUGGY BLANKET",
        GOLDENMACHETE = "'TIS SHINY TOOL O' SLASHINGS",
        GRASS_TALL = {
            BURNING = "FWOOSH'DING",
            GENERIC = "AS LONG AS THE DAY IS MERRY",
            PICKED = "THE LONG AND SHORT OF IT",
        },
        MACHETE = "YON SLASHY TOOL",
        PEAGAWK = {
            DEAD = "IS'T EYES LOOKED IS'T LAST",
            GENERIC = "WHAT A ROGUE AND PEASANT SLAVE AM EYE-BIRD!",
            SLEEPING = "O GENTLE SLEEP!",
        },
        PEAGAWKFEATHER = "IS'T A BIRD THING O' PRETTY",
        PEAGAWK_BUSH = "'TIS NAUGHT A BUSH",
        SHEARS = "FOR THE CUTTINGS OF THE SHRUBS",
        TREE_PILLAR = "'TIS STRONG TREE",
        WEEVOLE = "GO AWAY BUGS",
        WEEVOLE_CARAPACE = "WILBA BEAT ANNOYING BUGS",
    },
}