return {
	DESCRIBE = {
		PEAGAWK = {
			DEAD = "IS'T EYES LOOKED IS'T LAST",
			GENERIC = "WHAT A ROGUE AND PEASANT SLAVE AM EYE-BIRD!",
			SLEEPING = "O GENTLE SLEEP!",
		},
		PEAGAWKFEATHER = "IS'T A BIRD THING O' PRETTY",
		PEAGAWK_BUSH = "'TIS NAUGHT A BUSH",
	},
}