return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Ugh, why would I do that now?",
        },
        SHOP = {
            CANTPAY = "It's too expensive.",
            GENERIC = "I didn't want it anyway.",
        },
        USEDOOR = {
            GENERIC = "Probably boring in there anyway.",
            LOCKED = "How am I supposed to get in?!",
        },
    },
    ANNOUCE_ALARMOVER = "That was easy.",
    ANNOUCE_BATS = "Bats! Go away!",
    ANNOUCE_OTHERWORLD_DEED = "This house isn't around here.",
    ANNOUCE_UNDERLEAFCANOPY = "It's too dark. I wish I could burn all these trees.",
    ANNOUNCE_BOAT_DAMAGED = "My boat is wounded!",
    ANNOUNCE_BOAT_SINKING = "I'm going down!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Goodbye cruel world!",
    ANNOUNCE_DEHUMID = {
        "Ahh...it's cooled down.",
    },
    ANNOUNCE_GAS_DAMAGE = "Cough. Cough. It's like smoke without the fire.",
    ANNOUNCE_HAYFEVER = "My sinuses are burning.",
    ANNOUNCE_HAYFEVER_OFF = "Sniff! I feel better now!",
    ANNOUNCE_HOUSE_DOOR = "Agh! Those jerk pigs won't let me build without a permit!",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "I found a door.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "There's nothing there.",
    ANNOUNCE_MYSTERY_FOUND = "I found something!",
    ANNOUNCE_MYSTERY_NOREWARD = "Nothing.",
    ANNOUNCE_NOTHING_FOUND = "This thing isn't picking up anything around here.",
    ANNOUNCE_PICKPOOP = {
        "Ick!",
        "Gross!",
        "Burn it all!!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Ugh! Just die already!",
        "Why won't you break?!",
        "I should just burn you!",
    },
    ANNOUNCE_ROOM_STUCK = "I gotta get out of this room before I burn it down.",
    ANNOUNCE_SNEEZE = "Achoo!!",
    ANNOUNCE_SUITUP = "BURN IT ALL!",
    ANNOUNCE_TAXDAY = "Everyone give me money or I burn everything down!",
    ANNOUNCE_TOOLCORRODED = "Agh! I hope my lighter doesn't corrode!",
    ANNOUNCE_TOO_HUMID = {
        "It's burning hot. But not in a good way.",
        "It's too hot.",
    },
    ANNOUNCE_TURFTOOHARD = "Burning it won't even help.",
    ANNOUNCE_WAVE_BOOST = "Weeee!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "It's very dead now.",
            GENERIC = "You look like you'd burn well.",
            SLEEPING = "It's sleeping.",
        },
        ALLOY = "Fire makes everything better.",
        ALOE = "Gross. It's all gooey inside.",
        ALOE_COOKED = "I put fire on it.",
        ALOE_PLANTED = "I could eat that.",
        ALOE_SEEDS = "Should I plant this?",
        ANCIENT_HERALD = "What's he all about?",
        ANCIENT_HULK = "Hey! Burning is my thing!",
        ANCIENT_REMNANT = "It's from that apocalypse jerk.",
        ANCIENT_ROBOTS_ASSEMBLY = "It's not gonna work like that.",
        ANCIENT_ROBOT_CLAW = "Dang! Can't burn it!",
        ANCIENT_ROBOT_HEAD = "Ugly.",
        ANCIENT_ROBOT_LEG = "I should kick it.",
        ANCIENT_ROBOT_RIBS = "Aww... It won't burn.",
        ANTCHEST = "I won't burn it, but only because it makes me honey.",
        ANTCOMBHOME = "Gross!",
        ANTHILL = "Ughh. I do  not want to go in there.",
        ANTIVENOM = "This'll help if I'm poisoned.",
        ANTLER = "Here birdie birdie...",
        ANTLER_CORRUPTED = "Seeya round big birdie. Or not.",
        ANTMAN = {
            DEAD = "Gross and dead.",
            GENERIC = "You're gross.",
            SLEEPING = "Still gross.",
        },
        ANTMAN_WARRIOR = "Yeesh. What are you so angry about?",
        ANTMAN_WARRIOR_EGG = "A baby jerk.",
        ANTMASKHAT = "This is the nastiest thing I've ever made.",
        ANTQUEEN = "Ugh. Ugly.",
        ANTQUEEN_CHAMBERS = "Am I supposed to be impressed.",
        ANTQUEEN_THRONE = "There's stuff in there I can steal.",
        ANTSUIT = "This is the worst.",
        ANT_CAVE_LANTERN = "Sweet, sweet fire.",
        APORKALYPSE_CLOCK = "Looks ominous. I like it.",
        ARMORVORTEXCLOAK = "Reminds me of my lighter. It keeps away the darkness.",
        ARMOR_METALPLATE = "I feel like a tin can.",
        ARMOR_SNAKESKIN = "This coat makes me feel dangerous.",
        ARMOR_WEEVOLE = "This feels gross. I hope it works.",
        ASPARAGUS_PLANTED = "Haha! Found you!",
        BALLPEIN_HAMMER = "This only smashes little bits off things.",
        BAMBOO = "Looks flammable.",
        BANDITHAT = "Sneaky!",
        BANDITMAP = "Good. Now I can steal his stuff.",
        BANDITTREASURE = "I should dig there.",
        BASEFAN = "Fan the flames.",
        BATHAT = "Ugh. I can still smell the jerkiness.",
        BAT_HIDE = "Weird. Is it from a pig bat?",
        BILL = {
            DEAD = "That's what you get.",
            GENERIC = "You're weird.",
            SLEEPING = "It even sleeps weird.",
        },
        BILL_QUILL = "I could probably use this for something.",
        BLUNDERBUSS = "Fire makes it go boom.",
        BOATREPAIRKIT = "This should patch up any little leaks.",
        BOAT_CARGO = "I can carry so many flammables on this.",
        BOAT_CORK = "It'd be better if I could light it on fire.",
        BOAT_LOGRAFT = "Campfire wood has other uses, apparently!",
        BOAT_ROW = "Rowing? Really?",
        BOAT_TORCH = "Strangely not for torching boats.",
        BONESTAFF = "I'd prefer to burn my enemies but... meh.",
        BRAMBLESPIKE = "Let's see if it's flammable.",
        BRAMBLE_BULB = "I can't plant it, so what do I want it for?",
        BRAMBLE_CORE = "Pretty. But will it burn?",
        BUGREPELLENT = "I guess if I can't burn those bugs...",
        BURR = "Looks like kindling to me.",
        BURR_SAPLING = {
            BURNING = "Burn! Yeah!",
            GENERIC = "Baby firewood.",
            PICKED = "Nothing but kindling now.",
            WITHERED = "It's so dry, it's like it WANTS to be on fire.",
        },
        CANDLEHAT = "A little fire hat.",
        CAVE_EXIT_ROC = "I should wreck that.",
        CHITIN = "Bug skin.",
        CITY_HAMMER = "Less fun than burning the city down.",
        CITY_LAMP = {
            GENERIC = "Fire is so versatile.",
            ON = "They're kinda dull in the daytime.",
        },
        CLAWPALMTREE = "I bet that will burn.",
        CLAWPALMTREE_SAPLING = "It won't even set on fire.",
        CLIPPINGS = "I bet I could burn those.",
        COCONADE = {
            BURNING = "Here we go...",
            GENERIC = "First it booms, then it burns.",
        },
        COFFEE = "I suddenly feel motivated.",
        COFFEEBEANS = "These could use fire.",
        COFFEEBEANS_COOKED = "Ahhh, that aroma.",
        CONSTRUCTION_PERMIT = "More rooms mean more room for fires.",
        CORK = "I can still set it on fire.",
        CORKCHEST = "It doesn't burn but it does keep the pests out.",
        CORK_BAT = "For bashing things.",
        CURTAIN_DOOR = "It's curtains for that door.",
        CUTLASS = "This sword smells.",
        CUTNETTLE = "It smells funny.",
        DECO_ANTIQUITIES_BEEFALO = "I never liked them when they were alive.",
        DECO_ANTIQUITIES_WALLFISH = "Ugh. It still smells.",
        DECO_CAVE_BAT_BURROW = "Ugh! What a smell!",
        DECO_CAVE_BEAM_ROOM = "That looks pretty sturdy.",
        DECO_CHAIR_BENCH = "It'd be better if I could burn it.",
        DECO_CHAIR_CLASSIC = "It'd be better if I could burn it.",
        DECO_CHAIR_CORNER = "It'd be better if I could burn it.",
        DECO_CHAIR_FOOTREST = "It'd be better if I could burn it.",
        DECO_CHAIR_HORNED = "It'd be better if I could burn it.",
        DECO_CHAIR_LOUNGE = "It'd be better if I could burn it.",
        DECO_CHAIR_MASSAGER = "I like this.",
        DECO_CHAIR_OTTOMAN = "It'd be better if I could burn it.",
        DECO_CHAIR_ROCKING = "It'd be better if I could burn it.",
        DECO_CHAIR_STUFFED = "It'd be better if I could burn it.",
        DECO_CHAISE = "It'd be better if I could burn it.",
        DECO_LAMP_2EMBROIDERED = "A fire hazard. I like it.",
        DECO_LAMP_2FRINGES = "A fire hazard. I like it.",
        DECO_LAMP_2UPTURNS = "A boring old lamp.",
        DECO_LAMP_ADJUSTABLE = "A boring old lamp.",
        DECO_LAMP_BELLSHADE = "A fire hazard. I like it.",
        DECO_LAMP_CANDELABRA = "Needs fire.",
        DECO_LAMP_CERAMIC = "A boring old lamp.",
        DECO_LAMP_CRYSTALS = "A boring old lamp.",
        DECO_LAMP_DOWNBRIDGE = "A boring old lamp.",
        DECO_LAMP_EDISON = "A boring old lightbulb.",
        DECO_LAMP_ELIZABETHAN = "A boring old lamp.",
        DECO_LAMP_FRINGE = "A fire hazard. I like it.",
        DECO_LAMP_GLASS = "A boring old lamp.",
        DECO_LAMP_GOTHIC = "A boring old lamp.",
        DECO_LAMP_HOOFSPA = "A fire hazard. I like it.",
        DECO_LAMP_ORB = "A boring old lamp.",
        DECO_LAMP_RIGHTANGLES = "A boring old lamp.",
        DECO_LAMP_SPOOL = "A boring old lamp.",
        DECO_LAMP_STAINGLASS = "A boring old lamp.",
        DECO_LAMP_UPTURN = "A boring old lamp.",
        DECO_MARBLE = "Oohh... fancy.",
        DECO_MARBLE_CORNERBEAM = "Oohh... fancy.",
        DECO_MILLINERY = "So what?",
        DECO_PLANTHOLDER_BASIC = "Yawn.",
        DECO_PLANTHOLDER_BIRDCAGE = "A soggy sack of boring.",
        DECO_PLANTHOLDER_BONSAI = "Ugh. So boring.",
        DECO_PLANTHOLDER_DISHGARDEN = "A dish of boring.",
        DECO_PLANTHOLDER_DRACEANA = "Yawn.",
        DECO_PLANTHOLDER_FANCY = "Boring.",
        DECO_PLANTHOLDER_FERN = "A lot of boring.",
        DECO_PLANTHOLDER_FERNSTAND = "Ugh. So boring.",
        DECO_PLANTHOLDER_MARBLE = "Pretty. Pretty boring.",
        DECO_PLANTHOLDER_ORCHID = "Pretty. Pretty boring.",
        DECO_PLANTHOLDER_PALM = "So boring.",
        DECO_PLANTHOLDER_PHILODENDRON = "Yawn.",
        DECO_PLANTHOLDER_PITCHERS = "Yawn.",
        DECO_PLANTHOLDER_PLANTPET = "Awww...Still boring.",
        DECO_PLANTHOLDER_TERRARIUM = "A container for boring.",
        DECO_PLANTHOLDER_TRAPS = "Gross... and boring.",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "Nice, but I still want to burn it down.",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "It'd be better if I burnt it.",
        DECO_PLANTHOLDER_WIP = "Snore.",
        DECO_PLANTHOLDER_XEROGRAPHICA = "A hanging bunch of boring.",
        DECO_PLANTHOLDER_ZZ = "Zzzzz...",
        DECO_ROUND = "So what?",
        DECO_RUINS_BEAM_ROOM = "If that goes the whole thing will fall down.",
        DECO_RUINS_BEAM_ROOM_BLUE = "That looks pretty sturdy.",
        DECO_RUINS_ENDSWELL = "There's something different about this well.",
        DECO_RUINS_FOUNTAIN = "I wish... to see the world burn.",
        DECO_TABLE_BANKER = "Rectangular boring.",
        DECO_TABLE_CHESS = "Chess is boring.",
        DECO_TABLE_CRATE = "Ugly.",
        DECO_TABLE_DIY = "Ugly.",
        DECO_TABLE_RAW = "Ugh. What even is that?",
        DECO_TABLE_ROUND = "Circular boring.",
        DECO_WALLORNAMENT_AXE = "It's no lighter.",
        DECO_WALLORNAMENT_BLACK_CAT = "Ugly.",
        DECO_WALLORNAMENT_CAPE = "Well that's dramatic.",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Bunch of mushy nonsense.",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Boring.",
        DECO_WALLORNAMENT_GEARS_ART = "Can't even set it on fire.",
        DECO_WALLORNAMENT_HUNT = "Stabby things.",
        DECO_WALLORNAMENT_MOSAIC = "A bunch of rocks.",
        DECO_WALLORNAMENT_NO_SMOKING = "Not even fires?",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "I don't get it.",
        DECO_WALLORNAMENT_PHOTO = "Ugly.",
        DECO_WALLORNAMENT_WREATH = "Ugh.",
        DECO_WOOD = "So what?",
        DECO_WOOD_CORNERBEAM = "So what?",
        DEED = "My own house to burn to the ground.",
        DEMOLITION_PERMIT = "Burn! Burn it all down!",
        DISARMING_KIT = "Those traps are goners now.",
        DISGUISEHAT = "Who would fall for that disguise?",
        DUG_NETTLE = "I bet this would like to be in the ground.",
        DUNGBALL = "Can't even set it on fire.",
        DUNGBEETLE = {
            DEAD = "Squashed.",
            GENERIC = "Beat it, smelly beetle!",
            SLEEPING = "How do you sleep with that smell?",
            UNDUNGED = "You better run.",
        },
        DUNGPILE = {
            GENERIC = "Haha, that pile's huge!",
            PICKED = "What? I needed it.",
        },
        FABRIC = "Amazing what you can do with bamboo.",
        FEATHER_THUNDER = "Funny little feather.",
        FEIJOADA = "Ha! Now I can eat those jerk bugs.",
        FLOWER_RAINFOREST = "It's kinda ugly. But it burns.",
        FROGLEGS_POISON = "I'm not sure I should eat that.",
        FROGLEGS_POISON_COOKED = "Only one way to find out if it's still poison...",
        FROG_POISON = {
            DEAD = "Yeah, that thing is dead.",
            GENERIC = "Doesn't look too dangerous to me.",
            SLEEPING = "It's sleeping.",
        },
        GASCLOUD = "Ugh. That looks deadly. And not in a good way.",
        GASMASKHAT = "Cuts down on the coughing.",
        GIANTGRUB = "Likes destroying things as much as I do.",
        GLOWFLY = {
            DEAD = "Squashed.",
            GENERIC = "Looks slimy.",
            SLEEPING = "(Psst... you're gross.)",
        },
        GLOWFLY_COCOON = "Doing a bad job of hiding from me.",
        GNAT = "Agh! They're too small to burn!",
        GNATMOUND = "I can't even burn it down.",
        GOLDENMACHETE = "I don't want to scuff it up.",
        GOLDPAN = "You mean I have to do work?",
        GOLD_DUST = "It's probably not worth much.",
        GRABBING_VINE = "Ugh, vines!",
        GRASS_TALL = {
            BURNING = "I win.",
            GENERIC = "This grass is tough!",
            PICKED = "Not tough enough!",
        },
        GUMMY_CAKE = "Little chewier than most cakes.",
        HALBERD = "Weapons are only good if they're twice your size.",
        HANGING_VINE = "Ugh, vines!",
        HARDSHELL_TACOS = "I like the crunchy part.",
        HEDGE = {
            BURNING = "It's burning! Yes!",
            BURNT = "Beautiful, beautiful ash.",
            GENERIC = "It's just a big shrub.",
            SHAVEABLE = "I might be able to shave that.",
        },
        HEDGE_BLOCK_ITEM = "I'll build it, then I'll burn it down.",
        HEDGE_CONE_ITEM = "Why am I lugging this around?",
        HEDGE_LAYERED_ITEM = "Just because it's pretty, doesn't mean I won't burn it down.",
        HIPPOPOTAMOOSE = "Sure you have impressive horns but can you light fires?",
        HIPPO_ANTLER = "Yeesh. It's pretty big.",
        HOGUSPORKUSATOR = "What's a pig going to teach me?",
        ICEDTEA = "I prefer hot things.",
        INFUSED_IRON = "Are you supposed to be special or something?",
        INTERIOR_FLOOR_CHECK = "Boring floor.",
        INTERIOR_FLOOR_GARDENSTONE = "That's not going to burn.",
        INTERIOR_FLOOR_GEOMETRICTILES = "Boring floor.",
        INTERIOR_FLOOR_HERRINGBONE = "Boring floor.",
        INTERIOR_FLOOR_HEXAGON = "Boring floor.",
        INTERIOR_FLOOR_HOOF_CURVY = "Boring pig floor.",
        INTERIOR_FLOOR_MARBLE = "Boring floor.",
        INTERIOR_FLOOR_OCTAGON = "Boring floor.",
        INTERIOR_FLOOR_PLAID_TILE = "Boring floor.",
        INTERIOR_FLOOR_SHAG_CARPET = "Dang. It won't burn.",
        INTERIOR_FLOOR_SHEET_METAL = "Boring floor.",
        INTERIOR_FLOOR_TRANSITIONAL = "It's not even done!",
        INTERIOR_FLOOR_WOOD = "Dang. Won't burn.",
        INTERIOR_FLOOR_WOODPANELS = "Dang. It won't even burn!",
        INTERIOR_WALL_CHECKERED = "It's a boring wall.",
        INTERIOR_WALL_CIRCLES = "It's a boring wall.",
        INTERIOR_WALL_FLORAL = "It's a boring wall.",
        INTERIOR_WALL_FULLWALL_MOULDING = "It's nice, but will it burn?",
        INTERIOR_WALL_HARLEQUIN = "It's a boring wall.",
        INTERIOR_WALL_MARBLE = "This definitely won't burn.",
        INTERIOR_WALL_MAYORSOFFICE = "Could be better.",
        INTERIOR_WALL_PEAGAWK = "Where'd the eyes go?",
        INTERIOR_WALL_PLAIN_DS = "It's a boring wall.",
        INTERIOR_WALL_PLAIN_ROG = "It's a boring wall.",
        INTERIOR_WALL_ROPE = "It's nice, but will it burn?",
        INTERIOR_WALL_SUNFLOWER = "It's a boring wall.",
        INTERIOR_WALL_UPHOLSTERED = "Psht. I'm not impressed.",
        INTERIOR_WALL_WOOD = "Dang. Won't burn.",
        IRON = "I can't burn it with just my lighter.",
        IRON_DOOR = "Not even burnable.",
        JELLYBUG = "Eww. That does not look appetizing.",
        JELLYBUG_COOKED = "Still gross!",
        KEY_TO_CITY = "A whole city of my own to burn down!",
        KINGFISHER = {
            DEAD = "Ugly and dead.",
            GENERIC = "What's wrong with your face?",
            SLEEPING = "I should catch it while its guard is down.",
        },
        LAVAPOOL = "What marvelous heat and fury!",
        LAWNORNAMENT = {
            BURNING = "It looks better this way.",
            BURNT = "Much more decorative.",
            GENERIC = "A fancy bush or something.",
        },
        LIFEPLANT = "I guess it's okay.",
        LILYPAD = "I can't burn stuff out on the water.",
        LIVING_ARTIFACT = "Think of the things I can burn with it!",
        LOTUS = "Can I eat it? Or burn it?",
        LOTUS_FLOWER = "Just a dumb flower.",
        LOTUS_FLOWER_COOKED = "Fire makes it better.",
        MACHETE = "Or I could just burn my way through.",
        MAGNIFYING_GLASS = "A poor substitute for my lighter.",
        MANDRAKEHOUSE = "Gross.",
        MANDRAKEMAN = "Great. It's a big one. Just what I need.",
        MEAN_FLYTRAP = {
            DEAD = "Good. It's dead.",
            GENERIC = "Wanna see what my lighter does?",
            SLEEPING = "It's taking a nap.",
        },
        MEATED_NETTLE = "It clears my snot.",
        METALPLATEHAT = "This protects my brain.",
        NECTAR_POD = "Is this even good for anything?",
        NETTLE = {
            DEFAULT = "This smells so strong it clears my nose.",
            EMPTY = "Nothing here yet.",
            MOIST = "Why you so happy being wet?",
            WITHERED = "It really doesn't like this dirt.",
        },
        NETTLELOSANGE = "It clears my snot.",
        OBSIDIAN = "A fire rock!",
        OINC = "Some sort of weird coin.",
        OINC10 = "Maybe it's worth something?",
        OINC100 = "I have money to burn!",
        ORGANIC_DOOR = "It's wood. I could burn it.",
        OX_FLUTE = "I hear a storm a-coming.",
        OX_HORN = "I could use an ox-tra one of these.",
        PANGOLDEN = "Yeesh, he's sucking up all the gold!",
        PARROT_BLUE = {
            DEAD = "Demised.",
            GENERIC = "Never seen a bird like that.",
            SLEEPING = "I should catch it while its guard is down.",
        },
        PEAGAWK = {
            DEAD = "Very dead.",
            GENERIC = "Jeepers peepers!",
            SLEEPING = "I wonder what burning feathers smell like.",
        },
        PEAGAWKFEATHER = "Fancy feathers.",
        PEAGAWK_BUSH = "A bush. I think.",
        PEDESTAL_KEY = "I just have to find out what it locks.",
        PHEROMONESTONE = "Ughhhh, it stinks!",
        PIGBANDIT = "He's after my money!",
        PIGCROWNHAT = "I think it suits me.",
        PIGEON = {
            DEAD = "Whoops.",
            GENERIC = "Flying rats.",
            SLEEPING = "Sleeping flying rats.",
        },
        PIGGHOST = "Go away! I didn't like you when you were alive!",
        PIGHOUSE_CITY = {
            BURNING = "Yes! Burn!",
            GENERIC = "Pig houses look pretty different here.",
        },
        PIGHOUSE_FARM = {
            BURNING = "Yes! It's burning!",
            GENERIC = "I think it's a farmhouse.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Buuuurn!",
            GENERIC = "Is that a mine?",
        },
        PIGMAN_BANKER = {
            GENERIC = "Huh. Doesn't even manage money.",
            SLEEPING = "He's napping.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "What a piece of work!",
            SLEEPING = "She's sleeping.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "You look boring. What are you selling today?",
            SLEEPING = "Just as exciting asleep as he is awake.",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "Any of this magic stuff burn things?",
            SLEEPING = "Well, that's rude.",
        },
        PIGMAN_FARMER = {
            GENERIC = "I didn't know pigs did farm work.",
            SLEEPING = "What a lazy pig!",
        },
        PIGMAN_FLORIST = {
            GENERIC = "Can I burn your stuff?",
            SLEEPING = "She's asleep.",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "That hat is ugly.",
            SLEEPING = "She doesn't even take off her hat to sleep.",
        },
        PIGMAN_HUNTER = {
            GENERIC = "Fire is the best weapon.",
            SLEEPING = "Huh. Completely defenseless like that.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Pigs have mayors?",
            SLEEPING = "He's dozing.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "I'll burn everything down, and you can keep fixing it, okay?",
            SLEEPING = "He's dozing.",
        },
        PIGMAN_MINER = {
            GENERIC = "Yeah. He looks like a miner.",
            SLEEPING = "Dreaming of rocks, no doubt.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "A lot of old stuff in here.",
            SLEEPING = "Someone check for a pulse.",
        },
        PIGMAN_QUEEN = "Hey there, your majesty.",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Those guards don't look so tough.",
            SLEEPING = "He's snoozing.",
        },
        PIGMAN_ROYALGUARD_2 = {
            GENERIC = "Those guys give me the creeps.",
            SLEEPING = "He should get fired.",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "I bet their life is super boring.",
            SLEEPING = "Asleep. Figures.",
        },
        PIGMAN_USHER = {
            GENERIC = "How do you see through those glasses?",
            SLEEPING = "Who sleeps on the street?",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Quick, put it out! Haha, just kidding.",
            GENERIC = "What's there to guard from, exactly?",
        },
        PIG_PALACE = "Pompous.",
        PIG_RUINS_ARTICHOKE = "Is that... an artichoke?",
        PIG_RUINS_CREEPING_VINES = "I wish I could burn these.",
        PIG_RUINS_DART_STATUE = "Looking to get burned.",
        PIG_RUINS_DART_TRAP = "Rude.",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "It must lead somewhere.",
            LOCKED = "I can't even burn through this door.",
        },
        PIG_RUINS_ENTRANCE2 = "Looks dark.",
        PIG_RUINS_ENTRANCE3 = "Do I even want to go in there?",
        PIG_RUINS_ENTRANCE4 = "Why would want to go in there?",
        PIG_RUINS_ENTRANCE5 = "Probably a lot of old stuff in there.",
        PIG_RUINS_ENTRANCE_SMALL = "Looks dark down there.",
        PIG_RUINS_EXIT = "I think this is the backside.",
        PIG_RUINS_EXIT2 = "A way to get out of this place.",
        PIG_RUINS_EXIT4 = "A door. I guess I could go through it.",
        PIG_RUINS_HEAD = "Doesn't look very flammable.",
        PIG_RUINS_IDOL = "I should take that off and sell it to a pig.",
        PIG_RUINS_PLAQUE = "If I could break it, I could sell it.",
        PIG_RUINS_PRESSURE_PLATE = "I'm not stepping on that.",
        PIG_RUINS_SPEAR_TRAP = "I'm not stepping over those.",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "Haha. Can't get me anymore.",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Missed me.",
        PIG_RUINS_TORCH = "I should light it!",
        PIG_RUINS_TORCH_WALL = "I could put fire in there!",
        PIG_SCEPTER = "This means everyone has to listen to me.",
        PIG_SHOP_ACADEMY = {
            BURNING = "All that history, up in flames!",
            GENERIC = "Museums usually have something on Great Fires.",
        },
        PIG_SHOP_ANTIQUITIES = {
            BURNING = "BURN! BURN!",
            GENERIC = "A lot of weird things to burn in there.",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "Yes! Burn! Burn it all down!",
            GENERIC = "Are there books about magical fires in there?",
        },
        PIG_SHOP_BANK = {
            BURNING = "YES! FIRE! FIRE!",
            GENERIC = "A bunch of big shots in there.",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "Nice!",
            GENERIC = "That's where that bossy jerk works.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Let it burn!",
            GENERIC = "My own office to burn down.",
        },
        PIG_SHOP_DELI = {
            BURNING = "Burn! Burn! Burn!",
            GENERIC = "Food!",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "Burn. Burn. Burn!",
            GENERIC = "For growing stuff.",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "Buuuuurn!",
            GENERIC = "I wonder if they have matches.",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "That's what I like to see!",
            GENERIC = "Maybe I could use a new hat.",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "What a blaze!",
            GENERIC = "For all my cuts and bruises.",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "Burn it down!",
            GENERIC = "I can't believe I ever took food stores for granted.",
        },
        PIG_SHOP_TINKER = {
            BURNING = "A lot of paper in there to burn.",
            GENERIC = "Now I can build more things to burn.",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "Destroy the weapons with fire!",
            GENERIC = "Maybe they have a flaming axe in there.",
        },
        PIKO = {
            DEAD = "Didn't run fast enough.",
            GENERIC = "Squirrelly little guy.",
            SLEEPING = "I bet I could catch it now.",
        },
        PIKO_ORANGE = {
            DEAD = "Didn't run fast enough.",
            GENERIC = "Squirrelly little guy.",
            SLEEPING = "I bet I could catch it now.",
        },
        PILLAR_DOOR = "Ha ha! That bat's dead.",
        PITHHAT = "Meh. Not my style, but I'll wear it.",
        PLATE_DOOR = "Not even burnable.",
        PLAYERHOUSE_CITY = {
            BURNT = "That looked like it was a glorious fire!",
            FORSALE = "There's probably something wrong with it.",
            SOLD = "I wonder how long before it burns down.",
        },
        PLAYER_HOUSE_BRICK_CRAFT = "Brick isn't known for being flammable",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Stuff to build a small house.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "There's a lot of non-flammable wrought iron in this.",
        PLAYER_HOUSE_MANOR_CRAFT = "I'll build my own fireplace to set fires in.",
        PLAYER_HOUSE_TUDOR_CRAFT = "A bunch of things to build a fancy house.",
        PLAYER_HOUSE_TURRET_CRAFT = "Ugh. Stone is so heavy. And fire-proof.",
        PLAYER_HOUSE_VILLA_CRAFT = "I can build this house and then burn it down.",
        POG = {
            APORKALYPSE = "I don't like the look of that dog!",
            FOLLOWER = "Hey! Shoo!",
            GENERIC = "Hey! A doggy!",
            SLEEPING = "Aw, it's sleeping.",
        },
        POISONBALM = "I actually kinda like that burning feeling.",
        PORKLAND_INTRO_BALLOON = "Useless. Can't even burn it.",
        PORKLAND_INTRO_BASKET = "Psht. That didn't last long.",
        PORKLAND_INTRO_FLAGS = "Totally useless.",
        PORKLAND_INTRO_SANDBAG = "Meh. I don't need it.",
        PORKLAND_INTRO_SUITCASE = "I'm not lugging that around.",
        PORKLAND_INTRO_TRUNK = "Well it has a 'W' on it so it must be mine.",
        PROP_DOOR = "Wonder what's in there.",
        PUGALISK = "I'm gonna set it on fire!",
        PUGALISK_CORPSE = "Not sorry about this at all.",
        PUGALISK_FOUNTAIN = "I'll take some of that.",
        PUGALISK_RUINS_PILLAR = "I can't set it on fire.",
        PUGALISK_SKULL = "Ha! That's what you get!",
        PUGALISK_TRAP_DOOR = "I don't trust it.",
        RABID_BEETLE = {
            DEAD = "Looks dead to me.",
            GENERIC = "What're you so mad about?",
            SLEEPING = "I should draw a mustache on its mustache while it sleeps.",
        },
        RADISH = "Like little balls of fire.",
        RADISH_COOKED = "Spicy. Like fire for your mouth.",
        RADISH_PLANTED = "What are they hiding from?",
        RADISH_SEEDS = "Ugh! Why can't this just be food already?!",
        RAINFORESTTREE = {
            BURNING = "Yes! Fire! Fire!",
            BURNT = "Much better.",
            CHOPPED = "No one can save you now, rainforest.",
            GENERIC = "It's a tree.",
        },
        RAINFORESTTREE_ROT = "I can burn it down and it won't be so sick.",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "A pile of garbage.",
            SCAFFOLD = "Someone's building something.",
        },
        REEDS_WATER = "Can I burn it?",
        RELIC_1 = "Its grin creeps me out.",
        RELIC_2 = "It's really old.",
        RELIC_3 = "Snooty.",
        RELIC_4 = "Looks fancier than those other old things.",
        RELIC_5 = "Ugh. Can't get those jewels out.",
        ROCK_ANTCAVE = "I can't burn it.",
        ROCK_BASALT = "It's a rock. I can't even burn it.",
        ROCK_FLIPPABLE = "Might as well see what's underneath.",
        ROC_HEAD = "A little too pecky for me.",
        ROC_LEG = "That would look good barbequed.",
        ROC_NEST_BRANCH1 = "Wish I could burn it.",
        ROC_NEST_BRANCH2 = "That'd look good up in flames.",
        ROC_NEST_BUSH = "Wish I could burn it!",
        ROC_NEST_DEBRIS1 = "What's that doing there?",
        ROC_NEST_DEBRIS2 = "Who leaves a stick just laying around?",
        ROC_NEST_DEBRIS3 = "It's a stick.",
        ROC_NEST_DEBRIS4 = "A weird looking stick.",
        ROC_NEST_EGG1 = "Do egg shells burn?",
        ROC_NEST_EGG2 = "Needs some fire.",
        ROC_NEST_EGG3 = "Where's the bird?",
        ROC_NEST_EGG4 = "It looks old.",
        ROC_NEST_HOUSE = "Anyone there?",
        ROC_NEST_RUSTY_LAMP = "Aww... can't even light a fire in there.",
        ROC_NEST_TREE1 = "I can't even burn it.",
        ROC_NEST_TREE2 = "It would look better burnt.",
        ROC_NEST_TRUNK = "Broken, but not burnt.",
        ROC_ROBIN_EGG = "It needs fire. Like me.",
        ROC_TAIL = "That's a big bird butt.",
        ROOTTRUNK = "Now I don't have to lug everything around with me.",
        ROUND_DOOR = "What's it smiling about?",
        ROYAL_GALLERY = "How am I supposed to unlock that?",
        RO_BIN = "Do you have to squeek all the time?",
        RO_BIN_GIZZARD_STONE = "Ugh. I really want to burn it.",
        RUG_BEARD = "Ew.",
        RUG_BRAID = "Soft and ugly.",
        RUG_CATCOON = "Ha! That's what you get.",
        RUG_CRIME = "Interesting...",
        RUG_FUR = "Haha. That's what you get.",
        RUG_HEDGEHOG = "Ugly. And boring.",
        RUG_HOOFPRINT = "Ugh. So ugly.",
        RUG_METAL = "Can't even set this on fire.",
        RUG_NAILBED = "I'm not stepping on that.",
        RUG_OCTAGON = "Soft and ugly.",
        RUG_OVAL = "Soft and ugly.",
        RUG_PORCUPUSS = "Take that, abomination.",
        RUG_RECTANGLE = "Soft and ugly.",
        RUG_ROUND = "What are you looking at?",
        RUG_RUBBERMAT = "This isn't flammable.",
        RUG_SQUARE = "Soft and ugly.",
        RUG_SWIRL = "Soft and ugly.",
        RUG_TILES = "Ugh. So ugly.",
        RUG_WEB = "Ew.",
        RUG_WORMHOLE = "Ew.",
        SAIL_SNAKESKIN = "What a morbid sail.",
        SAND = "Big deal, it's sand.",
        SCORPION = {
            DEAD = "Just as gross dead as alive.",
            GENERIC = "Ugh, gross!",
            SLEEPING = "I should step on it.",
        },
        SECURITYCONTRACT = "Now I can hire a guard to help me burn stuff!",
        SEDIMENTPUDDLE = "Yeesh, there's a lot of sparkles in there.",
        SHEARS = "Not as good as fire, but I guess it has its uses.",
        SHELF_ADJUSTABLE = "Ugly.",
        SHELF_AFRAME = "Blah.",
        SHELF_BASIC = "Blah.",
        SHELF_CINDERBLOCKS = "Can't even set this on fire.",
        SHELF_CRATES = "I deserve better.",
        SHELF_FLOATING = "Everything's slanted!",
        SHELF_FRIDGE = "Is this a fridge, or...",
        SHELF_GLASS = "Can't even set this on fire.",
        SHELF_HATTREE = "Blah.",
        SHELF_HOOKS = "Ugly.",
        SHELF_HUTCH = "Ugly.",
        SHELF_INDUSTRIAL = "Blah.",
        SHELF_LADDER = "Ugly.",
        SHELF_MARBLE = "Marble isn't flammable.",
        SHELF_METAL = "Cold and ugly.",
        SHELF_MIDCENTURY = "Ugly.",
        SHELF_PALLET = "What even is this?",
        SHELF_PIPE = "Ugly.",
        SHELF_WALLMOUNT = "Blah.",
        SHELF_WOOD = "Might be flammable.",
        SLUGBUG = "Ugh!",
        SLUGBUG_COOKED = "The fire did nothing to make it more appetizing.",
        SMASHINGPOT = "Wish I could burn it.",
        SMELTER = {
            BURNT = "Okay, that's a liitle bit too far.",
            COOKING_SHORT = "The fire is doing its thing!",
            DONE = "When are we do this again?",
            EMPTY = "Oh yeah! Now I can burn metal.",
        },
        SNAKEBONESOUP = "Water and bones are better with fire.",
        SNAKEOIL = "I'm not convinced.",
        SNAKESKIN = "Leathery.",
        SNAKESKINHAT = "Water just runs right off it.",
        SNAKE_AMPHIBIOUS = "Jerks.",
        SNAKE_BONE = "Haha. I have its bone.",
        SPIDER_MONKEY = {
            DEAD = "One dead monkey.",
            GENERIC = "Ugh, what are you?!",
            SLEEPING = "It doesn't look so tough now.",
        },
        SPIDER_MONKEY_NEST = "This must burn!",
        SPIDER_MONKEY_TREE = "Looks burnable.",
        SPRINKLER = "It better not put out any of my fires.",
        STEAMEDHAMSANDWICH = "It's a ham sandwich.",
        STONE_DOOR = "Not even burnable.",
        SWINGING_LIGHT1 = "Sheesh. Someone doesn't care.",
        SWINGING_LIGHT_BASIC_BULB = "Sheesh. Someone doesn't care.",
        SWINGING_LIGHT_BASIC_METAL = "Sheesh. Someone doesn't care.",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "This needs fire.",
        SWINGING_LIGHT_DERBY = "Dressed up boring.",
        SWINGING_LIGHT_FLORAL_BLOOMER = "Ugly.",
        SWINGING_LIGHT_FLORAL_BULB = "Ugly.",
        SWINGING_LIGHT_FLORAL_SCALLOP = "Ugly.",
        SWINGING_LIGHT_PENDANT_CHERRIES = "Ugly.",
        SWINGING_LIGHT_ROPE_1 = "Sheesh. Someone doesn't care.",
        SWINGING_LIGHT_ROPE_2 = "Sheesh. Someone doesn't care.",
        SWINGING_LIGHT_TOPHAT = "Someone just dressed up boring.",
        TEA = "Fire makes everything better.",
        TEATREE = "It'll burn. That's all I care about.",
        TEATREE_NUT = "I'd burn it but it helps my allergies.",
        TEATREE_NUT_COOKED = "I set it on fire so now I can eat it.",
        TEATREE_NUT_SAPLING = "It's not even worth burning.",
        THUNDERBIRD = "It likes lightning like I like fire.",
        THUNDERBIRDNEST = "I could set that on fire.",
        THUNDERHAT = "This looks good on me.",
        TOPIARY = "Someone spent a lot of time pruning this kindling.",
        TOUCAN = "I like your nose.",
        TRAWLNET = "I'll catch a bunch of wet stuff with this.",
        TRAWLNETDROPPED = {
            GENERIC = "What's in the baaaag?",
            SOON = "It's going to sink soon!",
            SOONISH = "I believe that bag is sinking.",
        },
        TREE_PILLAR = "That's a big ol' tree.",
        TRINKET_GIFTSHOP_1 = "Looks kinda bossy.",
        TRINKET_GIFTSHOP_3 = "Who would want that?",
        TRINKET_GIFTSHOP_4 = "Hehe. It's so silly.",
        TUBERTREE = "An axe won't destroy this but fire will.",
        TUBER_BLOOM_CROP = "The flower means it's ripe.",
        TUBER_BLOOM_CROP_COOKED = "Aw. The flower didn't even burn.",
        TUBER_CROP = "Should be ripe before I burn it.",
        TUBER_CROP_COOKED = "Fire: it always makes things better.",
        TUNACAN = "Aw, but I like mine with ballphin!",
        TURF_COBBLEROAD = "The road is boring.",
        TURF_DEEPRAINFOREST = "The ground is boring.",
        TURF_DEEPRAINFOREST_NOCANOPY = "The ground is boring.",
        TURF_FIELDS = "The ground is boring.",
        TURF_FOUNDATION = "The ground is boring.",
        TURF_GASJUNGLE = "The ground is boring.",
        TURF_LAWN = "The ground is boring.",
        TURF_MOSS = "The ground is boring.",
        TURF_PAINTED = "The ground is boring.",
        TURF_PIGRUINS = "The ground is boring.",
        TURF_PLAINS = "The ground is boring.",
        TURF_RAINFOREST = "The ground is boring.",
        VAMPIREBAT = {
            DEAD = "Creepy and dead.",
            GENERIC = "Oh, you're creepy.",
            SLEEPING = "It must be tired from being such a jerk.",
        },
        VAMPIREBATCAVE = "Creepy things live there.",
        VAMPIRE_BAT_WING = "Yuck!",
        VENOMGLAND = "Gross! I wish I had gloves.",
        VENUS_STALK = "Looks like kindling.",
        VINE = "I could use this for something. Or I could just burn it.",
        WALKINGSTICK = "Zoom!",
        WALLCRACK_RUINS = "I should burn it down.",
        WALL_PIG_RUINS = "Some old wall.",
        WATERDROP = "It should really be a flame.",
        WEEVOLE = "Stand still so I can burn you.",
        WEEVOLE_CARAPACE = "Ew.",
        WINDOW_GREENHOUSE = "A big window looking out into nothing.",
        WINDOW_LARGE_SQUARE = "Outside is boring.",
        WINDOW_LARGE_SQUARE_CURTAIN = "Pretty and boring.",
        WINDOW_ROUND = "I can't even burn it.",
        WINDOW_ROUND_BURLAP = "I need a better decorator.",
        WINDOW_ROUND_CURTAINS_NAILS = "Outside is boring.",
        WINDOW_SMALL_PEAKED = "Outside is boring.",
        WINDOW_SMALL_PEAKED_CURTAIN = "Outside is boring.",
        WINDOW_TALL = "Outside is boring.",
        WINDOW_TALL_CURTAIN = "Outside is boring.",
        WOOD_DOOR = "It's wood. I could burn it.",
    },
}
