return {
    ANNOUNCE_DEHUMID = {
        "Ahh...it's cooled down.",
    },
    ANNOUNCE_HAYFEVER = "My sinuses are burning.",
    ANNOUNCE_HAYFEVER_OFF = "Sniff! I feel better now!",
    ANNOUNCE_SNEEZE = "Achoo!!",
    ANNOUNCE_TOO_HUMID = {
        "It's burning hot. But not in a good way.",
        "It's too hot.",
    },
    DESCRIBE = {
        ALLOY = "Fire makes everything better.",
        APORKALYPSE_CLOCK = "Looks ominous. I like it.",
        ARMOR_METALPLATE = "I feel like a tin can.",
        ARMOR_WEEVOLE = "This feels gross. I hope it works.",
        ASPARAGUS_PLANTED = "Haha! Found you!",
        CHITIN = "Bug skin.",
        CUTNETTLE = "It smells funny.",
        FLOWER_RAINFOREST = "It's kinda ugly. But it burns.",
        GLOWFLY = {
            DEAD = "Squashed.",
            GENERIC = "Looks slimy.",
            SLEEPING = "(Psst... you're gross.)",
        },
        GLOWFLY_COCOON = "Doing a bad job of hiding from me.",
        GRASS_TALL = {
            BURNING = "I win.",
            GENERIC = "This grass is tough!",
            PICKED = "Not tough enough!",
        },
        HALBERD = "Weapons are only good if they're twice your size.",
        PEAGAWK = {
            DEAD = "Very dead.",
            GENERIC = "Jeepers peepers!",
            SLEEPING = "I wonder what burning feathers smell like.",
        },
        PEAGAWKFEATHER = "Fancy feathers.",
        PEAGAWK_BUSH = "A bush. I think.",
        RABID_BEETLE = {
            DEAD = "Looks dead to me.",
            GENERIC = "What're you so mad about?",
            SLEEPING = "I should draw a mustache on its mustache while it sleeps.",
        },
        SHEARS = "Not as good as fire, but I guess it has its uses.",
        TREE_PILLAR = "That's a big ol' tree.",
        WEEVOLE = "Stand still so I can burn you.",
        WEEVOLE_CARAPACE = "Ew.",
    },
}
