return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Ugh, why would I do that now?",
        },
    },
    ANNOUCE_BATS = "Bats! Go away!",
    ANNOUNCE_BOAT_DAMAGED = "My boat is wounded!",
    ANNOUNCE_BOAT_SINKING = "I'm going down!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Goodbye cruel world!",
    ANNOUNCE_DEHUMID = {
        "Ahh...it's cooled down.",
    },
    ANNOUNCE_HAYFEVER = "My sinuses are burning.",
    ANNOUNCE_HAYFEVER_OFF = "Sniff! I feel better now!",
    ANNOUNCE_PICKPOOP = {
        "Ick!",
        "Gross!",
        "Burn it all!!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Ugh! Just die already!",
        "Why won't you break?!",
        "I should just burn you!",
    },
    ANNOUNCE_SNEEZE = "Achoo!!",
    ANNOUNCE_TOO_HUMID = {
        "It's burning hot. But not in a good way.",
        "It's too hot.",
    },
    ANNOUNCE_WAVE_BOOST = "Weeee!",
    DESCRIBE = {
        ALLOY = "Fire makes everything better.",
        ANCIENT_HULK = "Hey! Burning is my thing!",
        ANCIENT_ROBOTS_ASSEMBLY = "It's not gonna work like that.",
        ANCIENT_ROBOT_CLAW = "Dang! Can't burn it!",
        ANCIENT_ROBOT_HEAD = "Ugly.",
        ANCIENT_ROBOT_LEG = "I should kick it.",
        ANCIENT_ROBOT_RIBS = "Aww... It won't burn.",
        APORKALYPSE_CLOCK = "Looks ominous. I like it.",
        ARMOR_METALPLATE = "I feel like a tin can.",
        ARMOR_WEEVOLE = "This feels gross. I hope it works.",
        ASPARAGUS_PLANTED = "Haha! Found you!",
        BASEFAN = "Fan the flames.",
        BILL = {
            DEAD = "That's what you get.",
            GENERIC = "You're weird.",
            SLEEPING = "It even sleeps weird.",
        },
        BILL_QUILL = "I could probably use this for something.",
        BOATREPAIRKIT = "This should patch up any little leaks.",
        BOAT_CARGO = "I can carry so many flammables on this.",
        BOAT_CORK = "It'd be better if I could light it on fire.",
        BOAT_LOGRAFT = "Campfire wood has other uses, apparently!",
        BOAT_ROW = "Rowing? Really?",
        BOAT_TORCH = "Strangely not for torching boats.",
        BONESTAFF = "I'd prefer to burn my enemies but... meh.",
        CHITIN = "Bug skin.",
        COFFEE = "I suddenly feel motivated.",
        COFFEEBEANS = "These could use fire.",
        COFFEEBEANS_COOKED = "Ahhh, that aroma.",
        CUTNETTLE = "It smells funny.",
        DUNGBALL = "Can't even set it on fire.",
        DUNGBEETLE = {
            DEAD = "Squashed.",
            GENERIC = "Beat it, smelly beetle!",
            SLEEPING = "How do you sleep with that smell?",
            UNDUNGED = "You better run.",
        },
        DUNGPILE = {
            GENERIC = "Haha, that pile's huge!",
            PICKED = "What? I needed it.",
        },
        FLOWER_RAINFOREST = "It's kinda ugly. But it burns.",
        FROGLEGS_POISON = "I'm not sure I should eat that.",
        FROGLEGS_POISON_COOKED = "Only one way to find out if it's still poison...",
        FROG_POISON = {
            DEAD = "Yeah, that thing is dead.",
            GENERIC = "Doesn't look too dangerous to me.",
            SLEEPING = "It's sleeping.",
        },
        GLOWFLY = {
            DEAD = "Squashed.",
            GENERIC = "Looks slimy.",
            SLEEPING = "(Psst... you're gross.)",
        },
        GLOWFLY_COCOON = "Doing a bad job of hiding from me.",
        GOLDENMACHETE = "I don't want to scuff it up.",
        GOLDPAN = "You mean I have to do work?",
        GOLD_DUST = "It's probably not worth much.",
        GRABBING_VINE = "Ugh, vines!",
        GRASS_TALL = {
            BURNING = "I win.",
            GENERIC = "This grass is tough!",
            PICKED = "Not tough enough!",
        },
        HALBERD = "Weapons are only good if they're twice your size.",
        HANGING_VINE = "Ugh, vines!",
        HIPPOPOTAMOOSE = "Sure you have impressive horns but can you light fires?",
        HIPPO_ANTLER = "Yeesh. It's pretty big.",
        ICEDTEA = "I prefer hot things.",
        INFUSED_IRON = "Are you supposed to be special or something?",
        IRON = "I can't burn it with just my lighter.",
        LILYPAD = "I can't burn stuff out on the water.",
        LIVING_ARTIFACT = "Think of the things I can burn with it!",
        LOTUS = "Can I eat it? Or burn it?",
        LOTUS_FLOWER = "Just a dumb flower.",
        LOTUS_FLOWER_COOKED = "Fire makes it better.",
        MACHETE = "Or I could just burn my way through.",
        MANDRAKEHOUSE = "Gross.",
        MANDRAKEMAN = "Great. It's a big one. Just what I need.",
        PANGOLDEN = "Yeesh, he's sucking up all the gold!",
        PEAGAWK = {
            DEAD = "Very dead.",
            GENERIC = "Jeepers peepers!",
            SLEEPING = "I wonder what burning feathers smell like.",
        },
        PEAGAWKFEATHER = "Fancy feathers.",
        PEAGAWK_BUSH = "A bush. I think.",
        PIKO = {
            DEAD = "Didn't run fast enough.",
            GENERIC = "Squirrelly little guy.",
            SLEEPING = "I bet I could catch it now.",
        },
        PIKO_ORANGE = {
            DEAD = "Didn't run fast enough.",
            GENERIC = "Squirrelly little guy.",
            SLEEPING = "I bet I could catch it now.",
        },
        PUGALISK = "I'm gonna set it on fire!",
        PUGALISK_CORPSE = "Not sorry about this at all.",
        PUGALISK_FOUNTAIN = "I'll take some of that.",
        PUGALISK_RUINS_PILLAR = "I can't set it on fire.",
        PUGALISK_SKULL = "Ha! That's what you get!",
        PUGALISK_TRAP_DOOR = "I don't trust it.",
        RABID_BEETLE = {
            DEAD = "Looks dead to me.",
            GENERIC = "What're you so mad about?",
            SLEEPING = "I should draw a mustache on its mustache while it sleeps.",
        },
        SAIL_SNAKESKIN = "What a morbid sail.",
        SEDIMENTPUDDLE = "Yeesh, there's a lot of sparkles in there.",
        SHEARS = "Not as good as fire, but I guess it has its uses.",
        SMELTER = {
            BURNT = "Okay, that's a liitle bit too far.",
            COOKING_SHORT = "The fire is doing its thing!",
            DONE = "When are we do this again?",
            EMPTY = "Oh yeah! Now I can burn metal.",
        },
        SNAKEBONESOUP = "Water and bones are better with fire.",
        SNAKESKIN = "Leathery.",
        SNAKE_BONE = "Haha. I have its bone.",
        TEA = "Fire makes everything better.",
        TEATREE = "It'll burn. That's all I care about.",
        TEATREE_NUT = "I'd burn it but it helps my allergies.",
        TEATREE_NUT_COOKED = "I set it on fire so now I can eat it.",
        TEATREE_NUT_SAPLING = "It's not even worth burning.",
        TREE_PILLAR = "That's a big ol' tree.",
        WEEVOLE = "Stand still so I can burn you.",
        WEEVOLE_CARAPACE = "Ew.",
    },
}
