return {
    ANNOUNCE_DEHUMID = {
        "This is much more comfortable.",
    },
    ANNOUNCE_HAYFEVER = "My nose is itchy...",
    ANNOUNCE_HAYFEVER_OFF = "Huh, finally comfortable.",
    ANNOUNCE_PICKPOOP = {
        "Alas!",
        "So dirty!",
        "Unbearable!",
    },
    ANNOUNCE_SNEEZE = "Ah chirp!",
    ANNOUNCE_TOO_HUMID = {
        "%s is not breathable at all.",
        "This %s is so boring that I can't breathe.",
    },
    DESCRIBE = {
        ALLOY = "Proper processing makes it better.",
        APORKALYPSE_CLOCK = "A fairly complex set of instrumentation.",
        ARMOR_METALPLATE = "Bulky, but surprisingly well-protected.",
        ARMOR_WEEVOLE = "Not very comfortable, just let it go.",
        ASPARAGUS_PLANTED = "Wholesome green vegetables.",
        BALLPEIN_HAMMER = "This way I can get them out without damaging them.",
        BASEFAN = "I'm sure bossman would be very interested in it.",
        CHITIN = "I don't know what this can be used for.",
        CUTNETTLE = "Keep your breath flowing and refresh your mind.",
        DUNGBALL = "I would never touch it.",
        DUNGBEETLE = {
            DEAD = "Is she dead?",
            GENERIC = "No matter how many times you see it, it’s hard to accept.",
            SLEEPING = "Rest is a must.",
            UNDUNGED = "It looks like the loss of a loved one.",
        },
        DUNGPILE = {
            GENERIC = "Ugh, gross.",
            PICKED = "I thought it was over?",
        },
        FLOWER_RAINFOREST = "I have never seen such flowers.",
        GLOWFLY = {
            DEAD = "It's broken.",
            GENERIC = "Flying spotlights.",
            SLEEPING = "It's time for maintenance.",
        },
        GLOWFLY_COCOON = "Change is happening.",
        GOLDENMACHETE = "This just made my job easier.",
        GOLDPAN = "Separate the metal.",
        GOLD_DUST = "gold! My luck has come!",
        GRABBING_VINE = "I saw a strong rope.",
        GRASS_TALL = {
            BURNING = "A Grass fire!",
            GENERIC = "That's some... very tall grass.",
            PICKED = "All work is done.",
        },
        HALBERD = "More suited to combat than to work.",
        HANGING_VINE = "I saw a strong rope.",
        IRON = "Invaluable material for manufacturing useful tools.",
        MACHETE = "Hack and slash! Working's always fun.",
        PANGOLDEN = "Living metallurgical.",
        PEAGAWK = {
            GENERIC = "Always be vigilant.",
            SLEEPING = "It let down its guard.",
        },
        PEAGAWKFEATHER = "It's still looking at me.",
        PEAGAWK_BUSH = "A vigilant bush, how strange!",
        PIG_RUINS_HEAD = "There must be some way to remove the middle part.",
        PIG_RUINS_IDOL = "There must be some way to remove the top part.",
        PIG_RUINS_PIG = "It's a bit too showy.",
        PIG_RUINS_PLAQUE = "There must be some way to remove the top part.",
        PIG_RUINS_SOW = "This one looks different, let's bring it back.",
        RABID_BEETLE = {
            DEAD = "Ah, it stopped.",
            GENERIC = "What are you all excited about?",
            SLEEPING = "Calm down!",
        },
        RELIC_1 = "There will be rich people who want this.",
        RELIC_2 = "I guess it would have some cultural value.",
        RELIC_3 = "After all, it is a cultural relic, and maybe the pigs will want it.",
        RELIC_4 = "This one looks different, maybe she's special.",
        RELIC_5 = "It is inlaid with many precious stones and must be very valuable.",
        SEDIMENTPUDDLE = "The metal content is seriously over the limit.",
        SHEARS = "Shears for gardening.",
        SMELTER = {
            BURNT = "Forgot fire rules, didn't you?",
            COOKING_SHORT = "Rome was not built in a day.",
            DONE = "knock off!",
            EMPTY = "Process the metallic material.",
        },
        TREE_PILLAR = "It stretches to the end of my field of vision.",
        WEEVOLE = "Once you've dealt with bedbugs, weevils aren't so bad.",
        WEEVOLE_CARAPACE = "It can be regarded as clean.",
    },
}
