return {
    ACTIONFAIL = {
        USEDOOR = {
            GENERIC = "This door doesn't work.",
            LOCKED = "I need the right key.",
        },
    },
    ANNOUCE_BATS = "bat! It seems like it’s coming for me!",
    ANNOUNCE_BOAT_DAMAGED = "I should tape these holes up.",
    ANNOUNCE_BOAT_SINKING = "I don't think tape will be enough now.",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "That's a lotta damage!",
    ANNOUNCE_DEHUMID = {
        "This is much more comfortable.",
    },
    ANNOUNCE_HAYFEVER = "My nose is itchy...",
    ANNOUNCE_HAYFEVER_OFF = "Huh, finally comfortable.",
    ANNOUNCE_PICKPOOP = {
        "Alas!",
        "So dirty!",
        "Unbearable!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "So hard!",
        "My hands are numb!",
        "It definitely has a weak spot.",
    },
    ANNOUNCE_SNEEZE = "Ah chirp!",
    ANNOUNCE_TOO_HUMID = {
        "%s is not breathable at all.",
        "This %s is so boring that I can't breathe.",
    },
    ANNOUNCE_WAVE_BOOST = "Whoo nelly!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "I think it was dead already.",
            GENERIC = "A guy who just waits for food to come to his mouth.",
            SLEEPING = "It's resting.",
        },
        ALLOY = "Proper processing makes it better.",
        ANCIENT_HULK = "Why is it always killer automations?",
        ANCIENT_ROBOTS_ASSEMBLY = "There is still work to be done.",
        ANCIENT_ROBOT_CLAW = "I'll handle it.",
        ANCIENT_ROBOT_HEAD = "A hideous mechanical head.",
        ANCIENT_ROBOT_LEG = "This boot is not insulated at all.",
        ANCIENT_ROBOT_RIBS = "Machine frame, I guess.",
        APORKALYPSE_CLOCK = "A fairly complex set of instrumentation.",
        ARMOR_METALPLATE = "Bulky, but surprisingly well-protected.",
        ARMOR_WEEVOLE = "Not very comfortable, just let it go.",
        ASPARAGUS_PLANTED = "Wholesome green vegetables.",
        BALLPEIN_HAMMER = "So I can take them out without damaging them.",
        BASEFAN = "I'm sure bossman would be very interested in it.",
        BILL = {
            DEAD = "Alas, he died.",
            GENERIC = "Wow, you are so annoying.",
            SLEEPING = "take a break.",
        },
        BILL_QUILL = "I think I can use it on...",
        BOATREPAIRKIT = "Who needs glue? My tape is sticky enough.",
        BOAT_CARGO = "It's my big, bouyant toolbox.",
        BOAT_CORK = "It definitely fails any security tests.",
        BOAT_LOGRAFT = "I could do better...",
        BOAT_ROW = "If I wanna move, I gotta put my back into it.",
        BOAT_TORCH = "This torch is a little light. Ha!",
        BONESTAFF = "This is definitely a huge security risk.",
        CHITIN = "I don't know what this can be used for.",
        COFFEE = "Essential for any hard worker!",
        COFFEEBEANS = "I should toss them over a fire.",
        COFFEEBEANS_COOKED = "Ah, the smell of coffee beans in the morning!",
        CUTNETTLE = "Keep your breath flowing and refresh your mind.",
        DISARMING_KIT = "Say no to unfriendly machines.",
        DUNGBALL = "I would never touch it.",
        DUNGBEETLE = {
            DEAD = "Is she dead?",
            GENERIC = "No matter how many times you see it, it’s hard to accept.",
            SLEEPING = "Rest is a must.",
            UNDUNGED = "It looks like the loss of a loved one.",
        },
        DUNGPILE = {
            GENERIC = "Ugh, gross.",
            PICKED = "I thought it was over...",
        },
        FLOWER_RAINFOREST = "I have never seen such flowers.",
        FROGLEGS_POISON = "This can be harmful to us.",
        FROGLEGS_POISON_COOKED = "Such processing...",
        FROG_POISON = {
            DEAD = "Alas, he died.",
            GENERIC = "There's something vicious underneath their skin.",
            SLEEPING = "take a break.",
        },
        GLOWFLY = {
            DEAD = "It's broken.",
            GENERIC = "Flying spotlights.",
            SLEEPING = "It's time for maintenance.",
        },
        GLOWFLY_COCOON = "Change is happening.",
        GOLDENMACHETE = "This just made my job easier.",
        GOLDPAN = "Separate the metal.",
        GOLD_DUST = "gold! My luck has come!",
        GRABBING_VINE = "I saw a strong rope.",
        GRASS_TALL = {
            BURNING = "A Grass fire!",
            GENERIC = "That's some... very tall grass.",
            PICKED = "All work is done.",
        },
        HALBERD = "More suited to combat than to work.",
        HANGING_VINE = "I saw a strong rope.",
        HIPPOPOTAMOOSE = "Bathing all day long didn't make them smell any better.",
        HIPPO_ANTLER = "This could probably be made into a luxury item or something.",
        ICEDTEA = "What a enjoyment.",
        INFUSED_IRON = "This is not a natural metal pattern.",
        IRON = "Invaluable material for manufacturing useful tools.",
        KINGFISHER = {
            DEAD = "Dead as a doornail.",
            GENERIC = "Oh, a fisher bird!",
            SLEEPING = "Sleeping on the job.",
        },
        LIFEPLANT = "I am also a good gardener.",
        LILYPAD = "I have never seen such a big water lily!",
        LIVING_ARTIFACT = "WX seems confused about us wearing it",
        LOTUS = "What a beautiful aquatic plant.",
        LOTUS_FLOWER = "it's beautiful!",
        LOTUS_FLOWER_COOKED = "It tastes crunchy.",
        MACHETE = "Hack and slash! Working's always fun.",
        MAGNIFYING_GLASS = "Make sure you don't miss even the smallest detail.",
        MANDRAKEHOUSE = "It was built to look like a screaming face.",
        MANDRAKEMAN = "Even I can't stand this.",
        MEAN_FLYTRAP = {
            DEAD = "It's dead.",
            GENERIC = "Insatiable hunger for foods.",
            SLEEPING = "It's resting.",
        },
        METALPLATEHAT = "Looks like something a colonist would wear.",
        NECTAR_POD = "Semi-finished product of honey.",
        PANGOLDEN = "Living metallurgical.",
        PARROT_BLUE = {
            DEAD = "Dead as a doornail.",
            GENERIC = "Blue parrot.",
            SLEEPING = "Sleeping on the job.",
        },
        PEAGAWK = {
            GENERIC = "Always be vigilant.",
            SLEEPING = "It let down its guard.",
        },
        PEAGAWKFEATHER = "It's still looking at me.",
        PEAGAWK_BUSH = "A vigilant bush, how strange!",
        PIGEON = {
            DEAD = "Dead as a doornail.",
            GENERIC = "You seen one, you seen'em all.",
            SLEEPING = "Sleeping on the job.",
        },
        PIGHOUSE_CITY = {
            BURNING = "Burned to the ground.",
            GENERIC = "It's hard to imagine such a house being built by pigs.",
        },
        PIGHOUSE_FARM = {
            BURNING = "The flames consumed everything here.",
            GENERIC = "A farm house for farmer.",
        },
        PIGHOUSE_MINE = {
            BURNING = "The flames consumed everything here.",
            GENERIC = "A mine house for miner.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "A restless guy.",
            SLEEPING = "Go to sleep, lazy pig.",
        },
        PIGMAN_QUEEN = "Pampered guy.",
        PIG_PALACE = "Uh, is it necessary to be so exaggerated?",
        PIG_RUINS_ARTICHOKE = "So they really like artichokes.",
        PIG_RUINS_HEAD = "There must be some way to remove the middle part.",
        PIG_RUINS_IDOL = "There must be some way to remove the top part.",
        PIG_RUINS_MUSHROOM = "It is inlaid with many precious stones and must be very valuable.",
        PIG_RUINS_PLAQUE = "There must be some way to remove the top part.",
        PIG_RUINS_SOW = "This one looks different, let's bring it back.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Firefighting work was not done well.",
            GENERIC = "The place where officials work.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Hey! Who did it?",
            GENERIC = "My new workshop.",
        },
        PIKO = {
            DEAD = "died.",
            GENERIC = "An annoying thief.",
            SLEEPING = "Recharge your batteries for more trouble.",
        },
        PIKO_ORANGE = {
            DEAD = "died.",
            GENERIC = "It eats almost anything.",
            SLEEPING = "Recharge your batteries for more trouble.",
        },
        PUGALISK = "monster! I'll let you know you messed with the wrong person!",
        PUGALISK_CORPSE = "It is also partially buried underground.",
        PUGALISK_FOUNTAIN = "No one can refuse to stay young forever.",
        PUGALISK_RUINS_PILLAR = "Shaky.",
        PUGALISK_SKULL = "We beat the proof of it.",
        PUGALISK_TRAP_DOOR = "Possibly a shaft cover.",
        RABID_BEETLE = {
            DEAD = "Ah, it stopped.",
            GENERIC = "What are you all excited about?",
            SLEEPING = "Calm down!",
        },
        REEDS_WATER = "Looks like they're hollow inside.",
        RELIC_1 = "There will be rich people who want this.",
        RELIC_2 = "I guess it would have some cultural value.",
        RELIC_3 = "After all, it is a cultural relic, and maybe the pigs will want it.",
        RELIC_4 = "Maybe she is special.",
        RELIC_5 = "Be careful not to break it.",
        SAIL_SNAKESKIN = "Just watch those scales catch the wind!",
        SCORPION = {
            DEAD = "Phew, now I don't have to be nervous all the time.",
            GENERIC = "I don't like you.",
            SLEEPING = "Don't wake it.",
        },
        SEDIMENTPUDDLE = "The metal content is seriously over the limit.",
        SHEARS = "Shears for gardening.",
        SMELTER = {
            BURNT = "Forgot fire rules, didn't you?",
            COOKING_SHORT = "Rome was not built in a day.",
            DONE = "knock off!",
            EMPTY = "Process the metallic material.",
        },
        SNAKEBONESOUP = "To put it bluntly, cooking this way is self-deception.",
        SNAKEOIL = "Riiight. I don't buy it.",
        SNAKESKIN = "The texture feels incredible. I got some ideas for this.",
        SNAKE_AMPHIBIOUS = "Stay away from me, you vicious creature!",
        SNAKE_BONE = "I should be able to do something with it...",
        TEA = "A good pot of tea sets the spirit of the day.",
        TEATREE = "Enough to whole workshop's tea supply.",
        TEATREE_NUT = "Save my nose from fire and water.",
        TEATREE_NUT_COOKED = "Heat enhances its effects.",
        TEATREE_NUT_SAPLING = "Our tea supply for next season.",
        TOUCAN = "Look at the beak on that one!",
        TREE_PILLAR = "It stretches to the end of my field of vision.",
        VAMPIREBAT = {
            DEAD = "Go back to your shadow!",
            GENERIC = "Messenger of the woes.",
            SLEEPING = "Recharge your batteries.",
        },
        VAMPIREBATCAVE = "I felt a chill running down my spine.",
        VENOMGLAND = "Haha, gross.",
        VENUS_STALK = "As far as building materials are concerned, it's a bit too watery.",
        VINE = "It's strong! I can tie stuff up with this.",
        WALKINGSTICK = "When dehydrated it becomes a durable crutch.",
        WATERDROP = "Is this really...water?",
        WEEVOLE = "Once you've dealt with bedbugs, weevils aren't so bad.",
        WEEVOLE_CARAPACE = "It can be regarded as clean.",
    },
}
