return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Small boat has no damages to repair! Wolfgang could punch it?",
        },
    },
    ANNOUCE_BATS = "Bats not get Wolfgang!",
    ANNOUNCE_BOAT_DAMAGED = "Ship is weak! Needs fixingtimes.",
    ANNOUNCE_BOAT_SINKING = "I will fight sea!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Wolfgang will punch death!",
    ANNOUNCE_DEHUMID = {
        "Ha! Wolfgang beat the heat!",
    },
    ANNOUNCE_HAYFEVER = "Allergies strong like Wolfgang!",
    ANNOUNCE_HAYFEVER_OFF = "Ha! Wolfgang beat allergies!",
    ANNOUNCE_PICKPOOP = {
        "Bah!",
        "Ew!",
        "Wolfgang is disgusted!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Why Wolfgang not hurting you?!",
        "Is tough beast to crack!",
        "Wolfgang needs to fight smarter...",
    },
    ANNOUNCE_SNEEZE = "Achoo! Excuse Wolfgang.",
    ANNOUNCE_TOO_HUMID = {
        "Wolfgang don't like %s in this heat.",
        "Is too muggy.",
    },
    ANNOUNCE_WAVE_BOOST = "I am mighty!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Is not working.",
            GENERIC = "Do not eat Wolfgang!",
            SLEEPING = "Plant is bedtime.",
        },
        ALLOY = "Fire make it strong like Wolfgang.",
        ANCIENT_HULK = "Big robot not too big for Wolfgang to smash!",
        ANCIENT_ROBOTS_ASSEMBLY = "Is missing pieces. Wolfgang will help!",
        ANCIENT_ROBOT_CLAW = "Is sleepy little robot.",
        ANCIENT_ROBOT_HEAD = "Is big head. Wolfgang head is bigger!",
        ANCIENT_ROBOT_LEG = "It have to work on legs.",
        ANCIENT_ROBOT_RIBS = "Wolfgang can eat ribs?",
        APORKALYPSE_CLOCK = "Is clock of scary things.",
        ARMOR_METALPLATE = "No one beat Wolfgang now!",
        ARMOR_WEEVOLE = "Wolfgang win!",
        ASPARAGUS_PLANTED = "Haha. Is like tiny vegetable hats.",
        BALLPEIN_HAMMER = "Wolfgang not good with subtlety.",
        BASEFAN = "Is cool on Wolfgang skin.",
        BILL = {
            DEAD = "Wolfgang win.",
            GENERIC = "Wolfgang stronger than spiky goose rat.",
            SLEEPING = "Spiky goose rat is night night.",
        },
        BILL_QUILL = "Is for teeny diggings.",
        BOATREPAIRKIT = "Restore my mighty vessel!",
        BOAT_CARGO = "What a mighty storage hold!",
        BOAT_CORK = "Is weakling.",
        BOAT_LOGRAFT = "This raft is... not so mighty.",
        BOAT_ROW = "I will row with powerful arms!",
        BOAT_TORCH = "Flame on boat is good idea!",
        BONESTAFF = "Is freezing ray made of mighty beast.",
        CHITIN = "Icky bug pieces.",
        COFFEE = "Strong, like Wolfgang!",
        COFFEEBEANS = "Tiny beans give Wolfgang strength!",
        COFFEEBEANS_COOKED = "Is bitter beans!",
        CUTNETTLE = "Is good for clearing nose.",
        DISARMING_KIT = "Wolfgang beat booby trap now.",
        DUNGBALL = "Is ball of poop.",
        DUNGBEETLE = {
            DEAD = "Is dead. Is still stink.",
            GENERIC = "Bug runs on ball of poop.",
            SLEEPING = "Is pooped.",
            UNDUNGED = "Bug fell off ball of poop.",
        },
        DUNGPILE = {
            GENERIC = "Is more smelly than armpit.",
            PICKED = "All gone. For now.",
        },
        FLOWER_RAINFOREST = "Little smelly flower.",
        FROGLEGS_POISON = "Is danger froggy parts!",
        FROGLEGS_POISON_COOKED = "Even danger food make Wolfgang strong.",
        FROG_POISON = {
            DEAD = "Is no life.",
            GENERIC = "Is danger froggy.",
            SLEEPING = "Sleepy little froggy.",
        },
        GLOWFLY = {
            DEAD = "Light bug is lights out.",
            GENERIC = "Is light bug.",
            SLEEPING = "Light bug is dark.",
        },
        GLOWFLY_COCOON = "Bug look cozy.",
        GOLDENMACHETE = "Hoighty toighty knife!",
        GOLDPAN = "Is for eating from?",
        GOLD_DUST = "Wolfgang like. Is shiny.",
        GRABBING_VINE = "Watch out for that tree!",
        GRASS_TALL = {
            BURNING = "Wolfgang is not doing that!",
            GENERIC = "Very sturdy grass.",
            PICKED = "Wolfgang is mightiest!",
        },
        HALBERD = "Sword is for weak no-muscle men.",
        HANGING_VINE = "Watch out for that tree!",
        HIPPOPOTAMOOSE = "Is mighty but Wolfgang is mightier!",
        HIPPO_ANTLER = "Wolfgang get mighty antler!",
        ICEDTEA = "Is cool. Like Wolfgang.",
        INFUSED_IRON = "Is strong and glowing.",
        IRON = "Iron is strong like Wolfgang.",
        LILYPAD = "Big water leaf.",
        LIVING_ARTIFACT = "Mighty Wolfgang can get mightier!",
        LOTUS = "Is puny pond plant.",
        LOTUS_FLOWER = "Is puny pond flower.",
        LOTUS_FLOWER_COOKED = "Wolfgang eat you now.",
        MACHETE = "Ah! Very good!",
        MAGNIFYING_GLASS = "Hehe! Wolfgang eye is big now!",
        MANDRAKEHOUSE = "Hill for plant mans.",
        MANDRAKEMAN = "Wolfgang stronger than you!",
        MEAN_FLYTRAP = {
            DEAD = "Is not life.",
            GENERIC = "Plant Men is puny and weak!",
            SLEEPING = "Plant Men is full of sleep.",
        },
        METALPLATEHAT = "Is funny little tin hat.",
        NECTAR_POD = "Is sweet like honey.",
        PANGOLDEN = "Hehe. Haves big nose.",
        PEAGAWK = {
            DEAD = "Is blink-blink no more.",
            GENERIC = "Funny blink-blink bird!",
            SLEEPING = "Is sleep, but eyes still blink-blink.",
        },
        PEAGAWKFEATHER = "Is blink-blink bird feather.",
        PEAGAWK_BUSH = "Is just bush.",
        PIG_RUINS_ARTICHOKE = "Is odd statue.",
        PIG_RUINS_HEAD = "Is big and mighty head. Like Wolfgang!",
        PIG_RUINS_IDOL = "Piggies might like those.",
        PIG_RUINS_PLAQUE = "Is piggy thing.",
        PIKO = {
            DEAD = "Is tiny fluff dead part.",
            GENERIC = "Tiny, weak fluff.",
            SLEEPING = "Tiny fluff is sleep time.",
        },
        PIKO_ORANGE = {
            DEAD = "Is tiny orange fluff dead part.",
            GENERIC = "Tiny, weak orange fluff.",
            SLEEPING = "Tiny orange fluff is sleep time.",
        },
        PUGALISK = "Stay still so Wolfgang can fight you!",
        PUGALISK_CORPSE = "Wolfgang conquer mighty beast!",
        PUGALISK_FOUNTAIN = "Wolfgang stay young forever.",
        PUGALISK_RUINS_PILLAR = "Wolfgang is stronger.",
        PUGALISK_SKULL = "Is mighty skull. Wolfgang is mightier.",
        PUGALISK_TRAP_DOOR = "Is funny rock.",
        RABID_BEETLE = {
            DEAD = "Is stomped.",
            GENERIC = "Wolfgang will stomp bad beetle!",
            SLEEPING = "Hehe. Is funny mustache.",
        },
        REEDS_WATER = "Is pond plant.",
        RELIC_1 = "Is like little pig men.",
        RELIC_2 = "Is thing from little pig men.",
        RELIC_3 = "Is stone piggie nose.",
        RELIC_4 = "Is not mighty. Is fancy.",
        RELIC_5 = "Has the shiny rocks in it.",
        SAIL_SNAKESKIN = "Skin of dead snake will help me sail.",
        SCORPION = {
            DEAD = "Ha! Is dead!",
            GENERIC = "Stay away from Wolfgang!",
            SLEEPING = "Shhh. Is sleep.",
        },
        SEDIMENTPUDDLE = "Hello little sparklies!",
        SHEARS = "Is for cutting plant things.",
        SMELTER = {
            BURNT = "Smelter is dead.",
            COOKING_SHORT = "Is almost melt!",
            DONE = "Fire make metal bricks.",
            EMPTY = "Wolfgang lifted it without difficulty.",
        },
        SNAKEBONESOUP = "Is food little for Wolfgang.",
        SNAKEOIL = "Good for shining Wolfgang's muscles!",
        SNAKESKIN = "I will use as bandana.",
        SNAKE_AMPHIBIOUS = "Wolfgang punch you!",
        SNAKE_BONE = "Wolfgang win.",
        TEA = "Wolfgang love tea time!",
        TEATREE = "Is strong but not strong like Wolfgang.",
        TEATREE_NUT = "Is good for Wolfgang's mighty sneezes.",
        TEATREE_NUT_COOKED = "Wolfgang eat tiny tree baby.",
        TEATREE_NUT_SAPLING = "Is tiny little big tree.",
        TOUCAN = "Bird flees at the sight of Wolfgang.",
        TREE_PILLAR = "Mightiest tree!",
        VAMPIREBAT = {
            DEAD = "Is dead. Wolfgang win!",
            GENERIC = "Is flappy bad guy!",
            SLEEPING = "Flappy bad guy is night-night.",
        },
        VAMPIREBATCAVE = "Wolfgang is no like dark hole.",
        VENUS_STALK = "Is Plant Men parts.",
        VINE = "For string enemies together.",
        WALKINGSTICK = "Is for good walk steps.",
        WEEVOLE = "Pesky bug. Leave Wolfgang alone!",
        WEEVOLE_CARAPACE = "Is pesky bug skin.",
    },
}
