return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Small boat has no damages to repair! Wolfgang could punch it?",
        },
        USEDOOR = {
            GENERIC = "Open for Wolfgang!",
            LOCKED = "Wolfgang needs a mighty key.",
        },
    },
    ANNOUCE_ALARMOVER = "Nothing can harm mighty Wolfgang!",
    ANNOUCE_BATS = "Bats not get Wolfgang!",
    ANNOUCE_OTHERWORLD_DEED = "Wolfgang don't know where this is.",
    ANNOUCE_UNDERLEAFCANOPY = "Wolfgang does not like tree dark!",
    ANNOUNCE_BOAT_DAMAGED = "Ship is weak! Needs fixingtimes.",
    ANNOUNCE_BOAT_SINKING = "I will fight sea!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Wolfgang will punch death!",
    ANNOUNCE_DEHUMID = {
        "Ha! Wolfgang beat the heat!",
    },
    ANNOUNCE_GAS_DAMAGE = "Hack! Cough! Ack!",
    ANNOUNCE_HAYFEVER = "Allergies strong like Wolfgang!",
    ANNOUNCE_HAYFEVER_OFF = "Ha! Wolfgang beat allergies!",
    ANNOUNCE_HOUSE_DOOR = "Wolfgang will get mightiest permit first!",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "Is door.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Is no door.",
    ANNOUNCE_MYSTERY_FOUND = "Wolfgang found something.",
    ANNOUNCE_MYSTERY_NOREWARD = "Is nothing.",
    ANNOUNCE_NOTHING_FOUND = "Is not finding anything here.",
    ANNOUNCE_PICKPOOP = {
        "Bah!",
        "Ew!",
        "Wolfgang is disgusted!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Why Wolfgang not hurting you?!",
        "Is tough beast to crack!",
        "Wolfgang needs to fight smarter...",
    },
    ANNOUNCE_ROOM_STUCK = "No. Sometimes smashing lead to Wolfgang's downfall.",
    ANNOUNCE_SNEEZE = "Achoo! Excuse Wolfgang.",
    ANNOUNCE_SUITUP = "WOLFGANG IS MIGHTY!",
    ANNOUNCE_TAXDAY = "Time for piggies to pay Wolfgang.",
    ANNOUNCE_TOOLCORRODED = "Wolfgang need better tools.",
    ANNOUNCE_TOO_HUMID = {
        "Wolfgang don't like %s in this heat.",
        "Is too muggy.",
    },
    ANNOUNCE_TURFTOOHARD = "Ugh! UGH! Wolfgang let you be for now.",
    ANNOUNCE_WAVE_BOOST = "I am mighty!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Is not working.",
            GENERIC = "Do not eat Wolfgang!",
            SLEEPING = "Plant is bedtime.",
        },
        ALLOY = "Fire make it strong like Wolfgang.",
        ALOE = "Wolfgang eat everything.",
        ALOE_COOKED = "It make Wolfgang big and strong.",
        ALOE_PLANTED = "Wolfgang pick it.",
        ALOE_SEEDS = "Is for planting.",
        ANCIENT_HERALD = "Wolfgang just let him be.",
        ANCIENT_HULK = "Big robot not too big for Wolfgang to smash!",
        ANCIENT_REMNANT = "Is piece of scary man.",
        ANCIENT_ROBOTS_ASSEMBLY = "Is missing pieces. Wolfgang will help!",
        ANCIENT_ROBOT_CLAW = "Is sleepy little robot.",
        ANCIENT_ROBOT_HEAD = "Is big head. Wolfgang head is bigger!",
        ANCIENT_ROBOT_LEG = "It have to work on legs.",
        ANCIENT_ROBOT_RIBS = "Wolfgang can eat ribs?",
        ANTCHEST = "Sweet stuff for Wolfgang!",
        ANTCOMBHOME = "Is looking like Bug Man home.",
        ANTMAN = {
            DEAD = "Bug Man is dead.",
            GENERIC = "Hello, Bug Man!",
            SLEEPING = "Night-night, Bug Man!",
        },
        ANTMAN_WARRIOR = "Wolfgang smash mighty Bug Man!",
        ANTMASKHAT = "Make Wolfgang look like Bug Man.",
        ANTQUEEN_THRONE = "Stuff hiding in there.",
        ANTSUIT = "Wolfgang just want to fit in.",
        ANT_CAVE_LANTERN = "It sticky and keep dark away.",
        APORKALYPSE_CLOCK = "Is clock of scary things.",
        ARMORVORTEXCLOAK = "Scary cloak! Wolfgang wear it anyway.",
        ARMOR_METALPLATE = "No one beat Wolfgang now!",
        ARMOR_SNAKESKIN = "Is made to show my mighty muscles.",
        ARMOR_WEEVOLE = "Wolfgang win!",
        ASPARAGUS_PLANTED = "Haha. Is like tiny vegetable hats.",
        BALLPEIN_HAMMER = "Wolfgang not good with subtlety.",
        BANDITHAT = "Wolfgang win at hide-and-seek now.",
        BANDITMAP = "Is where bad guy hide Wolfgang money.",
        BANDITTREASURE = "Wolfgang find it!",
        BASEFAN = "Is cool on Wolfgang skin.",
        BATHAT = "Is funny little bat hat.",
        BILL = {
            DEAD = "Wolfgang win.",
            GENERIC = "Wolfgang stronger than spiky goose rat.",
            SLEEPING = "Spiky goose rat is night night.",
        },
        BILL_QUILL = "Is for teeny diggings.",
        BLUNDERBUSS = "Is making big boom.",
        BOATREPAIRKIT = "Restore my mighty vessel!",
        BOAT_CARGO = "What a mighty storage hold!",
        BOAT_CORK = "Is weakling.",
        BOAT_LOGRAFT = "This raft is... not so mighty.",
        BOAT_ROW = "I will row with powerful arms!",
        BOAT_TORCH = "Flame on boat is good idea!",
        BONESTAFF = "Is freezing ray made of mighty beast.",
        BRAMBLESPIKE = "Wolfgang punch it!",
        BRAMBLE_BULB = "Is food? Wolfgang hungry.",
        BRAMBLE_CORE = "Is pretty. Wolfgang punch brambles for it.",
        BUGREPELLENT = "Is for punching teensy bugs.",
        BURR = "Is tiny tree bits.",
        BURR_SAPLING = "Is tiny tree.",
        CANDLEHAT = "Now Wolfgang hands free for punching.",
        CHITIN = "Icky bug pieces.",
        CITY_HAMMER = "Wolfgang destroy whole city!",
        CITY_LAMP = {
            GENERIC = "Wolfgang does not like the dark.",
            ON = "Is lamp for night lights.",
        },
        CLAWPALMTREE = "Is creepy tree.",
        CLAWPALMTREE_SAPLING = "Is grow up big and strong.",
        CLIPPINGS = "Wolfgang work hard!",
        COFFEE = "Strong, like Wolfgang!",
        COFFEEBEANS = "Tiny beans give Wolfgang strength!",
        COFFEEBEANS_COOKED = "Is bitter beans!",
        CONSTRUCTION_PERMIT = "Paper says Wolfgang can build mighty extension!",
        CORK = "Is from funny tree.",
        CORKCHEST = "Is for keeping little doggies out.",
        CORK_BAT = "Wolfgang hardly feel this at all.",
        CUTNETTLE = "Is good for clearing nose.",
        DECO_CAVE_BAT_BURROW = "Is smelly like flappy bad guys.",
        DECO_CAVE_BEAM_ROOM = "Is strong like Wolfgang.",
        DECO_CHAIR_BENCH = "Chair big like Wolfgang.",
        DECO_CHAIR_CLASSIC = "Is for sitting.",
        DECO_CHAIR_CORNER = "Is for sitting.",
        DECO_CHAIR_FOOTREST = "Wolfgang put big foots on.",
        DECO_CHAIR_HORNED = "Is for sitting.",
        DECO_CHAIR_LOUNGE = "Chair big like Wolfgang.",
        DECO_CHAIR_MASSAGER = "Is for... sitting?",
        DECO_CHAIR_OTTOMAN = "Wolfgang put big foots on.",
        DECO_CHAIR_ROCKING = "Is for rocking.",
        DECO_CHAIR_STUFFED = "Wolfgang deserve relax.",
        DECO_RUINS_BEAM_ROOM = "Is strong like Wolfgang.",
        DECO_RUINS_BEAM_ROOM_BLUE = "Is strong like Wolfgang.",
        DECO_RUINS_ENDSWELL = "Spooky water not frighten Wolfgang.",
        DECO_RUINS_FOUNTAIN = "Should Wolfgang take a chance?",
        DEED = "Wolfgang have place to keep stuff now.",
        DEMOLITION_PERMIT = "Wolfgang can punch walls down now.",
        DISARMING_KIT = "Wolfgang beat booby trap now.",
        DISGUISEHAT = "Hehe. Is funny little pig mask.",
        DUG_NETTLE = "Wolfgang put in ground.",
        DUNGBALL = "Is ball of poop.",
        DUNGBEETLE = {
            DEAD = "Is dead. Is still stink.",
            GENERIC = "Bug runs on ball of poop.",
            SLEEPING = "Is pooped.",
            UNDUNGED = "Bug fell off ball of poop.",
        },
        DUNGPILE = {
            GENERIC = "Is more smelly than armpit.",
            PICKED = "All gone. For now.",
        },
        FEATHER_THUNDER = "Wolfgang find feather!",
        FLOWER_RAINFOREST = "Little smelly flower.",
        FROGLEGS_POISON = "Is danger froggy parts!",
        FROGLEGS_POISON_COOKED = "Even danger food make Wolfgang strong.",
        FROG_POISON = {
            DEAD = "Is no life.",
            GENERIC = "Is danger froggy.",
            SLEEPING = "Sleepy little froggy.",
        },
        GASCLOUD = "Wolfgang stay away.",
        GASMASKHAT = "Is good for Wolfgang lungs.",
        GLOWFLY = {
            DEAD = "Light bug is lights out.",
            GENERIC = "Is light bug.",
            SLEEPING = "Light bug is dark.",
        },
        GLOWFLY_COCOON = "Bug look cozy.",
        GNAT = "Is too small for smashing!",
        GNATMOUND = "Wolfgang smash bug home!",
        GOLDENMACHETE = "Hoighty toighty knife!",
        GOLDPAN = "Is for eating from?",
        GOLD_DUST = "Wolfgang like. Is shiny.",
        GRABBING_VINE = "Watch out for that tree!",
        GRASS_TALL = {
            BURNING = "Wolfgang is not doing that!",
            GENERIC = "Very sturdy grass.",
            PICKED = "Wolfgang is mightiest!",
        },
        HALBERD = "Sword is for weak no-muscle men.",
        HANGING_VINE = "Watch out for that tree!",
        HEDGE = {
            BURNING = "Is fire!",
            BURNT = "Wolfgang is not doing that!",
            GENERIC = "Is fancy bush.",
            SHAVEABLE = "Is needs a trim.",
        },
        HIPPOPOTAMOOSE = "Is mighty but Wolfgang is mightier!",
        HIPPO_ANTLER = "Wolfgang get mighty antler!",
        HOGUSPORKUSATOR = "Hee hee. Funny little piggie.",
        ICEDTEA = "Is cool. Like Wolfgang.",
        INFUSED_IRON = "Is strong and glowing.",
        IRON = "Iron is strong like Wolfgang.",
        JELLYBUG = "Is food with legs.",
        JELLYBUG_COOKED = "Wolfgang eat anything!",
        KINGFISHER = {
            DEAD = "Is dead. Make Wolfgang sad.",
            GENERIC = "Skinny bird is big beak.",
            SLEEPING = "Shhh. Skinny bird is sleep.",
        },
        LAWNORNAMENT = {
            BURNING = "Is all fire!",
            BURNT = "All burned.",
            GENERIC = "Stone for pretty-making.",
        },
        LIFEPLANT = "Is pretty flower.",
        LILYPAD = "Big water leaf.",
        LIVING_ARTIFACT = "Mighty Wolfgang can get mightier!",
        LOTUS = "Is puny pond plant.",
        LOTUS_FLOWER = "Is puny pond flower.",
        LOTUS_FLOWER_COOKED = "Wolfgang eat you now.",
        MACHETE = "Ah! Very good!",
        MAGNIFYING_GLASS = "Hehe! Wolfgang eye is big now!",
        MANDRAKEHOUSE = "Hill for plant mans.",
        MANDRAKEMAN = "Wolfgang stronger than you!",
        MEAN_FLYTRAP = {
            DEAD = "Is not life.",
            GENERIC = "Plant Men is puny and weak!",
            SLEEPING = "Plant Men is full of sleep.",
        },
        MEATED_NETTLE = "Meaty snack clears Wolfgang's mighty nostrils!",
        METALPLATEHAT = "Is funny little tin hat.",
        NECTAR_POD = "Is sweet like honey.",
        NETTLE = {
            DEFAULT = "Is smelly plant but is clearing Wolfgang nose.",
            EMPTY = "Is nothing to pick here.",
            MOIST = "Water is making plant happy.",
            WITHERED = "Soil is making plant sad.",
        },
        NETTLELOSANGE = "Is strong smell. Like Wolfgang.",
        OBSIDIAN = "There is strong fire in this stone.",
        OINC = "Wolfgang is stronger than little coin.",
        OINC10 = "Wolfgang like coin.",
        OINC100 = "Can buy many nice things Wolfgang deserve.",
        PANGOLDEN = "Hehe. Haves big nose.",
        PARROT_BLUE = {
            DEAD = "Is no more.",
            GENERIC = "Is blue bird.",
            SLEEPING = "Is just resting.",
        },
        PEAGAWK = {
            DEAD = "Is blink-blink no more.",
            GENERIC = "Funny blink-blink bird!",
            SLEEPING = "Is sleep, but eyes still blink-blink.",
        },
        PEAGAWKFEATHER = "Is blink-blink bird feather.",
        PEAGAWK_BUSH = "Is just bush.",
        PHEROMONESTONE = "Is smell like bug.",
        PIGBANDIT = "Leave Wolfgang money alone!",
        PIGEON = {
            DEAD = "Is dead.",
            GENERIC = "Is little grey bird.",
            SLEEPING = "Is asleep.",
        },
        PIGGHOST = "Agghhh!",
        PIGHOUSE_CITY = {
            BURNING = "Wolfgang not start fire!",
            GENERIC = "Little pig! Little pig! Let Wolfgang come in!",
        },
        PIGHOUSE_FARM = {
            BURNING = "Is fire!",
            GENERIC = "House for little farmy pigs.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Hope mustache pig not inside.",
            GENERIC = "Mining mustache pig is live there.",
        },
        PIGMAN_BANKER = {
            GENERIC = "Is like Wolfgang's piggie bank!",
            SLEEPING = "Piggie banker sleeping.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "Little pig make Wolfgang better?",
            SLEEPING = "Aww. Piggie is sleeping.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "Is selling weird stuff.",
            SLEEPING = "Is weird sleeping.",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "You have magic stuff?",
            SLEEPING = "Is sleeping.",
        },
        PIGMAN_FARMER = {
            GENERIC = "Pig is good little farmer.",
            SLEEPING = "Farmer is earn good sleep.",
        },
        PIGMAN_FLORIST = {
            GENERIC = "Little pig is run garden shop.",
            SLEEPING = "Sleep piggie. Sleep.",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "Wolfgang is creeped out.",
            SLEEPING = "Is a still creepy.",
        },
        PIGMAN_HUNTER = {
            GENERIC = "Weapons make Wolfgang mightier.",
            SLEEPING = "Is leaving himself open to attack.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Wolfgang think this important man.",
            SLEEPING = "Important man need sleep, too.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "Little piggie fix things.",
            SLEEPING = "Sleep well little piggie.",
        },
        PIGMAN_MINER = {
            GENERIC = "Wolfgang like your mustache!",
            SLEEPING = "Miner Piggie dreaming of mustache.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "Is old piggy.",
            SLEEPING = "Is just sleeping.",
        },
        PIGMAN_QUEEN = "Wolfgang should curtsy?",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Is strong, but is not as strong as Wolfgang.",
            SLEEPING = "Wolfgang would never sleep on job.",
        },
        PIGMAN_ROYALGUARD_2 = {
            GENERIC = "Wolfgang does not need guarding.",
            SLEEPING = "Wolfgang sleep better.",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "Wolfgang can sell him stuff.",
            SLEEPING = "Wolfgang cannot buy from sleeping pig.",
        },
        PIGMAN_USHER = {
            GENERIC = "Hello, old piggie.",
            SLEEPING = "Shh... Is sleeping.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Big tower is fire!",
            GENERIC = "Is big tall tower.",
        },
        PIG_PALACE = "Is fancy place.",
        PIG_RUINS_ARTICHOKE = "Is odd statue.",
        PIG_RUINS_CREEPING_VINES = "Wolfgang no liking vines.",
        PIG_RUINS_DART_STATUE = "Wolfgang suspicious...",
        PIG_RUINS_DART_TRAP = "Is gonna spit at Wolfgang?",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "Where is going to?",
            LOCKED = "Nothing keep out mighty Wolfgang!",
        },
        PIG_RUINS_ENTRANCE2 = "Is dark inside.",
        PIG_RUINS_ENTRANCE3 = "Where is going to?",
        PIG_RUINS_ENTRANCE4 = "Is scary dark in there.",
        PIG_RUINS_ENTRANCE5 = "Is door.",
        PIG_RUINS_ENTRANCE_SMALL = "Is for going into.",
        PIG_RUINS_EXIT = "Stone door is come from tunnel.",
        PIG_RUINS_EXIT2 = "Is lighter up there.",
        PIG_RUINS_EXIT4 = "Is for going through.",
        PIG_RUINS_HEAD = "Is big and mighty head. Like Wolfgang!",
        PIG_RUINS_IDOL = "Piggies might like those.",
        PIG_RUINS_PLAQUE = "Is piggy thing.",
        PIG_RUINS_PRESSURE_PLATE = "Is weird stone.",
        PIG_RUINS_SPEAR_TRAP = "Tiny holes in ground.",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "Wolfgang win!",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "You not get Wolfgang!",
        PIG_RUINS_TORCH = "Light is Wolfgang friend.",
        PIG_RUINS_TORCH_WALL = "Wolfgang like light.",
        PIG_SHOP_ACADEMY = {
            BURNING = "Is not supposed to fire!",
            GENERIC = "Is full of old things.",
        },
        PIG_SHOP_ANTIQUITIES = {
            BURNING = "Was not Wolfgang fault.",
            GENERIC = "Strange things inside.",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "The magics is fire!",
            GENERIC = "Is place for magics things.",
        },
        PIG_SHOP_BANK = {
            BURNING = "Is mighty fire.",
            GENERIC = "Is having many coins.",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "Is on fire!",
            GENERIC = "Is big bossy pig place.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Is on fire!",
            GENERIC = "Wolfgang working there now.",
        },
        PIG_SHOP_DELI = {
            BURNING = "Food is on fire!",
            GENERIC = "Is food!",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "Is full of fire!",
            GENERIC = "Is shop for little growing things.",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "Is not supposed to do that!",
            GENERIC = "Many things inside little shop.",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "The hats is fire!",
            GENERIC = "Maybe Wolfgang find mighty hat.",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "Is supposed to be on fire?",
            GENERIC = "Wolfgang need stuff for boo-boos.",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "Fire! Wolfgang see fire!",
            GENERIC = "Shop of food!",
        },
        PIG_SHOP_TINKER = {
            BURNING = "Is on fire.",
            GENERIC = "Is shop for making things.",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "Is fire! Is fire!",
            GENERIC = "Wolfgang is stronger than any weapon.",
        },
        PIKO = {
            DEAD = "Is tiny fluff dead part.",
            GENERIC = "Tiny, weak fluff.",
            SLEEPING = "Tiny fluff is sleep time.",
        },
        PIKO_ORANGE = {
            DEAD = "Is tiny orange fluff dead part.",
            GENERIC = "Tiny, weak orange fluff.",
            SLEEPING = "Tiny orange fluff is sleep time.",
        },
        PITHHAT = "Is hard like Wolfgang head.",
        PLAYERHOUSE_CITY = {
            BURNT = "Agh! Is burning! Is fire!",
            FORSALE = "Wolfgang is looking for new home.",
            SOLD = "Is mighty Wolfgang house!",
        },
        PLAYER_HOUSE_BRICK = "Bricks heavy but Wolfgang strong!",
        PLAYER_HOUSE_BRICK_CRAFT = "Bricks heavy but Wolfgang strong!",
        PLAYER_HOUSE_COTTAGE = "Wolfgang build little home.",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Wolfgang build little home.",
        PLAYER_HOUSE_GOTHIC = "Is fancy things for fancy house.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "Is fancy things for fancy house.",
        PLAYER_HOUSE_MANOR = "Is stuff for house. Big like Wolfgang.",
        PLAYER_HOUSE_MANOR_CRAFT = "Is stuff for house. Mighty like Wolfgang.",
        PLAYER_HOUSE_TUDOR = "Wolfgang build fancy house.",
        PLAYER_HOUSE_TUDOR_CRAFT = "Wolfgang build fancy house.",
        PLAYER_HOUSE_TURRET = "Stones heavy but Wolfgang strong!",
        PLAYER_HOUSE_TURRET_CRAFT = "Stones heavy but Wolfgang strong!",
        PLAYER_HOUSE_VILLA = "Wolfgang build big house.",
        PLAYER_HOUSE_VILLA_CRAFT = "Wolfgang build big house.",
        POISONBALM = "Wolfgang does not fear poison! But will take just in case!",
        PORKLAND_INTRO_BALLOON = "Is broken.",
        PORKLAND_INTRO_BASKET = "It fall from sky.",
        PORKLAND_INTRO_FLAGS = "Is useless.",
        PORKLAND_INTRO_SANDBAG = "Wolfgang could carry it but doesn't want to.",
        PORKLAND_INTRO_SUITCASE = "Wolfgang leave it there.",
        PORKLAND_INTRO_TRUNK = "Is nothing to Wolfgang.",
        PROP_DOOR = "Wolfgang go in.",
        PUGALISK = "Stay still so Wolfgang can fight you!",
        PUGALISK_CORPSE = "Wolfgang conquer mighty beast!",
        PUGALISK_FOUNTAIN = "Wolfgang stay young forever.",
        PUGALISK_RUINS_PILLAR = "Wolfgang is stronger.",
        PUGALISK_SKULL = "Is mighty skull. Wolfgang is mightier.",
        PUGALISK_TRAP_DOOR = "Is funny rock.",
        RABID_BEETLE = {
            DEAD = "Is stomped.",
            GENERIC = "Wolfgang will stomp bad beetle!",
            SLEEPING = "Hehe. Is funny mustache.",
        },
        RADISH = "Is spicy.",
        RADISH_COOKED = "Is make Wolfgang breath big and strong.",
        RADISH_PLANTED = "Little vegetable...Wolfgang see you...",
        RADISH_SEEDS = "Is little baby foods for Wolfgang.",
        RAINFORESTTREE = {
            BURNING = "Is fire!",
            BURNT = "Tree is no more.",
            CHOPPED = "Wolfgang win.",
            GENERIC = "Is tree. Hello!",
        },
        RAINFORESTTREE_ROT = "Is sick little tree.",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "Rubble rocks.",
            SCAFFOLD = "Is less broke now.",
        },
        REEDS_WATER = "Is pond plant.",
        RELIC_1 = "Is like little pig men.",
        RELIC_2 = "Is thing from little pig men.",
        RELIC_3 = "Is stone piggie nose.",
        RELIC_4 = "Is not mighty. Is fancy.",
        RELIC_5 = "Has the shiny rocks in it.",
        ROCK_ANTCAVE = "Wolfgang is stronger.",
        ROCK_BASALT = "Is rock.",
        ROCK_FLIPPABLE = "Wolfgang strong. Wolfgang flip big stone.",
        ROOTTRUNK_CHILD = "Wolfgang's stuff many places now!",
        SAIL_SNAKESKIN = "Skin of dead snake will help me sail.",
        SCORPION = {
            DEAD = "Ha! Is dead!",
            GENERIC = "Stay away from Wolfgang!",
            SLEEPING = "Shhh. Is sleep.",
        },
        SECURITYCONTRACT = "Wolfgang can get piggy friend now.",
        SEDIMENTPUDDLE = "Hello little sparklies!",
        SHEARS = "Is for cutting plant things.",
        SLUGBUG = "Is slimy... but Wolfgang still eat it.",
        SLUGBUG_COOKED = "Is food? Wolfgang will eat anyway!",
        SMASHINGPOT = "Wolfgang will smash!",
        SMELTER = {
            BURNT = "Smelter is dead.",
            COOKING_SHORT = "Is almost melt!",
            DONE = "Fire make metal bricks.",
            EMPTY = "Wolfgang lifted it without difficulty.",
        },
        SNAKEBONESOUP = "Is food little for Wolfgang.",
        SNAKEOIL = "Good for shining Wolfgang's muscles!",
        SNAKESKIN = "I will use as bandana.",
        SNAKESKINHAT = "Very good.",
        SNAKE_AMPHIBIOUS = "Wolfgang punch you!",
        SNAKE_BONE = "Wolfgang win.",
        SPIDER_MONKEY = {
            DEAD = "Is dead.",
            GENERIC = "Is very bad!",
            SLEEPING = "Is helpless. Wolfgang can smash it!",
        },
        SPIDER_MONKEY_NEST = "Bad things come out.",
        SPIDER_MONKEY_TREE = "Is tree for bad things.",
        SPRINKLER = "Weeee. Wolfgang play in sprinkler!",
        TEA = "Wolfgang love tea time!",
        TEATREE = "Is strong but not strong like Wolfgang.",
        TEATREE_NUT = "Is good for Wolfgang's mighty sneezes.",
        TEATREE_NUT_COOKED = "Wolfgang eat tiny tree baby.",
        TEATREE_NUT_SAPLING = "Is tiny little big tree.",
        THUNDERBIRD = "Is sparky bird.",
        THUNDERBIRDNEST = "Is home of sparky bird.",
        THUNDERHAT = "Wolfgang look good in hat.",
        TOPIARY = "Is very funny bush!",
        TOUCAN = "Bird flees at the sight of Wolfgang.",
        TREE_PILLAR = "Mightiest tree!",
        TUBERTREE = "Axe is not strong for cutting this down.",
        TUBER_BLOOM_CROP = "Wolfgang like little flower.",
        TUBER_BLOOM_CROP_COOKED = "Wolfgang eat.",
        TUBER_CROP = "Is food?",
        TUBER_CROP_COOKED = "Is good food?",
        TURF_COBBLEROAD = "Step stones.",
        TURF_DEEPRAINFOREST = "Step stones.",
        TURF_DEEPRAINFOREST_NOCANOPY = "Step stones.",
        TURF_FIELDS = "Step stones.",
        TURF_FOUNDATION = "Step stones.",
        TURF_GASJUNGLE = "Step stones.",
        TURF_LAWN = "Step stones.",
        TURF_MOSS = "Step stones.",
        TURF_PAINTED = "Step stones.",
        TURF_PIGRUINS = "Step stones.",
        TURF_PLAINS = "Step stones.",
        TURF_RAINFOREST = "Step stones.",
        VAMPIREBAT = {
            DEAD = "Is dead. Wolfgang win!",
            GENERIC = "Is flappy bad guy!",
            SLEEPING = "Flappy bad guy is night-night.",
        },
        VAMPIREBATCAVE = "Wolfgang is no like dark hole.",
        VENOMGLAND = "Is weapon of cowards.",
        VENUS_STALK = "Is Plant Men parts.",
        VINE = "For string enemies together.",
        WALKINGSTICK = "Is for good walk steps.",
        WALLCRACK_RUINS = "How Wolfgang breaking that?",
        WALL_PIG_RUINS = "Is broken.",
        WATERDROP = "Is magic water seed.",
        WEEVOLE = "Pesky bug. Leave Wolfgang alone!",
        WEEVOLE_CARAPACE = "Is pesky bug skin.",
        WINDOW_GREENHOUSE = "Is window worthy of mighty Wolfgang!",
        WINDOW_LARGE_SQUARE = "Wolfgang can see outside.",
        WINDOW_LARGE_SQUARE_CURTAIN = "Wolfgang can see outside.",
        WINDOW_ROUND = "Wolfgang can see outside.",
        WINDOW_ROUND_BURLAP = "Wolfgang need better decorator.",
        WINDOW_ROUND_CURTAINS_NAILS = "Wolfgang good decorator.",
        WINDOW_SMALL_PEAKED = "Wolfgang can see outside.",
        WINDOW_SMALL_PEAKED_CURTAIN = "Wolfgang can see outside now.",
        WINDOW_TALL = "Wolfgang can see outside.",
        WINDOW_TALL_CURTAIN = "Wolfgang can see outside.",
    },
}
