return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It be jus'like new!",
        },
        USEDOOR = {
            GENERIC = "'tis closed ta me.",
            LOCKED = "It be needin' somethin' ta open't.",
        },
    },
    ANNOUCE_ALARMOVER = "Ol'Woodlegs wins ag'in!",
    ANNOUCE_BATS = "Beasties be flappin' about.",
    ANNOUCE_OTHERWORLD_DEED = "'Tis not from 'round here.",
    ANNOUCE_UNDERLEAFCANOPY = "'Tis dark!",
    ANNOUNCE_BOAT_DAMAGED = "She's takin' on water!",
    ANNOUNCE_BOAT_SINKING = "She be goin' doooon!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Be this th'day th'sea claims me?",
    ANNOUNCE_DEHUMID = {
        "Ah! Th'air be cool again.",
    },
    ANNOUNCE_GAS_DAMAGE = "Koff! Koff! Smelly as tha bilgewater!",
    ANNOUNCE_HAYFEVER = "Me nose be itchier than a sliver in me pegleg.",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Th'air be clear again!",
    ANNOUNCE_HOUSE_DOOR = "Woodlegs be needin'a permit fer't.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "Ol' Woodlegs found'a door!",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Bah. Nothin'.",
    ANNOUNCE_MYSTERY_FOUND = "Treasure!",
    ANNOUNCE_MYSTERY_NOREWARD = "Bah. Tha treasure be gone.",
    ANNOUNCE_NOTHING_FOUND = "Thar b'nothin' ta find 'round these parts.",
    ANNOUNCE_PICKPOOP = {
        "Arrgh!",
        "Avast!",
        "Ye repulsive thing!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Tha' hide be too tough!",
        "Where's me harpoon!",
        "What's ye weakness, ye land Leviathan?",
    },
    ANNOUNCE_ROOM_STUCK = "Ol' Woodlegs is na lookin' ta get trapped'ere!",
    ANNOUNCE_SNEEZE = "Ahh-pheww!!",
    ANNOUNCE_SUITUP = "Yarrrrrg!",
    ANNOUNCE_TAXDAY = "Ye'll be needin' ta pay tha taxes!",
    ANNOUNCE_TOOLCORRODED = "Arrgh! Me tools be fallin' apart!",
    ANNOUNCE_TOO_HUMID = {
        "Arrgh! It be hot!",
        "This %s is makin' me sweat me britches.",
    },
    ANNOUNCE_TURFTOOHARD = "No use pullin' up this ground.",
    ANNOUNCE_WAVE_BOOST = "We be a silver streak on th'blue now!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Danc'd tha hemp'n jig.",
            GENERIC = "Yer in fer it now.",
            SLEEPING = "Thar sails b'furled.",
        },
        ALLOY = "Ahoy, alloy!",
        ALOE = "Thar be gooey treasure with'n.",
        ALOE_COOKED = "'Tis treasu're fer me belly.",
        ALOE_PLANTED = "Land seaweed.",
        ALOE_SEEDS = "Fer puttin' in tha'ground.",
        ANCIENT_HERALD = "Scallywag, if'n Woodlegs e'er seen one.",
        ANCIENT_HULK = "Ye be lookin' fer a fight?",
        ANCIENT_REMNANT = "Like Davey Jones' sailcloth.",
        ANCIENT_ROBOTS_ASSEMBLY = "An'alf t'gether metal leviathan.",
        ANCIENT_ROBOT_CLAW = "I've no need fer a'extra hand.",
        ANCIENT_ROBOT_HEAD = "I'll hang tha' head from me bowsprit.",
        ANCIENT_ROBOT_LEG = "Arrg! I could use tha' leg!",
        ANCIENT_ROBOT_RIBS = "'Tis an iron leviathan.",
        ANTCHEST = "'t be makin' tha sweet golden treasure!",
        ANTCOMBHOME = "Thar buggie beasties reside within.",
        ANTMAN = {
            DEAD = "Its 'atches 'ave been battened.",
            GENERIC = "Whut mann'r o'beast be ye?",
            SLEEPING = "Keelhaul tha beast!",
        },
        ANTMAN_WARRIOR = "Ye be meetin' yer match!",
        ANTMASKHAT = "T'mask yer ugly mug.",
        ANTQUEEN_THRONE = "Thar be treas're within.",
        ANTSUIT = "'Tis an unpleasant bus'niss.",
        ANT_CAVE_LANTERN = "'Tis a sweet lantern.",
        APORKALYPSE_CLOCK = "Tha time be nigh!",
        ARMORVORTEXCLOAK = "T'be like starin' into th'ocean depths.",
        ARMOR_METALPLATE = "Not good fer swimmin' in.",
        ARMOR_SNAKESKIN = "Leathers ta slick th'rain away.",
        ARMOR_WEEVOLE = "Aye. Finery made o' bug skin.",
        ASPARAGUS_PLANTED = "Tiny masts growin' from the ground.",
        BALLPEIN_HAMMER = "Fer diggin' treasures from'tha artifacts.",
        BANDITHAT = "'Tis a sneaky 'at.",
        BANDITMAP = "Arrgh! 'Tis treasure!",
        BANDITTREASURE = "Let's get'ta diggin'!",
        BASEFAN = "A cool wind blows from thee!",
        BATHAT = "Has the look o' tha' flyin' beasties.",
        BILL = {
            DEAD = "It's been run through.",
            GENERIC = "A cannonball o' fur.",
            SLEEPING = "Arrgh. It's takin' tha caulk.",
        },
        BILL_QUILL = "'Tis a part o' tha spiky beastie.",
        BLUNDERBUSS = "It be a hand cannon.",
        BOATREPAIRKIT = "Never set sail wit'out'er.",
        BOAT_CARGO = "Fer th'hoarder at sea.",
        BOAT_CORK = "It be'a poorly ship.",
        BOAT_LOGRAFT = "She don't look too sturdy.",
        BOAT_ROW = "I ain't rowed since I was a young swab.",
        BOAT_TORCH = "Fer a torch on me boat, not fer torchin' me boat.",
        BONESTAFF = "'twill chill ye to tha bone.",
        BRAMBLESPIKE = "Argh! A mast with shark's teeth.",
        BRAMBLE_BULB = "Tha heart o' the flower.",
        BRAMBLE_CORE = "A rose in'a sea o' brambles.",
        BUGREPELLENT = "A land cannon fer th' wee buggies.",
        BURR = "Sticks t'yer pegs.",
        BURR_SAPLING = "Legs'n th'makin'.",
        CANDLEHAT = "A fine hat fer lootin' temples.",
        CHITIN = "A harden'd hull.",
        CITY_HAMMER = "'Tis a pow'rful 'ammer!",
        CITY_LAMP = {
            GENERIC = "Sanctuary!",
            ON = "A landlamp.",
        },
        CLAWPALMTREE = "Strange wood b'within.",
        CLAWPALMTREE_SAPLING = "Too small fer a mast.",
        CLIPPINGS = "A bit o' plant bilge.",
        COFFEE = "Arrr thet be th'real treasure.",
        COFFEEBEANS = "Just add water.",
        COFFEEBEANS_COOKED = "No hot water?",
        CONSTRUCTION_PERMIT = "Fer buildin' on ta me land ship.",
        CORK = "Barely seaworthy.",
        CORKCHEST = "'Tis fer keepin' the pests a'bay.",
        CORK_BAT = "Lighter than a belayin' pin.",
        CUTNETTLE = "Cleans tha' nose as good as sea air.",
        DECO_CAVE_BAT_BURROW = "Arr. Tha flyin' devils be within ye.",
        DECO_CAVE_BEAM_ROOM = "Fine mast fer'a room.",
        DECO_CHAIR_BENCH = "Thar's room inn'at chair fer two captains.",
        DECO_CHAIR_CLASSIC = "Captain's chair fer'a house.",
        DECO_CHAIR_CORNER = "A poor captain's chair.",
        DECO_CHAIR_FOOTREST = "A poor captain's chair.",
        DECO_CHAIR_HORNED = "A captain's chair fer'a house.",
        DECO_CHAIR_LOUNGE = "A captain's chair fer'a house.",
        DECO_CHAIR_MASSAGER = "A captain's chair fer Davey Jones.",
        DECO_CHAIR_OTTOMAN = "A poor captain's chair.",
        DECO_CHAIR_ROCKING = "A poor captain's chair.",
        DECO_CHAIR_STUFFED = "A poor captain's chair.",
        DECO_RUINS_BEAM_ROOM = "Fine mast fer'a room.",
        DECO_RUINS_BEAM_ROOM_BLUE = "Fine mast fer'a room.",
        DECO_RUINS_ENDSWELL = "Na'a drop ta'drink.",
        DECO_RUINS_FOUNTAIN = "Shall I throw m'luck to th'wind?",
        DEED = "Only a deed to a 'ouse, not a ship.",
        DEMOLITION_PERMIT = "Me rooms be headin' fer a careenin'.",
        DISARMING_KIT = "Now Woodlegs' got'tha upp'r hand!",
        DISGUISEHAT = "'Tis fer foolin' tha'pigs.",
        DUG_NETTLE = "Be needin' some land.",
        DUNGBALL = "Throw it o'erboard!",
        DUNGBEETLE = {
            DEAD = "'tas been run through!",
            GENERIC = "Cre'ture o' tha dung.",
            SLEEPING = "Too much o' the grog?",
            UNDUNGED = "Th'foul stench follows ye.",
        },
        DUNGPILE = {
            GENERIC = "Foul.",
            PICKED = "Argh! Sweet seawat'r could'na cleanse me now.",
        },
        FEATHER_THUNDER = "Argh! Found'a treasure!",
        FLOWER_RAINFOREST = "Ol'Woodlegs na'got use fer'it.",
        FROGLEGS_POISON = "Best b'careful eatin' thet!",
        FROGLEGS_POISON_COOKED = "Na'a prop'r meal.",
        FROG_POISON = {
            DEAD = "Walk'd tha plank.",
            GENERIC = "Scallywag of o' tha land!",
            SLEEPING = "Maroon tha' beastie!",
        },
        GASCLOUD = "An ill wind.",
        GASMASKHAT = "Cuts down onna coughin'.",
        GLOWFLY = {
            DEAD = "Tells no tales.",
            GENERIC = "A fly'o'glow!",
            SLEEPING = "Becalm'd.",
        },
        GLOWFLY_COCOON = "'e be sleepin' it off.",
        GNAT = "Flyin' minnows.",
        GNATMOUND = "Barnacle's o'tha land.",
        GOLDENMACHETE = "'Tis a mighty 'eavy blade.",
        GOLDPAN = "Fer fishin' fer gold.",
        GOLD_DUST = "Aye! 'Tis treasure dust!",
        GRABBING_VINE = "Them be th'ropes.",
        GRASS_TALL = {
            BURNING = "'Tis ablaze!",
            GENERIC = "As tall'as th'sky.",
            PICKED = "Plunder'd.",
        },
        HALBERD = "T'ain't no cutlass.",
        HANGING_VINE = "Them be th'ropes.",
        HEDGE = {
            BURNING = "Avast! Man tha pumps!",
            BURNT = "Been pillag'd!",
            GENERIC = "'Tis th'way o'th'land.",
            SHAVEABLE = "Could do wit'a shave.",
        },
        HIPPOPOTAMOOSE = "Avast! 'Tis a land Kracken!",
        HIPPO_ANTLER = "'Tis tha riggin' o' tha'beastie.",
        HOGUSPORKUSATOR = "Thars a funny little pig.",
        ICEDTEA = "'Tis relief ta be sure.",
        INFUSED_IRON = "'as th'look 'o treasure to't.",
        IRON = "'Tis not gold, but a treasure nonetheless.",
        JELLYBUG = "Avast ye, jumpin' beans!",
        JELLYBUG_COOKED = "Tha virtue o'this meat be dubious.",
        KINGFISHER = {
            DEAD = "Met Davey Jones.",
            GENERIC = "Ye live off'th'ocean too?",
            SLEEPING = "'Tis not on watch.",
        },
        LAWNORNAMENT = {
            BURNING = "Ablaze!",
            BURNT = "Tha hull be burnt'out.",
            GENERIC = "Ol'Woodlegs prefers a touch'o'gold.",
        },
        LIFEPLANT = "Grew from a drop o' water.",
        LILYPAD = "A leaf aft'r me own heart.",
        LIVING_ARTIFACT = "A Man o' War o' tha land!",
        LOTUS = "It be a big pink flow'r.",
        LOTUS_FLOWER = "Tis a flow'r'o'th'land.",
        LOTUS_FLOWER_COOKED = "It b'cooked.",
        MACHETE = "Ye be slicin'!",
        MAGNIFYING_GLASS = "'Tis a spyglass o' tha land.",
        MANDRAKEHOUSE = "They live b'low decks.",
        MANDRAKEMAN = "I'll run ye through!",
        MEAN_FLYTRAP = {
            DEAD = "Belay'd of life.",
            GENERIC = "'Tis a land shark!",
            SLEEPING = "Thar sails be furled.",
        },
        MEATED_NETTLE = "A bite o' meat to go with th'nose clearin'!",
        METALPLATEHAT = "Prefer me captain's hat.",
        NECTAR_POD = "Tha sweet, sweet nectar!",
        NETTLE = {
            DEFAULT = "Arrr. Tis a strong smell!",
            EMPTY = "Pillag'd.",
            MOIST = "Water be doin'it good.",
            WITHERED = "Na'tha right dirt fer'it.",
        },
        NETTLELOSANGE = "Like eatin'a bunch'a fresh air.",
        OBSIDIAN = "A powerful stone.",
        OINC = "Pieces o' Eight!",
        OINC10 = "Thet b'gold!!",
        OINC100 = "'tis a small tre'sure!",
        PANGOLDEN = "Eatin' up all tha treasure!",
        PARROT_BLUE = {
            DEAD = "Thar be an ex-parrot.",
            GENERIC = "Blue as th'sea.",
            SLEEPING = "'Tis just restin'",
        },
        PEAGAWK = {
            DEAD = "It tells no tales.",
            GENERIC = "Arr, them eyes need patches!",
            SLEEPING = "She be grabbin' some shuteye.",
        },
        PEAGAWKFEATHER = "Feather'o'glimmer.",
        PEAGAWK_BUSH = "'Tis unsettlin' t'b'sure.",
        PHEROMONESTONE = "Be a stone'o'tongues.",
        PIGBANDIT = "Argh! Stay away from me gold!",
        PIGEON = {
            DEAD = "Tells no tales.",
            GENERIC = "Be'a gulls o'th' land.",
            SLEEPING = "Grabbin' shuteye.",
        },
        PIGGHOST = "I've faced worse than ye!",
        PIGHOUSE_CITY = {
            BURNING = "A flamin' abode!",
            GENERIC = "Boathouse'o'th'land.",
        },
        PIGHOUSE_FARM = {
            BURNING = "Not long fer'tha world!",
            GENERIC = "'Tis th'home o'a landlubber.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Avast! 'Tis afire!",
            GENERIC = "Them b'th'mines.",
        },
        PIGMAN_BANKER = {
            GENERIC = "Moneygrubbin' landlubbin' swine.",
            SLEEPING = "Moneygrubbin' landlubbin' groundnappin' swine.",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "P'rty swine.",
            SLEEPING = "A sleepin' p'rty swine.",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "Full o'tha strange treas're, 'e is!",
            SLEEPING = "Be'a sleepin' treasure'oardin' swine.",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "Yer a wizard then?",
            SLEEPING = "Thet be a sleepin' magicin' swine.",
        },
        PIGMAN_FARMER = {
            GENERIC = "Walkin' sw'ne ye be.",
            SLEEPING = "A dung haulin' sw'ne.",
        },
        PIGMAN_FLORIST = {
            GENERIC = "'Tis a swine, fer sure.",
            SLEEPING = "Sleepin' sweet smellin'sw'ne.",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "Ye'ave 'ats fer tha piratin'?",
            SLEEPING = "Sleepin'atted swine.",
        },
        PIGMAN_HUNTER = {
            GENERIC = "'as tha look'o' a swashbuckl'r.",
            SLEEPING = "Sleepin' swashbucklin' swine.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Too plump fer'is own good.",
            SLEEPING = "Sleepin' landlubbin' swine.",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "Whut'a snout ye'ave!",
            SLEEPING = "Sleepin'swine.",
        },
        PIGMAN_MINER = {
            GENERIC = " 'e picks tha treas're o' the ground.",
            SLEEPING = "Sleepin'sw'ne.",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "Grizzl'd 'un, ain't ye.",
            SLEEPING = "Sleepin' rusty swine.",
        },
        PIGMAN_QUEEN = "Whar be yer treasure?",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Dare ye ta cross swords wit ol'Woodlegs?",
            SLEEPING = "Sleepin' scallywag'n swine.",
        },
        PIGMAN_ROYALGUARD_2 = {
            GENERIC = "Ye'll not be nabbin' me.",
            SLEEPING = "'es a lazy one.",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "'e be'a boar!",
            SLEEPING = "Thet be a sleepin' hornswagglin' swine.",
        },
        PIGMAN_USHER = {
            GENERIC = "Older'n ol' Woodlegs, 'e be.",
            SLEEPING = "Thar be better places fer that!",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Yo ho ho! It'be done fer!",
            GENERIC = "Thems tha lookout.",
        },
        PIG_PALACE = "A brigantine o' tha land.",
        PIG_RUINS_ARTICHOKE = "Thar be treas're in't.",
        PIG_RUINS_CREEPING_VINES = "Thar be sneaky tree riggin'.",
        PIG_RUINS_DART_STATUE = "I'll be keepin' me eye on ye!",
        PIG_RUINS_DART_TRAP = "Aye. 'tis a trap.",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "Unholy depths.",
            LOCKED = "Arrggh! Let Ol' Woodlegs in!",
        },
        PIG_RUINS_ENTRANCE2 = "Inta tha depths with me.",
        PIG_RUINS_ENTRANCE3 = "Below decks.",
        PIG_RUINS_ENTRANCE4 = "Leads to powerful magicin'.",
        PIG_RUINS_ENTRANCE5 = "Inta tha depths with me.",
        PIG_RUINS_ENTRANCE_SMALL = "Inta tha depths with me.",
        PIG_RUINS_EXIT = "Th'way be clear.",
        PIG_RUINS_EXIT2 = "Above decks.",
        PIG_RUINS_EXIT4 = "'tbe tha way out!",
        PIG_RUINS_HEAD = "Thar be th'head.",
        PIG_RUINS_IDOL = "Tha' treasure atop there.",
        PIG_RUINS_PLAQUE = "Tha' treasure needs a diggin' out.",
        PIG_RUINS_PRESSURE_PLATE = "Ol' Woodlegs' got me s'spicions...",
        PIG_RUINS_SPEAR_TRAP = "Don't like tha looks o'those.",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "It's been run through!",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Tha trap's been sprung!",
        PIG_RUINS_TORCH = "A port fer fire.",
        PIG_RUINS_TORCH_WALL = "A port fer fire.",
        PIG_SHOP_ACADEMY = {
            BURNING = "Blazes! 'Tis ablaze!",
            GENERIC = "Full o'tha 'oary plunder.",
        },
        PIG_SHOP_ANTIQUITIES = {
            BURNING = "'tis done fer.",
            GENERIC = "Full o' tha strange treasures.",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "'Tis ablaze!",
            GENERIC = "Thar be magic in that there store.",
        },
        PIG_SHOP_BANK = {
            BURNING = "'t goin' up'n flames!",
            GENERIC = "'t be fulla tha dubloons!",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "Good riddance.",
            GENERIC = "Full o'tha pesky bigshots.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Avast!",
            GENERIC = "Where I capt'n me city.",
        },
        PIG_SHOP_DELI = {
            BURNING = "Afire!",
            GENERIC = "Ah. Grub!",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "'Tis ablaze!",
            GENERIC = "A house'o'land plants.",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "Headed for Davey Jones' Locker!",
            GENERIC = "Thar b'no treasure t'be had inside.",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "Arr, 'tis'a shame.",
            GENERIC = "Already gotme 'at!",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "'tas been scuttl'd!",
            GENERIC = "Ripe fer th'plunder.",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "'Tis ablaze!",
            GENERIC = "T'ward off th'scurvy.",
        },
        PIG_SHOP_TINKER = {
            BURNING = "Goin' down!",
            GENERIC = "Fer tha tinkerin' about me ship.",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "T'were not me!",
            GENERIC = "I be'in need o'tha piratin' gear.",
        },
        PIKO = {
            DEAD = "Tells no tales.",
            GENERIC = "Thievin' scoundr'l.",
            SLEEPING = "Grabbin' some shuteye.",
        },
        PIKO_ORANGE = {
            DEAD = "Tells no tales.",
            GENERIC = "Aye, 'tis a useful brood.",
            SLEEPING = "Grabbin' some shuteye.",
        },
        PITHHAT = "Tougher than me pirate hat.",
        PLAYERHOUSE_CITY = {
            BURNT = "Avast ye! 'Tis afire!",
            FORSALE = "A main deck fer'tha land.",
            SOLD = "Ol' Woodlegs prefers tha'seas.",
        },
        PLAYER_HOUSE_BRICK = "Bricks be not good fer buildin'a ship.",
        PLAYER_HOUSE_BRICK_CRAFT = "Bricks be not good fer buildin'a ship.",
        PLAYER_HOUSE_COTTAGE = "I've built m'own ship. I ken handle this.",
        PLAYER_HOUSE_COTTAGE_CRAFT = "I've built m'own ship. I ken handle this.",
        PLAYER_HOUSE_GOTHIC = "These ol' bones could still build.",
        PLAYER_HOUSE_GOTHIC_CRAFT = "These ol' bones could still build s'methin'.",
        PLAYER_HOUSE_MANOR = "Like buildin'a brigantine.",
        PLAYER_HOUSE_MANOR_CRAFT = "Like buildin'a brigantine.",
        PLAYER_HOUSE_TUDOR = "I miss m'crew fer tha hard labor jobs.",
        PLAYER_HOUSE_TUDOR_CRAFT = "I miss m'crew fer tha hard labor jobs.",
        PLAYER_HOUSE_TURRET = "Stone be not good fer buildin'a ship.",
        PLAYER_HOUSE_TURRET_CRAFT = "Stone be not good fer buildin'a ship.",
        PLAYER_HOUSE_VILLA = "Argh. I'll put me shipbuildin' skills t'work.",
        PLAYER_HOUSE_VILLA_CRAFT = "Argh. I'll put me ship buildin' skills t'work.",
        POISONBALM = "Aye, that'll take the sting out.",
        PORKLAND_INTRO_BALLOON = "A poor sky vessel.",
        PORKLAND_INTRO_BASKET = "Na good fer na'thin'.",
        PORKLAND_INTRO_FLAGS = "I'll na fly't on me boat.",
        PORKLAND_INTRO_SANDBAG = "I've na need fer ballast.",
        PORKLAND_INTRO_SUITCASE = "'tas been pillag'd.",
        PORKLAND_INTRO_TRUNK = "'tas been pillag'd.",
        PROP_DOOR = "Thar'be adventure down thar.",
        PUGALISK = "'Tis a land Leviathan!",
        PUGALISK_CORPSE = "'es danc'd the hemp'n jig.",
        PUGALISK_FOUNTAIN = "Argh! 'Tis but a tiny sea.",
        PUGALISK_RUINS_PILLAR = "Steady as a ship inna storm.",
        PUGALISK_SKULL = "Bigger than me crows nest.",
        PUGALISK_TRAP_DOOR = "That be'a strange sight.",
        RABID_BEETLE = {
            DEAD = "Aye, 'tis fer'tha best.",
            GENERIC = "Ornery buggie.",
            SLEEPING = "Thar she blows!",
        },
        RADISH = "Fer keepin' off tha scurvy.",
        RADISH_COOKED = "A veg'table brew.",
        RADISH_PLANTED = "Arrgh. Litt'le buried treasures.",
        RADISH_SEEDS = "It belon' in'tha ground.",
        RAINFORESTTREE = {
            BURNING = "'Tis aflame!",
            BURNT = "A touch o' the scurvy.",
            CHOPPED = "Cleav'd i'twain.",
            GENERIC = "'Tis a land mast.",
        },
        RAINFORESTTREE_ROT = "Would'na make a good mast.",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "Rubble'n'stone.",
            SCAFFOLD = "Repairs be in order.",
        },
        REEDS_WATER = "Sticks aft'r me'own 'eart.",
        RELIC_1 = "Long fergott'n treas're.",
        RELIC_2 = "'oary treas're!",
        RELIC_3 = "Treasure b'this!",
        RELIC_4 = "A queenly tre'sure.",
        RELIC_5 = "t'be worth more than'a pretty penny.",
        ROCK_ANTCAVE = "A pointy mizz'nmast.",
        ROCK_BASALT = "'tis a rock. Nothin' ta lose yer 'ead over.",
        ROCK_FLIPPABLE = "Plenty o'booty t'be found under a rock.",
        ROOTTRUNK_CHILD = "Yarr! All o'Woodleg's treasures!",
        SAIL_SNAKESKIN = "Thet be a sail.",
        SCORPION = {
            DEAD = "Aye! 'Tis defeated!",
            GENERIC = "A terible foe t'be sure.",
            SLEEPING = "Keelhaul tha'beast, while ye can!",
        },
        SECURITYCONTRACT = "Articles fer a guard o' my own.",
        SEDIMENTPUDDLE = "Alas, not big enough to sail in.",
        SHEARS = "A cutlass fer tha'bushes.",
        SLUGBUG = "A land eel.",
        SLUGBUG_COOKED = "Rather eat me hat.",
        SMASHINGPOT = "Due fer'a smashin'.",
        SMELTER = {
            BURNT = "Blast the bore!",
            COOKING_SHORT = "Ye'll be done soon 'nuff.",
            DONE = "She's ready ta fire!",
            EMPTY = "A cannon fer makin' metals.",
        },
        SNAKEBONESOUP = "A hearty brew, t'be sure.",
        SNAKEOIL = "Me knows a good deal when me sees it.",
        SNAKESKIN = "Me leathers do need replacin'.",
        SNAKESKINHAT = "On me head? Wear thet?",
        SNAKE_AMPHIBIOUS = "'Tis a land and sea serpent.",
        SNAKE_BONE = "A treasure o'tha snake.",
        SPIDER_MONKEY = {
            DEAD = "Shark bait now.",
            GENERIC = "Man th'cannons!",
            SLEEPING = "Arg! Cleav'im while ya got th' chance!",
        },
        SPIDER_MONKEY_NEST = "Whut slumbers wit'in?",
        SPIDER_MONKEY_TREE = "Be'fulla tha beasties.",
        SPRINKLER = "Relief fer tha'plants.",
        TEA = "Ah, a fine brew.",
        TEATREE = "'Tis a growin' ship mast.",
        TEATREE_NUT = "A botan'cal barber-surgeon.",
        TEATREE_NUT_COOKED = "Grub.",
        TEATREE_NUT_SAPLING = "'e'll be a fine one.",
        THUNDERBIRD = "Ye'll not b'shockin' me.",
        THUNDERBIRDNEST = "'Tis nature's treasure chest.",
        THUNDERHAT = "Not me piratin' 'at, but I'll take it.",
        TOPIARY = "Whut strange manner'o'tree b'this?",
        TOUCAN = "Yer name wouldn't be Sam, would it?",
        TREE_PILLAR = "Vessel i'th'makin'.",
        TUBERTREE = "'Tis too hardy fer an axe.",
        TUBER_BLOOM_CROP = "What can I make o' ye?",
        TUBER_BLOOM_CROP_COOKED = "A fine meal fer a fine fellow.",
        TUBER_CROP = "Give ya a bout of scurvy that.",
        TUBER_CROP_COOKED = "Not m'usual grub.",
        TURF_COBBLEROAD = "Me ain't no ground lubber.",
        TURF_DEEPRAINFOREST = "Me ain't no ground lubber.",
        TURF_DEEPRAINFOREST_NOCANOPY = "Me ain't no ground lubber.",
        TURF_FIELDS = "Me ain't no ground lubber.",
        TURF_FOUNDATION = "Me ain't no ground lubber.",
        TURF_GASJUNGLE = "Me ain't no ground lubber.",
        TURF_LAWN = "Me ain't no ground lubber.",
        TURF_MOSS = "Me ain't no ground lubber.",
        TURF_PAINTED = "Me ain't no ground lubber.",
        TURF_PIGRUINS = "Me ain't no ground lubber.",
        TURF_PLAINS = "Me ain't no ground lubber.",
        TURF_RAINFOREST = "Me ain't no ground lubber.",
        VAMPIREBAT = {
            DEAD = "Avast ye! The bilge-sucker's been cleaved.",
            GENERIC = "'Tis a wretch'd bloodsucker.",
            SLEEPING = "'Tha scurvy dog be defenceless.",
        },
        VAMPIREBATCAVE = "Inta th'depths wit'ye.",
        VENOMGLAND = "Aye, 'tis th'source o'th'venom.",
        VENUS_STALK = "A plant skelerton.",
        VINE = "Them's be th'stranglin' kind.",
        WALKINGSTICK = "Moor legs mean moor walkin'.",
        WALLCRACK_RUINS = "There be treasure a'hind it!",
        WALL_PIG_RUINS = "A wall.",
        WATERDROP = "'Tis only a wee bit o' water.",
        WEEVOLE = "'ave at ye landlubbers!",
        WEEVOLE_CARAPACE = "Longcoat made o' them pesky bugs.",
        WINDOW_GREENHOUSE = "'tis a grand porthole!",
        WINDOW_LARGE_SQUARE = "A porthole.",
        WINDOW_LARGE_SQUARE_CURTAIN = "The gun ports.",
        WINDOW_ROUND = "'tbe a sturdy porthole!",
        WINDOW_ROUND_BURLAP = "Scuppers fer the house.",
        WINDOW_ROUND_CURTAINS_NAILS = "Tha gun ports.",
        WINDOW_SMALL_PEAKED = "Tha gun ports.",
        WINDOW_SMALL_PEAKED_CURTAIN = "A porthole.",
        WINDOW_TALL = "Scuppers fer tha house.",
        WINDOW_TALL_CURTAIN = "A porthole.",
    },
}
