return {
    ANNOUNCE_DEHUMID = {
        "That feels better.",
    },
    ANNOUNCE_HAYFEVER = "You have allergies like me, Lucy?",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Clean air again.",
    ANNOUNCE_SNEEZE = "Achoo! Excuse me. Sorry.",
    ANNOUNCE_TOO_HUMID = {
        "It's blazing with this %s.",
        "Whew! this %s is hot, eh?",
    },
    DESCRIBE = {
        ALLOY = "It's like a block of wood made out of metal.",
        APORKALYPSE_CLOCK = "Looks like it's the end of days.",
        ARMOR_METALPLATE = "Feel a little funny in this.",
        ARMOR_WEEVOLE = "Nice use of bug carcasses.",
        ASPARAGUS_PLANTED = "They're like little trees to chop down.",
        CHITIN = "It's got some heft to it.",
        CUTNETTLE = "It has a smell to it.",
        FLOWER_RAINFOREST = "It's a pretty lil' thing.",
        GLOWFLY = {
            DEAD = "Dead.",
            GENERIC = "Thanks for lightin' the way, buddy.",
            SLEEPING = "A well-deserved nap.",
        },
        GLOWFLY_COCOON = "That looks comfy, eh?",
        GRASS_TALL = {
            BURNING = "It caught fire.",
            GENERIC = "Don't worry your head aboot this one, Lucy.",
            PICKED = "Got all I could.",
        },
        HALBERD = "Well, it's no axe.",
        PEAGAWK = {
            DEAD = "It's a goner.",
            GENERIC = "Filthy animal!",
            SLEEPING = "Catching forty winks.",
        },
        PEAGAWKFEATHER = "It has a foul bird stench.",
        PEAGAWK_BUSH = "There's a wretched bird nearby. I feel it.",
        RABID_BEETLE = {
            DEAD = "For the best.",
            GENERIC = "Seems mighty angry.",
            SLEEPING = "Let sleeping bugs lie, I say.",
        },
        SHEARS = "Don't get jealous, Lucy.",
        TREE_PILLAR = "That's a real beaut.",
        WEEVOLE = "Worse than black flies.",
        WEEVOLE_CARAPACE = "That'll teach 'em!",
    },
}
