return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It be jus'like new!",
        },
    },
    ANNOUCE_BATS = "Beasties be flappin' about.",
    ANNOUNCE_BOAT_DAMAGED = "She's takin' on water!",
    ANNOUNCE_BOAT_SINKING = "She be goin' doooon!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Be this th'day th'sea claims me?",
    ANNOUNCE_DEHUMID = {
        "Ah! Th'air be cool again.",
    },
    ANNOUNCE_HAYFEVER = "Me nose be itchier than a sliver in me pegleg.",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Th'air be clear again!",
    ANNOUNCE_PICKPOOP = {
        "Arrgh!",
        "Avast!",
        "Ye repulsive thing!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Tha' hide be too tough!",
        "Where's me harpoon!",
        "What's ye weakness, ye land Leviathan?",
    },
    ANNOUNCE_SNEEZE = "Ahh-pheww!!",
    ANNOUNCE_TOO_HUMID = {
        "Arrgh! It be hot!",
        "This %s is makin' me sweat me britches.",
    },
    ANNOUNCE_WAVE_BOOST = "We be a silver streak on th'blue now!",
    DESCRIBE = {
        ALLOY = "Ahoy, alloy!",
        APORKALYPSE_CLOCK = "Tha time be nigh!",
        ARMOR_METALPLATE = "Not good fer swimmin' in.",
        ARMOR_WEEVOLE = "Aye. Finery made o' bug skin.",
        ASPARAGUS_PLANTED = "Tiny masts growin' from the ground.",
        BASEFAN = "A cool wind blows from thee!",
        BILL = {
            DEAD = "It's been run through.",
            GENERIC = "A cannonball o' fur.",
            SLEEPING = "Arrgh. It's takin' tha caulk.",
        },
        BILL_QUILL = "'Tis a part o' tha spiky beastie.",
        BOATREPAIRKIT = "Never set sail wit'out'er.",
        BOAT_CARGO = "Fer th'hoarder at sea.",
        BOAT_CORK = "It be'a poorly ship.",
        BOAT_LOGRAFT = "She don't look too sturdy.",
        BOAT_ROW = "I ain't rowed since I was a young swab.",
        BOAT_TORCH = "Fer a torch on me boat, not fer torchin' me boat.",
        BONESTAFF = "'twill chill ye to tha bone.",
        CHITIN = "A harden'd hull.",
        COFFEE = "Arrr thet be th'real treasure.",
        COFFEEBEANS = "Just add water.",
        COFFEEBEANS_COOKED = "No hot water?",
        CUTNETTLE = "Cleans tha' nose as good as sea air.",
        DUNGBALL = "Throw it o'erboard!",
        DUNGBEETLE = {
            DEAD = "'tas been run through!",
            GENERIC = "Cre'ture o' tha dung.",
            SLEEPING = "Too much o' the grog?",
            UNDUNGED = "Th'foul stench follows ye.",
        },
        DUNGPILE = {
            GENERIC = "Foul.",
            PICKED = "Argh! Sweet seawat'r could'na cleanse me now.",
        },
        FLOWER_RAINFOREST = "Ol'Woodlegs na'got use fer'it.",
        FROGLEGS_POISON = "Best b'careful eatin' thet!",
        FROGLEGS_POISON_COOKED = "Na'a prop'r meal.",
        FROG_POISON = {
            DEAD = "Walk'd tha plank.",
            GENERIC = "Scallywag of o' tha land!",
            SLEEPING = "Maroon tha' beastie!",
        },
        GLOWFLY = {
            DEAD = "Tells no tales.",
            GENERIC = "A fly'o'glow!",
            SLEEPING = "Becalm'd.",
        },
        GLOWFLY_COCOON = "'e be sleepin' it off.",
        GOLDENMACHETE = "'Tis a mighty 'eavy blade.",
        GOLDPAN = "Fer fishin' fer gold.",
        GOLD_DUST = "Aye! 'Tis treasure dust!",
        GRABBING_VINE = "Them be th'ropes.",
        GRASS_TALL = {
            BURNING = "'Tis ablaze!",
            GENERIC = "As tall'as th'sky.",
            PICKED = "Plunder'd.",
        },
        HALBERD = "T'ain't no cutlass.",
        HANGING_VINE = "Them be th'ropes.",
        HIPPOPOTAMOOSE = "Avast! 'Tis a land Kracken!",
        HIPPO_ANTLER = "'Tis tha riggin' o' tha'beastie.",
        ICEDTEA = "'Tis relief ta be sure.",
        IRON = "'Tis not gold, but a treasure nonetheless.",
        LIFEPLANT = "Grew from a drop o' water.",
        LILYPAD = "A leaf aft'r me own heart.",
        LOTUS = "It be a big pink flow'r.",
        LOTUS_FLOWER = "Tis a flow'r'o'th'land.",
        LOTUS_FLOWER_COOKED = "It b'cooked.",
        MACHETE = "Ye be slicin'!",
        MANDRAKEHOUSE = "They live b'low decks.",
        MANDRAKEMAN = "I'll run ye through!",
        PANGOLDEN = "Eatin' up all tha treasure!",
        PEAGAWK = {
            DEAD = "It tells no tales.",
            GENERIC = "Arr, them eyes need patches!",
            SLEEPING = "She be grabbin' some shuteye.",
        },
        PEAGAWKFEATHER = "Feather'o'glimmer.",
        PEAGAWK_BUSH = "'Tis unsettlin' t'b'sure.",
        PIKO = {
            DEAD = "Tells no tales.",
            GENERIC = "Thievin' scoundr'l.",
            SLEEPING = "Grabbin' some shuteye.",
        },
        PIKO_ORANGE = {
            DEAD = "Tells no tales.",
            GENERIC = "Aye, 'tis a useful brood.",
            SLEEPING = "Grabbin' some shuteye.",
        },
        PUGALISK = "'Tis a land Leviathan!",
        PUGALISK_CORPSE = "'es danc'd the hemp'n jig.",
        PUGALISK_FOUNTAIN = "Argh! 'Tis but a tiny sea.",
        PUGALISK_RUINS_PILLAR = "Steady as a ship inna storm.",
        PUGALISK_SKULL = "Bigger than me crows nest.",
        PUGALISK_TRAP_DOOR = "That be'a strange sight.",
        RABID_BEETLE = {
            DEAD = "Aye, 'tis fer'tha best.",
            GENERIC = "Ornery buggie.",
            SLEEPING = "Thar she blows!",
        },
        SAIL_SNAKESKIN = "Thet be a sail.",
        SEDIMENTPUDDLE = "Alas, not big enough to sail in.",
        SHEARS = "A cutlass fer tha'bushes.",
        SMELTER = {
            BURNT = "Blast the bore!",
            COOKING_SHORT = "Ye'll be done soon 'nuff.",
            DONE = "She's ready ta fire!",
            EMPTY = "A cannon fer makin' metals.",
        },
        SNAKEBONESOUP = "A hearty brew, t'be sure.",
        SNAKESKIN = "Me leathers do need replacin'.",
        SNAKE_BONE = "A treasure o'tha snake.",
        TEA = "Ah, a fine brew.",
        TEATREE = "'Tis a growin' ship mast.",
        TEATREE_NUT = "A botan'cal barber-surgeon.",
        TEATREE_NUT_COOKED = "Grub.",
        TEATREE_NUT_SAPLING = "'e'll be a fine one.",
        TREE_PILLAR = "Vessel i'th'makin'.",
        WEEVOLE = "'ave at ye landlubbers!",
        WEEVOLE_CARAPACE = "Longcoat made o' them pesky bugs.",
    },
}
