return {
    ANNOUNCE_DEHUMID = {
        "That feels better.",
    },
    ANNOUNCE_HAYFEVER = "You have allergies like me, Lucy?",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Clean air again.",
    ANNOUNCE_PICKPOOP = {
        "Ew!",
        "Blah!",
        "That's gross, eh?",
    },
    ANNOUNCE_SNEEZE = "Achoo! Excuse me. Sorry.",
    ANNOUNCE_TOO_HUMID = {
        "It's blazing with this %s.",
        "Whew! this %s is hot, eh?",
    },
    DESCRIBE = {
        ALLOY = "It's like a block of wood made out of metal.",
        APORKALYPSE_CLOCK = "Looks like it's the end of days.",
        ARMOR_METALPLATE = "Feel a little funny in this.",
        ARMOR_WEEVOLE = "Nice use of bug carcasses.",
        ASPARAGUS_PLANTED = "They're like little trees to chop down.",
        BASEFAN = "Yep. That's a nice breeze.",
        BOATREPAIRKIT = "Patch'er up, eh?",
        BOAT_LOGRAFT = "My specialty!",
        BOAT_ROW = "Powered by elbow grease.",
        BOAT_TORCH = "I can go night fishing.",
        CHITIN = "It's got some heft to it.",
        COFFEE = "Good old joe.",
        COFFEEBEANS = "I should cook these up.",
        COFFEEBEANS_COOKED = "Canadians love their coffee.",
        CUTNETTLE = "It has a smell to it.",
        DUNGBALL = "Dung to go.",
        DUNGBEETLE = {
            DEAD = "It's a goner.",
            GENERIC = "There's a bit of a stink.",
            SLEEPING = "Getting some shut eye.",
            UNDUNGED = "I don't think she liked that.",
        },
        DUNGPILE = {
            GENERIC = "Dung gone it.",
            PICKED = "There'll be more.",
        },
        FLOWER_RAINFOREST = "It's a pretty lil' thing.",
        GLOWFLY = {
            DEAD = "Dead.",
            GENERIC = "Thanks for lightin' the way, buddy.",
            SLEEPING = "A well-deserved nap.",
        },
        GLOWFLY_COCOON = "That looks comfy, eh?",
        GOLDENMACHETE = "It chops AND sparkles!",
        GOLDPAN = "Haven't done any prospectin' in a while.",
        GOLD_DUST = "Look at all that gold!",
        GRABBING_VINE = "Don't trust that.",
        GRASS_TALL = {
            BURNING = "It caught fire.",
            GENERIC = "Don't worry your head aboot this one, Lucy.",
            PICKED = "Got all I could.",
        },
        HALBERD = "Well, it's no axe.",
        HANGING_VINE = "Don't trust that.",
        ICEDTEA = "Nice and refreshing.",
        IRON = "Can't chop this too well.",
        LILYPAD = "Nature's real good, eh?",
        MACHETE = "Ooh, that's a thing for chopping.",
        PANGOLDEN = "Looks expensive.",
        PEAGAWK = {
            DEAD = "It's a goner.",
            GENERIC = "Filthy animal!",
            SLEEPING = "Catching forty winks.",
        },
        PEAGAWKFEATHER = "It has a foul bird stench.",
        PEAGAWK_BUSH = "There's a wretched bird nearby. I feel it.",
        PIKO = {
            DEAD = "Poor little critter...",
            GENERIC = "They like trees almost as much as us.",
            SLEEPING = "All tuckered out.",
        },
        PIKO_ORANGE = {
            DEAD = "Poor little critter...",
            GENERIC = "They like trees almost as much as us.",
            SLEEPING = "All tuckered out.",
        },
        RABID_BEETLE = {
            DEAD = "For the best.",
            GENERIC = "Seems mighty angry.",
            SLEEPING = "Let sleeping bugs lie, I say.",
        },
        SAIL_SNAKESKIN = "Sailin' in style.",
        SEDIMENTPUDDLE = "What's that shiny stuff in there?",
        SHEARS = "Don't get jealous, Lucy.",
        SMELTER = {
            BURNT = "How did it get burned?!",
            COOKING_SHORT = "Oh boy! Here it comes!",
            DONE = "Hrumph. A big production for a little metal.",
            EMPTY = "It's like a giant maple syrup bucket.",
        },
        SNAKESKIN = "I'm sure the snake didn't need this.",
        TEA = "I could go for some tea.",
        TEATREE = "Welp. Better get choppin'.",
        TEATREE_NUT = "Helps with allergies, eh.",
        TEATREE_NUT_COOKED = "Too late to plant this now.",
        TEATREE_NUT_SAPLING = "It's better if you let them grow a little.",
        TREE_PILLAR = "That's a real beaut.",
        WEEVOLE = "Worse than black flies.",
        WEEVOLE_CARAPACE = "That'll teach 'em!",
    },
}
