return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "I'm afraid I can't.",
        },
        USEDOOR = {
            GENERIC = "Can't go through there.",
            LOCKED = "It needs a key or something.",
        },
    },
    ANNOUCE_ALARMOVER = "Phew.",
    ANNOUCE_BATS = "It's bats, eh?",
    ANNOUCE_OTHERWORLD_DEED = "Must be somewhere in the Algonquins.",
    ANNOUCE_UNDERLEAFCANOPY = "Sure is dark in here, eh?",
    ANNOUNCE_BOAT_DAMAGED = "My boat's pretty banged up, eh?",
    ANNOUNCE_BOAT_SINKING = "I'm aboot to sink!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "We're goin' down!",
    ANNOUNCE_DEHUMID = {
        "That feels better.",
    },
    ANNOUNCE_GAS_DAMAGE = "Cough! Cough! Ahem.",
    ANNOUNCE_HAYFEVER = "You have allergies like me, Lucy?",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Clean air again.",
    ANNOUNCE_HOUSE_DOOR = "Oops. Need a permit first.",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "There's a door, eh.",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Nope. Nothing.",
    ANNOUNCE_MYSTERY_FOUND = "Found something, Lucy.",
    ANNOUNCE_MYSTERY_NOREWARD = "Nothing here, eh.",
    ANNOUNCE_NOTHING_FOUND = "Sorry. Nothing here.",
    ANNOUNCE_PICKPOOP = {
        "Ew!",
        "Blah!",
        "That's gross, eh?",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "That won't break, eh?",
        "That part's too tough.",
        "Got any ideas, Lucy?",
    },
    ANNOUNCE_ROOM_STUCK = "I need to get out first.",
    ANNOUNCE_SNEEZE = "Achoo! Excuse me. Sorry.",
    ANNOUNCE_SUITUP = "Let's go, eh!",
    ANNOUNCE_TAXDAY = "Sorry, eh. I gotta collect taxes now.",
    ANNOUNCE_TOOLCORRODED = "These tools just aren't as good as you, Lucy.",
    ANNOUNCE_TOO_HUMID = {
        "It's blazing with this %s.",
        "Whew! this %s is hot, eh?",
    },
    ANNOUNCE_TURFTOOHARD = "I'll leave that where it is.",
    ANNOUNCE_WAVE_BOOST = "For the North!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "As a doornail.",
            GENERIC = "That's a big one there, eh?",
            SLEEPING = "No need to wake it.",
        },
        ALLOY = "It's like a block of wood made out of metal.",
        ALOE = "I hear aloe's good for you.",
        ALOE_COOKED = "I guess I can eat it.",
        ALOE_PLANTED = "Looks like a plant, eh?",
        ALOE_SEEDS = "I should plant this before those pesky birds get it.",
        ANCIENT_HERALD = "How's it goin'?",
        ANCIENT_HULK = "Yep. That's a big one.",
        ANCIENT_REMNANT = "Looks important. I should hold on to it.",
        ANCIENT_ROBOTS_ASSEMBLY = "Doesn't look like it can put itself back together.",
        ANCIENT_ROBOT_CLAW = "No axe in that hand.",
        ANCIENT_ROBOT_HEAD = "I wonder how long it's slept.",
        ANCIENT_ROBOT_LEG = "Somebody lost their leg, eh?",
        ANCIENT_ROBOT_RIBS = "It's only full of iron, not wood.",
        ANTCHEST = "That's neat.",
        ANTQUEEN_THRONE = "There's stuff in there, eh?",
        APORKALYPSE_CLOCK = "Looks like it's the end of days.",
        ARMORVORTEXCLOAK = "Pretty roomy in there, eh.",
        ARMOR_METALPLATE = "Feel a little funny in this.",
        ARMOR_SNAKESKIN = "I feel suave in it.",
        ARMOR_WEEVOLE = "Nice use of bug carcasses.",
        ASPARAGUS_PLANTED = "They're like little trees to chop down.",
        BALLPEIN_HAMMER = "Subtle.",
        BASEFAN = "Yep. That's a nice breeze.",
        BILL = {
            DEAD = "Well that's too bad.",
            GENERIC = "Doesn't he get dizzy?",
            SLEEPING = "We should let him sleep.",
        },
        BILL_QUILL = "What'aya think this is for?",
        BLUNDERBUSS = "Yeesh. Bit of overkill.",
        BOATREPAIRKIT = "Patch'er up, eh?",
        BOAT_CARGO = "I'd prefer cargo shorts.",
        BOAT_CORK = "Only good for a short trip.",
        BOAT_LOGRAFT = "My specialty!",
        BOAT_ROW = "Powered by elbow grease.",
        BOAT_TORCH = "I can go night fishing.",
        BONESTAFF = "Freeze you colder than winter in Winnipeg.",
        BRAMBLESPIKE = "Let's chop it!",
        BRAMBLE_BULB = "What should I do with it, Lucy?",
        BRAMBLE_CORE = "Aw, that's pretty.",
        BURR = "This'll come in handy.",
        BURR_SAPLING = "Still growing.",
        CHITIN = "It's got some heft to it.",
        CITY_LAMP = {
            GENERIC = "A little bit of safe haven.",
            ON = "Looks like a street lamp.",
        },
        CLAWPALMTREE = "That's some weird wood.",
        CLAWPALMTREE_SAPLING = "Too small to chop right now.",
        COFFEE = "Good old joe.",
        COFFEEBEANS = "I should cook these up.",
        COFFEEBEANS_COOKED = "Canadians love their coffee.",
        CORK = "It came from that weird tree.",
        CORKCHEST = "No pests are getting in there.",
        CUTNETTLE = "It has a smell to it.",
        DECO_CHAIR_BENCH = "For when company comes over.",
        DECO_CHAIR_CLASSIC = "Well that's a pretty chair.",
        DECO_CHAIR_CORNER = "A big arm chair for two to curl up in.",
        DECO_CHAIR_FOOTREST = "I can put my feet up.",
        DECO_CHAIR_HORNED = "Just a chair, eh?",
        DECO_CHAIR_LOUNGE = "That's a chair, eh?",
        DECO_CHAIR_MASSAGER = "I wouldn't trust that.",
        DECO_CHAIR_OTTOMAN = "I can put my feet up.",
        DECO_CHAIR_ROCKING = "A rocking chair for someone who likes to rock.",
        DECO_CHAIR_STUFFED = "There's no wood in that.",
        DISARMING_KIT = "Well that's smart, eh?",
        DUNGBALL = "Dung to go.",
        DUNGBEETLE = {
            DEAD = "It's a goner.",
            GENERIC = "There's a bit of a stink.",
            SLEEPING = "Getting some shut eye.",
            UNDUNGED = "I don't think she liked that.",
        },
        DUNGPILE = {
            GENERIC = "Dung gone it.",
            PICKED = "There'll be more.",
        },
        FLOWER_RAINFOREST = "It's a pretty lil' thing.",
        FROGLEGS_POISON = "Those legs look toxic.",
        FROGLEGS_POISON_COOKED = "I don't know, eh...",
        FROG_POISON = {
            DEAD = "It croaked.",
            GENERIC = "Don't like the look of that guy.",
            SLEEPING = "Let sleeping frogs lie, I say.",
        },
        GASMASKHAT = "Keeps my lungs clear.",
        GLOWFLY = {
            DEAD = "Dead.",
            GENERIC = "Thanks for lightin' the way, buddy.",
            SLEEPING = "A well-deserved nap.",
        },
        GLOWFLY_COCOON = "That looks comfy, eh?",
        GOLDENMACHETE = "It chops AND sparkles!",
        GOLDPAN = "Haven't done any prospectin' in a while.",
        GOLD_DUST = "Look at all that gold!",
        GRABBING_VINE = "Don't trust that.",
        GRASS_TALL = {
            BURNING = "It caught fire.",
            GENERIC = "Don't worry your head aboot this one, Lucy.",
            PICKED = "Got all I could.",
        },
        HALBERD = "Well, it's no axe.",
        HANGING_VINE = "Don't trust that.",
        HIPPOPOTAMOOSE = "Reminds me of something I saw in Algonquin Park once.",
        HIPPO_ANTLER = "Yep. That's a big one.",
        ICEDTEA = "Nice and refreshing.",
        INFUSED_IRON = "I still prefer wood.",
        IRON = "Can't chop this too well.",
        KINGFISHER = {
            DEAD = "Poor little guy.",
            GENERIC = "Looks shifty.",
            SLEEPING = "Hope he stays that way.",
        },
        LAWNORNAMENT = {
            BURNING = "That ain't long for this world.",
            BURNT = "Burnt right down.",
            GENERIC = "I prefer wood sculpture.",
        },
        LIFEPLANT = "Pretty little flower.",
        LILYPAD = "Nature's real good, eh?",
        LIVING_ARTIFACT = "This looks interesting eh, Lucy?",
        LOTUS = "Pretty nice, dontcha think Lucy?",
        LOTUS_FLOWER = "That's a beaut.",
        LOTUS_FLOWER_COOKED = "Cooks up real good.",
        MACHETE = "Ooh, that's a thing for chopping.",
        MAGNIFYING_GLASS = "Pretty clever.",
        MANDRAKEHOUSE = "It's where those little plant guys live.",
        MANDRAKEMAN = "He's looking for a fight.",
        MEAN_FLYTRAP = {
            DEAD = "Pretty dead, eh?",
            GENERIC = "Look at them chompers.",
            SLEEPING = "No need to wake it.",
        },
        METALPLATEHAT = "It's a little cold.",
        NECTAR_POD = "Nectar makes honey, eh.",
        OBSIDIAN = "It's a little toasty.",
        OINC = "Looks valuable, eh?",
        OINC10 = "Let's buy something nice eh, Lucy?",
        OINC100 = "Can buy a lot of supplies with this.",
        PANGOLDEN = "Looks expensive.",
        PARROT_BLUE = {
            DEAD = "Pushin' up the daisies.",
            GENERIC = "I don't like him.",
            SLEEPING = "Shagged out after a long squawk.",
        },
        PEAGAWK = {
            DEAD = "It's a goner.",
            GENERIC = "Filthy animal!",
            SLEEPING = "Catching forty winks.",
        },
        PEAGAWKFEATHER = "It has a foul bird stench.",
        PEAGAWK_BUSH = "There's a wretched bird nearby. I feel it.",
        PIGEON = {
            DEAD = "Good.",
            GENERIC = "Horrible vermin.",
            SLEEPING = "They're never really sleeping you know.",
        },
        PIGGHOST = "You ever see something like that before, Lucy?",
        PIGHOUSE_CITY = {
            BURNING = "Hope no one's been hurt.",
            GENERIC = "Not as good as a cabin in the woods.",
        },
        PIGHOUSE_FARM = {
            BURNING = "That farm just bought the farm.",
            GENERIC = "This pig town's a real cowtown.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Woosh. Went up just like that!",
            GENERIC = "What are they mining in there?",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Can't be all that much mayoring to do 'round here.",
            SLEEPING = "Sweet dreams.",
        },
        PIGMAN_QUEEN = "We separated from the crown ages ago.",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Seems like an upstanding sort.",
            SLEEPING = "Sleep tight.",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Hope no one was hurt.",
            GENERIC = "Someone's gotta keep an eye out.",
        },
        PIG_PALACE = "Too fancy for my taste.",
        PIG_RUINS_ARTICHOKE = "Doesn't look too tasty.",
        PIG_RUINS_HEAD = "Someone missing a head?",
        PIG_RUINS_IDOL = "Be nice if we could get that top part off.",
        PIG_RUINS_PLAQUE = "It's one of those statues the pigs like.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Yep. That's a good one.",
            GENERIC = "Big shots in there.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Who did that, eh?",
            GENERIC = "We're all fancy, Lucy.",
        },
        PIG_SHOP_DELI = {
            BURNING = "It's on fire.",
            GENERIC = "I could go for some lunch.",
        },
        PIKO = {
            DEAD = "Poor little critter...",
            GENERIC = "They like trees almost as much as us.",
            SLEEPING = "All tuckered out.",
        },
        PIKO_ORANGE = {
            DEAD = "Poor little critter...",
            GENERIC = "They like trees almost as much as us.",
            SLEEPING = "All tuckered out.",
        },
        POISONBALM = "I really like not bein' poisoned.",
        PROP_DOOR = "You wanna go in, Lucy?",
        PUGALISK = "Whoa. That guy's in a hurry.",
        PUGALISK_CORPSE = "Gotta be useful for something.",
        PUGALISK_FOUNTAIN = "Well that's something I've never seen before.",
        PUGALISK_RUINS_PILLAR = "Don't think it's too sturdy there.",
        PUGALISK_SKULL = "Pretty big, eh?",
        PUGALISK_TRAP_DOOR = "Wonder what this does.",
        RABID_BEETLE = {
            DEAD = "For the best.",
            GENERIC = "Seems mighty angry.",
            SLEEPING = "Let sleeping bugs lie, I say.",
        },
        RADISH = "Kinda tiny, aren't they?",
        RADISH_COOKED = "I have to eat my vegetables.",
        RADISH_PLANTED = "I think that's food, Lucy.",
        RADISH_SEEDS = "It'll make some fine vegetables one day.",
        RAINFORESTTREE = {
            BURNING = "Forest fire!",
            BURNT = "Such a shame.",
            CHOPPED = "We did a number on that one, eh Lucy?",
            GENERIC = "Prime for the chopping.",
        },
        RAINFORESTTREE_ROT = "I hate to see a tree like this.",
        REEDS_WATER = "I could find a use for'em.",
        RELIC_1 = "This has been around awhile.",
        RELIC_2 = "Hey there, little buddy.",
        RELIC_3 = "Who nose what that is, eh?",
        RELIC_4 = "Must have been some important lady.",
        RELIC_5 = "Oh. This one looks valuable.",
        ROCK_BASALT = "Bet I could break that.",
        ROCK_FLIPPABLE = "We should flip it.",
        ROOTTRUNK_CHILD = "It moves all my stuff for me. That's nice.",
        SAIL_SNAKESKIN = "Sailin' in style.",
        SCORPION = {
            DEAD = "For the best.",
            GENERIC = "Keep out of my boots.",
            SLEEPING = "Still wouldn't touch it with a ten foot pole.",
        },
        SEDIMENTPUDDLE = "What's that shiny stuff in there?",
        SHEARS = "Don't get jealous, Lucy.",
        SMELTER = {
            BURNT = "How did it get burned?!",
            COOKING_SHORT = "Oh boy! Here it comes!",
            DONE = "Hrumph. A big production for a little metal.",
            EMPTY = "It's like a giant maple syrup bucket.",
        },
        SNAKEBONESOUP = "Nothin' like a nice warm bowl of soup.",
        SNAKEOIL = "I'm not falling for this.",
        SNAKESKIN = "I'm sure the snake didn't need this.",
        SNAKESKINHAT = "Now would this be a \"touque\" or a \"tuque\"?",
        SNAKE_AMPHIBIOUS = "Rather keep away from that guy.",
        SNAKE_BONE = "A good bone's always good for somethin'.",
        SPIDER_MONKEY = {
            DEAD = "I feel safer already.",
            GENERIC = "He's lookin' for a kerfuffle.",
            SLEEPING = "Better get out of here before it wakes up.",
        },
        SPIDER_MONKEY_NEST = "Real dangerous creatures in there.",
        TEA = "I could go for some tea.",
        TEATREE = "Welp. Better get choppin'.",
        TEATREE_NUT = "Helps with allergies, eh.",
        TEATREE_NUT_COOKED = "Too late to plant this now.",
        TEATREE_NUT_SAPLING = "It's better if you let them grow a little.",
        THUNDERHAT = "How do I look?",
        TOUCAN = "That thing looks shifty.",
        TREE_PILLAR = "That's a real beaut.",
        TUBERTREE = "I can't use you for these trees, Lucy.",
        TUBER_BLOOM_CROP = "Well it's ripe now.",
        TUBER_BLOOM_CROP_COOKED = "Well that's fancy.",
        TUBER_CROP = "Better not eat it until it's ripe.",
        TUBER_CROP_COOKED = "Nothing fancy, just some tubers.",
        TURF_COBBLEROAD = "Just some road, eh?",
        TURF_DEEPRAINFOREST = "Just some ground, eh?",
        TURF_DEEPRAINFOREST_NOCANOPY = "Just some ground, eh?",
        TURF_FIELDS = "Just some ground, eh?",
        TURF_FOUNDATION = "Just some ground, eh?",
        TURF_GASJUNGLE = "Just some ground, eh?",
        TURF_LAWN = "Just some ground, eh?",
        TURF_MOSS = "Just some ground, eh?",
        TURF_PAINTED = "Just some ground, eh?",
        TURF_PIGRUINS = "Just some ground, eh?",
        TURF_PLAINS = "Just some ground, eh?",
        TURF_RAINFOREST = "Just some ground, eh?",
        VAMPIREBAT = {
            DEAD = "It's a goner.",
            GENERIC = "You're a bit batty, eh?",
            SLEEPING = "Let sleeping bats lie, I say.",
        },
        VAMPIREBATCAVE = "Don't look none too inviting.",
        VENOMGLAND = "It smells kind of funny.",
        VENUS_STALK = "I got it from that big leafy hoser.",
        VINE = "Sigh. Not a tree.",
        WALKINGSTICK = "Just out for a walk.",
        WATERDROP = "Into every life a little rain must fall.",
        WEEVOLE = "Worse than black flies.",
        WEEVOLE_CARAPACE = "That'll teach 'em!",
        WINDOW_GREENHOUSE = "It's big, eh?",
        WINDOW_LARGE_SQUARE = "Yep. That's a nice window.",
        WINDOW_LARGE_SQUARE_CURTAIN = "Yep. That's a nice window.",
        WINDOW_ROUND = "Not too homey, but I'm not complaining.",
        WINDOW_ROUND_BURLAP = "We don't need fancy curtains.",
        WINDOW_ROUND_CURTAINS_NAILS = "We don't need fancy curtains.",
        WINDOW_SMALL_PEAKED = "We don't need fancy curtains.",
        WINDOW_SMALL_PEAKED_CURTAIN = "Yep. That's a nice window.",
        WINDOW_TALL = "Yep. That's a nice window.",
        WINDOW_TALL_CURTAIN = "Yep. That's a nice window.",
    },
}
