return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "It be jus'like new!",
        },
        USEDOOR = {
            GENERIC = "'tis closed ta me.",
            LOCKED = "It be needin' somethin' ta open't.",
        },
    },
    ANNOUCE_BATS = "Beasties be flappin' about.",
    ANNOUNCE_BOAT_DAMAGED = "She's takin' on water!",
    ANNOUNCE_BOAT_SINKING = "She be goin' doooon!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Be this th'day th'sea claims me?",
    ANNOUNCE_DEHUMID = {
        "Ah! Th'air be cool again.",
    },
    ANNOUNCE_HAYFEVER = "Me nose be itchier than a sliver in me pegleg.",
    ANNOUNCE_HAYFEVER_OFF = "Ah! Th'air be clear again!",
    ANNOUNCE_PICKPOOP = {
        "Arrgh!",
        "Avast!",
        "Ye repulsive thing!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Tha' hide be too tough!",
        "Where's me harpoon!",
        "What's ye weakness, ye land Leviathan?",
    },
    ANNOUNCE_SNEEZE = "Ahh-pheww!!",
    ANNOUNCE_TOO_HUMID = {
        "Arrgh! It be hot!",
        "This %s is makin' me sweat me britches.",
    },
    ANNOUNCE_WAVE_BOOST = "We be a silver streak on th'blue now!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "Danc'd tha hemp'n jig.",
            GENERIC = "Yer in fer it now.",
            SLEEPING = "Thar sails b'furled.",
        },
        ALLOY = "Ahoy, alloy!",
        ANCIENT_HULK = "Ye be lookin' fer a fight?",
        ANCIENT_ROBOTS_ASSEMBLY = "An'alf t'gether metal leviathan.",
        ANCIENT_ROBOT_CLAW = "I've no need fer a'extra hand.",
        ANCIENT_ROBOT_HEAD = "I'll hang tha' head from me bowsprit.",
        ANCIENT_ROBOT_LEG = "Arrg! I could use tha' leg!",
        ANCIENT_ROBOT_RIBS = "'Tis an iron leviathan.",
        APORKALYPSE_CLOCK = "Tha time be nigh!",
        ARMOR_METALPLATE = "Not good fer swimmin' in.",
        ARMOR_WEEVOLE = "Aye. Finery made o' bug skin.",
        ASPARAGUS_PLANTED = "Tiny masts growin' from the ground.",
        BALLPEIN_HAMMER = "Fer diggin' treasures from'tha artifacts.",
        BASEFAN = "A cool wind blows from thee!",
        BILL = {
            DEAD = "It's been run through.",
            GENERIC = "A cannonball o' fur.",
            SLEEPING = "Arrgh. It's takin' tha caulk.",
        },
        BILL_QUILL = "'Tis a part o' tha spiky beastie.",
        BOATREPAIRKIT = "Never set sail wit'out'er.",
        BOAT_CARGO = "Fer th'hoarder at sea.",
        BOAT_CORK = "It be'a poorly ship.",
        BOAT_LOGRAFT = "She don't look too sturdy.",
        BOAT_ROW = "I ain't rowed since I was a young swab.",
        BOAT_TORCH = "Fer a torch on me boat, not fer torchin' me boat.",
        BONESTAFF = "'twill chill ye to tha bone.",
        CHITIN = "A harden'd hull.",
        COFFEE = "Arrr thet be th'real treasure.",
        COFFEEBEANS = "Just add water.",
        COFFEEBEANS_COOKED = "No hot water?",
        CUTNETTLE = "Cleans tha' nose as good as sea air.",
        DISARMING_KIT = "Now Woodlegs' got'tha upp'r hand!",
        DUNGBALL = "Throw it o'erboard!",
        DUNGBEETLE = {
            DEAD = "'tas been run through!",
            GENERIC = "Cre'ture o' tha dung.",
            SLEEPING = "Too much o' the grog?",
            UNDUNGED = "Th'foul stench follows ye.",
        },
        DUNGPILE = {
            GENERIC = "Foul.",
            PICKED = "Argh! Sweet seawat'r could'na cleanse me now.",
        },
        FLOWER_RAINFOREST = "Ol'Woodlegs na'got use fer'it.",
        FROGLEGS_POISON = "Best b'careful eatin' thet!",
        FROGLEGS_POISON_COOKED = "Na'a prop'r meal.",
        FROG_POISON = {
            DEAD = "Walk'd tha plank.",
            GENERIC = "Scallywag of o' tha land!",
            SLEEPING = "Maroon tha' beastie!",
        },
        GLOWFLY = {
            DEAD = "Tells no tales.",
            GENERIC = "A fly'o'glow!",
            SLEEPING = "Becalm'd.",
        },
        GLOWFLY_COCOON = "'e be sleepin' it off.",
        GOLDENMACHETE = "'Tis a mighty 'eavy blade.",
        GOLDPAN = "Fer fishin' fer gold.",
        GOLD_DUST = "Aye! 'Tis treasure dust!",
        GRABBING_VINE = "Them be th'ropes.",
        GRASS_TALL = {
            BURNING = "'Tis ablaze!",
            GENERIC = "As tall'as th'sky.",
            PICKED = "Plunder'd.",
        },
        HALBERD = "T'ain't no cutlass.",
        HANGING_VINE = "Them be th'ropes.",
        HIPPOPOTAMOOSE = "Avast! 'Tis a land Kracken!",
        HIPPO_ANTLER = "'Tis tha riggin' o' tha'beastie.",
        ICEDTEA = "'Tis relief ta be sure.",
        INFUSED_IRON = "'as th'look 'o treasure to't.",
        IRON = "'Tis not gold, but a treasure nonetheless.",
        KINGFISHER = {
            DEAD = "Met Davey Jones.",
            GENERIC = "Ye live off'th'ocean too?",
            SLEEPING = "'Tis not on watch.",
        },
        LIFEPLANT = "Grew from a drop o' water.",
        LILYPAD = "A leaf aft'r me own heart.",
        LIVING_ARTIFACT = "A Man o' War o' tha land!",
        LOTUS = "It be a big pink flow'r.",
        LOTUS_FLOWER = "Tis a flow'r'o'th'land.",
        LOTUS_FLOWER_COOKED = "It b'cooked.",
        MACHETE = "Ye be slicin'!",
        MAGNIFYING_GLASS = "'Tis a spyglass o' tha land.",
        MANDRAKEHOUSE = "They live b'low decks.",
        MANDRAKEMAN = "I'll run ye through!",
        MEAN_FLYTRAP = {
            DEAD = "Belay'd of life.",
            GENERIC = "'Tis a land shark!",
            SLEEPING = "Thar sails be furled.",
        },
        METALPLATEHAT = "Prefer me captain's hat.",
        NECTAR_POD = "Tha sweet, sweet nectar!",
        OINC = "Pieces o' Eight!",
        OINC10 = "Thet b'gold!!",
        OINC100 = "'tis a small tre'sure!",
        PANGOLDEN = "Eatin' up all tha treasure!",
        PARROT_BLUE = {
            DEAD = "Thar be an ex-parrot.",
            GENERIC = "Blue as th'sea.",
            SLEEPING = "'Tis just restin'",
        },
        PEAGAWK = {
            DEAD = "It tells no tales.",
            GENERIC = "Arr, them eyes need patches!",
            SLEEPING = "She be grabbin' some shuteye.",
        },
        PEAGAWKFEATHER = "Feather'o'glimmer.",
        PEAGAWK_BUSH = "'Tis unsettlin' t'b'sure.",
        PIGEON = {
            DEAD = "Tells no tales.",
            GENERIC = "Be'a gulls o'th' land.",
            SLEEPING = "Grabbin' shuteye.",
        },
        PIGHOUSE_CITY = {
            BURNING = "A flamin' abode!",
            GENERIC = "Boathouse'o'th'land.",
        },
        PIGHOUSE_FARM = {
            BURNING = "Not long fer'tha world!",
            GENERIC = "'Tis th'home o'a landlubber.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Avast! 'Tis afire!",
            GENERIC = "Them b'th'mines.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Too plump fer'is own good.",
            SLEEPING = "Sleepin' landlubbin' swine.",
        },
        PIGMAN_QUEEN = "Whar be yer treasure?",
        PIG_PALACE = "A brigantine o' tha land.",
        PIG_RUINS_ARTICHOKE = "Thar be treas're in't.",
        PIG_RUINS_HEAD = "Thar be th'head.",
        PIG_RUINS_IDOL = "Tha' treasure atop there.",
        PIG_RUINS_PLAQUE = "Tha' treasure needs a diggin' out.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Good riddance.",
            GENERIC = "Full o'tha pesky bigshots.",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Avast!",
            GENERIC = "Where I capt'n me city.",
        },
        PIKO = {
            DEAD = "Tells no tales.",
            GENERIC = "Thievin' scoundr'l.",
            SLEEPING = "Grabbin' some shuteye.",
        },
        PIKO_ORANGE = {
            DEAD = "Tells no tales.",
            GENERIC = "Aye, 'tis a useful brood.",
            SLEEPING = "Grabbin' some shuteye.",
        },
        PUGALISK = "'Tis a land Leviathan!",
        PUGALISK_CORPSE = "'es danc'd the hemp'n jig.",
        PUGALISK_FOUNTAIN = "Argh! 'Tis but a tiny sea.",
        PUGALISK_RUINS_PILLAR = "Steady as a ship inna storm.",
        PUGALISK_SKULL = "Bigger than me crows nest.",
        PUGALISK_TRAP_DOOR = "That be'a strange sight.",
        RABID_BEETLE = {
            DEAD = "Aye, 'tis fer'tha best.",
            GENERIC = "Ornery buggie.",
            SLEEPING = "Thar she blows!",
        },
        REEDS_WATER = "Sticks aft'r me'own 'eart.",
        RELIC_1 = "Long fergott'n treas're.",
        RELIC_2 = "'oary treas're!",
        RELIC_3 = "Treasure b'this!",
        RELIC_4 = "A queenly tre'sure.",
        RELIC_5 = "t'be worth more than'a pretty penny.",
        SAIL_SNAKESKIN = "Thet be a sail.",
        SCORPION = {
            DEAD = "Aye! 'Tis defeated!",
            GENERIC = "A terible foe t'be sure.",
            SLEEPING = "Keelhaul tha'beast, while ye can!",
        },
        SEDIMENTPUDDLE = "Alas, not big enough to sail in.",
        SHEARS = "A cutlass fer tha'bushes.",
        SMELTER = {
            BURNT = "Blast the bore!",
            COOKING_SHORT = "Ye'll be done soon 'nuff.",
            DONE = "She's ready ta fire!",
            EMPTY = "A cannon fer makin' metals.",
        },
        SNAKEBONESOUP = "A hearty brew, t'be sure.",
        SNAKEOIL = "Me knows a good deal when me sees it.",
        SNAKESKIN = "Me leathers do need replacin'.",
        SNAKE_AMPHIBIOUS = "'Tis a land and sea serpent.",
        SNAKE_BONE = "A treasure o'tha snake.",
        TEA = "Ah, a fine brew.",
        TEATREE = "'Tis a growin' ship mast.",
        TEATREE_NUT = "A botan'cal barber-surgeon.",
        TEATREE_NUT_COOKED = "Grub.",
        TEATREE_NUT_SAPLING = "'e'll be a fine one.",
        TOUCAN = "Yer name wouldn't be Sam, would it?",
        TREE_PILLAR = "Vessel i'th'makin'.",
        VAMPIREBAT = {
            DEAD = "Avast ye! The bilge-sucker's been cleaved.",
            GENERIC = "'Tis a wretch'd bloodsucker.",
            SLEEPING = "'Tha scurvy dog be defenceless.",
        },
        VAMPIREBATCAVE = "Inta th'depths wit'ye.",
        VENOMGLAND = "Aye, 'tis th'source o'th'venom.",
        VENUS_STALK = "A plant skelerton.",
        VINE = "Them's be th'stranglin' kind.",
        WALKINGSTICK = "Moor legs mean moor walkin'.",
        WATERDROP = "'Tis only a wee bit o' water.",
        WEEVOLE = "'ave at ye landlubbers!",
        WEEVOLE_CARAPACE = "Longcoat made o' them pesky bugs.",
    },
}
