return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Nope. Can't fix ",
        },
        SHOP = {
            CANTPAY = "Can't pay",
            GENERIC = "Can't buy",
        },
        USEDOOR = {
            GENERIC = "Won't open",
            LOCKED = "Nope. Locked",
        },
    },
    ANNOUCE_ALARMOVER = "Whew! Safe again",
    ANNOUCE_BATS = "Ack! Flying Claws coming!",
    ANNOUCE_OTHERWORLD_DEED = "Not for here",
    ANNOUCE_UNDERLEAFCANOPY = "Hello, leaves!",
    ANNOUNCE_BOAT_DAMAGED = "Oh. Floater is wobbly",
    ANNOUNCE_BOAT_SINKING = "Why sinking, Floater?",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Sunk",
    ANNOUNCE_DEHUMID = {
        "Cooler now",
    },
    ANNOUNCE_GAS_DAMAGE = "kack! kack!",
    ANNOUNCE_HAYFEVER = "Happy time is coming!",
    ANNOUNCE_HAYFEVER_OFF = "Oh. Happy time gone",
    ANNOUNCE_HOUSE_DOOR = "Need paper first",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "Found wall hole",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Nope. No wall hole",
    ANNOUNCE_MYSTERY_FOUND = "Something there?",
    ANNOUNCE_MYSTERY_NOREWARD = "Nothing",
    ANNOUNCE_NOTHING_FOUND = "Nothing here",
    ANNOUNCE_PICKPOOP = {
        "Wheee!",
        "Yay!",
        "Woohoo!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Nope. Not there",
        "Too hard",
        "Wrong spot",
    },
    ANNOUNCE_ROOM_STUCK = "Nope",
    ANNOUNCE_SNEEZE = "Hiccup!",
    ANNOUNCE_SUITUP = "YAY!",
    ANNOUNCE_TAXDAY = "Pay day!",
    ANNOUNCE_TOOLCORRODED = "Oh. It broke",
    ANNOUNCE_TOO_HUMID = {
        "%s is heavy",
        "%s too hot",
    },
    ANNOUNCE_TURFTOOHARD = "Ugh. Ugh. Can't move it",
    ANNOUNCE_WAVE_BOOST = "Whee!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "(sob)",
            GENERIC = "Wants belly stuff",
            SLEEPING = "Tired. Shh...",
        },
        ALLOY = "Bar of Clink Rock",
        ALOE = "Clumpy friend",
        ALOE_COOKED = "Squishy",
        ALOE_PLANTED = "Having fun in dirt",
        ALOE_SEEDS = "Want some dirt?",
        ANCIENT_HERALD = "Dark Floaty Man",
        ANCIENT_HULK = "Clinky Rock Man is awake!",
        ANCIENT_REMNANT = "Feels cold",
        ANCIENT_ROBOTS_ASSEMBLY = "Not done",
        ANCIENT_ROBOT_CLAW = "Shake?",
        ANCIENT_ROBOT_HEAD = "Full of Clinky Rock",
        ANCIENT_ROBOT_LEG = "Clinky Rock Walker",
        ANCIENT_ROBOT_RIBS = "Piece of Clinky Rock Man",
        ANTCHEST = "Buzz juice! Where's Buzz?",
        ANTCOMBHOME = "Little baby Chr'ik home",
        ANTIVENOM = "Sick Fixer",
        ANTMAN = {
            DEAD = "(sniff) Too bad",
            GENERIC = "Chr'ik?",
            SLEEPING = "Sleep well",
        },
        ANTMAN_WARRIOR = "Mad Chr'ik! Agh!",
        ANTMASKHAT = "Chr'ik clothes",
        ANTQUEEN_THRONE = "Looks comfy",
        ANTSUIT = "Makes Chr'ik friends",
        ANT_CAVE_LANTERN = "Sticky light",
        APORKALYPSE_CLOCK = "Tic Tock",
        ARMORVORTEXCLOAK = "Dark Floaty clothes",
        ARMOR_METALPLATE = "Clink Rock clothes",
        ARMOR_SNAKESKIN = "Poor Squirmy",
        ARMOR_WEEVOLE = "Bzzter clothes",
        ASPARAGUS_PLANTED = "Hello there!",
        BALLPEIN_HAMMER = "Teeny Smasher",
        BAMBOO = "Greenstick",
        BANDITHAT = "Sneaky Head Thing",
        BANDITMAP = "Where's stuff?",
        BANDITTREASURE = "Stuff!",
        BASEFAN = "Wind",
        BATHAT = "Woo Woo Head Thing",
        BILL = {
            DEAD = "Oh. Oh dear",
            GENERIC = "Prick beast",
            SLEEPING = "Don't wake it",
        },
        BILL_QUILL = "Pokey part",
        BLUNDERBUSS = "Boom Stick!",
        BOATREPAIRKIT = "Fix it stuff",
        BOAT_CARGO = "Big Floater of friends",
        BOAT_CORK = "Puny Floater",
        BOAT_LOGRAFT = "Friend ship",
        BOAT_ROW = "Push Pull Floater",
        BOAT_TORCH = "For dark times on floater",
        BONESTAFF = "Stare Stick",
        BRAMBLESPIKE = "Wheeee!",
        BRAMBLE_BULB = "Not ground stuff",
        BRAMBLE_CORE = "Friend! Beautiful friend!",
        BUGREPELLENT = "Smells bad",
        BURR = "Cute!",
        BURR_SAPLING = {
            BURNING = "NOOOO!",
            GENERIC = "Sleeping friend",
            PICKED = "Keep growing",
            WITHERED = "Sick?",
        },
        CANDLEHAT = "Scary head thing!",
        CHITIN = "Bzzter clothes",
        CITY_HAMMER = "Town Smasher",
        CITY_LAMP = {
            GENERIC = "Big light stick",
            ON = "No light",
        },
        CLAWPALMTREE = "Friend?",
        CLAWPALMTREE_SAPLING = "Grow friend! Grow!",
        CLIPPINGS = "Can sell this hair",
        COCONADE = {
            BURNING = "Burning!!!",
            GENERIC = "BOOMER!",
        },
        COFFEE = "Wheee!!!",
        COFFEEBEANS = "Zoomberries!",
        COFFEEBEANS_COOKED = "Smells good",
        CONSTRUCTION_PERMIT = "Build rooms?",
        CORK = "Wood? Not wood",
        CORKCHEST = "Put stuff inside",
        CORK_BAT = "Puny Whacker",
        CURTAIN_DOOR = "Another room",
        CUTLASS = "Swooshy Stick",
        CUTNETTLE = "(sniiiiiff)",
        DECO_ANTIQUITIES_BEEFALO = "Oh",
        DECO_ANTIQUITIES_WALLFISH = "Oh",
        DECO_CAVE_BAT_BURROW = "Hard",
        DECO_CAVE_BEAM_ROOM = "Hard",
        DECO_CHAIR_BENCH = "Sitting thing",
        DECO_CHAIR_CLASSIC = "Sitting thing",
        DECO_CHAIR_CORNER = "Sitting thing",
        DECO_CHAIR_FOOTREST = "Foot thing",
        DECO_CHAIR_HORNED = "Sitting thing",
        DECO_CHAIR_LOUNGE = "Sitting thing",
        DECO_CHAIR_MASSAGER = "Sitting thing?",
        DECO_CHAIR_OTTOMAN = "Foot thing",
        DECO_CHAIR_ROCKING = "Sitting thing",
        DECO_CHAIR_STUFFED = "Sitting thing",
        DECO_CHAISE = "Sitting thing",
        DECO_LAMP_2EMBROIDERED = "Light",
        DECO_LAMP_2FRINGES = "Light",
        DECO_LAMP_2UPTURNS = "Light",
        DECO_LAMP_ADJUSTABLE = "Light",
        DECO_LAMP_BELLSHADE = "Light",
        DECO_LAMP_CANDELABRA = "Light",
        DECO_LAMP_CERAMIC = "Light",
        DECO_LAMP_CRYSTALS = "Light",
        DECO_LAMP_DOWNBRIDGE = "Light",
        DECO_LAMP_EDISON = "Light",
        DECO_LAMP_ELIZABETHAN = "Light",
        DECO_LAMP_FRINGE = "Light",
        DECO_LAMP_GLASS = "Light",
        DECO_LAMP_GOTHIC = "Light",
        DECO_LAMP_HOOFSPA = "Twirly Tail light",
        DECO_LAMP_ORB = "Light",
        DECO_LAMP_RIGHTANGLES = "Light",
        DECO_LAMP_SPOOL = "Light",
        DECO_LAMP_STAINGLASS = "Light",
        DECO_LAMP_UPTURN = "Light",
        DECO_MARBLE = "Hard",
        DECO_MARBLE_CORNERBEAM = "Hard",
        DECO_MILLINERY = "Friend?",
        DECO_PLANTHOLDER_BASIC = "Friend?",
        DECO_PLANTHOLDER_BIRDCAGE = "Trapped?",
        DECO_PLANTHOLDER_BONSAI = "You look nice",
        DECO_PLANTHOLDER_DISHGARDEN = "Small friends",
        DECO_PLANTHOLDER_DRACEANA = "Hi there!",
        DECO_PLANTHOLDER_FANCY = "Hello!",
        DECO_PLANTHOLDER_FERN = "Hello up there!",
        DECO_PLANTHOLDER_FERNSTAND = "Friend!",
        DECO_PLANTHOLDER_MARBLE = "Friend",
        DECO_PLANTHOLDER_ORCHID = "Nice friend",
        DECO_PLANTHOLDER_PALM = "Hello",
        DECO_PLANTHOLDER_PHILODENDRON = "Neat friend",
        DECO_PLANTHOLDER_PITCHERS = "Hanging around?",
        DECO_PLANTHOLDER_PLANTPET = "Sit! Stay",
        DECO_PLANTHOLDER_TERRARIUM = "Anyone home?",
        DECO_PLANTHOLDER_TRAPS = "Cute!",
        DECO_PLANTHOLDER_WINTERFEASTTREE = "Nice to see a friend!",
        DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "Okay, friend?",
        DECO_PLANTHOLDER_WIP = "Need help?",
        DECO_PLANTHOLDER_XEROGRAPHICA = "How are you?",
        DECO_PLANTHOLDER_ZZ = "Nice hair!",
        DECO_ROUND = "Hard",
        DECO_RUINS_BEAM_ROOM = "Hard",
        DECO_RUINS_BEAM_ROOM_BLUE = "Hard",
        DECO_RUINS_ENDSWELL = "Not good water. Not good",
        DECO_RUINS_FOUNTAIN = "Wishy water",
        DECO_TABLE_BANKER = "Flat thing",
        DECO_TABLE_CHESS = "Game?",
        DECO_TABLE_CRATE = "Friends made a box",
        DECO_TABLE_DIY = "Knew that tree",
        DECO_TABLE_RAW = "Friends?",
        DECO_TABLE_ROUND = "Flat thing",
        DECO_WALLORNAMENT_AXE = "Yikes!",
        DECO_WALLORNAMENT_BLACK_CAT = "Mow? Mow?",
        DECO_WALLORNAMENT_CAPE = "Hmm...",
        DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Hmm...",
        DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Friend?",
        DECO_WALLORNAMENT_GEARS_ART = "Hmm...",
        DECO_WALLORNAMENT_HUNT = "Pointy sticks",
        DECO_WALLORNAMENT_MOSAIC = "Hmm...",
        DECO_WALLORNAMENT_NO_SMOKING = "Hmm...",
        DECO_WALLORNAMENT_PERIODIC_TABLE = "Hmm...",
        DECO_WALLORNAMENT_PHOTO = "Hmm...",
        DECO_WALLORNAMENT_WREATH = "Circle of friends",
        DECO_WOOD = "Hello?",
        DECO_WOOD_CORNERBEAM = "Friend?",
        DEED = "For home",
        DEMOLITION_PERMIT = "Break rooms?",
        DISARMING_KIT = "Things for tricky walls",
        DISGUISEHAT = "Twirly Tail?",
        DUG_NETTLE = "Needs dirt",
        DUNGBALL = "Yay! Ball of poop!",
        DUNGBEETLE = {
            DEAD = "Poor poop rider",
            GENERIC = "You like poop too?!",
            SLEEPING = "Shhh...",
            UNDUNGED = "Where's poop?",
        },
        DUNGPILE = {
            GENERIC = "Poop!",
            PICKED = "Aw. No more poop",
        },
        FABRIC = "Soft. Made from friends",
        FEATHER_THUNDER = "Zzzt Tweeter clothes",
        FEIJOADA = "Full of Jumpies",
        FLOWER_RAINFOREST = "Dirt made a friend",
        FROGLEGS_POISON = "(sniff, sniff) Smells bad",
        FROGLEGS_POISON_COOKED = "(sniff, sniff) Smells okay",
        FROG_POISON = {
            DEAD = "Too bad",
            GENERIC = "Sick Ribbit",
            SLEEPING = "Tired of ribbiting",
        },
        GASCLOUD = "Bad air",
        GASMASKHAT = "Breather with Tweeter clothes",
        GLOWFLY = {
            DEAD = "(sob)",
            GENERIC = "Bzzter with bright peepers",
            SLEEPING = "No light",
        },
        GLOWFLY_COCOON = "Changing",
        GNAT = "Stay away, Bzzters!",
        GNATMOUND = "Hello?",
        GOLDENMACHETE = "Pretty Slicer",
        GOLDPAN = "Gets Shiny from puddle",
        GOLD_DUST = "Shiny dirt",
        GRABBING_VINE = "Wants stuff",
        GRASS_TALL = {
            BURNING = "No!!",
            GENERIC = "You're so tall!",
            PICKED = "Keep growing!",
        },
        GUMMY_CAKE = "Squishy",
        HALBERD = "Twirly Tail Fight Stick",
        HANGING_VINE = "Wants stuff",
        HARDSHELL_TACOS = "Crunchy Bzzters",
        HEDGE = {
            BURNING = "AGGGHHH!",
            BURNT = "(sob)",
            GENERIC = "How are you?",
            SHAVEABLE = "Needs hair cut",
        },
        HEDGE_BLOCK_ITEM = "Where you want to live?",
        HEDGE_CONE_ITEM = "Nice haircut!",
        HEDGE_LAYERED_ITEM = "Fancy friend wall",
        HIPPOPOTAMOOSE = "Big Water Hoppy",
        HIPPO_ANTLER = "Big Head Branch",
        HOGUSPORKUSATOR = "Twirly Tail Tweeter?",
        ICEDTEA = "Cold Zippy water",
        INFUSED_IRON = "Oh... shiny",
        IRON = "Clinky Rock",
        IRON_DOOR = "Twirly door",
        JELLYBUG = "Jumpies",
        JELLYBUG_COOKED = "Why not jumping?",
        KEY_TO_CITY = "For Twirly Tail Town",
        KINGFISHER = {
            DEAD = "Sad. So sad",
            GENERIC = "Poke Nose Tweeter",
            SLEEPING = "Nighty night",
        },
        LAWNORNAMENT = {
            BURNING = "Save friend! Save friend!",
            BURNT = "(sob) No more",
            GENERIC = "Want to be friends?",
        },
        LIFEPLANT = "Lively friend",
        LILYPAD = "Nice day for swim?",
        LIVING_ARTIFACT = "Boom clothes!",
        LOTUS = "Hello! How's water?",
        LOTUS_FLOWER = "Smells sweet!",
        LOTUS_FLOWER_COOKED = "Holey belly stuff",
        MACHETE = "Slicer. For friend haircuts",
        MAGNIFYING_GLASS = "Peeper",
        MANDRAKEHOUSE = "Hello? Anyone?",
        MANDRAKEMAN = "Screamy",
        MEAN_FLYTRAP = {
            DEAD = "(sob)",
            GENERIC = "Hungry?",
            SLEEPING = "Tired. Shh...",
        },
        MEATED_NETTLE = "Mmmm...",
        METALPLATEHAT = "Clink Rock Head Thing",
        NECTAR_POD = "Sweet!",
        NETTLE = {
            DEFAULT = "Hello! Doing good?",
            EMPTY = "Grow back",
            MOIST = "Growing good",
            WITHERED = "Not wet enough",
        },
        NETTLELOSANGE = "Mmm...",
        OBSIDIAN = "Fire trapped in rock",
        OINC = "Twirly Tails like this",
        OINC10 = "Can buy things now",
        OINC100 = "Wow!!",
        ORGANIC_DOOR = "Hello? Welcome",
        OX_FLUTE = "Toot! Toot!",
        OX_HORN = "Branches?",
        PANGOLDEN = "Shiny Pooper",
        PARROT_BLUE = {
            DEAD = "Dead",
            GENERIC = "Blue Tweeter",
            SLEEPING = "Resting",
        },
        PEAGAWK = {
            DEAD = "Oh dear",
            GENERIC = "Gubble Gubble Tweeter",
            SLEEPING = "Sleeping?",
        },
        PEAGAWKFEATHER = "Gubble Gubble Tweeter clothes",
        PEAGAWK_BUSH = "Looking good!",
        PEDESTAL_KEY = "Little key",
        PHEROMONESTONE = "Smells like Chr'ik",
        PIGBANDIT = "Sneaky Twirly Tail",
        PIGEON = {
            DEAD = "(sob)",
            GENERIC = "Gray Tweeter",
            SLEEPING = "Shh...",
        },
        PIGGHOST = "Floaty Twirly Tail",
        PIGHOUSE_CITY = {
            BURNING = "Fire not good",
            GENERIC = "Twirly tail home",
        },
        PIGHOUSE_FARM = {
            BURNING = "Save it! Save it!",
            GENERIC = "Home of dirt",
        },
        PIGHOUSE_MINE = {
            BURNING = "Bad fire! Bad!",
            GENERIC = "Twirly Tail home",
        },
        PIGMAN_BANKER = {
            GENERIC = "Likes buying stuff",
            SLEEPING = "Sleep tight",
        },
        PIGMAN_BEAUTICIAN = {
            GENERIC = "Boo Boo Twirly Tail",
            SLEEPING = "Shh...",
        },
        PIGMAN_COLLECTOR = {
            GENERIC = "Have odd stuff?",
            SLEEPING = "Night night",
        },
        PIGMAN_ERUDITE = {
            GENERIC = "Odd Twirly Tail",
            SLEEPING = "Snoring Twirly Tail",
        },
        PIGMAN_FARMER = {
            GENERIC = "Likes grass friends",
            SLEEPING = "Shh... sleeping",
        },
        PIGMAN_FLORIST = {
            GENERIC = "Have dirt things?",
            SLEEPING = "Why not in bed?",
        },
        PIGMAN_HATMAKER = {
            GENERIC = "Have head stuff?",
            SLEEPING = "Tired",
        },
        PIGMAN_HUNTER = {
            GENERIC = "Wants sharp things",
            SLEEPING = "Bedtime",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Your town?",
            SLEEPING = "Sweet dreams",
        },
        PIGMAN_MECHANIC = {
            GENERIC = "Fix things?",
            SLEEPING = "Sleepy twirly tail...",
        },
        PIGMAN_MINER = {
            GENERIC = "Likes rocks",
            SLEEPING = "Goodnight",
        },
        PIGMAN_PROFESSOR = {
            GENERIC = "Wise old Twirly Tail",
            SLEEPING = "Sleepytime",
        },
        PIGMAN_QUEEN = "Fancy Twirly Tail",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Twirly Tail tough guy",
            SLEEPING = "Sleepy",
        },
        PIGMAN_ROYALGUARD_2 = {
            GENERIC = "Twirly Tail Tough Guy",
            SLEEPING = "Needs bed",
        },
        PIGMAN_STOREOWNER = {
            GENERIC = "Likes friend hair",
            SLEEPING = "So tired",
        },
        PIGMAN_USHER = {
            GENERIC = "Good day, Twirly Tail",
            SLEEPING = "Shh...",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Stay back, fire!",
            GENERIC = "For Twirly Tails",
        },
        PIG_PALACE = "Pretty!",
        PIG_RUINS_ANT = "Chr'ik rock",
        PIG_RUINS_ARTICHOKE = "Friend? Nope, rock",
        PIG_RUINS_CREEPING_VINES = "Friends?",
        PIG_RUINS_DART_STATUE = "Patuey!",
        PIG_RUINS_DART_TRAP = "Patuey!",
        PIG_RUINS_ENTRANCE = {
            GENERIC = "Dark in there",
            LOCKED = "Friends are in the way",
        },
        PIG_RUINS_ENTRANCE2 = "Dark in there",
        PIG_RUINS_ENTRANCE3 = "What's in there?",
        PIG_RUINS_ENTRANCE4 = "Where does that go?",
        PIG_RUINS_ENTRANCE5 = "What's in there?",
        PIG_RUINS_ENTRANCE_SMALL = "Dark in there",
        PIG_RUINS_EXIT = "Out",
        PIG_RUINS_EXIT2 = "Door to outside",
        PIG_RUINS_EXIT4 = "Goes somewhere else",
        PIG_RUINS_HEAD = "Must have big rock brain",
        PIG_RUINS_IDOL = "Twirly Tail rock",
        PIG_RUINS_MUSHROOM = "Not friend.",
        PIG_RUINS_PLAQUE = "Twirly Tail rock",
        PIG_RUINS_PRESSURE_PLATE = "Hmm...Odd rock",
        PIG_RUINS_SPEAR_TRAP = "Hello, sticks!",
        PIG_RUINS_SPEAR_TRAP_BROKEN = "Sorry, sticks",
        PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Oh!",
        PIG_RUINS_TORCH = "Burns stick friends",
        PIG_RUINS_TORCH_WALL = "Burns stick friends",
        PIG_SHOP_ACADEMY = {
            BURNING = "Stay away! Stay away!",
            GENERIC = "Old stuff place",
        },
        PIG_SHOP_ANTIQUITIES = {
            BURNING = "Fire! Fire!",
            GENERIC = "Strange Things place",
        },
        PIG_SHOP_ARCANE = {
            BURNING = "Oh no!!!",
            GENERIC = "Magics place",
        },
        PIG_SHOP_BANK = {
            BURNING = "Oh",
            GENERIC = "Twirly Tail Shiny place",
        },
        PIG_SHOP_CITYHALL = {
            BURNING = "Nooooo!",
            GENERIC = "Papers inside",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "Stay back!",
            GENERIC = "Work place",
        },
        PIG_SHOP_DELI = {
            BURNING = "Don't like fire",
            GENERIC = "Good belly stuff!",
        },
        PIG_SHOP_FLORIST = {
            BURNING = "NOOOOO!",
            GENERIC = "Has dirt things",
        },
        PIG_SHOP_GENERAL = {
            BURNING = "(sob)",
            GENERIC = "Sells stuff",
        },
        PIG_SHOP_HATSHOP = {
            BURNING = "Save the head things!",
            GENERIC = "Has head things",
        },
        PIG_SHOP_HOOFSPA = {
            BURNING = "Help! Help!",
            GENERIC = "Boo Boo Place",
        },
        PIG_SHOP_PRODUCE = {
            BURNING = "AGGHHH!",
            GENERIC = "Belly stuff inside",
        },
        PIG_SHOP_TINKER = {
            BURNING = "Aggh!",
            GENERIC = "For stuff making",
        },
        PIG_SHOP_WEAPONS = {
            BURNING = "Friends are burning!",
            GENERIC = "Stuff for fighting",
        },
        PIKO = {
            DEAD = "Aw...",
            GENERIC = "Fluffy Nabber",
            SLEEPING = "Sleeping. Shh...",
        },
        PIKO_ORANGE = {
            DEAD = "Aw...",
            GENERIC = "Fluffy Nabber",
            SLEEPING = "Sleeping. Shh...",
        },
        PILLAR_DOOR = "Hello! Hello?",
        PITHHAT = "Zoomy Head Thing",
        PLATE_DOOR = "Another room",
        PLAYERHOUSE_CITY = {
            BURNT = "AGGGGHH!",
            FORSALE = "Empty",
            SOLD = "Home",
        },
        PLAYER_HOUSE_BRICK = "Rock home",
        PLAYER_HOUSE_BRICK_CRAFT = "Rocks for home",
        PLAYER_HOUSE_COTTAGE = "Home made of friends",
        PLAYER_HOUSE_COTTAGE_CRAFT = "Makes home made of friends",
        PLAYER_HOUSE_GOTHIC = "Home",
        PLAYER_HOUSE_GOTHIC_CRAFT = "Builds home",
        PLAYER_HOUSE_MANOR = "Really big home",
        PLAYER_HOUSE_MANOR_CRAFT = "Makes REALLY big home",
        PLAYER_HOUSE_TUDOR = "Big home",
        PLAYER_HOUSE_TUDOR_CRAFT = "Friends to build home",
        PLAYER_HOUSE_TURRET = "Pointy top home",
        PLAYER_HOUSE_TURRET_CRAFT = "Builds pointy top home",
        PLAYER_HOUSE_VILLA = "Big home",
        PLAYER_HOUSE_VILLA_CRAFT = "Makes big home",
        POG = {
            APORKALYPSE = "Bad Woofer",
            FOLLOWER = "Friend",
            GENERIC = "Bouncy Woofer",
            SLEEPING = "Sleepy Snoozer",
        },
        POISONBALM = "Takes away sick",
        PORKLAND_INTRO_BALLOON = "Went pbblt",
        PORKLAND_INTRO_BASKET = "Fell from sky",
        PORKLAND_INTRO_FLAGS = "Pretty string",
        PORKLAND_INTRO_SANDBAG = "Dirt bag exploded",
        PORKLAND_INTRO_SUITCASE = "Going on trip?",
        PORKLAND_INTRO_TRUNK = "Something inside? Nope",
        PROP_DOOR = "Where to?",
        PUGALISK = "Big Wiggler",
        PUGALISK_CORPSE = "Growing bones?",
        PUGALISK_FOUNTAIN = "Life water",
        PUGALISK_RUINS_PILLAR = "Hard",
        PUGALISK_SKULL = "From big Wiggler",
        PUGALISK_TRAP_DOOR = "Hmm...What's here?",
        RABID_BEETLE = {
            DEAD = "Too bad",
            GENERIC = "Why so mad, Bzzter?",
            SLEEPING = "Let it sleep",
        },
        RADISH = "Red balls for belly",
        RADISH_COOKED = "Where green part go?",
        RADISH_PLANTED = "See you hiding!",
        RADISH_SEEDS = "You're going in dirt!",
        RAINFORESTTREE = {
            BURNING = "Stay away, fire!",
            BURNT = "(sob)",
            CHOPPED = "Sorry. Didn't want to",
            GENERIC = "Pretty hair, friend!",
        },
        RAINFORESTTREE_ROT = "You sick, friend?",
        RECONSTRUCTION_PROJECT = {
            RUBBLE = "Broken",
            SCAFFOLD = "Making things",
        },
        REEDS_WATER = "Good day, friend!",
        RELIC_1 = {
            GENERIC = "Happy rock!",
            SUNKEN = "Swimming",
        },
        RELIC_2 = {
            GENERIC = "Old Twirly Tail thing",
            SUNKEN = "Something hiding?",
        },
        RELIC_3 = {
            GENERIC = "Lost sniffer?",
            SUNKEN = "See you!",
        },
        RELIC_4 = "Ohh... pretty rock",
        RELIC_5 = "Fancy old thing",
        ROCK_ANTCAVE = "Rock. Looks hard",
        ROCK_BASALT = "Rock",
        ROCK_FLIPPABLE = "Things hiding?",
        ROOTTRUNK = "Friends help carry stuff",
        ROUND_DOOR = "Big mouth door",
        ROYAL_GALLERY = "Has little lock",
        RUG_BEARD = "Ground thing",
        RUG_BRAID = "Ground thing",
        RUG_CATCOON = "Oh",
        RUG_CRIME = "Ground thing",
        RUG_FUR = "Aww...",
        RUG_HEDGEHOG = "Ground thing",
        RUG_HOOFPRINT = "Ground thing",
        RUG_METAL = "Ground thing",
        RUG_NAILBED = "Pokey",
        RUG_OCTAGON = "Ground thing",
        RUG_OVAL = "Ground thing",
        RUG_PORCUPUSS = "Friend? Friend?",
        RUG_RECTANGLE = "Ground thing",
        RUG_ROUND = "Ground thing",
        RUG_RUBBERMAT = "Ground thing",
        RUG_SQUARE = "Ground thing",
        RUG_SWIRL = "Ground thing",
        RUG_TILES = "Ground thing",
        RUG_WEB = "Sticky",
        RUG_WORMHOLE = "Ground thing",
        SAIL_SNAKESKIN = "Squirmy Wind Nabber",
        SCORPION = {
            DEAD = "No more stabby",
            GENERIC = "Stabby bzzter",
            SLEEPING = "Nighty night",
        },
        SECURITYCONTRACT = "For a Twirly Tail friend",
        SEDIMENTPUDDLE = "Shiny puddle",
        SHEARS = "For hair cuts",
        SHELF_ADJUSTABLE = "For stuff",
        SHELF_AFRAME = "For stuff",
        SHELF_BASIC = "For stuff",
        SHELF_CINDERBLOCKS = "For stuff",
        SHELF_CRATES = "For stuff",
        SHELF_FLOATING = "For stuff",
        SHELF_FRIDGE = "For stuff",
        SHELF_GLASS = "For stuff",
        SHELF_HATTREE = "For stuff",
        SHELF_HOOKS = "For stuff",
        SHELF_HUTCH = "For stuff",
        SHELF_INDUSTRIAL = "For stuff",
        SHELF_LADDER = "For stuff",
        SHELF_MARBLE = "For stuff",
        SHELF_METAL = "For stuff",
        SHELF_MIDCENTURY = "For stuff",
        SHELF_PALLET = "For stuff",
        SHELF_PIPE = "For stuff",
        SHELF_WALLMOUNT = "For stuff",
        SHELF_WOOD = "Helping friends",
        SLUGBUG = "Slimies",
        SLUGBUG_COOKED = "Hello, teeny sticks!",
        SMASHINGPOT = "Smash! Smash!",
        SMELTER = {
            BURNT = "Nothing",
            COOKING_SHORT = "Hot! Hot!",
            DONE = "Done!",
            EMPTY = "Clinky rock cooker",
        },
        SNAKEBONESOUP = "Squirmy water",
        SNAKEOIL = "Hmmm...",
        SNAKESKIN = "Squirmy clothes",
        SNAKESKINHAT = "Snazzy Squirmy head thing",
        SNAKE_AMPHIBIOUS = "Squirmy",
        SNAKE_BONE = "Ouch! Has sharp bits",
        SPIDER_MONKEY = {
            DEAD = "Oh dear",
            GENERIC = "Leggy Bug? or Cheeky?",
            SLEEPING = "Shh... Don't wake him",
        },
        SPIDER_MONKEY_NEST = "Anyone home?",
        SPIDER_MONKEY_TREE = "Trapped friend?",
        SPRINKLER = "Makes air water",
        STONE_DOOR = "Another room",
        SWINGING_LIGHT1 = "Light!",
        SWINGING_LIGHT_BASIC_BULB = "Light",
        SWINGING_LIGHT_BASIC_METAL = "Light",
        SWINGING_LIGHT_CHANDALIER_CANDLES = "Little fires",
        SWINGING_LIGHT_DERBY = "Light made of a Head Thing",
        SWINGING_LIGHT_FLORAL_BLOOMER = "Light",
        SWINGING_LIGHT_FLORAL_BULB = "Light",
        SWINGING_LIGHT_FLORAL_SCALLOP = "Light",
        SWINGING_LIGHT_PENDANT_CHERRIES = "Light",
        SWINGING_LIGHT_ROPE_1 = "Light",
        SWINGING_LIGHT_ROPE_2 = "Light",
        SWINGING_LIGHT_TOPHAT = "Light made of a Head Thing",
        TEA = "Warm Zippy water",
        TEATREE = "Let them sleep",
        TEATREE_NUT = "Want in belly? Or dirt?",
        TEATREE_NUT_COOKED = "Not for dirt now",
        TEATREE_NUT_SAPLING = "Hello, little friend",
        THUNDERBIRD = "Zzzt Tweeter",
        THUNDERBIRDNEST = "Zzzt Tweeter home",
        THUNDERHAT = "Pointy Head Thing",
        TOPIARY = "You look nice",
        TOUCAN = "Big Nose Tweeter",
        TRAWLNET = "Glub Glub Snagger",
        TRAWLNETDROPPED = {
            GENERIC = "Water stuff",
            SOON = "Have to wait",
            SOONISH = "Have to wait more",
        },
        TREE_PILLAR = "Big friend?",
        TRINKET_GIFTSHOP_1 = "Rock. Pretty rock",
        TRINKET_GIFTSHOP_3 = "Ooohh... nice place",
        TRINKET_GIFTSHOP_4 = "Twirly Tail Can",
        TUBERTREE = "Odd friend",
        TUBER_BLOOM_CROP = "Ready!",
        TUBER_BLOOM_CROP_COOKED = "Hello flower friend!",
        TUBER_CROP = "Not ready",
        TUBER_CROP_COOKED = "Good now",
        TUNACAN = "Glub Glub inside?",
        TURF_COBBLEROAD = "Not dirt",
        TURF_DEEPRAINFOREST = "Dirt",
        TURF_DEEPRAINFOREST_NOCANOPY = "Dirt. Good dirt",
        TURF_FIELDS = "Dirt",
        TURF_FOUNDATION = "Not dirt",
        TURF_GASJUNGLE = "Dirt",
        TURF_LAWN = "Dirt",
        TURF_MOSS = "Soft and squishy",
        TURF_PAINTED = "Dirt",
        TURF_PIGRUINS = "Not dirt",
        TURF_PLAINS = "Dirt",
        TURF_RAINFOREST = "Dirt",
        VAMPIREBAT = {
            DEAD = "Oh",
            GENERIC = "Flying claws",
            SLEEPING = "Sleeping down side up",
        },
        VAMPIREBATCAVE = "Smells good!",
        VENOMGLAND = "For sickness",
        VENUS_STALK = "Mmmm...",
        VINE = "String branches",
        WALKINGSTICK = "Wheee!",
        WALLCRACK_RUINS = "Broken",
        WALL_PIG_RUINS = "Wall",
        WATERDROP = "For dirt",
        WEEVOLE = "Wee Bzzter",
        WEEVOLE_CARAPACE = "Crunchy",
        WINDOW_GREENHOUSE = "Can see lots of outside!",
        WINDOW_LARGE_SQUARE = "Outside",
        WINDOW_LARGE_SQUARE_CURTAIN = "Outside",
        WINDOW_ROUND = "Outside",
        WINDOW_ROUND_BURLAP = "Outside",
        WINDOW_ROUND_CURTAINS_NAILS = "Outside",
        WINDOW_SMALL_PEAKED = "Outside",
        WINDOW_SMALL_PEAKED_CURTAIN = "Outside",
        WINDOW_TALL = "Outside",
        WINDOW_TALL_CURTAIN = "Outside",
        WOOD_DOOR = "Door of friends",
    },
}
