return {
    ANNOUNCE_DEHUMID = {
        "Cooler now",
    },
    ANNOUNCE_HAYFEVER = "Happy time is coming!",
    ANNOUNCE_HAYFEVER_OFF = "Oh. Happy time gone",
    ANNOUNCE_SNEEZE = "Hiccup!",
    ANNOUNCE_TOO_HUMID = {
        "%s is heavy",
        "%s too hot",
    },
    DESCRIBE = {
        ALLOY = "Bar of Clink Rock",
        APORKALYPSE_CLOCK = "Tic Tock",
        ARMOR_METALPLATE = "Clink Rock clothes",
        ARMOR_WEEVOLE = "Bzzter clothes",
        ASPARAGUS_PLANTED = "Hello there!",
        CHITIN = "Bzzter clothes",
        CUTNETTLE = "(sniiiiiff)",
        FLOWER_RAINFOREST = "Dirt made a friend",
        GLOWFLY = {
            DEAD = "(sob)",
            GENERIC = "Bzzter with bright peepers",
            SLEEPING = "No light",
        },
        GLOWFLY_COCOON = "Changing",
        GRASS_TALL = {
            BURNING = "No!!",
            GENERIC = "You're so tall!",
            PICKED = "Keep growing!",
        },
        HALBERD = "Twirly Tail Fight Stick",
        PEAGAWK = {
            DEAD = "Oh dear",
            GENERIC = "Gubble Gubble Tweeter",
            SLEEPING = "Sleeping?",
        },
        PEAGAWKFEATHER = "Gubble Gubble Tweeter clothes",
        PEAGAWK_BUSH = "Looking good!",
        RABID_BEETLE = {
            DEAD = "Too bad",
            GENERIC = "Why so mad, Bzzter?",
            SLEEPING = "Let it sleep",
        },
        SHEARS = "For hair cuts",
        TREE_PILLAR = "Big friend?",
        WEEVOLE = "Wee Bzzter",
        WEEVOLE_CARAPACE = "Crunchy",
    },
}
