return {
    ACTIONFAIL = {
        REPAIRBOAT = {
            GENERIC = "Nope. Can't fix ",
        },
    },
    ANNOUCE_BATS = "Ack! Flying Claws coming!",
    ANNOUNCE_BOAT_DAMAGED = "Oh. Floater is wobbly",
    ANNOUNCE_BOAT_SINKING = "Why sinking, Floater?",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Sunk",
    ANNOUNCE_DEHUMID = {
        "Cooler now",
    },
    ANNOUNCE_HAYFEVER = "Happy time is coming!",
    ANNOUNCE_HAYFEVER_OFF = "Oh. Happy time gone",
    ANNOUNCE_PICKPOOP = {
        "Wheee!",
        "Yay!",
        "Woohoo!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Nope. Not there",
        "Too hard",
        "Wrong spot",
    },
    ANNOUNCE_SNEEZE = "Hiccup!",
    ANNOUNCE_TOO_HUMID = {
        "%s is heavy",
        "%s too hot",
    },
    ANNOUNCE_WAVE_BOOST = "Whee!",
    DESCRIBE = {
        ALLOY = "Bar of Clink Rock",
        ANCIENT_HULK = "Clinky Rock Man is awake!",
        ANCIENT_ROBOTS_ASSEMBLY = "Not done",
        ANCIENT_ROBOT_CLAW = "Shake?",
        ANCIENT_ROBOT_HEAD = "Full of Clinky Rock",
        ANCIENT_ROBOT_LEG = "Clinky Rock Walker",
        ANCIENT_ROBOT_RIBS = "Piece of Clinky Rock Man",
        APORKALYPSE_CLOCK = "Tic Tock",
        ARMOR_METALPLATE = "Clink Rock clothes",
        ARMOR_WEEVOLE = "Bzzter clothes",
        ASPARAGUS_PLANTED = "Hello there!",
        BASEFAN = "Wind",
        BILL = {
            DEAD = "Oh. Oh dear",
            GENERIC = "Prick beast",
            SLEEPING = "Don't wake it",
        },
        BILL_QUILL = "Pokey part",
        BOATREPAIRKIT = "Fix it stuff",
        BOAT_CARGO = "Big Floater of friends",
        BOAT_CORK = "Puny Floater",
        BOAT_LOGRAFT = "Friend ship",
        BOAT_ROW = "Push Pull Floater",
        BOAT_TORCH = "For dark times on floater",
        BONESTAFF = "Stare Stick",
        CHITIN = "Bzzter clothes",
        COFFEE = "Wheee!!!",
        COFFEEBEANS = "Zoomberries!",
        COFFEEBEANS_COOKED = "Smells good",
        CUTNETTLE = "(sniiiiiff)",
        DISARMING_KIT = "Things for tricky walls",
        DUNGBALL = "Yay! Ball of poop!",
        DUNGBEETLE = {
            DEAD = "Poor poop rider",
            GENERIC = "You like poop too?!",
            SLEEPING = "Shhh...",
            UNDUNGED = "Where's poop?",
        },
        DUNGPILE = {
            GENERIC = "Poop!",
            PICKED = "Aw. No more poop",
        },
        FLOWER_RAINFOREST = "Dirt made a friend",
        FROGLEGS_POISON = "(sniff, sniff) Smells bad",
        FROGLEGS_POISON_COOKED = "(sniff, sniff) Smells okay",
        FROG_POISON = {
            DEAD = "Too bad",
            GENERIC = "Sick Ribbit",
            SLEEPING = "Tired of ribbiting",
        },
        GLOWFLY = {
            DEAD = "(sob)",
            GENERIC = "Bzzter with bright peepers",
            SLEEPING = "No light",
        },
        GLOWFLY_COCOON = "Changing",
        GOLDENMACHETE = "Pretty Slicer",
        GOLDPAN = "Gets Shiny from puddle",
        GOLD_DUST = "Shiny dirt",
        GRABBING_VINE = "Wants stuff",
        GRASS_TALL = {
            BURNING = "No!!",
            GENERIC = "You're so tall!",
            PICKED = "Keep growing!",
        },
        HALBERD = "Twirly Tail Fight Stick",
        HANGING_VINE = "Wants stuff",
        HIPPOPOTAMOOSE = "Big Water Hoppy",
        HIPPO_ANTLER = "Big Head Branch",
        ICEDTEA = "Cold Zippy water",
        INFUSED_IRON = "Oh... shiny",
        IRON = "Clinky Rock",
        LIFEPLANT = "Lively friend",
        LILYPAD = "Nice day for swim?",
        LIVING_ARTIFACT = "Boom clothes!",
        LOTUS = "Hello! How's water?",
        LOTUS_FLOWER = "Smells sweet!",
        LOTUS_FLOWER_COOKED = "Holey belly stuff",
        MACHETE = "Slicer. For friend haircuts",
        MANDRAKEHOUSE = "Hello? Anyone?",
        MANDRAKEMAN = "Screamy",
        METALPLATEHAT = "Clink Rock Head Thing",
        PANGOLDEN = "Shiny Pooper",
        PEAGAWK = {
            DEAD = "Oh dear",
            GENERIC = "Gubble Gubble Tweeter",
            SLEEPING = "Sleeping?",
        },
        PEAGAWKFEATHER = "Gubble Gubble Tweeter clothes",
        PEAGAWK_BUSH = "Looking good!",
        PIKO = {
            DEAD = "Aw...",
            GENERIC = "Fluffy Nabber",
            SLEEPING = "Sleeping. Shh...",
        },
        PIKO_ORANGE = {
            DEAD = "Aw...",
            GENERIC = "Fluffy Nabber",
            SLEEPING = "Sleeping. Shh...",
        },
        PUGALISK = "Big Wiggler",
        PUGALISK_CORPSE = "Growing bones?",
        PUGALISK_FOUNTAIN = "Life water",
        PUGALISK_RUINS_PILLAR = "Hard",
        PUGALISK_SKULL = "From big Wiggler",
        PUGALISK_TRAP_DOOR = "Hmm...What's here?",
        RABID_BEETLE = {
            DEAD = "Too bad",
            GENERIC = "Why so mad, Bzzter?",
            SLEEPING = "Let it sleep",
        },
        REEDS_WATER = "Good day, friend!",
        SAIL_SNAKESKIN = "Squirmy Wind Nabber",
        SEDIMENTPUDDLE = "Shiny puddle",
        SHEARS = "For hair cuts",
        SMELTER = {
            BURNT = "Nothing",
            COOKING_SHORT = "Hot! Hot!",
            DONE = "Done!",
            EMPTY = "Clinky rock cooker",
        },
        SNAKEBONESOUP = "Squirmy water",
        SNAKESKIN = "Squirmy clothes",
        SNAKE_BONE = "Ouch! Has sharp bits",
        TEA = "Warm Zippy water",
        TEATREE = "Let them sleep",
        TEATREE_NUT = "Want in belly? Or dirt?",
        TEATREE_NUT_COOKED = "Not for dirt now",
        TEATREE_NUT_SAPLING = "Hello, little friend",
        TREE_PILLAR = "Big friend?",
        WEEVOLE = "Wee Bzzter",
        WEEVOLE_CARAPACE = "Crunchy",
    },
}
