return {
    ANNOUCE_BATS = "Hum! The vampires are coming!",
    ANNOUNCE_BOAT_DAMAGED = "Oh dear, this water bodes ill.",
    ANNOUNCE_BOAT_SINKING = "I'm up to my tail in water!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Into the drink I go, hyuyu!",
    ANNOUNCE_DEHUMID = {
        "Freedom, this is me!",
    },
    ANNOUNCE_HAYFEVER = "Oops, so much pollen, it's going to be uncomfortable.",
    ANNOUNCE_HAYFEVER_OFF = "The pollen is gone. finally.",
    ANNOUNCE_PICKPOOP = {
        "Disgusting!",
        "It's still warm!",
        "My paws!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "It's won't work.",
        "Almost a rock!",
        "This isn't its weakness!",
    },
    ANNOUNCE_SNEEZE = "(breathing) Ah chirp! Ahhhhhh!",
    ANNOUNCE_TOO_HUMID = {
        "I can't stand %s anymore!",
        "Take off %s.",
    },
    ANNOUNCE_WAVE_BOOST = "Hyuyu!",
    DESCRIBE = {
        ALLOY = "Ahh!!!",
        APORKALYPSE_CLOCK = "Magic on such a large scale, man, this is going to be fun.",
        ARMOR_METALPLATE = "What a horrible torture.",
        ARMOR_WEEVOLE = "I'm getting goosebumps.",
        ASPARAGUS_PLANTED = "A spear that grows out of the earth.",
        BASEFAN = "The breeze is blowing, so happy.",
        BILL = {
            DEAD = "It's stalled... forever.",
            GENERIC = "Hyuyu! He spin like a top!",
            SLEEPING = "It's stalled.",
        },
        BILL_QUILL = "A toothpick long enough.",
        BOATREPAIRKIT = "To keep those boats afloat.",
        BOAT_CARGO = "I dislike being burdened while traveling.",
        BOAT_CORK = "Hither and thither, in a wayward course.",
        BOAT_LOGRAFT = "It's not so strong, but I don't have long.",
        BOAT_ROW = "Gently down the merry stream!",
        BOAT_TORCH = "A light to lead me through the night.",
        BONESTAFF = "One, two, three, wooden man!",
        CHITIN = "The shell of those guys.",
        COFFEE = "Sure to put a pep in someone's step!",
        COFFEEBEANS = "Beans from a fiery bush we picked.",
        COFFEEBEANS_COOKED = "The fire brings out the magic within.",
        CUTNETTLE = "Just smelling it blows my nose.",
        DUNGBALL = "Why would anyone like it?",
        DUNGBEETLE = {
            DEAD = "Sorry, ma'am.",
            GENERIC = "Is that... poop?",
            SLEEPING = "I thought they would have a loud purring sound.",
            UNDUNGED = "Please stop do that.",
        },
        DUNGPILE = {
            GENERIC = "The stench is overwhelming...",
            PICKED = "Still there?",
        },
        FLOWER_RAINFOREST = "There is a wild beauty.",
        FROGLEGS_POISON = "I decided not to try it.",
        FROGLEGS_POISON_COOKED = "Maybe mortals can eat it after cooked?",
        FROG_POISON = {
            DEAD = "I am sorry! So sorry!",
            GENERIC = "I'm not gonna kiss you for anything.",
            SLEEPING = "Have a wet dream.",
        },
        GLOWFLY = {
            DEAD = "sorry.",
            GENERIC = "Shiny little guy.",
            SLEEPING = "Have a good dream.",
        },
        GLOWFLY_COCOON = "What will become of it?",
        GOLDENMACHETE = "Fit for a sophisticated imp!",
        GOLDPAN = "A big slotted spoon, for gold and glory.",
        GOLD_DUST = "Many mortals try to use it to fill the void in their souls.",
        GRABBING_VINE = "Hello, what do you want?",
        GRASS_TALL = {
            BURNING = "Oops, it's burning.",
            GENERIC = "Solid tall grass, really nice.",
            PICKED = "Gone, all gone.",
        },
        HALBERD = "What a vicious weapon.",
        HANGING_VINE = "Hello, what do you want?",
        HIPPOPOTAMOOSE = "He looks like a fat imp from a distance.",
        HIPPO_ANTLER = "I know a guy who's obsessed with this stuff.",
        ICEDTEA = "Cold gives it flavor.",
        IRON = "Oooh. Almost burned me.",
        LILYPAD = "The boat passed in the pond, and the duckweed gave way.",
        LOTUS = "Lovely flower from water.",
        LOTUS_FLOWER = "Mortals eat flowers now?",
        LOTUS_FLOWER_COOKED = "*Crunch* It's still connected!",
        MACHETE = "To chop and slash!",
        MANDRAKEHOUSE = "So they have their own bag end.",
        MANDRAKEMAN = "It's full of prank juice... maybe too much.",
        PANGOLDEN = "How are you today? Any outcome?",
        PEAGAWK = {
            GENERIC = "You must have seen a lot, right?",
            SLEEPING = "Huh, let's close our eyes and take a break?",
        },
        PEAGAWKFEATHER = "Feather of a small peacock.",
        PEAGAWK_BUSH = "Well, this trick can't fool me.",
        PIKO = {
            DEAD = "That's not what dhyana's supposed to be.",
            GENERIC = "No one can mess with the squirrel.",
            SLEEPING = "It must be dreaming of giant pine cones.",
        },
        PIKO_ORANGE = {
            DEAD = "That's not what dhyana's supposed to be.",
            GENERIC = "Hey, hey, I got nothing on my hand.",
            SLEEPING = "It must be dreaming of giant pine cones.",
        },
        PUGALISK = "Hyuyu! A googly eye contest?",
        PUGALISK_CORPSE = "Hey, why don't you move?",
        PUGALISK_FOUNTAIN = "This is a tempting trap.",
        PUGALISK_RUINS_PILLAR = "The devil does not stand under a dangerous pillar.",
        PUGALISK_SKULL = "I already have a lot of good ideas.",
        PUGALISK_TRAP_DOOR = "Watch your step.",
        RABID_BEETLE = {
            DEAD = "it's a pity.",
            GENERIC = "Really energetic, do you want to dance?",
            SLEEPING = "Then intermission.",
        },
        SAIL_SNAKESKIN = "The stripes complement the colour, I say, I say.",
        SEDIMENTPUDDLE = "These are not for drink.",
        SHEARS = "Click, click, leaves fall.",
        SMELTER = {
            BURNT = "I didn't know they were hot to stone.",
            COOKING_SHORT = "They are hotter now.",
            DONE = "It doesn't make them any better.",
            EMPTY = "Put the iron you hate in and burn it.",
        },
        SNAKEBONESOUP = "Mortals always dress their food fancy.",
        SNAKESKIN = "I prefer fur to scales.",
        SNAKE_BONE = "There's no magic in it anymore.",
        TEA = "Mortal's drink.",
        TEATREE = "The foundation of the squirrel kingdom.",
        TEATREE_NUT = "Very nice nuts and clears up my nose.",
        TEATREE_NUT_COOKED = "Does this really make it better?",
        TEATREE_NUT_SAPLING = "The future is promising.",
        TREE_PILLAR = "Blot out the sun.",
        WEEVOLE = "don't bite me!",
        WEEVOLE_CARAPACE = "What remains of their armor.",
    },
}
