return {
    ANNOUNCE_DEHUMID = {
        "Freedom, this is me!",
    },
    ANNOUNCE_HAYFEVER = "Oops, so much pollen, it's going to be uncomfortable.",
    ANNOUNCE_HAYFEVER_OFF = "The pollen is gone. finally.",
    ANNOUNCE_PICKPOOP = {
        "Disgusting!",
        "It's still warm!",
        "My paws!",
    },
    ANNOUNCE_SNEEZE = "(breathing) Ah chirp! Ahhhhhh!",
    ANNOUNCE_TOO_HUMID = {
        "I can't stand %s anymore!",
        "Take off %s.",
    },
    DESCRIBE = {
        APORKALYPSE_CLOCK = "Magic on such a large scale, man, this is going to be fun.",
        ARMOR_METALPLATE = "What a horrible torture.",
        ARMOR_WEEVOLE = "I'm getting goosebumps.",
        ASPARAGUS_PLANTED = "A spear that grows out of the earth.",
        BALLPEIN_HAMMER = "The loot is calling!",
        BASEFAN = "The breeze is blowing, so happy.",
        CHITIN = "The shell of those guys.",
        CUTNETTLE = "Just smelling it blows my nose.",
        DUNGBALL = "Why would anyone like it?",
        DUNGBEETLE = {
            DEAD = "Sorry, ma'am.",
            GENERIC = "Is that... poop?",
            SLEEPING = "I thought they would have a loud purring sound.",
            UNDUNGED = "Please stop do that.",
        },
        DUNGPILE = {
            GENERIC = "The stench is overwhelming...",
            PICKED = "Still there?",
        },
        FLOWER_RAINFOREST = "There is a wild beauty.",
        GLOWFLY = {
            DEAD = "sorry.",
            GENERIC = "Shiny little guy.",
            SLEEPING = "Have a good dream.",
        },
        GLOWFLY_COCOON = "What will become of it?",
        GOLDENMACHETE = "Fit for a sophisticated imp!",
        GRABBING_VINE = "Hello, what do you want?",
        GRASS_TALL = {
            BURNING = "Oops, it's burning.",
            GENERIC = "Solid tall grass, really nice.",
            PICKED = "Gone, all gone.",
        },
        HALBERD = "What a vicious weapon.",
        HANGING_VINE = "Hello, what do you want?",
        IRON = "Oooh. Almost burned me.",
        MACHETE = "To chop and slash!",
        PEAGAWK = {
            GENERIC = "You must have seen a lot, right?",
            SLEEPING = "Huh, let's close our eyes and take a break?",
        },
        PEAGAWKFEATHER = "Feather of a small peacock.",
        PEAGAWK_BUSH = "Well, this trick can't fool me.",
        PIG_RUINS_IDOL = "The little statue above is nice, let's take it away.",
        RABID_BEETLE = {
            DEAD = "it's a pity.",
            GENERIC = "Really energetic, do you want to dance?",
            SLEEPING = "Then intermission.",
        },
        SHEARS = "Click, click, leaves fall.",
        SMELTER = {
            BURNT = "I didn't know they were hot to stone.",
            COOKING_SHORT = "They are hotter now.",
            DONE = "It doesn't make them any better.",
            EMPTY = "Put the iron you hate in and burn it.",
        },
        TREE_PILLAR = "Blot out the sun.",
        WEEVOLE = "don't bite me!",
        WEEVOLE_CARAPACE = "What remains of their armor.",
    },
}
