return {
    ACTIONFAIL = {
        USEDOOR = {
            GENERIC = "Can't in.",
            LOCKED = "Can't Open.",
        },
    },
    ANNOUCE_ALARMOVER = "The story of the Fishman Kingdom is not over yet.",
    ANNOUCE_BATS = "Florp. What's this shadow of?",
    ANNOUCE_OTHERWORLD_DEED = "where is this place?",
    ANNOUCE_UNDERLEAFCANOPY = "Big trees blocked the light.",
    ANNOUNCE_BOAT_DAMAGED = "My boat don't look good.",
    ANNOUNCE_BOAT_SINKING = "Boat gets wet!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Need to find land quick!",
    ANNOUNCE_DEHUMID = {
        "Huh, cool off.",
    },
    ANNOUNCE_GAS_DAMAGE = "Huh-huh, it smells bad.",
    ANNOUNCE_HAYFEVER = "Gullah. The gills are so uncomfortable...",
    ANNOUNCE_HAYFEVER_OFF = "oh! The gills are finally comfortable!",
    ANNOUNCE_HOUSE_DOOR = "Why listening to Pigfolk here?",
    ANNOUNCE_MYSTERY_DOOR_FOUND = "How do we into that room?",
    ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Dirt, and Dirt.",
    ANNOUNCE_MYSTERY_FOUND = "There somthing.",
    ANNOUNCE_MYSTERY_NOREWARD = "Nothing.",
    ANNOUNCE_NOTHING_FOUND = "Is it too far?",
    ANNOUNCE_PICKPOOP = {
        "Dirty water!",
        "Glurgh...",
        "No next time!",
    },
    ANNOUNCE_PUGALISK_INVULNERABLE = {
        "Can't wear it!",
        "The scales are too hard!",
        "So sturdy!",
    },
    ANNOUNCE_ROOM_STUCK = "Let me out first!",
    ANNOUNCE_SNEEZE = "Heh-hoo, ha-choo! ! !",
    ANNOUNCE_SUITUP = "Flort Glurtsu flut!",
    ANNOUNCE_TAXDAY = "Every Pigfolk has to give me money today!",
    ANNOUNCE_TOOLCORRODED = "Tools melted. Florp.",
    ANNOUNCE_TOO_HUMID = {
        "%s is hot!",
        "I don't want to wear %s anymore!",
    },
    ANNOUNCE_TURFTOOHARD = "Very solid soil.",
    ANNOUNCE_WAVE_BOOST = "Splish splash!",
    DESCRIBE = {
        ADULT_FLYTRAP = {
            DEAD = "That's plant, florp.",
            GENERIC = "Plant eat meat? Why?",
            SLEEPING = "Sleeping?",
        },
        ALLOY = "The stone became harder.",
        ALOE = "Sweet and stick.",
        ALOE_COOKED = "But it don't taste like medicine. Ms. Wickerbottom.",
        ALOE_PLANTED = "Grrr, snack never seen.",
        ALOE_SEEDS = "Make more snacks, florp!",
        ANCIENT_HERALD = "bad story come true!",
        ANCIENT_HULK = "Rock beast is angry!",
        ANCIENT_REMNANT = "All torn up.",
        ANCIENT_ROBOTS_ASSEMBLY = "They are became a bigger beast.",
        ANCIENT_ROBOT_CLAW = "No fins? Florp.",
        ANCIENT_ROBOT_HEAD = "A rock beast head.",
        ANCIENT_ROBOT_LEG = "A stone shoe.",
        ANCIENT_ROBOT_RIBS = "Did a big fish die here?",
        ANTCHEST = "Turn flower juice to honey!",
        ANTIVENOM = "Can help when I feel bad.",
        ANTQUEEN_THRONE = "Antfolk boss' sit.",
        APORKALYPSE_CLOCK = "Stuff form bad story!",
        ARMORVORTEXCLOAK = "Scary cape...",
        ARMOR_METALPLATE = "Sturdy, but heavy.",
        ARMOR_SNAKESKIN = "Why scale-less scared of water?",
        ARMOR_WEEVOLE = "Nice and comfortable armor.",
        ASPARAGUS_PLANTED = "Green stick stick, smells good.",
        BALLPEIN_HAMMER = "Pry up everything!",
        BAMBOO = "Some bamboo, florp.",
        BASEFAN = "Water ran away! florpt!",
        BILL = {
            DEAD = "Hello? You good?",
            GENERIC = "Bird mouth?",
            SLEEPING = "Nap.",
        },
        BILL_QUILL = "Scale-less got other things.",
        BLUNDERBUSS = "Terrible flamethrower!",
        BOATREPAIRKIT = "Why repair? Let water in, florpt!",
        BOAT_CARGO = "It has room for treasures!",
        BOAT_CORK = "Why not swim? florp.",
        BOAT_LOGRAFT = "Is a small boat.",
        BOAT_ROW = "It good enough.",
        BOAT_TORCH = "It torch for boat.",
        BONESTAFF = "Makes chills down my fin, florp.",
        BRAMBLESPIKE = "Bad plant! Bad!",
        BRAMBLE_BULB = "Now it's my!",
        BRAMBLE_CORE = "Bad plant boss! Bad!",
        BURR = "All pointed.",
        BURR_SAPLING = {
            BURNING = "Are burning.",
            GENERIC = "It's a baby for now.",
            PICKED = "What's going on?",
            WITHERED = "What's going on?",
        },
        CHITIN = "Tough hide.",
        CITY_LAMP = {
            GENERIC = "It lights up.",
            ON = "Glurp... Made by rock?",
        },
        CLAWPALMTREE = "It a tree.",
        CLAWPALMTREE_SAPLING = "The poor tree needs help.",
        COCONADE = {
            BURNING = "That not safe!",
            GENERIC = "Splodey ball.",
        },
        COFFEE = "Flurph... this make head hurt.",
        COFFEEBEANS = "Yummy snacks!",
        COFFEEBEANS_COOKED = "No longer yummy, flort!",
        CORK = "Can it be used to make a campfire?",
        CORKCHEST = "Guard my things.",
        CUTLASS = "Glurgh...",
        CUTNETTLE = "It into my nose!",
        DECO_ANTIQUITIES_BEEFALO = "Not real.",
        DECO_ANTIQUITIES_WALLFISH = "Not real.",
        DECO_CHAIR_BENCH = "A place to sit.",
        DECO_CHAIR_CLASSIC = "A place to sit.",
        DECO_CHAIR_CORNER = "A place to sit.",
        DECO_CHAIR_FOOTREST = "A place to sit.",
        DECO_CHAIR_HORNED = "A place to sit.",
        DECO_CHAIR_LOUNGE = "A place to sit.",
        DECO_CHAIR_MASSAGER = "Many strange colorful rope.",
        DECO_CHAIR_OTTOMAN = "A place to sit.",
        DECO_CHAIR_ROCKING = "A place to sit.",
        DECO_CHAIR_STUFFED = "A place to sit.",
        DECO_TABLE_CHESS = "Wicker-lady! Chess all set!",
        DISARMING_KIT = "Mermfolk one, pigfolk trap zero.",
        DUG_NETTLE = "We'll take you to a great place!",
        DUNGBALL = "Crud ball.",
        DUNGBEETLE = {
            DEAD = "It not moving anymore.",
            GENERIC = "Beautiful, but stinky.",
            SLEEPING = "Just fell asleep.",
            UNDUNGED = "Still stinks.",
        },
        DUNGPILE = {
            GENERIC = "Smelly crud.",
            PICKED = "No more.",
        },
        FABRIC = "Is soft.",
        FEATHER_THUNDER = "Grrr... It's prick me.",
        FLOWER_RAINFOREST = "A slightly prettier plant is still ugly.",
        FROGLEGS_POISON = "Poor froggy...",
        FROGLEGS_POISON_COOKED = "Glurgh... can't look.",
        FROG_POISON = {
            DEAD = "He gone to big swamp in the sky.",
            GENERIC = "How you do?",
            SLEEPING = "Night-night, froggy.",
        },
        GASMASKHAT = "Bad smell.",
        GLOWFLY = {
            DEAD = "died.",
            GENERIC = "How do they glow?",
            SLEEPING = "sleeping.",
        },
        GLOWFLY_COCOON = "The little bug wrapped itself up.",
        GNAT = "Too many!",
        GNATMOUND = "Bugs hideout.",
        GOLDENMACHETE = "It better than normal hacker.",
        GOLDPAN = "Pick rocks in water up.",
        GOLD_DUST = "Shining...",
        GRABBING_VINE = "They're on top here.",
        GRASS_TALL = {
            BURNING = "Fire! Is fire!",
            GENERIC = "Greer... can't move.",
            PICKED = "It has been cut clean.",
        },
        HALBERD = "Strange weapon used by Pigfolk.",
        HANGING_VINE = "They're on top here.",
        HIPPOPOTAMOOSE = "Smart scale-less like water.",
        HIPPO_ANTLER = "Branched horn.",
        ICEDTEA = "Cold leaf water.",
        INFUSED_IRON = "Glowing...",
        IRON = "Red hard rock.",
        KINGFISHER = {
            DEAD = "Ewww, it dead.",
            GENERIC = "Bad bird! Get away from them!",
            SLEEPING = "Sleepy bad bird.",
        },
        LAWNORNAMENT = {
            BURNING = "Small tree is fire!",
            BURNT = "No more pretty small tree.",
            GENERIC = "Pretty small tree.",
        },
        LIFEPLANT = "Strange flower, florp.",
        LILYPAD = "Afloat leaf.",
        LIVING_ARTIFACT = "Bring power to Mermfolk!",
        LOTUS = "Fancy flower in the pool.",
        LOTUS_FLOWER = "Fancy flower.",
        LOTUS_FLOWER_COOKED = "Filar snacks!",
        MACHETE = "Plant hacker.",
        MAGNIFYING_GLASS = "Make small things bigger.",
        MANDRAKEHOUSE = "The ceiling is not as high as mine.",
        MANDRAKEMAN = "Always scream.",
        MEAN_FLYTRAP = {
            DEAD = "That's plant, florp.",
            GENERIC = "They're like living...",
            SLEEPING = "They... sleep?",
        },
        MEATED_NETTLE = "Why?",
        METALPLATEHAT = "The hat from Ms. Wickerbottom's book!",
        NECTAR_POD = "Flower juice.",
        NETTLE = {
            DEFAULT = "Grrr, something into my nose!",
            EMPTY = "Nothing left.",
            MOIST = "So you like water too.",
            WITHERED = "Bad land for it.",
        },
        NETTLELOSANGE = "little spicy.",
        OBSIDIAN = "It really hot!",
        OINC = "What it for?",
        OINC10 = "What is \"Gurrency\"?",
        OINC100 = "Stuff for stuff! \"Gurrency\"!",
        OX_FLUTE = "Makes drain, flort!",
        OX_HORN = "Is really sharp horn!",
        PANGOLDEN = "Don't drink them all!",
        PARROT_BLUE = {
            DEAD = "Ewww, it dead.",
            GENERIC = "The feathers are so beautiful!",
            SLEEPING = "Sleepy bird.",
        },
        PEAGAWK = {
            GENERIC = "Big weird bird.",
            SLEEPING = "The big monster fell asleep?",
        },
        PEAGAWKFEATHER = "There are big monster eyes on it.",
        PEAGAWK_BUSH = "Pretty feather bush.",
        PIGEON = {
            DEAD = "Ewww, it dead.",
            GENERIC = "Hello birdy!",
            SLEEPING = "Sleepy bird.",
        },
        PIGGHOST = "Glurph, Stay away!",
        PIGHOUSE_CITY = {
            BURNING = "Burn! Burn!",
            GENERIC = "Not wet! How stupid pigfolk.",
        },
        PIGHOUSE_FARM = {
            BURNING = "Pigfolk can mess up even with stone.",
            GENERIC = "Where pigfolk dig stone.",
        },
        PIGHOUSE_MINE = {
            BURNING = "Pigfolk can mess up even with stone.",
            GENERIC = "Where pigfolk plant snacks.",
        },
        PIGMAN_MAYOR = {
            GENERIC = "Glurp! A little big Pigfolk.",
            SLEEPING = "No sleeping you nasty Pigfolk!",
        },
        PIGMAN_QUEEN = "She no Queen, flort!!",
        PIGMAN_ROYALGUARD = {
            GENERIC = "Pigfolk wrapped themself in tin can.",
            SLEEPING = "Merm guard there will never let up!",
        },
        PIG_GUARD_TOWER = {
            BURNING = "Burn!",
            GENERIC = "Bad house.",
        },
        PIG_PALACE = "Mermfolk must have one!!!",
        PIG_RUINS_ARTICHOKE = "This plant everywhere.",
        PIG_RUINS_HEAD = "Giant pifrolk face!",
        PIG_RUINS_IDOL = "A Pigfolk idol, not Mermfolk.",
        PIG_RUINS_MUSHROOM = "Stone for food?",
        PIG_RUINS_PLAQUE = "Created by Pigfolk too?",
        PIG_RUINS_SOW = "A different Pigfolk.",
        PIG_SHOP_CITYHALL = {
            BURNING = "Burn!",
            GENERIC = "Mermfolk must have one!",
        },
        PIG_SHOP_CITYHALL_PLAYER = {
            BURNING = "It must be Pigfolk!",
            GENERIC = "Pigfolk listen Mermfolk now!",
        },
        PIG_SHOP_DELI = {
            BURNING = "What else do pigfokk eat?",
            GENERIC = "Not even kelp in here.",
        },
        PIG_SHOP_PRODUCE = {
            GENERIC = "This is real food.",
        },
        PIKO = {
            DEAD = "Glurp! Hold on!",
            GENERIC = "Hi! squirrel.",
            SLEEPING = "Sleep tight!",
        },
        PIKO_ORANGE = {
            DEAD = "Glurp! Hold on!",
            GENERIC = "Hello. How are you today?",
            SLEEPING = "Sleep tight!",
        },
        POG = {
            APORKALYPSE = "Doggies... why?",
            FOLLOWER = "Let's go! florp.",
            GENERIC = "Aww, hey doggies!",
            SLEEPING = "Night-night doggie.",
        },
        POISONBALM = "It helps with sick.",
        PORKLAND_INTRO_BALLOON = "Pack can't fly?",
        PORKLAND_INTRO_BASKET = "Uh...",
        PORKLAND_INTRO_FLAGS = "Bunting.",
        PORKLAND_INTRO_SANDBAG = "This is a big bag of sand.",
        PORKLAND_INTRO_SUITCASE = "Things of all of us.",
        PORKLAND_INTRO_TRUNK = "It’s really hard to move.",
        PROP_DOOR = "Where to move.",
        PUGALISK = "It has rocky scales!",
        PUGALISK_CORPSE = "It stayed down there.",
        PUGALISK_FOUNTAIN = "Glurp... It's water?",
        PUGALISK_RUINS_PILLAR = "Pigfolk's bad post.",
        PUGALISK_SKULL = "like stone...",
        PUGALISK_TRAP_DOOR = "A face?",
        RABID_BEETLE = {
            DEAD = "died.",
            GENERIC = "The little bug is going crazy!",
            SLEEPING = "The little bug was quiet.",
        },
        RADISH = "Hot spicy root!",
        RADISH_COOKED = "Not better than it was.",
        RADISH_PLANTED = "Grrr, snack never seen.",
        RADISH_SEEDS = "Make more snacks, florp!",
        RAINFORESTTREE = {
            BURNING = "Glurgh!! Big big flower on fire!",
            BURNT = "Gone.",
            CHOPPED = "Big big flower were chop down.",
            GENERIC = "A big big flower.",
        },
        RAINFORESTTREE_ROT = "Glorph... feel bad?",
        REEDS_WATER = "Pond full of useful things, florp.",
        RELIC_1 = "Pigfolk pay me for their own stuff. Good!",
        RELIC_2 = "Pigfolk pay me for their own stuff. Good!",
        RELIC_3 = "Loot!",
        RELIC_4 = "Pigfolks are not blue...",
        RELIC_5 = "Can't ate, but shining.",
        ROCK_BASALT = "Rock.",
        ROCK_FLIPPABLE = "A flat rock.",
        ROOTTRUNK_CHILD = "Vines haunt the box.",
        RUG_BEARD = "Lack the swamp smell.",
        RUG_BRAID = "Lack the swamp smell.",
        RUG_CATCOON = "Lack the swamp smell.",
        RUG_CRIME = "Lack the swamp smell.",
        RUG_FUR = "Lack the swamp smell.",
        RUG_HEDGEHOG = "Lack the swamp smell.",
        RUG_HOOFPRINT = "Lack the swamp smell.",
        RUG_METAL = "Lack the swamp smell.",
        RUG_NAILBED = "Lack the swamp smell.",
        RUG_OCTAGON = "Lack the swamp smell.",
        RUG_OVAL = "Lack the swamp smell.",
        RUG_PORCUPUSS = "Lack the swamp smell.",
        RUG_RECTANGLE = "Lack the swamp smell.",
        RUG_ROUND = "Lack the swamp smell.",
        RUG_RUBBERMAT = "Lack the swamp smell.",
        RUG_SQUARE = "That spot looks like tentacle...",
        RUG_SWIRL = "Lack the swamp smell.",
        RUG_TILES = "Lack the swamp smell.",
        RUG_WEB = "Webby-boy like it?",
        RUG_WORMHOLE = "Lack the swamp smell.",
        SAIL_SNAKESKIN = "It sail made of colourful scales.",
        SCORPION = {
            DEAD = "Good night forever, florp.",
            GENERIC = "Sharp and scary, florp.",
            SLEEPING = "Good night, florp.",
        },
        SEDIMENTPUDDLE = "Water are ... shining?",
        SHEARS = "Shape the plants.",
        SMELTER = {
            BURNT = "Glurph, ruined.",
            COOKING_SHORT = "Hot! Hot! Hot!",
            DONE = "Done!",
            EMPTY = "What to put in it?",
        },
        SNAKEBONESOUP = "Grrr, Gross.",
        SNAKEOIL = "Is best medicine!",
        SNAKESKIN = "Is a nice skin.",
        SNAKESKINHAT = "At least their scales pretty.",
        SNAKE_AMPHIBIOUS = "Snakefolk with beautiful coat.",
        SNAKE_BONE = "Big bones.",
        SPIDER_MONKEY = {
            DEAD = "Bye...",
            GENERIC = "Grrr... What would Webby-boy think?",
            SLEEPING = "It dreaming of spider... or monkey things.",
        },
        SPIDER_MONKEY_NEST = "Mass of gooops.",
        SPIDER_MONKEY_TREE = "Spiderfolk take over there.",
        SPRINKLER = "Yeah! Rain!",
        TEA = "Leaf water.",
        TEATREE = "Strange leaves there.",
        TEATREE_NUT = "Florp. Smell strong.",
        TEATREE_NUT_COOKED = "Crunch. Crunch. Crunch.",
        TEATREE_NUT_SAPLING = "Baby Tree.",
        THUNDERBIRD = "Sparky bird.",
        THUNDERBIRDNEST = "Sparky birds home.",
        THUNDERHAT = "I can call down lightning!",
        TOUCAN = "Why it need a beak that big, florp?",
        TRAWLNET = "Is for fishies.",
        TRAWLNETDROPPED = {
            GENERIC = "Any treasures inside?",
            SOON = "It will sink, florpt.",
            SOONISH = "It sinks.",
        },
        TREE_PILLAR = "A huge tree.",
        TUBERTREE = "Ms. Wickbottom! How do we cut it down?",
        TUBER_BLOOM_CROP = "There are flower on it",
        TUBER_BLOOM_CROP_COOKED = "So delicious.",
        TUBER_CROP = "Ms.Wickbottom told us not to eat it.",
        TUBER_CROP_COOKED = "Looks good?",
        TUNACAN = "Is fishie inside?",
        TURF_COBBLEROAD = "Make ground walk-ier!",
        TURF_DEEPRAINFOREST = "Ground bit.",
        TURF_DEEPRAINFOREST_NOCANOPY = "Ground bit.",
        TURF_FIELDS = "Ground bit.",
        TURF_FOUNDATION = "Ground bit.",
        TURF_GASJUNGLE = "Ground bit.",
        TURF_LAWN = "Ground bit.",
        TURF_MOSS = "Ground bit.",
        TURF_PAINTED = "Ground bit.",
        TURF_PIGRUINS = "Ground bit.",
        TURF_PLAINS = "Ground bit.",
        TURF_RAINFOREST = "Ground bit.",
        VAMPIREBAT = {
            DEAD = "Why against mermfolk.",
            GENERIC = "Grrr! Back off!",
            SLEEPING = "Quiet...",
        },
        VAMPIREBATCAVE = "It smell stink.",
        VENOMGLAND = "Glargh!....ugly tasting medicine.",
        VENUS_STALK = "Many water in it.",
        VINE = "Thick sticks!",
        WALKINGSTICK = "A dry stick.",
        WALL_PIG_RUINS = "A broken wall.",
        WATERDROP = "a bit sweet.",
        WEEVOLE = "go away go away!",
        WEEVOLE_CARAPACE = "hard shell.",
        WINDOW_GREENHOUSE = "For watch outside.",
        WINDOW_LARGE_SQUARE = "For watch outside.",
        WINDOW_LARGE_SQUARE_CURTAIN = "For watch outside.",
        WINDOW_ROUND = "For watch outside.",
        WINDOW_ROUND_BURLAP = "For watch outside.",
        WINDOW_ROUND_CURTAINS_NAILS = "For watch outside.",
        WINDOW_SMALL_PEAKED = "For watch outside.",
        WINDOW_SMALL_PEAKED_CURTAIN = "For watch outside.",
        WINDOW_TALL = "For watch outside.",
        WINDOW_TALL_CURTAIN = "For watch outside.",
    },
}
