return {
    ANNOUNCE_BOAT_DAMAGED = "My boat don't look good.",
    ANNOUNCE_BOAT_SINKING = "Boat gets wet!",
    ANNOUNCE_BOAT_SINKING_IMMINENT = "Need to find land quick!",
    ANNOUNCE_DEHUMID = {
        "Huh, cool off.",
    },
    ANNOUNCE_HAYFEVER = "Gullah. The gills are so uncomfortable...",
    ANNOUNCE_HAYFEVER_OFF = "oh! The gills are finally comfortable!",
    ANNOUNCE_SNEEZE = "Heh-hoo, ha-choo! ! !",
    ANNOUNCE_TOO_HUMID = {
        "%s is hot!",
        "I don't want to wear %s anymore!",
    },
    ANNOUNCE_WAVE_BOOST = "Splish splash!",
    DESCRIBE = {
        ALLOY = "The stone became harder.",
        ANNOUNCE_PICKPOOP = {
            "Dirty water!",
            "Glurgh...",
            "No next time!",
        },
        APORKALYPSE_CLOCK = "Stuff form bad story!",
        ARMOR_METALPLATE = "Sturdy, but heavy.",
        ARMOR_WEEVOLE = "Nice and comfortable armor.",
        ASPARAGUS_PLANTED = "Green stick stick, smells good.",
        BASEFAN = "Water ran away! florpt!",
        BOATREPAIRKIT = "Why repair? Let water in, florpt!",
        BOAT_CARGO = "It has room for treasures!",
        BOAT_CORK = "Why not swim? florp.",
        BOAT_LOGRAFT = "Is a small boat.",
        BOAT_ROW = "It good enough.",
        BOAT_TORCH = "It torch for boat.",
        CHITIN = "Tough hide.",
        COFFEE = "Flurph... this make head hurt.",
        COFFEEBEANS = "Yummy snacks!",
        COFFEEBEANS_COOKED = "No longer yummy, flort!",
        CUTNETTLE = "It into my nose!",
        DUNGBALL = "Crud ball.",
        DUNGBEETLE = {
            DEAD = "It not moving anymore.",
            GENERIC = "Beautiful, but stinky.",
            SLEEPING = "Just fell asleep.",
            UNDUNGED = "Still stinks.",
        },
        DUNGPILE = {
            GENERIC = "Smelly crud.",
            PICKED = "No more.",
        },
        FLOWER_RAINFOREST = "A slightly prettier plant is still ugly.",
        GLOWFLY = {
            DEAD = "died.",
            GENERIC = "How do they glow?",
            SLEEPING = "sleeping.",
        },
        GLOWFLY_COCOON = "The little bug wrapped itself up.",
        GOLDENMACHETE = "It better than normal hacker.",
        GOLDPAN = "Pick rocks in water up.",
        GOLD_DUST = "Shining...",
        GRABBING_VINE = "They're on top here.",
        GRASS_TALL = {
            BURNING = "Fire! Is fire!",
            GENERIC = "Greer... can't move.",
            PICKED = "It has been cut clean.",
        },
        HALBERD = "Strange weapon used by Pigfolk.",
        HANGING_VINE = "They're on top here.",
        ICEDTEA = "Cold leaf water.",
        IRON = "Red hard rock.",
        LILYPAD = "Afloat leaf.",
        LOTUS = "Fancy flower in the pool.",
        LOTUS_FLOWER = "Fancy flower.",
        MACHETE = "Plant hacker.",
        PANGOLDEN = "Don't drink them all!",
        PEAGAWK = {
            GENERIC = "Big weird bird.",
            SLEEPING = "The big monster fell asleep?",
        },
        PEAGAWKFEATHER = "There are big monster eyes on it.",
        PEAGAWK_BUSH = "Pretty feather bush.",
        PIKO = {
            DEAD = "Glurp! Hold on!",
            GENERIC = "Hi! squirrel.",
            SLEEPING = "Sleep tight!",
        },
        PIKO_ORANGE = {
            DEAD = "Glurp! Hold on!",
            GENERIC = "Hello. How are you today?",
            SLEEPING = "Sleep tight!",
        },
        RABID_BEETLE = {
            DEAD = "died.",
            GENERIC = "The little bug is going crazy!",
            SLEEPING = "The little bug was quiet.",
        },
        SAIL_SNAKESKIN = "It sail made of colourful scales.",
        SEDIMENTPUDDLE = "Water are ... shining?",
        SHEARS = "Shape the plants.",
        SMELTER = {
            BURNT = "Glurph, ruined.",
            COOKING_SHORT = "Hot! Hot! Hot!",
            DONE = "Done!",
            EMPTY = "What to put in it?",
        },
        SNAKESKIN = "Is a nice skin.",
        TEA = "Leaf water.",
        TEATREE = "Strange leaves there.",
        TEATREE_NUT = "Florp. Smell strong.",
        TEATREE_NUT_COOKED = "Crunch. Crunch. Crunch.",
        TEATREE_NUT_SAPLING = "Baby Tree.",
        TREE_PILLAR = "A huge tree.",
        WEEVOLE = "go away go away!",
        WEEVOLE_CARAPACE = "hard shell.",
    },
}
