return {
    DESCRIBE = {
        ARMOR_WEEVOLE = "BIOLOGICAL COMPUTER CASING",
        ASPARAGUS_PLANTED = "SMALL TREES OF ENERGY",
        GOLDENMACHETE = "AN OSTENTATIOUS HACKING DEVICE",
        GRASS_TALL = {
            BURNING = "GROUND PARTS ON FIRE",
            GENERIC = "TOWERING GROUND PARTS",
            PICKED = "GROUND PARTS PREVIOUSLY ACQUIRED",
        },
        MACHETE = "A LONG BLADE FOR EXPERT HACKING",
        PEAGAWK = {
            DEAD = "NONFUNCTIONING",
            GENERIC = "EXCESSIVE OCULAR MODULES ARE INEFFICIENT",
            SLEEPING = "IDLING",
        },
        PEAGAWKFEATHER = "IT HAS BEEN SEPARATED FROM ITS BIRD",
        PEAGAWK_BUSH = "GROUND PART",
        SHEARS = "I WILL DEFEAT SOME VEGETATION WITH THIS!",
        WEEVOLE = "BIOLOGICAL FLESHSACK VIRUS",
        WEEVOLE_CARAPACE = "THEY HAVE BEEN DEBUGGED",
    },
}