return {
    ANNOUNCE_DEHUMID = {
        "HUMIDEX HAS LOWERED TO ACCEPTABLE LEVELS",
    },
    ANNOUNCE_TOO_HUMID = {
        "IT IS HOT",
        "HUMIDEX REACHING LEVELS GREATER THAN 40",
    },
    DESCRIBE = {
        APORKALYPSE_CLOCK = "MY ANCIENT BRETHREN",
        ARMOR_WEEVOLE = "BIOLOGICAL COMPUTER CASING",
        ASPARAGUS_PLANTED = "SMALL TREES OF ENERGY",
        FLOWER_RAINFOREST = "I HATE IT",
        GLOWFLY = {
            DEAD = "IT HAS BEEN TURNED OFF",
            GENERIC = "IT IS RELEASING PHOTONS",
            SLEEPING = "REGENERATING PHOTONS",
        },
        GLOWFLY_COCOON = "UNDERGOING UPGRADE",
        GOLDENMACHETE = "AN OSTENTATIOUS HACKING DEVICE",
        GRASS_TALL = {
            BURNING = "GROUND PARTS ON FIRE",
            GENERIC = "TOWERING GROUND PARTS",
            PICKED = "GROUND PARTS PREVIOUSLY ACQUIRED",
        },
        MACHETE = "A LONG BLADE FOR EXPERT HACKING",
        PEAGAWK = {
            DEAD = "NONFUNCTIONING",
            GENERIC = "EXCESSIVE OCULAR MODULES ARE INEFFICIENT",
            SLEEPING = "IDLING",
        },
        PEAGAWKFEATHER = "IT HAS BEEN SEPARATED FROM ITS BIRD",
        PEAGAWK_BUSH = "GROUND PART",
        SHEARS = "I WILL DEFEAT SOME VEGETATION WITH THIS!",
        WEEVOLE = "BIOLOGICAL FLESHSACK VIRUS",
        WEEVOLE_CARAPACE = "THEY HAVE BEEN DEBUGGED",
    },
}