return {
	DESCRIBE = {
		PEAGAWK = {
			DEAD = "NONFUNCTIONING",
			GENERIC = "EXCESSIVE OCULAR MODULES ARE INEFFICIENT",
			SLEEPING = "IDLING",
		},
		PEAGAWKFEATHER = "IT HAS BEEN SEPARATED FROM ITS BIRD",
		PEAGAWK_BUSH = "GROUND PART",
	},
}